Repository web-infra-dev/rsbuild, pull requests merged in 2023-12, with the labels that each got.

#790 feat(uni-builder): support disableHtmlFolder
  .changeset/stale-hairs-check.md
  packages/compat/uni-builder/src/shared/parseCommonConfig.ts
  packages/compat/uni-builder/src/types.ts
  packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/shared/src/server.ts
  packages/shared/tests/server.test.ts
Labels: change: feat

#801 fix(deps): manage dependencies for uni-builder
  packages/compat/uni-builder/package.json
  packages/compat/uni-builder/tsconfig.json
  packages/compat/webpack/package.json
  packages/compat/webpack/tsconfig.json
  pnpm-lock.yaml
Labels: change: fix

#804 types: proxy.context should allow function type
  packages/document/docs/en/shared/config/server/proxy.md
  packages/document/docs/zh/shared/config/server/proxy.md
  packages/shared/package.json
  packages/shared/src/types/config/server.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: feat

#809 fix(plugin-babel): lodash breaks the mjs artifact
  .changeset/young-guests-shop.md
  packages/plugin-babel/package.json
  packages/plugin-babel/src/plugin.ts
  pnpm-lock.yaml
Labels: change: fix

#814 feat: optimize the order of print file size
  .changeset/gentle-years-lick.md
  packages/core/src/plugins/fileSize.ts
Labels: change: feat

#820 docs: add more description for writeToDisk
  README.zh-CN.md
  packages/document/docs/en/shared/config/dev/writeToDisk.md
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/document/docs/zh/api/start/build-target.md
  packages/document/docs/zh/shared/config/dev/writeToDisk.md
Labels: change: docs

#823 docs: mark getCompiledPath as private
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/shared/config/tools/webpack.md
  packages/document/docs/en/shared/config/tools/webpackChain.md
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/shared/config/tools/webpack.md
  packages/document/docs/zh/shared/config/tools/webpackChain.md
Labels: change: docs

#829 docs: add tip for ASSET_PREFIX env var
  packages/document/docs/en/shared/config/dev/assetPrefix.md
  packages/document/docs/en/shared/config/output/assetPrefix.md
  packages/document/docs/zh/guide/advanced/env-vars.md
  packages/document/docs/zh/shared/config/dev/assetPrefix.md
  packages/document/docs/zh/shared/config/output/assetPrefix.md
Labels: change: docs

#830 perf(plugin-react): reduce deps and fix peer dep warning
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: change: perf

#831 fix(plugin-babel): prebundle babel-loader to fix peer warning
  packages/plugin-babel/compiled/babel-loader/583.index.js
  packages/plugin-babel/compiled/babel-loader/index.d.ts
  packages/plugin-babel/compiled/babel-loader/index.js
  packages/plugin-babel/compiled/babel-loader/license
  packages/plugin-babel/compiled/babel-loader/package.json
  packages/plugin-babel/package.json
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
  scripts/prebundle/README.md
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: fix

#835 perf(server): load proxy module on demand
  packages/core/src/provider/plugins/minimize.ts
  packages/core/src/provider/plugins/rspackProfile.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
Labels: change: perf

#836 perf(build): no need to load dev middleware when building
  packages/core/src/provider/core/createCompiler.ts
Labels: change: perf

#837 perf(server): skip schema validation in webpack-dev-middleware
  packages/shared/compiled/webpack-dev-middleware/index.js
  packages/shared/compiled/webpack-dev-middleware/schema-utils.js
  packages/shared/compiled/webpack-dev-middleware/types/index.d.ts
  scripts/prebundle/src/constant.ts
Labels: change: perf

#841 docs: update web default browserslist
  packages/document/docs/zh/guide/advanced/browserslist.md
Labels: change: docs

#847 fix(server-plugin): not relay on modifyRsbuildConfig
  .changeset/light-turtles-hammer.md
  packages/compat/webpack/src/plugins/server.ts
  packages/compat/webpack/src/shared.ts
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/server.ts
  packages/core/src/provider/plugins/server.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/shared/src/types/plugin.ts
Labels: change: fix

#840 feat(uni-builder): compat builder default browserslist
  .changeset/soft-penguins-confess.md
  packages/compat/uni-builder/src/rspack/index.ts
  packages/compat/uni-builder/src/shared/parseCommonConfig.ts
  packages/compat/uni-builder/src/types.ts
  packages/compat/uni-builder/src/webpack/index.ts
  packages/compat/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
  packages/compat/uni-builder/tests/parseConfig.test.ts
Labels: change: feat

#848 feat: add type declaration for PluginSolidPresetOptions (#783)
  packages/plugin-solid/src/index.ts
  packages/plugin-solid/src/types.ts
Labels: change: feat

#850 fix(plugin-react): split react-refresh utils to lib-react chunk
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#851 feat(plugin-vue): apply default split chunk rules
  e2e/cases/vue/split-chunk/index.test.ts
  e2e/cases/vue/split-chunk/src/index.js
  e2e/package.json
  packages/compat/webpack/tests/core/initConfigs.test.ts
  packages/compat/webpack/tests/plugins/default.test.ts
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/en/plugins/list/plugin-vue.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-vue.mdx
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/splitChunks.ts
  pnpm-lock.yaml
Labels: change: feat

#852 feat(plugin-vue2): apply default split chunk rules
  e2e/cases/vue2/split-chunk/index.test.ts
  e2e/cases/vue2/split-chunk/src/index.js
  packages/document/docs/en/plugins/list/plugin-vue2.mdx
  packages/document/docs/zh/plugins/list/plugin-vue2.mdx
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/src/splitChunks.ts
Labels: change: feat

#853 perf(plugin-babel): skip schema-utils in babel-loader
  packages/plugin-babel/compiled/babel-loader/583.index.js
  packages/plugin-babel/compiled/babel-loader/index.js
  packages/plugin-babel/compiled/babel-loader/schema-utils.js
  scripts/prebundle/src/constant.ts
Labels: change: perf

#826 feat(uni-builder): apply builder default config
  .changeset/sweet-cows-sneeze.md
  packages/compat/uni-builder/src/rspack/defaults.ts
  packages/compat/uni-builder/src/rspack/index.ts
  packages/compat/uni-builder/src/shared/defaults.ts
  packages/compat/uni-builder/src/webpack/defaults.ts
  packages/compat/uni-builder/src/webpack/index.ts
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/compat/uni-builder/tests/default.test.ts
Labels: change: feat

#839 breaking change: remove deprecated source.entries config
  .changeset/warm-bears-exercise.md
  packages/core/src/provider/core/createContext.ts
  packages/shared/src/types/config/source.ts
Labels: change: breaking

#857 feat(uni-builder): add postcss legacy plugins
  .changeset/seven-moles-jam.md
  packages/compat/uni-builder/package.json
  packages/compat/uni-builder/src/rspack/index.ts
  packages/compat/uni-builder/src/shared/getCssSupport.ts
  packages/compat/uni-builder/src/shared/parseCommonConfig.ts
  packages/compat/uni-builder/src/shared/plugins/postcssLegacy.ts
  packages/compat/uni-builder/src/types.ts
  packages/compat/uni-builder/src/webpack/index.ts
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/compat/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap
  packages/compat/uni-builder/tests/postcssLegacy.test.ts
  pnpm-lock.yaml
Labels: change: feat

#750 fix: add charset test case
  e2e/cases/output/ascii/src/index.js
Labels: change: fix

#863 perf: avoid passing html plugin in plugin options
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/html.test.ts.snap
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/plugins/networkPerformance.ts
  packages/core/src/plugins/preloadOrPrefetch.ts
  packages/core/src/provider/plugins/css.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/rspack/HtmlCrossOriginPlugin.ts
  packages/core/src/rspack/HtmlNetworkPerformancePlugin.ts
  packages/core/src/rspack/HtmlNoncePlugin.ts
  packages/core/src/rspack/HtmlTagsPlugin.ts
  packages/core/src/rspack/InlineChunkHtmlPlugin.ts
  packages/core/src/rspack/RemoveCssSourcemapPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/html.test.ts.snap
  packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
  packages/core/tests/plugins/__snapshots__/networkPerformance.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: perf

#868 docs: add some example for server.proxy
  packages/document/docs/en/config/server/proxy.mdx
  packages/document/docs/zh/config/server/proxy.mdx
Labels: change: docs

#879 feat(core): expose loadConfig method
  packages/core/src/cli/commands.ts
  packages/core/src/cli/config.ts
  packages/core/src/index.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#881 docs: add output.targets document
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/api/start/_meta.json
  packages/document/docs/en/config/output/targets.mdx
  packages/document/docs/en/guide/advanced/browserslist.md
  packages/document/docs/en/guide/basic/output-files.md
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/instance.mdx
  packages/document/docs/zh/api/start/_meta.json
  packages/document/docs/zh/config/output/targets.mdx
  packages/document/docs/zh/guide/advanced/browserslist.md
  packages/document/docs/zh/guide/basic/output-files.md
  packages/document/docs/zh/guide/start/features.mdx
Labels: change: docs

#883 fix: avoid duplicated logs with multiple targets
  packages/core/src/provider/core/createCompiler.ts
Labels: change: fix

#884 fix: incorrect log name for service worker
  packages/shared/src/constants.ts
Labels: change: fix

#890 fix(plugin-react): should get the new targets from context
  packages/plugin-assets-retry/src/runtime/index.ts
  packages/plugin-react/src/antd.ts
  packages/plugin-react/src/arco.ts
  packages/plugin-react/src/splitChunks.ts
Labels: change: fix

#894 feat(core): support get original Rsbuild config
  packages/core/src/provider/core/initPlugins.ts
  packages/document/docs/en/shared/getRsbuildConfig.md
  packages/document/docs/zh/plugins/dev/index.md
  packages/document/docs/zh/shared/getRsbuildConfig.md
  packages/shared/src/types/plugin.ts
Labels: change: feat

#895 feat(plugin-stylus): support extension `.stylus`
  packages/document/docs/en/plugins/list/plugin-stylus.mdx
  packages/document/docs/zh/plugins/list/plugin-stylus.mdx
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
  packages/shared/src/constants.ts
Labels: change: feat

#891 feat: add new `@rsbuild/plugin-umd` package
  e2e/cases/umd/index.test.ts
  e2e/cases/umd/rsbuild.config.ts
  e2e/cases/umd/src/index.html
  e2e/cases/umd/src/index.js
  e2e/package.json
  packages/plugin-umd/CHANGELOG.md
  packages/plugin-umd/LICENSE
  packages/plugin-umd/README.md
  packages/plugin-umd/modern.config.ts
  packages/plugin-umd/package.json
  packages/plugin-umd/src/index.ts
  packages/plugin-umd/tsconfig.json
  pnpm-lock.yaml
Labels: change: feat

#896 breaking change: rename output.disableSourceMap to output.sourceMap
  e2e/cases/check-syntax/index.test.ts
  e2e/cases/external-helpers/index.test.ts
  e2e/cases/moment/index.test.ts
  e2e/cases/output/output.test.ts
  e2e/cases/polyfill/index.test.ts
  e2e/cases/source-map/source.test.ts
  e2e/cases/source-map/src/index.css
  e2e/cases/source-map/src/index.js
  packages/compat/uni-builder/src/shared/parseCommonConfig.ts
  packages/compat/uni-builder/src/shared/plugins/devtools.ts
  packages/compat/uni-builder/src/types.ts
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/compat/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap
  packages/compat/webpack/src/plugins/css.ts
  packages/compat/webpack/src/plugins/less.ts
  packages/compat/webpack/src/shared.ts
  packages/compat/webpack/tests/plugins/__snapshots__/css.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/plugins/css.test.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/devtool.ts
  packages/core/src/plugins/index.ts
  packages/core/src/provider/plugins/css.ts
  packages/core/src/provider/plugins/less.ts
  packages/core/src/provider/plugins/swc.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/rspack-provider/plugins/css.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/index.test.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
  packages/shared/src/config.ts
  packages/shared/src/css.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/utils.ts
Labels: change: breaking

#898 docs: update output.sourceMap document
  e2e/cases/css/css-modules-ts-declaration/index.test.ts
  e2e/cases/css/css-modules/index.test.ts
  e2e/cases/css/import-loaders/index.test.ts
  examples/service-worker/rsbuild.config.ts
  packages/document/docs/en/config/output/disable-source-map.mdx
  packages/document/docs/en/config/output/source-map.mdx
  packages/document/docs/en/guide/basic/output-files.md
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/zh/config/output/disable-source-map.mdx
  packages/document/docs/zh/config/output/source-map.mdx
  packages/document/docs/zh/guide/basic/output-files.md
  packages/document/docs/zh/guide/migration/vue-cli.mdx
  packages/document/docs/zh/guide/optimization/build-performance.mdx
  packages/document/docs/zh/guide/start/features.mdx
  packages/shared/src/types/config/output.ts
Labels: change: docs

#900 perf(deps): remove url-join dependency
  e2e/package.json
  packages/babel-preset/package.json
  packages/compat/webpack/package.json
  packages/core/package.json
  packages/create-rsbuild/package.json
  packages/document/package.json
  packages/monorepo-utils/package.json
  packages/plugin-babel/package.json
  packages/plugin-css-minimizer/package.json
  packages/plugin-image-compress/package.json
  packages/plugin-react/package.json
  packages/plugin-styled-components/package.json
  packages/plugin-svelte/package.json
  packages/plugin-svgr/package.json
  packages/shared/compiled/url-join/index.d.ts
  packages/shared/compiled/url-join/index.js
  packages/shared/compiled/url-join/license
  packages/shared/compiled/url-join/package.json
  packages/shared/package.json
  packages/shared/src/url.ts
  packages/test-helper/package.json
  pnpm-lock.yaml
  scripts/check-changeset/package.json
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
  scripts/update-packages/package.json
Labels: change: perf

#904 docs: remove separate CHANGELOG files
  packages/babel-preset/CHANGELOG.md
  packages/compat/plugin-esbuild/CHANGELOG.md
  packages/compat/plugin-swc/CHANGELOG.md
  packages/compat/uni-builder/CHANGELOG.md
  packages/compat/webpack/CHANGELOG.md
  packages/core/CHANGELOG.md
  packages/create-rsbuild/CHANGELOG.md
  packages/document/CHANGELOG.md
  packages/monorepo-utils/CHANGELOG.md
  packages/plugin-assets-retry/CHANGELOG.md
  packages/plugin-babel/CHANGELOG.md
  packages/plugin-check-syntax/CHANGELOG.md
  packages/plugin-css-minimizer/CHANGELOG.md
  packages/plugin-image-compress/CHANGELOG.md
  packages/plugin-node-polyfill/CHANGELOG.md
  packages/plugin-pug/CHANGELOG.md
  packages/plugin-react/CHANGELOG.md
  packages/plugin-rem/CHANGELOG.md
  packages/plugin-solid/CHANGELOG.md
  packages/plugin-source-build/CHANGELOG.md
  packages/plugin-styled-components/CHANGELOG.md
  packages/plugin-stylus/CHANGELOG.md
  packages/plugin-svelte/CHANGELOG.md
  packages/plugin-svgr/CHANGELOG.md
  packages/plugin-type-check/CHANGELOG.md
  packages/plugin-umd/CHANGELOG.md
  packages/plugin-vue-jsx/CHANGELOG.md
  packages/plugin-vue/CHANGELOG.md
  packages/plugin-vue2-jsx/CHANGELOG.md
  packages/plugin-vue2/CHANGELOG.md
  packages/shared/CHANGELOG.md
  packages/test-helper/CHANGELOG.md
Labels: change: docs

#902 feat: support rsbuild.createDevServer
  packages/compat/webpack/src/provider.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/provider/provider.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/index.ts
  packages/shared/src/types/provider.ts
  packages/shared/src/types/rsbuild.ts
  packages/shared/src/types/server.ts
Labels: change: feat

#906 breaking change: rename disableCssExtract to injectStyles
  e2e/cases/css/css-modules-dom/index.test.ts
  e2e/cases/css/style-loader/index.test.ts
  packages/compat/uni-builder/src/shared/parseCommonConfig.ts
  packages/compat/uni-builder/src/types.ts
  packages/compat/webpack/tests/plugins/css.test.ts
  packages/core/src/provider/plugins/css.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
  packages/core/tests/rspack-provider/plugins/css.test.ts
  packages/document/docs/en/config/output/inject-styles.mdx
  packages/document/docs/en/config/tools/css-loader.mdx
  packages/document/docs/en/config/tools/style-loader.mdx
  packages/document/docs/en/guide/basic/css-usage.md
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/en/plugins/list/plugin-svelte.mdx
  packages/document/docs/zh/config/output/inject-styles.mdx
  packages/document/docs/zh/config/tools/css-loader.mdx
  packages/document/docs/zh/config/tools/style-loader.mdx
  packages/document/docs/zh/guide/basic/css-usage.md
  packages/document/docs/zh/guide/migration/vue-cli.mdx
  packages/document/docs/zh/guide/start/features.mdx
  packages/document/docs/zh/plugins/list/plugin-svelte.mdx
  packages/plugin-svelte/src/index.ts
  packages/shared/src/config.ts
  packages/shared/src/css.ts
  packages/shared/src/types/config/output.ts
Labels: change: breaking

#907 docs: prefer relative links and fix broken links
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/en/config/source/alias.mdx
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/config/tools/css-loader.mdx
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/en/shared/alias.md
  packages/document/docs/zh/config/html/tags.mdx
  packages/document/docs/zh/config/source/alias.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/css-loader.mdx
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/shared/alias.md
Labels: change: docs

#908 fix(plugin-umd): add globalObject to support Node.js env
  e2e/cases/umd/index.test.ts
  packages/plugin-umd/src/index.ts
Labels: change: fix

#909 docs: add guide for UMD plugin
  e2e/cases/umd/rsbuild.config.ts
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-umd.mdx
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-umd.mdx
Labels: change: docs

#910 perf(shared): prebundle line-diff dependency
  packages/shared/compiled/line-diff/index.d.ts
  packages/shared/compiled/line-diff/index.js
  packages/shared/compiled/line-diff/license
  packages/shared/compiled/line-diff/package.json
  packages/shared/package.json
  packages/shared/src/loaders/cssModulesTypescriptLoader.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: perf

#914 types: export stats type from rspack
  packages/shared/src/types/stats.ts
Labels: change: feat

#916 feat: add stats params in onDevCompileDone hook
  packages/compat/webpack/src/core/createCompiler.ts
  packages/core/src/provider/core/createCompiler.ts
  packages/core/src/server/compiler-dev-middleware/index.ts
  packages/document/docs/en/shared/onDevCompileDone.md
  packages/document/docs/zh/shared/onDevCompileDone.md
  packages/shared/src/types/hooks.ts
Labels: change: feat

#918 fix: failed to resolve path/posix in some Node version
  packages/shared/src/url.ts
Labels: change: fix

#919 feat(plugin-umd): add new export option
  e2e/cases/umd/basic/index.test.ts
  e2e/cases/umd/basic/rsbuild.config.ts
  e2e/cases/umd/basic/src/index.html
  e2e/cases/umd/basic/src/index.js
  e2e/cases/umd/export-array/index.test.ts
  e2e/cases/umd/export-array/rsbuild.config.ts
  e2e/cases/umd/export-array/src/index.html
  e2e/cases/umd/export-array/src/index.js
  e2e/cases/umd/export/index.test.ts
  e2e/cases/umd/export/rsbuild.config.ts
  e2e/cases/umd/export/src/index.html
  e2e/cases/umd/export/src/index.js
  packages/document/docs/en/plugins/list/plugin-umd.mdx
  packages/document/docs/zh/plugins/list/plugin-umd.mdx
  packages/plugin-umd/src/index.ts
Labels: change: feat

#922 types: simplify options of createRsbuild
  e2e/cases/inspect-config/index.test.ts
  e2e/scripts/shared.ts
  packages/compat/webpack/tests/helper.ts
  packages/core/src/createRsbuild.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/shared/src/types/rsbuild.ts
  packages/test-helper/src/rsbuild.ts
Labels: change: feat

#923 docs: add more guides for DNF prefetch
  packages/document/docs/en/config/performance/dns-prefetch.mdx
  packages/document/docs/zh/config/performance/dns-prefetch.mdx
Labels: change: docs

#833 feat(plugin-babel): add include and exclude option
  .changeset/odd-lies-know.md
  e2e/cases/babel/build.test.ts
  e2e/cases/vue/jsx-basic/rsbuild.config.ts
  packages/plugin-babel/src/helper.ts
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/src/types.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-babel/tests/index.test.ts
Labels: change: feat

#925 docs(plugin-babel): add include and exclude options
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/plugin-babel/src/types.ts
Labels: change: docs

#927 docs: match less files to improve babel perf
  e2e/cases/solid/index.test.ts
  e2e/cases/vue/jsx-basic/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-jsx/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-tsx/rsbuild.config.ts
  e2e/cases/vue2/jsx-basic/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-jsx/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-tsx/rsbuild.config.ts
  packages/document/docs/en/plugins/list/plugin-solid.mdx
  packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx
  packages/document/docs/en/plugins/list/plugin-vue2-jsx.mdx
  packages/document/docs/zh/plugins/list/plugin-solid.mdx
  packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx
  packages/document/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Labels: change: docs

#928 docs: update path separator examples to match Windows path
  packages/document/docs/en/config/output/inline-scripts.mdx
  packages/document/docs/en/config/output/inline-styles.mdx
  packages/document/docs/en/config/performance/chunk-split.mdx
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/en/guide/advanced/browser-compatibility.md
  packages/document/docs/en/guide/optimization/optimize-bundle.md
  packages/document/docs/en/guide/optimization/split-chunk.md
  packages/document/docs/zh/config/output/inline-scripts.mdx
  packages/document/docs/zh/config/output/inline-styles.mdx
  packages/document/docs/zh/config/performance/chunk-split.mdx
  packages/document/docs/zh/config/source/include.mdx
  packages/document/docs/zh/guide/advanced/browser-compatibility.md
  packages/document/docs/zh/guide/optimization/optimize-bundle.md
  packages/document/docs/zh/guide/optimization/split-chunk.md
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-babel/tests/index.test.ts
Labels: change: docs

#926 feat(server): support use other server frameworks, like express
  e2e/cases/server/custom-server/index.test.ts
  e2e/cases/server/custom-server/package.json
  e2e/cases/server/custom-server/scripts/index.mjs
  e2e/cases/server/custom-server/scripts/server.mjs
  e2e/cases/server/custom-server/src/index.js
  packages/compat/webpack/src/provider.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/provider/provider.ts
  packages/core/src/server/compiler-dev-middleware/index.ts
  packages/core/src/server/compiler-dev-middleware/socketServer.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/index.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/server/proxy.ts
  packages/shared/src/types/provider.ts
  packages/shared/src/types/rsbuild.ts
  packages/shared/src/types/server.ts
  pnpm-lock.yaml
Labels: change: feat

#931 docs: fix getPortSilently typo
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/zh/api/javascript-api/instance.mdx
Labels: change: docs

#934 fix: clear the assigned env vars for reloading
  .changeset/early-panthers-reflect.md
  e2e/cases/cli/reload-env/index.test.ts
  packages/core/src/loadEnv.ts
Labels: change: fix

#938 feat(type-check): support for typescript project reference
  .changeset/eleven-cats-study.md
  e2e/cases/source-build/app/rsbuild.config.ts
  e2e/cases/source-build/app/src/index.tsx
  e2e/cases/source-build/components/src/card/index.tsx
  e2e/cases/source-build/index.test.ts
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
  packages/document/docs/zh/plugins/list/plugin-type-check.mdx
  packages/plugin-type-check/src/index.ts
  packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
Labels: change: feat

#948 perf: external yaml from yaml-loader
  packages/shared/compiled/yaml-loader/index.js
  packages/shared/compiled/yaml-loader/package.json
Labels: change: perf

#950 fix(plugin-solid): delegateEvents should be optional
  packages/document/docs/en/plugins/list/plugin-solid.mdx
  packages/document/docs/zh/plugins/list/plugin-solid.mdx
  packages/plugin-solid/src/types.ts
Labels: change: fix

#952 types: extend ProcessOptions of postcss
  packages/shared/src/types/thirdParty.ts
Labels: change: feat

#953 docs: prefer use postcss config instead of tools.postcss
  e2e/cases/css/tailwindcss/postcss.config.cjs
  packages/document/docs/en/guide/basic/tailwindcss.mdx
  packages/document/docs/en/guide/basic/unocss.mdx
  packages/document/docs/zh/guide/basic/tailwindcss.mdx
  packages/document/docs/zh/guide/basic/unocss.mdx
Labels: change: docs

#957 docs: update QoS dashboard link
  README.md
  README.zh-CN.md
Labels: change: docs

#960 feat: allow to read htmlWebpackPlugin.options.title in template
  e2e/cases/html/title/index.test.ts
  e2e/cases/html/title/src/plugin-options-title.html
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/html.test.ts.snap
  packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#961 docs: update the sourceMap default value of css loaders
  e2e/cases/css/resolve-alias/index.test.ts
  e2e/cases/css/resolve-alias/rsbuild.config.ts
  packages/core/src/provider/plugins/sass.ts
  packages/document/docs/en/config/tools/css-loader.mdx
  packages/document/docs/en/config/tools/less.mdx
  packages/document/docs/en/config/tools/postcss.mdx
  packages/document/docs/en/config/tools/sass.mdx
  packages/document/docs/zh/config/tools/css-loader.mdx
  packages/document/docs/zh/config/tools/less.mdx
  packages/document/docs/zh/config/tools/postcss.mdx
  packages/document/docs/zh/config/tools/sass.mdx
Labels: change: docs

#965 fix: should generate correct app icon URL in Windows
  packages/core/src/rspack/HtmlAppIconPlugin.ts
Labels: change: fix

#966 types(plugin-vue): fix SplitChunks typing error
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
Labels: change: feat

#967 fix: failed to inspect rsbuild config
  packages/shared/src/config.ts
Labels: change: fix

#971 fix(plugin-vue): failed to split lib-vue chunk in Windows
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/src/splitChunks.ts
Labels: change: fix

#974 docs: make default entry config clearer
  packages/document/docs/en/config/source/entry.mdx
  packages/document/docs/zh/config/source/entry.mdx
Labels: change: docs

#975 fix(startUrl): fallback to node.js open if applescript failed
  packages/core/src/plugins/startUrl.ts
Labels: change: fix

#977 feat: print debug logs when set DEBUG env
  .changeset/thin-cobras-cheat.md
  packages/core/src/cli/prepare.ts
  packages/shared/src/logger.ts
Labels: change: feat

#980 docs: add more example for cleanDistPath
  packages/document/docs/en/config/output/clean-dist-path.mdx
  packages/document/docs/zh/config/output/clean-dist-path.mdx
Labels: change: docs

#979 feat(create-rsbuild): set the name of package.json
  packages/create-rsbuild/src/index.ts
Labels: change: feat

#982 fix: setup logger level if use JavaScript API
  packages/core/src/cli/prepare.ts
  packages/shared/src/logger.ts
Labels: change: fix

#983 fix: failed to build wasm in Windows
  e2e/cases/solid/hmr/index.test.ts
  e2e/cases/solid/hmr/rsbuild.config.ts
  e2e/cases/solid/index.test.ts
  packages/core/src/plugins/wasm.ts
Labels: change: fix

#986 docs: update target type
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
Labels: change: docs

#988 fix(plugin-rem): complete postcss-pxtorem import path
  packages/plugin-rem/src/index.ts
Labels: change: fix

#990 types: use autoprefixer's official type definitions
  packages/shared/compiled/autoprefixer/index.d.ts
  packages/shared/compiled/autoprefixer/lib/autoprefixer.d.ts
  packages/shared/compiled/autoprefixer/package.json
  packages/shared/src/types/thirdParty.ts
  scripts/prebundle/src/constant.ts
Labels: change: feat

#991 perf(plugin-react): use prebundled semver
  packages/plugin-react/package.json
  packages/plugin-react/src/utils.ts
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: perf

#994 docs: update PostCSS configure guide
  packages/document/docs/en/guide/basic/css-usage.md
  packages/document/docs/zh/guide/basic/css-usage.md
Labels: change: docs

#997 fix: allow setting empty title to override default title
  .changeset/strong-pianos-cheer.md
  e2e/cases/html/title/index.test.ts
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
Labels: change: fix

#993 fix: use rspack config chain
  packages/compat/plugin-esbuild/compiled/esbuild-loader/minify-plugin.d.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/provider/core/rspackConfig.ts
  packages/core/src/provider/plugins/css.ts
  packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/shared/compiled/webpack-chain/types/index.d.ts
  packages/shared/src/chain.ts
  pnpm-lock.yaml
Labels: change: fix

#999 docs(hmr): external react users can use devtools to achieve hmr
  packages/document/docs/en/guide/faq/hmr.md
  packages/document/docs/zh/guide/faq/hmr.md
Labels: change: docs

#1002 docs: remove and merge some doc fragments
  README.md
  packages/document/docs/en/guide/advanced/alias.mdx
  packages/document/docs/en/guide/faq/hmr.md
  packages/document/docs/en/guide/start/glossary.mdx
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/en/shared/alias.md
  packages/document/docs/en/shared/bundler.md
  packages/document/docs/en/shared/nodeVersion.md
  packages/document/docs/en/shared/rspack.md
  packages/document/docs/en/shared/rspackPrecautions.md
  packages/document/docs/en/shared/rspackTip.mdx
  packages/document/docs/en/shared/swc.md
  packages/document/docs/zh/guide/advanced/alias.mdx
  packages/document/docs/zh/guide/faq/hmr.md
  packages/document/docs/zh/guide/start/glossary.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
  packages/document/docs/zh/shared/alias.md
  packages/document/docs/zh/shared/bundler.md
  packages/document/docs/zh/shared/nodeVersion.md
  packages/document/docs/zh/shared/rspack.md
  packages/document/docs/zh/shared/rspackPrecautions.md
  packages/document/docs/zh/shared/rspackTip.mdx
  packages/document/docs/zh/shared/swc.md
Labels: change: docs

#1005 docs(hmr): add missing content and update link
  packages/document/docs/en/guide/faq/hmr.md
  packages/document/docs/zh/guide/faq/hmr.md
Labels: change: docs

#1004 fix(plugin-less): remove duplicate calls
  packages/core/src/provider/plugins/less.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
Labels: change: fix

#1006 fix: get available port for a specified host
  packages/shared/src/port.ts
  packages/shared/src/server.ts
Labels: change: fix

#1008 fix(plugin-swc): should apply script condition
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
Labels: change: fix

#1007 fix(plugin-html): `inject: false` should behave as expected
  e2e/cases/html/inject/index.test.ts
  packages/core/src/plugins/html.ts
  packages/core/tests/plugins/__snapshots__/html.test.ts.snap
  packages/core/tests/plugins/html.test.ts
  packages/shared/src/mergeChainedOptions.ts
  packages/shared/src/utils.ts
  packages/shared/tests/mergeChainedOptions.test.ts
Labels: change: fix

#1009 fix: inspect config not works in dev
  e2e/cases/javascript-api/plugin-hooks/index.test.ts
  packages/core/src/server/devServer.ts
  packages/shared/src/types/server.ts
Labels: change: fix

#1013 fix(plugin-swc): output.charset not work
  e2e/cases/legal-comments/index.test.ts
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/types.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-swc/tsconfig.json
  packages/compat/webpack/src/plugins/minimize.ts
  packages/core/src/provider/plugins/minimize.ts
  packages/shared/src/config.ts
  packages/shared/src/minimize.ts
Labels: change: fix

#1001 fix: rspack 0.4.4 type error
  packages/compat/uni-builder/tests/__snapshots__/default.test.ts.snap
  packages/compat/uni-builder/tests/__snapshots__/globalVars.test.ts.snap
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/define.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/output.test.ts.snap
  packages/core/tests/rspack-provider/plugins/minimize.test.ts
  packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  packages/shared/src/chain.ts
  packages/test-helper/package.json
  pnpm-lock.yaml
Labels: change: fix

#1017 fix: missing core-js entry when using webpack SWC
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/uni-builder/src/webpack/plugins/babel.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap
  packages/shared/src/coreJs.ts
  packages/shared/src/index.ts
Labels: change: fix

#998 feat(client-hmr): auto-reconnect on server disconnect
  packages/core/src/client/hmr/index.ts
Labels: change: feat

#1020 feat(plugin-pug): support Vue SFC
  .changeset/witty-pots-know.md
  e2e/cases/pug/basic/index.test.ts
  e2e/cases/pug/basic/rsbuild.config.ts
  e2e/cases/pug/basic/src/index.js
  e2e/cases/pug/basic/src/index.pug
  e2e/cases/pug/vue2-template/index.test.ts
  e2e/cases/pug/vue2-template/package.json
  e2e/cases/pug/vue2-template/rsbuild.config.ts
  e2e/cases/pug/vue2-template/src/A.vue
  e2e/cases/pug/vue2-template/src/index.js
  e2e/cases/pug/vue2-template/src/index.pug
  e2e/cases/pug/vue3-template/index.test.ts
  e2e/cases/pug/vue3-template/package.json
  e2e/cases/pug/vue3-template/rsbuild.config.ts
  e2e/cases/pug/vue3-template/src/A.vue
  e2e/cases/pug/vue3-template/src/index.js
  e2e/cases/pug/vue3-template/src/index.pug
  e2e/cases/tools/pug/src/App.tsx
  e2e/cases/tools/pug/src/index.ts
  e2e/cases/tools/pug/tsconfig.json
  packages/document/docs/en/plugins/list/plugin-pug.mdx
  packages/document/docs/zh/plugins/list/plugin-pug.mdx
  packages/plugin-pug/src/loader.ts
  pnpm-lock.yaml
Labels: change: feat

#1012 feat: support override default html-plugin
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/src/provider/core/rspackConfig.ts
  packages/core/src/provider/htmlPluginUtil.ts
  packages/core/src/provider/index.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/rspack/HtmlCrossOriginPlugin.ts
  packages/core/src/rspack/HtmlNetworkPerformancePlugin.ts
  packages/core/src/rspack/HtmlNoncePlugin.ts
  packages/core/src/rspack/HtmlTagsPlugin.ts
  packages/core/src/rspack/InlineChunkHtmlPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
Labels: change: feat

#1021 types: improve defineConfig overload
  packages/core/src/cli/config.ts
Labels: change: feat

#1023 types: server.https supports all server options
  .vscode/settings.json
  packages/document/docs/en/config/server/https.mdx
  packages/document/docs/zh/config/server/https.mdx
  packages/shared/src/types/config/server.ts
Labels: change: feat

#1030 feat: support split-by-module with rspack
  .changeset/loud-planets-judge.md
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/plugins/__snapshots__/splitChunks.test.ts.snap
  packages/core/tests/plugins/splitChunks.test.ts
  packages/document/docs/en/config/performance/chunk-split.mdx
  packages/document/docs/zh/config/performance/chunk-split.mdx
  packages/shared/src/fs.ts
  packages/shared/src/types/config/performance.ts
Labels: change: feat

#1038 docs: improve dev.client document
  packages/document/docs/en/config/dev/client.mdx
  packages/document/docs/zh/config/dev/client.mdx
Labels: change: docs

#1040 docs(CLI): add rsbuild -h and fix title indent
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/basic/page-route.md
  packages/document/docs/zh/guide/basic/cli.mdx
  packages/document/docs/zh/guide/basic/page-route.md
Labels: change: docs

#1041 types: source.include supports RuleSetCondition
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/en/config/source/exclude.mdx
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/zh/config/html/tags.mdx
  packages/document/docs/zh/config/source/exclude.mdx
  packages/document/docs/zh/config/source/include.mdx
  packages/shared/src/types/config/source.ts
Labels: change: feat

#1043 docs: update notes in source.include document
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/zh/config/source/include.mdx
Labels: change: docs

#1044 feat(create-rsbuild): configure jsxImportSource vue by default
  packages/create-rsbuild/template-vue2-ts/tsconfig.json
  packages/create-rsbuild/template-vue3-ts/tsconfig.json
Labels: change: feat

#1045 docs: add compile node_modules note for CRA
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/config/source/include.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1046 docs: add description for hot-update file
  packages/document/docs/en/config/dev/client.mdx
  packages/document/docs/zh/config/dev/client.mdx
Labels: change: docs

#1047 fix: only clear env vars when restart server
  packages/core/src/loadEnv.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/restart.ts
Labels: change: fix

#1048 feat: make loadEnv a sync method
  packages/core/src/cli/commands.ts
  packages/core/src/loadEnv.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#1049 fix: should export loadEnv method from core
  e2e/cases/cli/custom-env-prefix/.env
  e2e/cases/cli/custom-env-prefix/index.test.ts
  e2e/cases/cli/custom-env-prefix/rsbuild.config.ts
  e2e/cases/cli/custom-env-prefix/src/index.js
  e2e/cases/cli/load-env/.env
  e2e/cases/cli/load-env/index.test.ts
  e2e/cases/cli/load-env/rsbuild.config.ts
  e2e/cases/cli/load-env/src/index.js
  e2e/cases/cli/public-env-vars/.env
  e2e/cases/cli/public-env-vars/index.test.ts
  e2e/cases/cli/public-env-vars/rsbuild.config.ts
  e2e/cases/cli/public-env-vars/src/index.js
  packages/core/src/index.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: fix

#1050 docs: add loadEnv to migration guides
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/vue-cli.mdx
Labels: change: docs

#1052 docs: add CRA config migration table
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1053 fix: RsbuildInstance generics type error
  packages/shared/src/types/rsbuild.ts
Labels: change: fix

#1054 docs: add migration guide for webpack projects
  packages/document/docs/en/guide/migration/_meta.json
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/en/guide/migration/webpack.mdx
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/guide/migration/_meta.json
  packages/document/docs/zh/guide/migration/webpack.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#1056 docs: comparing Rspack dev server
  packages/document/docs/en/config/server/history-api-fallback.mdx
  packages/document/docs/en/guide/basic/_meta.json
  packages/document/docs/en/guide/basic/server.md
  packages/document/docs/zh/config/server/history-api-fallback.mdx
  packages/document/docs/zh/guide/basic/_meta.json
  packages/document/docs/zh/guide/basic/server.md
Labels: change: docs

#1057 docs: add register Rspack plugins guide
  packages/document/docs/en/config/plugins.mdx
  packages/document/docs/zh/config/plugins.mdx
Labels: change: docs

#1060 docs(check-syntax): fix sourceMap config example
  packages/document/docs/en/config/output/source-map.mdx
  packages/document/docs/zh/config/output/source-map.mdx
Labels: change: docs

#1061 perf(plugin-vue): bump vue-loader v17.4 to reuse AST
  packages/plugin-vue/package.json
  pnpm-lock.yaml
Labels: change: perf

#1062 feat(plugin-vue): add feature flag for Vue v3.4
  .changeset/witty-cheetahs-study.md
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1063 fix(plugin-svelte): missing default mainFields
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1065 docs(check-syntax): fix incorrect line feed
  packages/document/docs/en/plugins/list/plugin-check-syntax.mdx
  packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
Labels: change: docs

#1067 docs: fix discord invitation invalid
  README.md
  README.zh-CN.md
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/guide/start/index.mdx
  packages/document/rspress.config.ts
Labels: change: docs

#1066 feat: add new dev.liveReload config
  e2e/cases/live-reload/index.test.ts
  e2e/cases/live-reload/rsbuild.config.ts
  e2e/cases/live-reload/src/App.css
  e2e/cases/live-reload/src/App.jsx
  e2e/cases/live-reload/src/index.js
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/socketServer.ts
  packages/shared/src/config.ts
  packages/shared/src/types/config/dev.ts
Labels: change: feat

#1068 docs: add document for dev.liveReload config
  packages/document/docs/en/config/dev/hmr.mdx
  packages/document/docs/en/config/dev/live-reload.mdx
  packages/document/docs/en/guide/advanced/hmr.md
  packages/document/docs/zh/config/dev/hmr.mdx
  packages/document/docs/zh/config/dev/live-reload.mdx
  packages/document/docs/zh/guide/advanced/hmr.md
Labels: change: docs

#1070 perf(plugin-svgr): reuse SWC loader to improve perf
  e2e/cases/svg/svgo.test.ts
  packages/plugin-svgr/modern.config.ts
  packages/plugin-svgr/package.json
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/src/loader.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: perf

#1072 fix: make hmr-client isomorphic
  .changeset/purple-dragons-rule.md
  packages/core/src/client/hmr/createSocketUrl.ts
Labels: change: fix

#1074 feat: bump Rspack v0.4.5, update lazy entry
  packages/core/package.json
  packages/core/src/provider/core/devMiddleware.ts
  packages/core/src/provider/plugins/transition.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/define.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/package.json
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  packages/test-helper/package.json
  pnpm-lock.yaml
Labels: change: feat

#1075 fix: reload when the updated modules is empty
  packages/core/src/client/hmr/index.ts
Labels: change: fix

#1079 docs: improve Svelte and Solid guide
  packages/document/docs/en/guide/framework/solid.mdx
  packages/document/docs/en/guide/framework/svelte.mdx
  packages/document/docs/en/plugins/list/plugin-solid.mdx
  packages/document/docs/zh/guide/framework/solid.mdx
  packages/document/docs/zh/guide/framework/svelte.mdx
  packages/document/docs/zh/plugins/list/plugin-solid.mdx
Labels: change: docs

#1080 docs: add Vue JSX type inference guide
  packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx
  packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx
Labels: change: docs

#1083 feat: support use entry description object
  e2e/cases/source/entry-description-object/index.test.ts
  e2e/cases/source/entry-description-object/rsbuild.config.ts
  e2e/cases/source/entry-description-object/src/bar.js
  e2e/cases/source/entry-description-object/src/baz.js
  e2e/cases/source/entry-description-object/src/foo.js
  packages/core/src/plugins/entry.ts
  packages/core/src/plugins/html.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/config/source/entry.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/instance.mdx
  packages/document/docs/zh/config/source/entry.mdx
  packages/shared/src/types/rsbuild.ts
Labels: change: feat

#1084 feat: allow use public files as template
  e2e/cases/server/public-dir-with-template/index.test.ts
  e2e/cases/server/public-dir-with-template/public/aa.txt
  e2e/cases/server/public-dir-with-template/public/index.html
  e2e/cases/server/public-dir-with-template/rsbuild.config.ts
  e2e/cases/server/public-dir-with-template/src/index.js
  e2e/cases/server/public-dir/publicDir.test.ts
  packages/compat/webpack/src/shared.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/server.ts
  packages/core/src/provider/plugins/server.ts
  packages/core/src/provider/shared.ts
  packages/document/docs/en/config/server/public-dir.mdx
  packages/document/docs/zh/config/server/public-dir.mdx
  packages/shared/src/types/config/server.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1087 fix: handle css-loader mode option correctly
  .changeset/new-vans-think.md
  packages/shared/src/css.ts
Labels: change: fix

#1091 perf: use non-capturing groups in regexp
  packages/compat/plugin-esbuild/tests/__snapshots__/index.test.ts.snap
  packages/compat/plugin-swc/src/constants.ts
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/constants.ts
Labels: change: perf

#1095 feat(CLI): support open specific URL
  packages/core/src/cli/commands.ts
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#1097 fix(plugin-source-build): should after babel/ts-loader/swc
  packages/plugin-source-build/src/index.ts
Labels: change: fix

#1098 fix(plugin-esbuild): compiled folder should be published
  packages/compat/plugin-esbuild/package.json
Labels: change: fix

#1099 docs: recommend using mjs config file
  packages/document/docs/en/guide/basic/config.mdx
  packages/document/docs/zh/guide/basic/config.mdx
Labels: change: docs

#1100 feat: output mjs files when inspecting configs
  e2e/cases/cli/inspect/index.test.ts
  e2e/cases/inspect-config/index.test.ts
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/basic/config.mdx
  packages/document/docs/en/guide/debug/debug-mode.md
  packages/document/docs/en/guide/faq/features.md
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/guide/basic/cli.mdx
  packages/document/docs/zh/guide/basic/config.mdx
  packages/document/docs/zh/guide/debug/debug-mode.md
  packages/document/docs/zh/guide/faq/features.md
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/shared/src/config.ts
Labels: change: feat

#1102 fix: missing dependency when using bundle analyzer
  packages/core/src/cli/commands.ts
  packages/shared/compiled/commander/index.js
  packages/shared/compiled/commander/license
  packages/shared/compiled/commander/package.json
  packages/shared/compiled/commander/typings/index.d.ts
  packages/shared/compiled/webpack-bundle-analyzer/index.d.ts
  packages/shared/compiled/webpack-bundle-analyzer/index.js
  packages/shared/compiled/webpack-bundle-analyzer/package.json
  packages/shared/compiled/webpack-bundle-analyzer/public/viewer.js
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: fix

#1103 fix: bundle analyzer failed to read assets during dev
  e2e/cases/performance/bundle-analyzer/index.test.ts
  e2e/cases/performance/bundle-analyzer/rsbuild.config.ts
  e2e/cases/performance/bundle-analyzer/src/index.js
  e2e/cases/performance/performance.test.ts
  packages/core/src/plugins/bundleAnalyzer.ts
  packages/document/docs/en/config/performance/bundle-analyze.mdx
  packages/document/docs/zh/config/performance/bundle-analyze.mdx
Labels: change: fix

#1105 fix: lock webpack-bundle-analyzer to v4.9.0 to compat Rspack
  packages/shared/compiled/webpack-bundle-analyzer/index.js
  packages/shared/compiled/webpack-bundle-analyzer/package.json
  packages/shared/compiled/webpack-bundle-analyzer/public/viewer.js
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: fix

#1108 docs: add guide for custom env prefix
  packages/document/docs/en/guide/advanced/env-vars.md
  packages/document/docs/zh/guide/advanced/env-vars.md
Labels: change: docs

#1109 docs(plugin-source-build): document sourceField
  packages/document/docs/en/plugins/list/plugin-source-build.mdx
  packages/document/docs/zh/plugins/list/plugin-source-build.mdx
  packages/plugin-source-build/src/index.ts
Labels: change: docs

#1114 fix: missing style-loader dependency when enable injectStyles
  packages/compat/webpack/package.json
  packages/compat/webpack/src/plugins/css.ts
  packages/core/src/provider/plugins/css.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/css.test.ts.snap
  packages/shared/compiled/style-loader/index.d.ts
  packages/shared/compiled/style-loader/index.js
  packages/shared/compiled/style-loader/license
  packages/shared/compiled/style-loader/package.json
  packages/shared/compiled/style-loader/runtime/injectStylesIntoLinkTag.js
  packages/shared/compiled/style-loader/runtime/injectStylesIntoStyleTag.js
  packages/shared/compiled/style-loader/runtime/insertBySelector.js
  packages/shared/compiled/style-loader/runtime/insertStyleElement.js
  packages/shared/compiled/style-loader/runtime/isEqualLocals.js
  packages/shared/compiled/style-loader/runtime/isOldIE.js
  packages/shared/compiled/style-loader/runtime/setAttributesWithAttributes.js
  packages/shared/compiled/style-loader/runtime/setAttributesWithAttributesAndNonce.js
  packages/shared/compiled/style-loader/runtime/setAttributesWithoutAttributes.js
  packages/shared/compiled/style-loader/runtime/singletonStyleDomAPI.js
  packages/shared/compiled/style-loader/runtime/styleDomAPI.js
  packages/shared/compiled/style-loader/runtime/styleTagTransform.js
  packages/shared/src/types/utils.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: fix

#1116 docs: update extend asset types example
  cspell.json
  packages/document/docs/en/guide/basic/static-assets.md
  packages/document/docs/zh/guide/basic/static-assets.md
Labels: change: docs

#1117 docs: add guide for custom asset rules
  packages/document/docs/en/guide/basic/static-assets.md
  packages/document/docs/zh/guide/basic/static-assets.md
Labels: change: docs

#1119 docs: fix example URL
  packages/document/docs/en/config/performance/preconnect.mdx
  packages/document/docs/zh/config/performance/preconnect.mdx
Labels: change: docs

#1120 docs: improve bundler chain document
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
Labels: change: docs
