Repository web-infra-dev/rsbuild, pull requests merged in 2024-11, with the labels that each got.

#3876 feat: export ModifyWebpackConfigFn hook type
  .changeset/old-dodos-smoke.md
  packages/core/src/index.ts
Labels: release: feature

#3877 docs(tailwindcss): improve configuration guide
  website/docs/en/guide/basic/tailwindcss.mdx
  website/docs/zh/guide/basic/tailwindcss.mdx
Labels: release: document

#3882 feat: automatically read tsconfig paths by `references`
  e2e/cases/alias/alias-by-target/index.test.ts
  e2e/cases/alias/alias-by-target/rsbuild.config.ts
  e2e/cases/alias/alias-by-target/src/common/test.js
  e2e/cases/alias/alias-by-target/src/common2/test.js
  e2e/cases/alias/alias-by-target/src/index.js
  e2e/cases/alias/jsconfig-paths/index.test.ts
  e2e/cases/alias/jsconfig-paths/jsconfig.json
  e2e/cases/alias/jsconfig-paths/src/common/test.js
  e2e/cases/alias/jsconfig-paths/src/common2/test.js
  e2e/cases/alias/jsconfig-paths/src/index.js
  e2e/cases/alias/tsconfig-paths-references/index.test.ts
  e2e/cases/alias/tsconfig-paths-references/src/common/test.ts
  e2e/cases/alias/tsconfig-paths-references/src/common2/test.ts
  e2e/cases/alias/tsconfig-paths-references/src/index.ts
  e2e/cases/alias/tsconfig-paths-references/tsconfig.app.json
  e2e/cases/alias/tsconfig-paths-references/tsconfig.json
  e2e/cases/alias/tsconfig-paths-specify-config/index.test.ts
  e2e/cases/alias/tsconfig-paths-specify-config/rsbuild.config.ts
  e2e/cases/alias/tsconfig-paths-specify-config/src/common/test.ts
  e2e/cases/alias/tsconfig-paths-specify-config/src/common2/test.ts
  e2e/cases/alias/tsconfig-paths-specify-config/src/index.ts
  e2e/cases/alias/tsconfig-paths-specify-config/tsconfig.custom.json
  e2e/cases/alias/tsconfig-paths-specify-config/tsconfig.json
  e2e/cases/alias/tsconfig-paths/index.test.ts
  e2e/cases/alias/tsconfig-paths/src/common/test.ts
  e2e/cases/alias/tsconfig-paths/src/common2/test.ts
  e2e/cases/alias/tsconfig-paths/src/index.ts
  e2e/cases/alias/tsconfig-paths/tsconfig.json
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: release: feature

#3883 feat: add `layer` option to `api.transform()`
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#3884 feat: add `issuerLayer` option to `api.transform()`
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#3886 fix(plugin-vue): allow to override builtin split chunks
  e2e/cases/vue/split-chunks/index.test.ts
  e2e/cases/vue/split-chunks/src/index.js
  packages/plugin-vue/src/splitChunks.ts
Labels: release: bug fix

#3887 fix(plugin-react): allow to override builtin split chunks
  e2e/cases/react/split-chunk/index.test.ts
  packages/plugin-react/src/splitChunks.ts
Labels: release: bug fix

#3888 fix: duplicated plugins info in the inspected Rsbuild config
  e2e/cases/cli/inspect/index.test.ts
  packages/core/src/config.ts
  packages/core/src/types/rsbuild.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/core/tests/inspect.test.ts
Labels: release: bug fix

#3889 feat: add `cliShortcuts.help` option
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/cli-shortcuts.mdx
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: feature

#3894 perf: enable Node cache before loading modules
  packages/core/bin/rsbuild.js
  packages/core/src/cli/prepare.ts
Labels: release: performance

#3895 fix: no need for checking NODE_DISABLE_COMPILE_CACHE
  packages/core/bin/rsbuild.js
Labels: release: bug fix

#3899 feat: allow to import TS files with js extension
  e2e/cases/typescript/const-enum/index.test.ts
  e2e/cases/typescript/const-enum/src/foo.ts
  e2e/cases/typescript/const-enum/src/index.ts
  e2e/cases/typescript/const-enum/tsconfig.json
  e2e/cases/typescript/extension-alias/index.test.ts
  e2e/cases/typescript/extension-alias/src/bar.tsx
  e2e/cases/typescript/extension-alias/src/foo.ts
  e2e/cases/typescript/extension-alias/src/index.ts
  e2e/cases/typescript/extension-alias/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: release: feature

#3900 feat: allow to import TSX files with .jsx extension
  e2e/cases/typescript/extension-alias-js/index.test.ts
  e2e/cases/typescript/extension-alias-js/src/bar.tsx
  e2e/cases/typescript/extension-alias-js/src/foo.ts
  e2e/cases/typescript/extension-alias-js/src/index.ts
  e2e/cases/typescript/extension-alias-js/tsconfig.json
  e2e/cases/typescript/extension-alias-jsx/index.test.ts
  e2e/cases/typescript/extension-alias-jsx/src/bar.tsx
  e2e/cases/typescript/extension-alias-jsx/src/foo.tsx
  e2e/cases/typescript/extension-alias-jsx/src/index.ts
  e2e/cases/typescript/extension-alias-jsx/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: release: feature

#3902 feat: optimize UI for assets report page
  e2e/cases/server/viewing-served-files/index.test.ts
  packages/core/src/server/middlewares.ts
Labels: release: feature

#3910 docs: add guide for assets report page
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#3913 feat(deps): bump rspack 1.1.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3918 fix(plugin-svelte): failed to compile *.svslte.ts
  e2e/cases/svelte/index.test.ts
  e2e/cases/svelte/ts/index.test.ts
  e2e/cases/svelte/ts/rsbuild.config.ts
  e2e/cases/svelte/ts/src/App.svelte
  e2e/cases/svelte/ts/src/count.svelte.ts
  e2e/cases/svelte/ts/src/index.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3920 fix(plugin-svelte): `*.svslte.ts` files are transformed twice
  .changeset/pretty-flowers-jog.md
  packages/core/src/server/middlewares.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/index.test.ts
Labels: release: bug fix

#3923 docs: improve guide for viewing dev output
  website/docs/en/config/dev/write-to-disk.mdx
  website/docs/en/guide/basic/output-files.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/config/dev/write-to-disk.mdx
  website/docs/zh/guide/basic/output-files.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#3936 fix: proxy type error
  packages/core/prebundle.config.mjs
Labels: release: bug fix

#3944 fix: line breaks ` \n` in error overlay messages
  packages/core/src/client/overlay.ts
Labels: release: bug fix

#3947 docs: reference other plugins
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#3946 feat: allow to configure dev.writeToDisk in environments
  e2e/cases/server/write-to-disk-environments/index.test.ts
  e2e/cases/server/write-to-disk-environments/src/index.js
  packages/core/package.json
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devServer.ts
  packages/core/src/types/config.ts
  pnpm-lock.yaml
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: release: feature

#3949 feat(deps): bump rspack 1.1.1
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3952 docs: explain TypeScript extension alias
  website/docs/en/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: document

#3943 feat: update the assignment method of host in baseUrl
  packages/core/src/server/open.ts
Labels: release: feature

#3954 fix: open page with the correct host
  packages/core/src/server/helper.ts
  packages/core/src/server/open.ts
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/server/open.mdx
Labels: release: bug fix

#3963 fix: `watchFiles.type` not work as expected
  e2e/cases/cli/watch-files/index.test.ts
  e2e/cases/cli/watch-files/rsbuild.config.ts
  packages/core/src/cli/init.ts
  packages/core/src/server/watchFiles.ts
Labels: release: bug fix

#3960 perf: bump chokidar to v4 and remove fsevents dependency
  .github/renovate.json5
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/watchFiles.ts
  packages/core/src/types/config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: release: performance

#3966 perf(build): custom Rslib minify options for Node output
  packages/compat/webpack/rslib.config.ts
  packages/core/rslib.config.ts
  scripts/config/rslib.config.ts
Labels: release: performance

#3967 feat: add new `output.emitCss` config
  e2e/cases/css/emit-css/index.test.ts
  e2e/cases/css/emit-css/src/a.css
  e2e/cases/css/emit-css/src/b.module.css
  e2e/cases/css/emit-css/src/index.js
  e2e/cases/css/ignore-css/removeCss.test.ts
  e2e/cases/css/ignore-css/rsbuild.config.ts
  e2e/cases/css/ignore-css/tsconfig.json
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/output.ts
  packages/core/src/types/config.ts
  website/docs/en/config/output/emit-css.mdx
  website/docs/en/config/output/target.mdx
  website/docs/zh/config/output/emit-css.mdx
  website/docs/zh/config/output/target.mdx
Labels: release: feature

#3969 fix: close API does not actually close the build
  packages/core/src/provider/build.ts
Labels: release: bug fix

#3970 docs: remove npm packages page
  website/docs/en/guide/start/_meta.json
  website/docs/en/guide/start/npm-packages.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/_meta.json
  website/docs/zh/guide/start/npm-packages.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#3972 fix(plugin-stylus): `stylusOptions.import` should be an array
  .changeset/popular-roses-learn.md
  packages/plugin-stylus/src/index.ts
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/zh/plugins/list/plugin-stylus.mdx
Labels: release: bug fix

#3986 feat: support print error module traces
  e2e/cases/config/stats-module-trace/index.test.ts
  e2e/cases/config/stats-module-trace/rsbuild.config.ts
  e2e/cases/config/stats-module-trace/src/index.tsx
  e2e/cases/config/stats-module-trace/src/test.tsx
  e2e/cases/config/stats-options/index.test.ts
  packages/core/src/client/format.ts
  packages/core/src/server/socketServer.ts
Labels: release: feature

#3990 fix(webpack): move Rslib to devDependencies
  packages/compat/plugin-webpack-swc/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3991 docs: add rsbuild-plugin-tailwindcss to optimize bundle size
  website/docs/en/guide/basic/tailwindcss.mdx
  website/docs/zh/guide/basic/tailwindcss.mdx
Labels: release: document

#3993 docs: add explanation to .env
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#3998 feat(plugin-sass): mute deprecation warnings of dependencies
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: feature

#4001 fix: pin Rspack 1.1.0 to fix "Tsconfig not found"
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4008 feat: enable module trace by default
  e2e/cases/config/stats-module-trace/index.test.ts
  e2e/cases/config/stats-module-trace/rsbuild.config.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/socketServer.ts
Labels: release: feature

#4012 fix: print wrong URLs with custom dist path in windows
  e2e/cases/server/print-urls/index.test.ts
  packages/core/src/server/helper.ts
Labels: release: bug fix

#4014 docs: unify handler param
  website/docs/en/plugins/dev/core.mdx
Labels: release: document

#4011 feat: reference script modules as URL assets
  e2e/cases/assets/script-as-assets/index.test.ts
  e2e/cases/assets/script-as-assets/rsbuild.config.ts
  e2e/cases/assets/script-as-assets/src/index.js
  e2e/cases/assets/script-as-assets/src/test1.js
  e2e/cases/assets/script-as-assets/src/test2.ts
  e2e/cases/assets/script-as-assets/src/test3.mjs
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: feature

#4016 feat: reference style modules as URL assets
  e2e/cases/assets/styles-as-assets/index.test.ts
  e2e/cases/assets/styles-as-assets/rsbuild.config.ts
  e2e/cases/assets/styles-as-assets/src/index.js
  e2e/cases/assets/styles-as-assets/src/test1.css
  e2e/cases/assets/styles-as-assets/src/test2.less
  e2e/cases/assets/styles-as-assets/src/test3.scss
  e2e/cases/assets/styles-as-assets/src/test4.styl
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: feature

#4013 feat(loadConfig): allow to pass a meta data
  packages/core/src/config.ts
Labels: release: feature

#4017 feat(deps): bump Rspack v1.1.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4019 docs: complete loadConfig options
  packages/core/src/config.ts
  packages/core/src/index.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: document

#4023 docs(deps): bump rspress 1.37.2
  pnpm-lock.yaml
  website/package.json
Labels: release: document

#4028 docs: fix broken api links
  website/docs/en/api/start/index.mdx
  website/docs/zh/api/start/index.mdx
Labels: release: document

#4027 fix: should close compiler when dev closed
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/getDevMiddlewares.ts
Labels: release: bug fix

#4025 fix(plugin-assets-retry): avoid __webpack_require__.e pollution and add some try catch to be safer
  .changeset/cyan-flies-destroy.md
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
Labels: release: bug fix

#4036 docs: add intro for TanStack Router
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: release: document

#4037 feat: allow `output.sourceMap` to be boolean value
  e2e/cases/source-map/index.test.ts
  packages/compat/plugin-webpack-swc/src/minimizer.ts
  packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/css.ts
  packages/core/src/types/config.ts
  packages/plugin-less/src/index.ts
  packages/plugin-stylus/src/index.ts
  website/docs/en/config/output/source-map.mdx
  website/docs/zh/config/output/source-map.mdx
Labels: release: feature

#4039 docs: update description for Rslib
  README.md
  README.zh-CN.md
  website/docs/en/community/releases/v1-0.mdx
  website/docs/en/guide/faq/general.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v1-0.mdx
  website/docs/zh/guide/faq/general.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#4043 docs: add JSDoc for `PrintFileSizeOptions`
  packages/core/src/types/config.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: document

#4044 feat: add `printFileSize.include` option
  e2e/cases/print-file-size/basic/index.test.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#4045 feat: add `printFileSize.exclude` option
  e2e/cases/print-file-size/basic/index.test.ts
  e2e/cases/print-file-size/basic/src/App.css
  e2e/cases/print-file-size/basic/src/App.jsx
  packages/core/src/plugins/fileSize.ts
  packages/core/src/types/config.ts
  packages/core/tests/fileSize.test.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#4051 docs: update configuration migration
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#4054 docs: update ts checker plugin links
  website/docs/en/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: document

#4055 docs: improve migration guides
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#4058 perf: ignore watching files in node_modules
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: performance

#4061 docs: update file watching
  website/docs/en/config/dev/watch-files.mdx
  website/docs/en/guide/advanced/hmr.mdx
  website/docs/zh/config/dev/watch-files.mdx
  website/docs/zh/guide/advanced/hmr.mdx
Labels: release: document

#4066 perf: no need to calc gzipped size for Node bundles
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: performance

#4067 feat(deps): bump Rspack v1.1.4
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4068 feat(CLI): close instance after building
  packages/core/src/cli/commands.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onCloseBuild.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onCloseBuild.mdx
Labels: release: feature

#4072 feat: only print total size if there are more than one asset
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#4073 docs: tip for style-loader source map
  website/docs/en/config/output/source-map.mdx
  website/docs/zh/config/output/source-map.mdx
Labels: release: document

#4074 feat: always write manifest to disk
  e2e/cases/output/manifest/index.test.ts
  packages/core/src/plugins/manifest.ts
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/zh/guide/advanced/ssr.mdx
Labels: release: feature

#4080 docs: update ssr environment to node environment
  e2e/cases/server/ssr/rsbuild.config.ts
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/ssr.mdx
Labels: release: document

#4083 feat(CLI): set default `process.title`
  packages/core/src/cli/prepare.ts
Labels: release: feature

#4086 docs: tip for gzip compression
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: document

#4087 docs: update MF guides to @module-federation/rsbuild-plugin
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
Labels: release: document

#4088 docs: clarify chunk-split behavior for different targets
  website/docs/en/config/performance/chunk-split.mdx
  website/docs/zh/config/performance/chunk-split.mdx
Labels: release: document

#4092 feat: add `resolve.dedupe` config
  e2e/cases/resolve/dedupe/index.test.ts
  e2e/cases/resolve/dedupe/rsbuild.config.ts
  e2e/cases/resolve/dedupe/src/index.js
  packages/core/src/config.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#4093 docs: add `resolve.dedupe` config
  website/docs/en/config/_meta.json
  website/docs/en/config/resolve/dedupe.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/resolve/dedupe.mdx
  website/theme/rsbuildPluginOverview.ts
Labels: release: document
