Repository web-infra-dev/rsbuild, pull requests merged in 2024-08, with the labels that each got.

#3089 fix: plugin type missing when set moduleResolution node16+
  packages/plugin-assets-retry/modern.config.ts
  packages/plugin-assets-retry/package.json
  packages/plugin-babel/modern.config.ts
  packages/plugin-babel/package.json
  packages/plugin-check-syntax/modern.config.ts
  packages/plugin-check-syntax/package.json
  packages/plugin-less/modern.config.ts
  packages/plugin-less/package.json
  packages/plugin-preact/modern.config.ts
  packages/plugin-preact/package.json
  packages/plugin-react/modern.config.ts
  packages/plugin-react/package.json
  packages/plugin-rem/modern.config.ts
  packages/plugin-rem/package.json
  packages/plugin-solid/modern.config.ts
  packages/plugin-solid/package.json
  packages/plugin-source-build/modern.config.ts
  packages/plugin-source-build/package.json
  packages/plugin-styled-components/modern.config.ts
  packages/plugin-styled-components/package.json
  packages/plugin-stylus/modern.config.ts
  packages/plugin-stylus/package.json
  packages/plugin-svelte/modern.config.ts
  packages/plugin-svelte/package.json
  packages/plugin-svgr/modern.config.ts
  packages/plugin-svgr/package.json
  packages/plugin-type-check/modern.config.ts
  packages/plugin-type-check/package.json
  packages/plugin-vue-jsx/modern.config.ts
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/modern.config.ts
  packages/plugin-vue/package.json
  packages/plugin-vue2-jsx/modern.config.ts
  packages/plugin-vue2-jsx/package.json
  packages/plugin-vue2/modern.config.ts
  packages/plugin-vue2/package.json
Labels: change: fix

#3090 perf(server): adjust gzip level for faster compression
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/gzipMiddleware.ts
  packages/core/src/server/prodServer.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: change: perf

#3066 feat!: `onBeforeBuild` hook supports calling multiple times in watch mode
  e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
  packages/compat/webpack/src/build.ts
  packages/compat/webpack/src/initConfigs.ts
  packages/compat/webpack/src/shared.ts
  packages/core/src/helpers.ts
  packages/core/src/internal.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/core/src/plugins/rspackProfile.ts
  packages/core/src/plugins/server.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/shared/onBeforeBuild.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
Labels: change: feat

#3091 docs: list which hooks will be triggered again when rebuild
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#3092 docs: distinguish between Global Hooks and Environment Hooks
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#3095 docs: add FAQ for Vue deprecated deep selector
  website/docs/en/plugins/list/plugin-vue.mdx
  website/docs/en/plugins/list/plugin-vue2.mdx
  website/docs/zh/plugins/list/plugin-vue.mdx
  website/docs/zh/plugins/list/plugin-vue2.mdx
Labels: change: docs

#3098 feat: support using `<port>` in `dev.assetPrefix`
  e2e/cases/asset-prefix/index.test.ts
  e2e/cases/asset-prefix/src/index.js
  packages/core/src/plugins/open.ts
  packages/core/src/plugins/output.ts
  packages/core/tests/open.test.ts
  packages/core/tests/output.test.ts
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/zh/config/dev/asset-prefix.mdx
Labels: change: feat

#3101 fix: set gzip level to 6 for preview server
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/gzipMiddleware.ts
  packages/core/src/server/prodServer.ts
Labels: change: fix

#3102 perf(mf): only patch split chunks for provider app
  packages/core/src/plugins/moduleFederation.ts
Labels: change: perf

#3104 perf(mf): set splitChunks.chunks to `async` by default if using module federation
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
Labels: change: perf

#3111 fix: ensure isolation of config objects between different builds
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/css.test.ts
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#3113 feat(deps): bump Rspack 1.0.0-beta.2
  packages/core/package.json
  packages/core/src/rspack/preload/helpers/extractChunks.ts
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: change: feat

#3115 docs: add UA polyfill guide
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
Labels: change: docs

#3119 docs: add configure SWC guide
  website/docs/en/config/tools/swc.mdx
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/zh/config/tools/swc.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/configure-swc.mdx
Labels: change: docs

#3120 docs: add guide for custom JS minimizer
  website/docs/en/config/output/minify.mdx
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/en/guide/start/npm-packages.mdx
  website/docs/zh/config/output/minify.mdx
  website/docs/zh/guide/basic/configure-swc.mdx
Labels: change: docs

#3121 docs: add tips for SWC plugin version
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/zh/guide/basic/configure-swc.mdx
Labels: change: docs

#3128 docs: add guide for watching files and reload dev server
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: change: docs

#3132 docs: add Rslib links
  README.md
  README.zh-CN.md
  scripts/dictionary.txt
  website/docs/en/guide/faq/general.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/faq/general.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#3108 feat: add environment hooks about compiler
  e2e/cases/plugin-api/plugin-hooks/environments.test.ts
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  packages/compat/webpack/src/build.ts
  packages/compat/webpack/src/createCompiler.ts
  packages/compat/webpack/src/shared.ts
  packages/core/src/createContext.ts
  packages/core/src/helpers.ts
  packages/core/src/hooks.ts
  packages/core/src/initHooks.ts
  packages/core/src/initPlugins.ts
  packages/core/src/internal.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/devServer.ts
  packages/core/src/types/context.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/__snapshots__/hooks.test.ts.snap
  packages/core/tests/createAsyncHook.test.ts
  packages/core/tests/hooks.test.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onAfterEnvironmentCompile.mdx
  website/docs/en/shared/onBeforeEnvironmentCompile.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onAfterEnvironmentCompile.mdx
  website/docs/zh/shared/onBeforeEnvironmentCompile.mdx
  website/docs/zh/shared/onDevCompileEnvironmentDone.mdx
Labels: change: feat

#3134 docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
  pnpm-lock.yaml
  website/package.json
Labels: change: docs

#3135 docs: link to Rspack document instead of webpack
  packages/core/src/plugins/swc.ts
  website/docs/en/config/security/nonce.mdx
  website/docs/en/shared/onAfterBuild.mdx
  website/docs/en/shared/onAfterCreateCompiler.mdx
  website/docs/en/shared/onAfterEnvironmentCompile.mdx
  website/docs/zh/config/security/nonce.mdx
  website/docs/zh/shared/onAfterBuild.mdx
  website/docs/zh/shared/onAfterCreateCompiler.mdx
  website/docs/zh/shared/onAfterEnvironmentCompile.mdx
Labels: change: docs

#3137 feat: allow to configure `output.filename.html`
  e2e/cases/html/custom-filename/index.test.ts
  e2e/cases/html/custom-filename/rsbuild.config.ts
  e2e/cases/html/custom-filename/src/bar.js
  e2e/cases/html/custom-filename/src/foo.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/config/output.ts
  packages/core/tests/htmlHelper.test.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: change: feat

#3138 docs: add guide for filename template string
  e2e/cases/html/filename-hash/index.test.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: change: docs

#3140 fix!(cli): rename env option of inspect command to mode
  e2e/cases/cli/inspect/index.test.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/core/src/cli/commands.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: change: fix, change: breaking

#3143 fix(plugin-sass): sassOptions type should defaults to modern API
  packages/plugin-sass/src/types.ts
Labels: release: bug fix

#3144 feat(deps): bump Rspack 1.0.0-beta.3
  e2e/cases/css/css-minify-options/rsbuild.config.ts
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/core/package.json
  packages/core/src/plugins/minimize.ts
  packages/core/src/server/environment.ts
  packages/core/src/server/socketServer.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/plugin-react/package.json
  packages/plugin-react/src/react.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/config/output/minify.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/config/output/minify.mdx
Labels: release: feature

#3146 fix: no need to override Rspack configuration type
  packages/core/src/configChain.ts
  packages/core/src/hooks.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config/output.ts
  packages/core/src/types/config/tools.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/rsbuild.ts
  packages/core/src/types/rspack.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/config/output/source-map.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onBeforeBuild.mdx
  website/docs/en/shared/onBeforeCreateCompiler.mdx
  website/docs/en/shared/onBeforeEnvironmentCompile.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/output/source-map.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
  website/docs/zh/shared/onBeforeCreateCompiler.mdx
  website/docs/zh/shared/onBeforeEnvironmentCompile.mdx
Labels: release: bug fix

#3145 docs: Add pt-BR Readme
  README.md
  README.pt-BR.md
  README.zh-CN.md
Labels: release: document

#3149 docs: add `environment` to glossary
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/shared/environment.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/shared/environment.mdx
Labels: release: document

#3148 docs: add SSR guide
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/shared/ssr.mdx
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/ssr.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/shared/ssr.mdx
Labels: release: document

#3150 docs: add link for Rsbuild 0.x website
  website/docs/en/_meta.json
  website/docs/zh/_meta.json
Labels: release: document

#3151 fix(create-rsbuild): failed to override package.json
  packages/create-rsbuild/src/index.ts
Labels: release: bug fix

#3155 feat: add new `mode` config
  packages/compat/webpack/src/build.ts
  packages/core/src/config.ts
  packages/core/src/helpers/index.ts
  packages/core/src/index.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config/index.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/rsbuild.ts
  packages/core/src/types/utils.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/default.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/index.test.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: feature

#3156 feat: prefer reading the mode config
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/helpers/index.ts
  packages/core/src/index.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/bundleAnalyzer.ts
  packages/core/src/plugins/define.ts
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/plugins/progress.ts
  packages/core/src/plugins/sri.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/types/hooks.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/types.ts
  packages/plugin-babel/src/plugin.ts
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-styled-components/src/index.ts
Labels: release: feature

#3157 docs: add `mode` config documentation
  website/docs/en/config/_meta.json
  website/docs/en/config/mode.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/mode.mdx
Labels: release: document

#3159 fix: define NODE_ENV conflicts when setting mode
  e2e/cases/mode/index.test.ts
  e2e/cases/mode/rsbuild.config.ts
  e2e/cases/mode/src/index.ts
  e2e/cases/mode/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/plugins/define.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/mode.mdx
  website/docs/zh/config/mode.mdx
Labels: release: bug fix

#3162 docs: display top level fields in the overview page
  website/docs/en/config/_meta.json
  website/docs/zh/config/_meta.json
  website/theme/rsbuildPluginOverview.ts
Labels: release: document

#3166 feat(CLI): add new `--mode` option
  e2e/cases/cli/mode/index.test.ts
  e2e/cases/cli/mode/src/index.ts
  e2e/cases/cli/mode/tsconfig.json
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#3168 feat: support for `import.meta.env.MODE`
  e2e/cases/mode/basic/index.test.ts
  e2e/cases/mode/basic/src/index.js
  e2e/cases/mode/define/index.test.ts
  e2e/cases/mode/define/src/index.js
  e2e/cases/mode/rsbuild.config.ts
  e2e/cases/mode/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/plugins/define.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: feature

#3170 feat: add new `root` config
  e2e/cases/root/index.test.ts
  e2e/cases/root/test/src/index.js
  packages/core/src/config.ts
  packages/core/src/createContext.ts
  packages/core/src/types/config/index.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/_meta.json
  website/docs/en/config/root.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/root.mdx
  website/theme/rsbuildPluginOverview.ts
Labels: release: feature

#3174 docs: add tip for using root with env files
  website/docs/en/config/mode.mdx
  website/docs/en/config/root.mdx
  website/docs/zh/config/mode.mdx
  website/docs/zh/config/root.mdx
Labels: release: document

#3176 docs: add MarsCode to online examples
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#3178 feat(deps): bump Rspack 1.0.0-beta.4
  package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3181 docs: Fix minor grammar errors in the contribution docs 📙
  CONTRIBUTING.md
Labels: release: document

#3190 fix: no need to print file size if there is any build error
  e2e/cases/print-file-size/basic/index.test.ts
  e2e/cases/print-file-size/basic/rsbuild.config.ts
  e2e/cases/print-file-size/basic/src/App.jsx
  e2e/cases/print-file-size/basic/src/index.js
  e2e/cases/print-file-size/with-error/index.test.ts
  e2e/cases/print-file-size/with-error/rsbuild.config.ts
  e2e/cases/print-file-size/with-error/src/index.js
  examples/react/src/App.tsx
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#3189 feat!: output inspect config to .rsbuild dir
  e2e/cases/cli/inspect/index.test.ts
  e2e/cases/inspect-config/debug.test.ts
  e2e/cases/inspect-config/index.test.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/core/src/constants.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/tests/cleanOutput.test.ts
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/en/guide/debug/debug-mode.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
  website/docs/zh/guide/debug/debug-mode.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: release: feature

#3195 docs: update benchmark data
  website/theme/components/Benchmark.tsx
Labels: release: document

#3197 fix: no need to print file size after rebuilding
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#3196 fix: onBeforeBuild hook should before onBeforeEnvironmentCompile hook
  e2e/cases/plugin-api/plugin-hooks/environments.test.ts
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  examples/react/src/App.tsx
  packages/core/src/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onBeforeEnvironmentCompile.mdx
Labels: release: bug fix

#3200 feat: add type attribute for SVG favicon
  e2e/cases/html/favicon/index.test.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
Labels: release: feature

#3204 fix: ensure postcss-loader uses the built-in postcss
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/prebundle.config.mjs
  packages/core/src/helpers/path.ts
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3207 docs(type-check): add exclude examples
  e2e/cases/type-check/basic/index.test.ts
  website/docs/en/plugins/list/plugin-type-check.mdx
  website/docs/zh/plugins/list/plugin-type-check.mdx
Labels: release: document

#3208 feat(create-rsbuild): improve tool selection instruction in prompt
  packages/create-rsbuild/src/index.ts
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: feature

#3210 fix: clean rsbuild outputs by default
  packages/core/src/plugins/cleanOutput.ts
Labels: release: bug fix

#3213 feat: `output.cleanDistPath` defaults to `auto`
  packages/core/src/config.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/core/src/types/config/output.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/output/clean-dist-path.mdx
  website/docs/zh/config/output/clean-dist-path.mdx
Labels: release: feature

#3214 fix: missing default mode when using `rsbuild.startDevServer`
  e2e/cases/mode/define/index.test.ts
  e2e/cases/mode/define/src/index.js
  packages/core/src/createRsbuild.ts
  packages/core/src/provider/build.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/config/mode.mdx
  website/docs/zh/config/mode.mdx
Labels: release: bug fix

#3218 docs: enable strict SSG and update X logo
  website/rspress.config.ts
Labels: release: document

#3219 feat!: support generating web app manifest when using `html.appIcon`
  e2e/cases/html/app-icon/index.test.ts
  e2e/cases/html/combined/html.test.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/types/config/html.ts
Labels: release: feature

#3216 feat!: use `connectWebSocket` instead of `onHTTPUpdate` method
  e2e/cases/server/custom-server/scripts/pureServer.mjs
  e2e/cases/server/custom-server/scripts/server.mjs
  packages/core/src/server/devServer.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/guide/advanced/ssr.mdx
Labels: release: feature

#3221 feat(deps): bump Rspack 1.0.0-beta.5
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3223 docs: update documentation for `html.appIcon`
  packages/core/src/types/config/html.ts
  website/docs/en/config/html/app-icon.mdx
  website/docs/zh/config/html/app-icon.mdx
Labels: release: document

#3225 feat: set default entry when entry is set to an empty object
  e2e/cases/source/entry-empty-object/index.test.ts
  e2e/cases/source/entry-empty-object/rsbuild.config.ts
  e2e/cases/source/entry-empty-object/src/index.js
  packages/core/src/provider/initConfigs.ts
Labels: release: feature

#3226 perf: use compilation.inputFileSystem to read app icons
  packages/core/src/helpers/fs.ts
  packages/core/src/plugins/appIcon.ts
Labels: release: performance

#3228 feat: allow to custom web app manifest filename
  e2e/cases/html/app-icon/index.test.ts
  packages/core/src/index.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/types/config/html.ts
  website/docs/en/config/html/app-icon.mdx
  website/docs/zh/config/html/app-icon.mdx
Labels: release: feature

#3234 feat: add mime type for web app manifest
  e2e/cases/html/app-icon/index.test.ts
  packages/core/package.json
  packages/core/src/plugins/appIcon.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/config/html/app-icon.mdx
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/config/html/app-icon.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: feature

#3235 feat: allow to specify target for app icons
  e2e/cases/html/app-icon/index.test.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/types/config/html.ts
  website/docs/en/config/html/app-icon.mdx
  website/docs/zh/config/html/app-icon.mdx
Labels: release: feature

#3237 feat: allow to set URL as app icon
  e2e/cases/html/app-icon/index.test.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/types/config/html.ts
  website/docs/en/config/html/app-icon.mdx
  website/docs/en/config/html/favicon.mdx
  website/docs/zh/config/html/app-icon.mdx
  website/docs/zh/config/html/favicon.mdx
Labels: release: feature

#3238 docs: add app icon to website
  website/rspress.config.ts
Labels: release: document

#3241 docs: add example for inlining async chunks
  website/docs/en/config/html/inject.mdx
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/zh/config/html/inject.mdx
  website/docs/zh/config/output/inline-scripts.mdx
Labels: release: document

#3243 docs: update Rspack stack layers
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#3245 docs: add more breaking changes about rsbuild 1.0
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3246 feat: allow to disable HTML for specific entry
  e2e/cases/source/entry-disable-html/index.test.ts
  e2e/cases/source/entry-disable-html/rsbuild.config.ts
  e2e/cases/source/entry-disable-html/src/bar.js
  e2e/cases/source/entry-disable-html/src/foo.js
  packages/core/src/createContext.ts
  packages/core/src/index.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/plugins/html.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/config/source/entry.mdx
  website/docs/zh/config/source/entry.mdx
Labels: release: feature

#3250 feat!: change default charset to utf8
  e2e/cases/output/charset/index.test.ts
  e2e/cases/output/charset/src/index.js
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/types/config/output.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/minimize.test.ts
  website/docs/en/config/output/charset.mdx
  website/docs/zh/config/output/charset.mdx
Labels: release: breaking change

#3252 docs: improve 0.x migration guide
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3257 perf: replace dev middleware with a lightweight version
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: performance

#3258 fix: not inline scripts / styles when enable not set
  e2e/cases/inline-chunk/index.test.ts
  packages/core/src/plugins/inlineChunk.ts
Labels: release: bug fix

#3260 feat: expose `server.printUrls` method
  packages/core/src/server/devServer.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#3261 fix: should terminate http server correctly
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/prodServer.ts
Labels: release: bug fix

#3262 docs: polish README
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#3263 fix: server.close should close http server
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
Labels: release: bug fix

#3264 feat: add `environments` to `onAfterStartProdServer`
  packages/core/src/server/prodServer.ts
  packages/core/src/types/hooks.ts
  website/docs/en/shared/onAfterStartProdServer.mdx
  website/docs/zh/shared/onAfterStartProdServer.mdx
Labels: release: feature

#3265 docs: add developing environment plugins guide
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#3267 docs: correct the default HTML template
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: document

#3268 feat(deps): bump Rspack 1.0.0-rc.0
  e2e/cases/module-federation/index.test.ts
  packages/core/package.json
  packages/core/src/helpers/fs.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  pnpm-lock.yaml
Labels: release: feature

#3266 feat: transformImport support function type
  packages/compat/plugin-swc/src/utils.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/types/config/source.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/swc.test.ts
  website/docs/en/config/source/transform-import.mdx
  website/docs/zh/config/source/transform-import.mdx
Labels: release: feature

#3269 fix(deps): use caret version for swc helpers
  packages/compat/plugin-swc/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3270 fix(mf): should compile `@module-federation/sdk`
  e2e/cases/module-federation/index.test.ts
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#3272 feat: minify CSS for injected styles
  e2e/cases/css/enable-experiments-css/index.test.ts
  e2e/cases/css/style-loader/index.test.ts
  packages/core/src/plugins/css.ts
  website/docs/en/config/output/inject-styles.mdx
  website/docs/en/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/output/inject-styles.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
Labels: release: feature

#3275 docs: update EJS usage
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: document

#3286 feat(deps): bump Rspack 1.0.0-rc.1
  packages/compat/plugin-swc/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3289 fix!: remove transformImport false option
  e2e/cases/source/plugin-import/foo/index.js
  e2e/cases/source/plugin-import/index.test.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/types/config/source.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/swc.test.ts
  website/docs/en/config/source/transform-import.mdx
  website/docs/zh/config/source/transform-import.mdx
Labels: release: bug fix

#3292 feat: allow to override Rspack config validate env
  e2e/cases/rspack-config-validate/index.test.ts
  e2e/cases/rspack-config-validate/rsbuild.config.ts
  e2e/cases/rspack-config-validate/src/index.js
  packages/core/src/plugins/basic.ts
Labels: release: feature

#3293 fix: avoid passing unsupported Rspack config
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3294 feat(deps): bump Rspack 1.0.0-rc.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3295 feat!: enable Rspack config schema validation by default
  e2e/cases/rspack-config-validate/index.test.ts
  e2e/cases/rspack-config-validate/rsbuild.config.ts
  packages/core/src/plugins/basic.ts
  scripts/dictionary.txt
Labels: release: feature

#3297 feat(deps): bump Rspack 1.0.0
  packages/core/package.json
  packages/core/src/helpers/index.ts
  pnpm-lock.yaml
Labels: release: feature

#3299 docs: add guide for other Rspack targets
  website/docs/en/config/output/target.mdx
  website/docs/zh/config/output/target.mdx
Labels: release: document

#3303 docs: add guide for error overlay
  website/docs/en/config/dev/client.mdx
  website/docs/zh/config/dev/client.mdx
Labels: release: document

#3305 docs: Update html-template.mdx
  website/docs/en/guide/basic/html-template.mdx
Labels: release: document

#3306 docs: use cross-env to set env var
  website/docs/en/config/performance/bundle-analyze.mdx
  website/docs/en/guide/debug/rsdoctor.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/config/performance/bundle-analyze.mdx
  website/docs/zh/guide/debug/rsdoctor.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: document

#3307 docs: update server.open guide rsbuild-0-x.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3308 docs: remove duplicated html tags example
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: document

#3309 docs: add Rspack config validation to migration guide
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3313 docs: config migration table
  README.md
  README.zh-CN.md
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/config/dev/hmr.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/config/dev/hmr.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#3317 docs: fix Benchmark graph width
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
  website/theme/components/Benchmark.module.scss
  website/theme/components/Benchmark.tsx
Labels: release: document

#3319 docs: add SECURITY.md
  SECURITY.md
Labels: release: document

#3320 docs: add /api in the example of server.proxy
  website/docs/en/config/server/proxy.mdx
  website/docs/zh/config/server/proxy.mdx
Labels: release: document

#3321 docs: add vite environment variables migrate guide
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#3323 docs(create-rsbuild): update README
  packages/create-rsbuild/README.md
  packages/create-rsbuild/package.json
  pnpm-lock.yaml
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#3324 fix: align stats types with Rspack
  packages/core/src/client/hmr.ts
  packages/core/src/helpers/stats.ts
  packages/core/src/hooks.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/environment.ts
  packages/core/src/server/socketServer.ts
  packages/core/src/types/config/dev.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/index.ts
  packages/core/src/types/stats.ts
Labels: release: bug fix

#3325 feat: add stats to the return value of `rsbuild.build`
  e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
  packages/compat/webpack/src/build.ts
  packages/core/src/index.ts
  packages/core/src/provider/build.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#3327 fix: `rsbuild.build` always return close method
  e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
  packages/compat/webpack/src/build.ts
  packages/core/src/provider/build.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: bug fix
