Repository web-infra-dev/rsbuild, pull requests merged in 2024-10, with the labels that each got.

#3617 docs: add Rspress link to footer
  website/rspress.config.ts
  website/theme/components/Copyright.module.scss
  website/theme/components/Copyright.tsx
Labels: release: document

#3620 docs: improve `output.assetPrefix`
  website/docs/en/config/output/asset-prefix.mdx
  website/docs/zh/config/output/asset-prefix.mdx
Labels: release: document

#3624 docs: add guide for migrating env vars
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#3542 feat: support `server.base` configuration
  e2e/cases/server/base/index.test.ts
  e2e/cases/server/base/public/aaa.txt
  e2e/cases/server/base/src/index.html
  e2e/cases/server/base/src/index.js
  packages/compat/plugin-webpack-swc/src/minimizer.ts
  packages/compat/plugin-webpack-swc/tests/plugin.test.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/constants.ts
  packages/core/src/plugins/define.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/default.test.ts
  packages/core/tests/helpers.test.ts
  packages/core/tests/server.test.ts
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/en/config/output/asset-prefix.mdx
  website/docs/en/config/server/base.mdx
  website/docs/en/config/server/public-dir.mdx
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/config/dev/asset-prefix.mdx
  website/docs/zh/config/output/asset-prefix.mdx
  website/docs/zh/config/server/base.mdx
  website/docs/zh/config/server/public-dir.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/server.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: feature

#3625 docs: add `base` version range
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/en/config/output/asset-prefix.mdx
  website/docs/en/config/server/base.mdx
  website/docs/zh/config/dev/asset-prefix.mdx
  website/docs/zh/config/output/asset-prefix.mdx
  website/docs/zh/config/server/base.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#3626 docs: add `base` to migration guide
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#3627 perf(CLI): enable Node.js compile cache
  packages/core/src/cli/prepare.ts
Labels: release: performance

#3629 fix(plugin-sass): mute the legacy API deprecation warnings
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/index.test.ts
Labels: release: bug fix

#3631 docs(plugin-sass): add legacy API deprecation tip
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: document

#3632 feat: define `import.meta.env.BASE_URL`
  e2e/cases/server/base-url-env-var/index.test.ts
  e2e/cases/server/base-url-env-var/src/index.html
  e2e/cases/server/base-url-env-var/src/index.js
  e2e/cases/server/base-url/index.test.ts
  e2e/cases/server/base-url/public/aaa.txt
  e2e/cases/server/base-url/src/index.js
  e2e/cases/server/base/src/index.html
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/plugins/define.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: feature

#3636 docs: list all default env vars
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#3638 feat: define `import.meta.env.ASSET_PREFIX`
  e2e/cases/asset-prefix/index.test.ts
  e2e/cases/asset-prefix/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/plugins/define.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: feature

#3639 docs: update plugin configuration API examples
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/en/shared/rspackChain.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/index.mdx
  website/docs/zh/shared/rspackChain.mdx
Labels: release: document

#3640 feat: allow `dev.watchFiles` to be an array
  e2e/cases/cli/reload-extra-config/tsconfig.json
  e2e/cases/cli/watch-files-array/index.test.ts
  e2e/cases/cli/watch-files-array/rsbuild.config.ts
  e2e/cases/cli/watch-files-array/src/index.js
  e2e/cases/cli/watch-files/index.test.ts
  e2e/cases/cli/watch-files/rsbuild.config.ts
  e2e/cases/cli/watch-files/src/index.js
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/server/watchFiles.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: release: feature

#3642 feat: check output folder when using preview JS API
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  packages/core/src/cli/commands.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
Labels: release: feature

#3644 perf: no need to init Rspack config before preview
  packages/core/src/cli/commands.ts
  packages/core/src/createRsbuild.ts
Labels: release: performance

#3645 feat: export `PreviewOptions` type and correct doc
  packages/core/src/createRsbuild.ts
  packages/core/src/index.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#3646 feat: allow to disable preview checks
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#3647 fix: correct `rsbuild.createCompiler` type
  packages/core/src/index.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/start/index.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/start/index.mdx
Labels: release: bug fix

#3614 feat: support for CLI shortcuts
  examples/react/rsbuild.config.ts
  packages/core/src/config.ts
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#3651 feat: support for CLI shortcuts (part 2)
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
Labels: release: feature

#3652 feat: enable CLI shortcuts by default when using Rsbuild CLI
  examples/react/rsbuild.config.ts
  packages/core/src/cli/init.ts
Labels: release: feature

#3654 docs: polish configuration documents
  website/docs/en/config/html/crossorigin.mdx
  website/docs/en/config/html/favicon.mdx
  website/docs/en/config/html/output-structure.mdx
  website/docs/en/config/output/data-uri-limit.mdx
  website/docs/en/config/output/externals.mdx
  website/docs/en/config/output/legal-comments.mdx
  website/docs/en/config/performance/preconnect.mdx
  website/docs/en/config/performance/profile.mdx
  website/docs/en/config/security/nonce.mdx
  website/docs/en/config/security/sri.mdx
  website/docs/en/config/server/base.mdx
  website/docs/en/config/server/history-api-fallback.mdx
  website/docs/en/config/server/open.mdx
  website/docs/en/config/server/port.mdx
  website/docs/en/config/server/strict-port.mdx
  website/docs/en/config/source/define.mdx
  website/docs/zh/config/html/crossorigin.mdx
  website/docs/zh/config/html/favicon.mdx
  website/docs/zh/config/html/output-structure.mdx
  website/docs/zh/config/output/data-uri-limit.mdx
  website/docs/zh/config/output/externals.mdx
  website/docs/zh/config/output/legal-comments.mdx
  website/docs/zh/config/performance/preconnect.mdx
  website/docs/zh/config/performance/profile.mdx
  website/docs/zh/config/security/nonce.mdx
  website/docs/zh/config/security/sri.mdx
  website/docs/zh/config/server/base.mdx
  website/docs/zh/config/server/history-api-fallback.mdx
  website/docs/zh/config/server/open.mdx
  website/docs/zh/config/server/port.mdx
  website/docs/zh/config/server/strict-port.mdx
  website/docs/zh/config/source/define.mdx
Labels: release: document

#3655 feat: restart dev server via CLI shortcut
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/restart.ts
Labels: release: feature

#3656 docs: add reload-server tip
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: release: document

#3657 fix: failed to transform Rsbuild runtime code
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3660 docs: add `dev.cliShortcuts` configuration
  website/docs/en/config/dev/cli-shortcuts.mdx
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: document

#3661 feat: support for custom CLI shortcuts
  e2e/cases/cli/shortcuts/devCustom.mjs
  e2e/cases/cli/shortcuts/index.test.ts
  e2e/cases/cli/shortcuts/previewCustom.mjs
  packages/core/src/index.ts
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/cli-shortcuts.mdx
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: feature

#3663 fix(comment): hmr broken docs link
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#3666 docs(cli-shortcuts): remove duplicate lines
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: document

#3667 feat: validate Rspack plugins configuration
  e2e/cases/rspack-config-validate/index.test.ts
  packages/core/src/provider/rspackConfig.ts
Labels: release: feature

#3668 feat: beautify file size logs for multiple environments
  e2e/cases/print-file-size/basic/index.test.ts
  e2e/cases/print-file-size/with-error/index.test.ts
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#3672 feat: update building logs
  e2e/cases/javascript-api/custom-logger/index.test.ts
  e2e/cases/progress/index.test.ts
  packages/compat/webpack/src/progress/ProgressPlugin.ts
  packages/compat/webpack/src/progress/helpers/nonTty.ts
  packages/core/src/provider/createCompiler.ts
Labels: release: feature

#3673 perf: merge file size logs
  packages/core/src/plugins/fileSize.ts
Labels: release: performance

#3676 feat(deps): bump rspack 1.0.9
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3682 perf: initialize PostCSS plugin to avoid multiple initialization
  packages/core/src/plugins/css.ts
Labels: release: performance

#3685 feat(deps): bump Rspack v1.0.10
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3679 feat(plugin-stylus): use Rslib to bundle
  package.json
  packages/plugin-stylus/modern.config.ts
  packages/plugin-stylus/package.json
  packages/plugin-stylus/rslib.config.ts
  packages/plugin-stylus/src/index.ts
  pnpm-lock.yaml
Labels: release: feature

#3693 feat(plugin-solid): use Rslib to bundle
  packages/plugin-solid/modern.config.ts
  packages/plugin-solid/package.json
  packages/plugin-solid/rslib.config.ts
  packages/plugin-solid/src/index.ts
  packages/plugin-solid/tsconfig.json
  scripts/config/tsconfig-node16.json
Labels: release: feature

#3691 feat(plugin-babel): use Rslib to bundle
  packages/plugin-babel/modern.config.ts
  packages/plugin-babel/package.json
  packages/plugin-babel/rslib.config.ts
  packages/plugin-babel/src/helper.ts
  packages/plugin-babel/src/index.ts
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tsconfig.json
Labels: release: feature

#3698 feat(plugin-svgr): use Rslib to bundle
  packages/plugin-svgr/modern.config.ts
  packages/plugin-svgr/package.json
  packages/plugin-svgr/rslib.config.ts
  packages/plugin-svgr/src/loader.ts
  packages/plugin-svgr/tsconfig.json
Labels: release: feature

#3688 feat(core): add `distPath.assets` and `filename.assets`
  e2e/cases/emit-assets/index.test.ts
  e2e/cases/emit-assets/src/assets/test.json
  e2e/cases/emit-assets/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/constants.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/asset.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: feature

#3703 feat(plugin-sass): use Rslib to bundle
  packages/plugin-sass/modern.config.ts
  packages/plugin-sass/package.json
  packages/plugin-sass/prebundle.config.mjs
  packages/plugin-sass/rslib.config.ts
  packages/plugin-sass/src/helpers.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/src/types.ts
  packages/plugin-sass/tsconfig.json
  packages/plugin-stylus/package.json
  pnpm-lock.yaml
Labels: release: feature

#3704 feat(plugin-react): use Rslib to bundle
  packages/plugin-react/modern.config.ts
  packages/plugin-react/package.json
  packages/plugin-react/rslib.config.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tsconfig.json
Labels: release: feature

#3705 feat(plugin-svelte): use Rslib to bundle
  packages/plugin-svelte/modern.config.ts
  packages/plugin-svelte/package.json
  packages/plugin-svelte/rslib.config.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tsconfig.json
Labels: release: feature

#3710 fix: prebundle breaks RspackChain type
  packages/core/prebundle.config.mjs
Labels: release: bug fix

#3714 feat(core): allow to unset the title tag
  e2e/cases/html/title/index.test.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  website/docs/en/config/html/title.mdx
  website/docs/zh/config/html/title.mdx
Labels: release: feature

#3715 feat: make it easier to remove the built-in alias
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/resolve.test.ts
  website/docs/en/config/source/alias.mdx
  website/docs/zh/config/source/alias.mdx
Labels: release: feature

#3716 fix(create-rsbuild): require is not defined
  packages/create-rsbuild/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3723 fix: eco-ci unexpected inputs & token
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/release.yml
Labels: release: bug fix

#3725 feat(deps): bump @rspack/core 1.0.11
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: release: feature

#3727 feat(assets-retry): use Rslib to bundle
  packages/plugin-assets-retry/modern.config.ts
  packages/plugin-assets-retry/package.json
  packages/plugin-assets-retry/rslib.config.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/tsconfig.json
  pnpm-lock.yaml
Labels: release: feature

#3729 fix: add ref when call eco-ci-selected workflow
  .github/workflows/ecosystem-ci.yml
  .github/workflows/release.yml
Labels: release: bug fix

#3732 feat: add rawPublicVars for `loadEnv`
  e2e/cases/javascript-api/load-env/index.test.ts
  packages/core/src/loadEnv.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: feature

#3734 docs: add note for destructuring of `process.env` to CRA guide
  website/docs/en/guide/migration/cra.mdx
  website/docs/zh/guide/migration/cra.mdx
Labels: release: document

#3736 docs: fix lazy compilation typo
  website/docs/zh/config/dev/lazy-compilation.mdx
Labels: release: document

#3737 fix: allow to print URLs when HTML is disabled
  e2e/cases/server/print-urls/index.test.ts
  e2e/scripts/helper.ts
  packages/core/src/server/helper.ts
  website/docs/en/config/server/print-urls.mdx
  website/docs/zh/config/server/print-urls.mdx
Labels: release: bug fix

#3740 feat(deps): bump rspack 1.0.12
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3738 feat(plugin-react): allow to disable fast refresh
  e2e/cases/react/disable-fast-refresh/index.test.ts
  e2e/cases/react/disable-fast-refresh/rsbuild.config.ts
  e2e/cases/react/disable-fast-refresh/src/App.css
  e2e/cases/react/disable-fast-refresh/src/App.tsx
  e2e/cases/react/disable-fast-refresh/src/index.ts
  e2e/cases/react/disable-fast-refresh/tsconfig.json
  e2e/cases/server/hmr/index.test.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: feature

#3743 feat(deps): bump rspack 1.0.13
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3744 docs: add `process.env.NODE_ENV` inject tip
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#3750 fix: use `getCompilationHooks` of HTML plugin
  packages/core/package.json
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  pnpm-lock.yaml
Labels: release: bug fix

#3753 fix: revert to the `getHooks` of HTML plugin
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
Labels: release: bug fix

#3755 feat: add appendRules util to `tools.rspack` config
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/default.test.ts
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: release: feature

#3757 fix: configure the default assetPrefix for MF apps correctly
  packages/core/src/plugins/moduleFederation.ts
  website/docs/en/config/module-federation/options.mdx
  website/docs/zh/config/module-federation/options.mdx
Labels: release: bug fix

#3752 feat: output.filename.css allow function
  e2e/cases/filename-function/rsbuild.config.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/output.ts
  packages/core/src/types/config.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: feature

#3764 docs: improve `output.filename` function type
  e2e/cases/filename-function/index.test.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: document

#3767 docs: fix proxy links in features.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/guide/start/features.mdx
Labels: release: document

#3783 docs: add example for get assets info after building
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/guide/framework/vue.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#3785 feat: support `api.resolve` hook
  e2e/cases/plugin-api/plugin-resolve/index.test.ts
  e2e/cases/plugin-api/plugin-resolve/myPlugin.ts
  e2e/cases/plugin-api/plugin-resolve/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-resolve/src/b.js
  e2e/cases/plugin-api/plugin-resolve/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#3789 fix: `dev.assetPrefix: true` not work with `server.base`
  e2e/cases/server/base-url/index.test.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/output.ts
Labels: release: bug fix

#3790 fix: failed to load MF remote modules when using `server.base`
  e2e/cases/module-federation/index.test.ts
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#3791 docs: update zh/configure-rsbuild.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: release: document

#3792 docs: update en/configure-rsbuild.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
Labels: release: document

#3793 feat(deps): bump rspack 1.0.14
  packages/core/package.json
  packages/core/src/types/plugin.ts
  pnpm-lock.yaml
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#3797 docs: fix output.target link
  packages/core/src/types/plugin.ts
  website/docs/en/guide/start/features.mdx
  website/docs/zh/guide/start/features.mdx
Labels: release: document

#3798 docs: update issue template for upstream bugs
  .github/ISSUE_TEMPLATE/bug-report.en-US.yml
Labels: release: document

#3802 docs: update vite.mdx to fix npm command reference
  website/docs/en/guide/migration/vite.mdx
Labels: release: document

#3795 docs: add guide for using Web Workers
  website/docs/en/config/output/target.mdx
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/web-workers.mdx
  website/docs/zh/config/output/target.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/web-workers.mdx
Labels: release: document

#3804 feat: improve JSDoc for `output` and `html` configurations
  packages/core/src/types/config.ts
  website/docs/en/config/html/template.mdx
  website/docs/zh/config/html/template.mdx
Labels: release: feature

#3809 docs: add guide for worker-loader
  website/docs/en/guide/basic/web-workers.mdx
  website/docs/zh/guide/basic/web-workers.mdx
Labels: release: document

#3808 feat: add new `source.assetsInclude` config
  e2e/cases/assets/addtional-assets/index.test.ts
  e2e/cases/assets/addtional-assets/rsbuild.config.ts
  e2e/cases/assets/addtional-assets/src/index.js
  packages/core/src/plugins/asset.ts
  packages/core/src/types/config.ts
  website/docs/en/config/source/assets-include.mdx
  website/docs/en/config/source/exclude.mdx
  website/docs/en/config/source/include.mdx
  website/docs/zh/config/source/assets-include.mdx
Labels: release: feature

#3811 docs: update guide for additional asset types
  website/docs/en/config/source/assets-include.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/config/source/assets-include.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#3816 docs: add how to import absolute path in CSS files
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: document

#3817 docs: correct `rsbuild.addPlugins` typing
  packages/core/src/types/plugin.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#3818 fix: allow Rsbuild plugin to be registered times
  packages/core/src/pluginManager.ts
Labels: release: bug fix

#3815 fix(plugin-less): lessLoaderOptions.lessOptions.plugins has lose it's prototype.
  packages/core/src/internal.ts
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/index.test.ts
Labels: release: bug fix

#3826 feat: allow to configure `dataUriLimit` for extended assets
  packages/core/src/config.ts
  packages/core/src/plugins/asset.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/output/data-uri-limit.mdx
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/config/output/data-uri-limit.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: feature

#2469 feat(plugin-prefresh): support for prefresh
  e2e/cases/preact/prefresh-disabled/index.test.ts
  e2e/cases/preact/prefresh-disabled/rsbuild.config.ts
  e2e/cases/preact/prefresh-disabled/src/A.jsx
  e2e/cases/preact/prefresh-disabled/src/B.jsx
  e2e/cases/preact/prefresh-disabled/src/index.js
  e2e/cases/preact/prefresh/index.test.ts
  e2e/cases/preact/prefresh/rsbuild.config.ts
  e2e/cases/preact/prefresh/src/A.jsx
  e2e/cases/preact/prefresh/src/B.jsx
  e2e/cases/preact/prefresh/src/index.js
  packages/plugin-preact/package.json
  packages/plugin-preact/src/index.ts
  packages/plugin-preact/tests/index.test.ts
  pnpm-lock.yaml
Labels: release: feature

#3829 docs(plugin-prefresh): add `prefreshEnabled` option
  .changeset/afraid-beers-train.md
  website/docs/en/plugins/list/plugin-preact.mdx
  website/docs/zh/plugins/list/plugin-preact.mdx
Labels: release: document

#3825 docs: update example in transform-import.mdx
  website/docs/zh/config/source/transform-import.mdx
Labels: release: document

#3831 fix(plugin-preact): allow to use Prefresh in IE11
  packages/plugin-preact/src/index.ts
Labels: release: bug fix

#3835 feat(plugin-preact): add `include` and `exclude` options
  e2e/cases/preact/basic/rsbuild.config.ts
  e2e/cases/preact/prefresh/rsbuild.config.ts
  packages/plugin-preact/src/index.ts
  website/docs/en/plugins/list/plugin-preact.mdx
  website/docs/zh/config/source/exclude.mdx
  website/docs/zh/config/source/include.mdx
  website/docs/zh/plugins/list/plugin-preact.mdx
Labels: release: feature

#3838 fix: remove RC version from peer dependencies
  .changeset/fast-crabs-sin.md
  packages/compat/plugin-webpack-swc/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-babel/package.json
  packages/plugin-less/package.json
  packages/plugin-preact/package.json
  packages/plugin-react/package.json
  packages/plugin-sass/package.json
  packages/plugin-solid/package.json
  packages/plugin-stylus/package.json
  packages/plugin-svelte/package.json
  packages/plugin-svgr/package.json
  packages/plugin-vue/package.json
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: bug fix

#3839 docs: add Prefesh recognition tip
  website/docs/en/guide/framework/preact.mdx
  website/docs/zh/guide/framework/preact.mdx
Labels: release: document

#3840 docs(plugin-sass): add note for deprecation warnings
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: document

#3842 feat(plugin-less): allow to register multiple times
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-less/tests/index.test.ts
Labels: release: feature

#3843 feat(plugin-less): add `include` option
  .changeset/tiny-shoes-pump.md
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-less/tests/index.test.ts
  scripts/test-helper/src/index.ts
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
Labels: release: feature

#3844 feat(plugin-sass): allow to register multiple times
  packages/plugin-sass/src/index.ts
Labels: release: feature

#3845 feat(plugin-sass): add `include` option
  .changeset/thick-pens-sip.md
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/src/types.ts
  packages/plugin-sass/tests/index.test.ts
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: feature

#3849 feat: support import attributes
  e2e/cases/import-attributes/basic/index.test.ts
  e2e/cases/import-attributes/basic/loaderWith.js
  e2e/cases/import-attributes/basic/rsbuild.config.ts
  e2e/cases/import-attributes/basic/src/index.js
  e2e/cases/import-attributes/basic/src/pkg-1.json
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#3850 docs: add practices for multiple Less plugins
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: document

#3853 feat: apply SRI to preload link tags
  e2e/cases/sri/preload/index.test.ts
  e2e/cases/sri/preload/rsbuild.config.ts
  e2e/cases/sri/preload/src/foo.js
  e2e/cases/sri/preload/src/index.css
  e2e/cases/sri/preload/src/index.js
  packages/core/src/plugins/sri.ts
  website/docs/en/config/security/sri.mdx
  website/docs/zh/config/security/sri.mdx
Labels: release: feature

#3854 docs: update `tools.postcss` config loading notes
  website/docs/en/config/tools/postcss.mdx
  website/docs/zh/config/tools/postcss.mdx
Labels: release: document

#3852 fix(plugin/assets-retry): calculate the times independently in each retry
  e2e/cases/assets/assets-retry/index.test.ts
  e2e/cases/assets/assets-retry/src/testParallelRetryEntry.js
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
Labels: release: bug fix

#3858 feat: support for `postcssOptions` function
  e2e/cases/css/postcss-function-options-merge/index.test.ts
  e2e/cases/css/postcss-function-options-merge/postcss.config.ts
  e2e/cases/css/postcss-function-options-merge/postcssPlugin.cjs
  e2e/cases/css/postcss-function-options-merge/rsbuild.config.ts
  e2e/cases/css/postcss-function-options-merge/src/bar/index.css
  e2e/cases/css/postcss-function-options-merge/src/bar/index.html
  e2e/cases/css/postcss-function-options-merge/src/bar/index.ts
  e2e/cases/css/postcss-function-options-merge/src/foo/index.css
  e2e/cases/css/postcss-function-options-merge/src/foo/index.html
  e2e/cases/css/postcss-function-options-merge/src/foo/index.ts
  e2e/cases/css/postcss-function-options-merge/tailwind.config.bar.cjs
  e2e/cases/css/postcss-function-options-merge/tailwind.config.foo.cjs
  e2e/cases/css/postcss-function-options/index.test.ts
  e2e/cases/css/postcss-function-options/rsbuild.config.ts
  e2e/cases/css/postcss-function-options/src/bar/index.css
  e2e/cases/css/postcss-function-options/src/bar/index.html
  e2e/cases/css/postcss-function-options/src/bar/index.ts
  e2e/cases/css/postcss-function-options/src/foo/index.css
  e2e/cases/css/postcss-function-options/src/foo/index.html
  e2e/cases/css/postcss-function-options/src/foo/index.ts
  e2e/cases/css/postcss-function-options/tailwind.config.bar.cjs
  e2e/cases/css/postcss-function-options/tailwind.config.foo.cjs
  packages/core/src/plugins/css.ts
  packages/core/src/types/thirdParty.ts
  website/docs/en/config/tools/postcss.mdx
  website/docs/zh/config/tools/postcss.mdx
Labels: release: feature

#3860 fix(plugin/assets-retry): make loadScript safer
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
Labels: release: bug fix

#3861 feat(plugin-preact): integrate `@swc/plugin-prefresh` to enhance prefresh
  e2e/cases/preact/prefresh-context/index.test.ts
  e2e/cases/preact/prefresh-context/rsbuild.config.ts
  e2e/cases/preact/prefresh-context/src/A.jsx
  e2e/cases/preact/prefresh-context/src/index.js
  packages/plugin-preact/package.json
  packages/plugin-preact/src/index.ts
  pnpm-lock.yaml
Labels: release: feature

#3865 docs: correct CSS Modules named import example
  website/docs/en/config/output/css-modules.mdx
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
  website/docs/zh/guide/basic/css-modules.mdx
Labels: release: document

#3866 docs: add license to website footer
  website/theme/components/Copyright.tsx
Labels: release: document

#3713 feat(webpack): use Rslib to bundle
  e2e/cases/config/inspect-config/index.test.ts
  packages/compat/webpack/modern.config.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/rslib.config.ts
  packages/compat/webpack/src/build.ts
  packages/compat/webpack/src/createCompiler.ts
  packages/compat/webpack/src/index.cjs
  packages/compat/webpack/src/index.ts
  packages/compat/webpack/src/initConfigs.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/compat/webpack/src/plugin.ts
  packages/compat/webpack/src/progress/ProgressPlugin.ts
  packages/compat/webpack/src/progress/helpers/bar.ts
  packages/compat/webpack/src/progress/helpers/bus.ts
  packages/compat/webpack/src/progress/helpers/index.ts
  packages/compat/webpack/src/provider.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/compat/webpack/tsconfig.json
  scripts/config/rslib.config.ts
Labels: release: feature

#3870 feat(deps): bump rspack 1.1.0-beta.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3871 fix(webpack): avoid duplicate import core package
  nx.json
  packages/compat/webpack/rslib.config.ts
  scripts/config/rslib.config.ts
Labels: release: bug fix

#3873 feat: support `queueMicroTask` on the server side of SSR
  e2e/cases/server/ssr/src/assert.server.ts
  e2e/cases/server/ssr/src/index.server.tsx
  packages/core/src/server/runner/cjs.ts
Labels: release: feature
