Repository web-infra-dev/rsbuild, pull requests merged in 2024-09, with the labels that each got.

#3333 feat: add `dev.client.reconnect` option
  packages/core/src/client/hmr.ts
  packages/core/src/config.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/socketServer.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/dev/client.mdx
  website/docs/zh/config/dev/client.mdx
Labels: release: feature

#3334 fix: escape characters in compilationId
  packages/core/src/server/helper.ts
Labels: release: bug fix

#3337 fix: remove lib-lodash from experience chunks
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/optimization/split-chunk.mdx
  website/docs/zh/guide/optimization/split-chunk.mdx
Labels: release: bug fix

#3339 fix: increase WebSocket reconnect interval
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#3344 fix(create-rsbuild): broken shebang line in bin file
  packages/create-rsbuild/bin.js
  packages/create-rsbuild/package.json
  packages/create-rsbuild/src/index.ts
Labels: release: bug fix

#3346 docs: improve selecting SWC plugin version
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/en/guide/debug/debug-mode.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/basic/configure-swc.mdx
  website/docs/zh/guide/debug/debug-mode.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: release: document

#3347 docs: correct addPlugins type
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#3348 feat: support nested plugins
  packages/core/src/createRsbuild.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/builder.test.ts
  scripts/test-helper/src/rsbuild.ts
  website/docs/en/config/plugins.mdx
  website/docs/zh/config/plugins.mdx
Labels: release: feature

#3351 feat: export more sub-types of Rsbuild config
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/core/src/index.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/config/html/tags.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/config/html/tags.mdx
Labels: release: feature

#3352 fix: correct proxy options type
  packages/core/src/index.ts
  packages/core/src/server/proxy.ts
  packages/core/src/types/config.ts
  website/docs/en/config/server/proxy.mdx
  website/docs/zh/config/server/proxy.mdx
Labels: release: bug fix

#3356 docs: remove repeat info in rsbuild-0-x.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3355 docs: remove repeat info in en rsbuild-0-x.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3349 docs(landingpage): new landingpage aligned with Rspack
  pnpm-lock.yaml
  website/docs/en/index.mdx
  website/docs/zh/index.mdx
  website/i18n.json
  website/package.json
  website/rspress.config.ts
  website/theme/components/Benchmark.module.scss
  website/theme/components/Benchmark.tsx
  website/theme/components/Copyright.module.scss
  website/theme/components/Copyright.tsx
  website/theme/components/Hero.module.scss
  website/theme/components/Hero.tsx
  website/theme/components/ToolStack.module.scss
  website/theme/components/ToolStack.tsx
  website/theme/components/WhyRsbuild.module.scss
  website/theme/components/WhyRsbuild.tsx
  website/theme/components/utils.ts
  website/theme/index.scss
  website/theme/pages/index.tsx
Labels: release: document

#3359 fix: resolve mjs extension before js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/resolve.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3360 feat(deps): bump Rspack v1.0.1
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3371 docs(website): typo for easy to configure text on homepage
  website/i18n.json
Labels: release: document

#3370 fix: skip resolution if Rsdoctor plugin is registered
  e2e/cases/rsdoctor/index.test.ts
  e2e/cases/rsdoctor/mock/index.cjs
  packages/core/src/plugins/rsdoctor.ts
Labels: release: bug fix

#3375 feat(deps): bump Rspack 1.0.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3378 feat(deps): bump Rspack 1.0.3
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3379 docs: fix rsdoctor link
  website/docs/en/guide/debug/rsdoctor.mdx
  website/docs/zh/guide/debug/rsdoctor.mdx
Labels: release: document

#3384 fix: failed to use html-loader
  e2e/cases/html-loader/index.test.ts
  e2e/cases/html-loader/package.json
  e2e/cases/html-loader/rsbuild.config.ts
  e2e/cases/html-loader/src/index.js
  e2e/cases/html-loader/src/template.html
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3389 docs: improve `output.charset`
  website/docs/en/config/output/charset.mdx
  website/docs/zh/config/output/charset.mdx
Labels: release: document

#3395 docs: should manually call loadEnv method when using Rsbuild Environment API
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#3396 fix: lightningcss-loader not work when using PostCSS
  e2e/cases/css/style-loader-lightningcss/index.test.ts
  e2e/cases/css/style-loader-lightningcss/rsbuild.config.ts
  e2e/cases/css/style-loader-lightningcss/src/index.css
  e2e/cases/css/style-loader-lightningcss/src/index.js
  e2e/cases/css/tailwindcss-vendor-prefix/.browserslistrc
  e2e/cases/css/tailwindcss-vendor-prefix/index.test.ts
  e2e/cases/css/tailwindcss-vendor-prefix/postcss.config.cjs
  e2e/cases/css/tailwindcss-vendor-prefix/rsbuild.config.ts
  e2e/cases/css/tailwindcss-vendor-prefix/src/index.css
  e2e/cases/css/tailwindcss-vendor-prefix/src/index.html
  e2e/cases/css/tailwindcss-vendor-prefix/src/index.ts
  e2e/cases/css/tailwindcss-vendor-prefix/tailwind.config.cjs
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/prebundle.config.mjs
  packages/core/src/plugins/css.ts
  packages/core/src/types/thirdParty.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3400 docs: add guide for disabling Lightning CSS
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: document

#3403 feat: basic support for Svelte 5
  examples/svelte5/package.json
  examples/svelte5/rsbuild.config.ts
  examples/svelte5/src/App.svelte
  examples/svelte5/src/index.css
  examples/svelte5/src/index.js
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/index.test.ts
  pnpm-lock.yaml
Labels: release: feature

#3413 docs: polish previous announcements
  README.md
  README.zh-CN.md
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/community/releases/v0-2.mdx
  website/docs/en/community/releases/v0-3.mdx
  website/docs/en/community/releases/v0-4.mdx
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/community/releases/v0-6.mdx
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/community/releases/v0-2.mdx
  website/docs/zh/community/releases/v0-3.mdx
  website/docs/zh/community/releases/v0-4.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/community/releases/v0-6.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/start/index.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
  website/rspress.config.ts
Labels: release: document

#3416 docs: announcing Rsbuild 1.0 🎉
  scripts/dictionary.txt
  website/docs/en/community/releases/_meta.json
  website/docs/en/community/releases/v1-0.mdx
  website/docs/zh/community/releases/_meta.json
  website/docs/zh/community/releases/v1-0.mdx
Labels: release: document

#3425 docs: add build tools image to introduction
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#3426 docs: add announcement banner
  pnpm-lock.yaml
  website/docs/en/community/releases/v1-0.mdx
  website/docs/zh/community/releases/v1-0.mdx
  website/package.json
  website/theme/index.tsx
Labels: release: document

#3432 docs: fix typo in 1.0 announcement
  website/docs/zh/community/releases/v1-0.mdx
Labels: release: document

#3437 docs: add example for merging Rspack config
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: release: document

#3434 feat(plugin-stylus): support `define` option
  packages/plugin-stylus/src/index.ts
Labels: release: feature

#3439 docs(plugin-stylus): update `StylusOptions`
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/zh/plugins/list/plugin-stylus.mdx
Labels: release: document

#3441 fix(create-rsbuild): eslint-plugin-react-hooks version conflict
  packages/create-rsbuild/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3442 docs: add recommended PostCSS plugins when not using Lightning CSS
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: document

#3443 feat(deps): bump Rspack v1.0.4
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3446 fix: allow to configure `dev.hmr` in environments
  packages/core/src/provider/initConfigs.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: release: bug fix

#3456 docs: remove non-existent utils variable in rspack config
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
Labels: release: document

#3459 docs: server open priority
  website/docs/en/config/dev/lazy-compilation.mdx
  website/docs/en/config/security/sri.mdx
  website/docs/en/config/server/open.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/config/security/sri.mdx
  website/docs/zh/config/server/open.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: document

#3464 docs: update outdated glossary
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/shared/environment.mdx
  website/docs/en/shared/ssr.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/ssr.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/shared/environment.mdx
  website/docs/zh/shared/ssr.mdx
Labels: release: document

#3465 docs(guide): fix improper punctuation in Chinese guide
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#3466 fix: set resolve.tsConfig by rspack-chain
  packages/core/package.json
  packages/core/src/plugins/resolve.ts
  pnpm-lock.yaml
Labels: release: bug fix

#3469 docs(plugin-svgr): correct named export guide
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
Labels: release: document

#3470 fix(type): eco-ci fail of watching close callback type
  packages/core/src/provider/build.ts
Labels: release: bug fix

#3462 feat(core): warn leading slash for output.distPath.html and default to `./`
  packages/core/src/constants.ts
  packages/core/src/initPlugins.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/output/dist-path.mdx
  website/docs/zh/config/output/dist-path.mdx
Labels: release: feature

#3477 feat(deps): bump Rspack v1.0.5
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3480 fix: should format printed url when htmlPath startsWith `./`
  e2e/cases/server/print-urls/index.test.ts
  packages/core/src/server/helper.ts
Labels: release: bug fix

#3498 feat: expose `devServer.open` API
  packages/core/src/createRsbuild.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/server.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/open.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/core/tests/open.test.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#3508 docs: htmlPaths typo
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#3510 feat: disable preserveAllComments by default
  packages/compat/plugin-webpack-swc/src/plugin.ts
  packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/tools/swc.mdx
  website/docs/zh/config/tools/swc.mdx
Labels: release: feature

#3517 docs: update `source.exclude` usage
  website/docs/en/config/source/exclude.mdx
  website/docs/zh/config/source/exclude.mdx
Labels: release: document

#3518 docs: correct style-loader example
  website/docs/en/config/tools/style-loader.mdx
  website/docs/zh/config/tools/style-loader.mdx
Labels: release: document

#3524 docs: fix `webpackContext` link
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#3525 docs: add preset types
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/en/guide/basic/json-files.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/basic/typescript.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/optimization/inline-assets.mdx
  website/docs/zh/guide/basic/css-modules.mdx
  website/docs/zh/guide/basic/json-files.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/typescript.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/optimization/inline-assets.mdx
Labels: release: document

#3526 fix(types): missing toml module type
  packages/core/types.d.ts
Labels: release: bug fix

#3527 feat(create-rsbuild): adds decorator configs to lit-html templates an…
  examples/lit/rsbuild.config.ts
  packages/create-rsbuild/template-lit-js/rsbuild.config.mjs
  packages/create-rsbuild/template-lit-ts/rsbuild.config.ts
  packages/create-rsbuild/template-lit-ts/tsconfig.json
Labels: release: feature

#3530 fix(create-rsbuild): useDefineForClassFields in lit template
  packages/create-rsbuild/template-lit-ts/tsconfig.json
Labels: release: bug fix

#3536 feat: allow to import TS files with js extension
  e2e/cases/typescript/const-enum/index.test.ts
  e2e/cases/typescript/const-enum/src/foo.ts
  e2e/cases/typescript/const-enum/src/index.ts
  e2e/cases/typescript/const-enum/tsconfig.json
  e2e/cases/typescript/extension-alias/index.test.ts
  e2e/cases/typescript/extension-alias/src/bar.tsx
  e2e/cases/typescript/extension-alias/src/foo.ts
  e2e/cases/typescript/extension-alias/src/index.ts
  e2e/cases/typescript/extension-alias/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/package.json
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  pnpm-lock.yaml
Labels: release: feature

#3537 fix: remove temp code for PostCSS AST
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/prebundle.config.mjs
  packages/core/src/plugins/css.ts
  packages/core/src/types/thirdParty.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#3538 perf: avoid requiring empty module
  packages/core/prebundle.config.mjs
Labels: release: performance

#3541 docs: fix html typo
  website/docs/en/config/output/manifest.mdx
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/en/config/server/html-fallback.mdx
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/zh/guide/advanced/ssr.mdx
Labels: release: document

#3544 feat(deps): bump Rspack v1.0.6
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3549 feat(deps): bump Rspack v1.0.7
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#3550 fix(plugin-webpack-swc): swcMinimizerPlugin sourceMap config
  packages/compat/plugin-webpack-swc/src/minimizer.ts
  packages/compat/plugin-webpack-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-webpack-swc/tests/plugin.test.ts
Labels: release: bug fix

#3561 docs: update tools.htmlPlugin options tip
  website/docs/en/config/tools/html-plugin.mdx
  website/docs/zh/config/tools/html-plugin.mdx
Labels: release: document

#3564 fix(webpack): move @rsbuild/core to peer dependency
  packages/compat/webpack/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3568 perf: reduce require calls for compiled packages
  packages/core/prebundle.config.mjs
  packages/core/tsconfig.json
Labels: release: performance

#3571 feat: add node polyfill tip for `node:` protocol
  e2e/cases/node-polyfill-tip/with-protocol/index.test.ts
  e2e/cases/node-polyfill-tip/with-protocol/src/index.js
  e2e/cases/node-polyfill-tip/without-protocol/index.test.ts
  e2e/cases/node-polyfill-tip/without-protocol/src/index.js
  packages/core/src/helpers/stats.ts
Labels: release: feature

#3573 docs: add module federation assets retry
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: release: document

#3574 docs: add rspack config modification order
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#3575 fix(plugin-react): exclude node_modules from react-refresh plugin
  packages/plugin-react/src/react.ts
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: bug fix

#3576 fix: correct webpack error message
  packages/compat/webpack/src/build.ts
Labels: release: bug fix

#3577 docs: add example for splitting single CSS chunk
  website/docs/en/guide/optimization/split-chunk.mdx
  website/docs/zh/guide/optimization/split-chunk.mdx
Labels: release: document

#3581 docs: add tools.lightningcssLoader false tip
  website/docs/en/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
Labels: release: document

#3585 perf: remove browserslist-to-es-version dependency
  e2e/cases/browserslist/browserslist-config-mock/index.json
  packages/core/package.json
  packages/core/src/plugins/target.ts
  packages/core/tests/target.test.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: release: performance

#3587 perf: using browserslist-load-config to load browserslist
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/createContext.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: release: performance

#3596 feat(deps): bump rspack 1.0.8
  packages/core/package.json
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: release: feature

#3597 fix: moduleFederation option only supports Rspack
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#3598 fix: failed load browserslist string value
  e2e/cases/browserslist/package-config-array/index.test.ts
  e2e/cases/browserslist/package-config-array/package.json
  e2e/cases/browserslist/package-config-array/rsbuild.config.ts
  e2e/cases/browserslist/package-config-array/src/index.js
  e2e/cases/browserslist/package-config-object/index.test.ts
  e2e/cases/browserslist/package-config-object/package.json
  e2e/cases/browserslist/package-config-object/rsbuild.config.ts
  e2e/cases/browserslist/package-config-object/src/index.js
  e2e/cases/browserslist/package-config-string/index.test.ts
  e2e/cases/browserslist/package-config-string/package.json
  e2e/cases/browserslist/package-config-string/rsbuild.config.ts
  e2e/cases/browserslist/package-config-string/src/index.js
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#3606 feat: improve logs order when port is in use
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/prodServer.ts
  packages/core/tests/server.test.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/start/index.mdx
  website/docs/en/config/server/https.mdx
  website/docs/en/config/server/print-urls.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/start/index.mdx
  website/docs/zh/config/server/https.mdx
  website/docs/zh/config/server/print-urls.mdx
Labels: release: feature

#3613 fix: only print children compiler time when multi compiler
  packages/core/src/provider/createCompiler.ts
Labels: release: bug fix
