Repository web-infra-dev/rsbuild, pull requests merged in 2024-04, with the labels that each got.

#1971 feat: add error overlay footer tips
  packages/core/src/client/hmr/overlay.ts
Labels: change: feat

#1972 feat: support for plugin communication
  e2e/cases/javascript-api/plugin-expose/index.test.ts
  e2e/cases/javascript-api/plugin-expose/src/index.js
  packages/core/src/provider/initPlugins.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1973 docs: add guide for plugin communication
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/zh/plugins/dev/core.mdx
Labels: change: docs

#1982 docs(plugin-svgr): typo of export type
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
Labels: change: docs

#1981 feat: add new transform plugin API
  packages/core/src/provider/initPlugins.ts
  packages/core/src/rspack/transformLoader.ts
  packages/core/src/types.ts
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/types/rspack.ts
  packages/shared/src/types/utils.ts
Labels: change: feat

#1986 feat: expose resource path and query for transform API
  packages/core/src/rspack/transformLoader.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1987 fix: missing Rspack bindings
  packages/core/package.json
  packages/plugin-lightningcss/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1991 feat: allow to add dependency in transform API
  packages/core/src/rspack/transformLoader.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1998 types: make RsbuildPluginAPI readonly
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2001 types: export more hook fn types
  examples/react/rsbuild.config.ts
  packages/core/src/index.ts
  packages/document/docs/en/api/javascript-api/types.mdx
  packages/document/docs/zh/api/javascript-api/types.mdx
Labels: change: feat

#2002 feat: add emitFile to transform API
  e2e/cases/plugin-api/plugin-transform/index.test.ts
  e2e/cases/plugin-api/plugin-transform/myPlugin.ts
  packages/core/src/rspack/transformLoader.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2003 docs: add support for RSS feed
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/community/releases/v0-2.mdx
  packages/document/docs/en/community/releases/v0-3.mdx
  packages/document/docs/en/community/releases/v0-4.mdx
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/zh/community/releases/v0-1.mdx
  packages/document/docs/zh/community/releases/v0-2.mdx
  packages/document/docs/zh/community/releases/v0-3.mdx
  packages/document/docs/zh/community/releases/v0-4.mdx
  packages/document/docs/zh/community/releases/v0-5.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#2004 docs: make build profiling a separate page
  packages/document/docs/en/guide/debug/_meta.json
  packages/document/docs/en/guide/debug/build-profiling.mdx
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/zh/guide/debug/_meta.json
  packages/document/docs/zh/guide/debug/build-profiling.mdx
  packages/document/docs/zh/guide/optimization/build-performance.mdx
Labels: change: docs

#2006 docs: add RSS link to homepage
  packages/document/docs/en/index.md
  packages/document/docs/zh/index.md
Labels: change: docs

#2007 docs: generate both rss and atom types
  packages/document/docs/en/index.md
  packages/document/docs/zh/index.md
  packages/document/rspress.config.ts
Labels: change: docs

#2009 docs: fix broken inline code
  packages/document/docs/zh/config/dev/asset-prefix.mdx
  packages/document/docs/zh/config/output/asset-prefix.mdx
Labels: change: docs

#2011 fix: skip prenonnect when HTML is disabled
  packages/core/src/plugins/networkPerformance.ts
Labels: change: fix

#2012 fix: avoid adding unexpected trailing slash to href
  e2e/cases/html-tags/basic/index.test.ts
  e2e/cases/html-tags/basic/rsbuild.config.ts
  packages/shared/src/url.ts
Labels: change: fix

#2010 fix(server): unexpected dev config overwrite server config
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/socketServer.ts
  packages/shared/src/types/server.ts
Labels: change: fix

#2022 docs: add rspack-examples to intro page
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#2021 feat: support apply some stats options
  e2e/cases/stats/stats-options/index.test.ts
  e2e/cases/stats/stats-options/src/App.scss
  e2e/cases/stats/stats-options/src/index.tsx
  packages/compat/webpack/src/core/createCompiler.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/index.ts
  packages/core/src/provider/shared.ts
  packages/shared/src/types/stats.ts
Labels: change: feat

#2038 docs: add reading jsconfig.json guide
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1985 feat: compat with Rspack 0.6 CSS modules
  e2e/cases/check-syntax/index.test.ts
  e2e/cases/stats/stats-options/src/index.tsx
  packages/compat/webpack/src/core/createCompiler.ts
  packages/core/package.json
  packages/core/src/provider/plugins/css.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/document/docs/en/index.md
  packages/plugin-lightningcss/package.json
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  packages/shared/src/types/stats.ts
  packages/shared/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#2042 docs(plugin-eslint): fix incorrect description
  packages/document/docs/zh/plugins/list/plugin-eslint.mdx
Labels: change: docs

#2016 feat: only inject overlay code when dev.client.overlay is enabled
  packages/core/modern.config.ts
  packages/core/package.json
  packages/core/src/client/hmr/createSocketUrl.ts
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/hmr/types.d.ts
  packages/core/src/client/overlay.ts
  packages/core/src/provider/devMiddleware.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/shared/src/types/server.ts
Labels: change: feat

#2045 fix: allow to use error overlay when hmr is disabled
  packages/core/src/client/hmr/createSocketUrl.ts
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/hmr/types.d.ts
  packages/core/src/provider/devMiddleware.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/server.ts
Labels: change: fix

#2041 feat(devServer): support add etag header
  packages/core/src/server/compilerDevMiddleware.ts
  packages/shared/compiled/webpack-dev-middleware/index.js
  packages/shared/compiled/webpack-dev-middleware/package.json
  packages/shared/compiled/webpack-dev-middleware/types/index.d.ts
  packages/shared/src/types/server.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: feat

#2049 feat: bump Rspack v0.6.0
  packages/core/package.json
  packages/plugin-lightningcss/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2050 feat: enable error overlay by default
  e2e/cases/server/overlay/rsbuild.config.ts
  packages/core/src/provider/config.ts
  packages/document/docs/en/config/dev/client.mdx
  packages/document/docs/zh/config/dev/client.mdx
Labels: change: feat

#2018 feat: support for Vue3 JSX HMR
  e2e/cases/solid/ref/src/App.jsx
  e2e/cases/vue/jsx-hmr/index.test.ts
  e2e/cases/vue/jsx-hmr/package.json
  e2e/cases/vue/jsx-hmr/rsbuild.config.ts
  e2e/cases/vue/jsx-hmr/src/Comp.tsx
  e2e/cases/vue/jsx-hmr/src/Comps.jsx
  e2e/cases/vue/jsx-hmr/src/Script.vue
  e2e/cases/vue/jsx-hmr/src/SrcImport.jsx
  e2e/cases/vue/jsx-hmr/src/SrcImport.vue
  e2e/cases/vue/jsx-hmr/src/TsImport.vue
  e2e/cases/vue/jsx-hmr/src/TsImportFile.ts
  e2e/cases/vue/jsx-hmr/src/index.jsx
  e2e/cases/vue/jsx-hmr/src/setup-syntax-jsx.vue
  packages/document/docs/en/config/tools/swc.mdx
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#2051 docs: add the transform plugin API
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/config/html/template-parameters.mdx
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/start/glossary.mdx
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/en/plugins/dev/index.md
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-rem.mdx
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/dev/core.mdx
  packages/shared/src/types/plugin.ts
Labels: change: docs

#2054 docs: update URL of some design resoureces
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/community/releases/v0-2.mdx
  packages/document/docs/en/community/releases/v0-3.mdx
  packages/document/docs/en/community/releases/v0-4.mdx
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/community/releases/v0-1.mdx
  packages/document/docs/zh/community/releases/v0-2.mdx
  packages/document/docs/zh/community/releases/v0-3.mdx
  packages/document/docs/zh/community/releases/v0-4.mdx
  packages/document/docs/zh/community/releases/v0-5.mdx
  packages/document/docs/zh/index.md
  packages/document/rspress.config.ts
  packages/document/theme/index.scss
  packages/document/theme/index.tsx
Labels: change: docs

#2058 docs: fix expose typo
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/zh/plugins/dev/core.mdx
Labels: change: docs

#2055 docs: announcing Rsbuild v0.6
  packages/document/docs/en/community/releases/_meta.json
  packages/document/docs/en/community/releases/v0-6.mdx
  packages/document/docs/zh/community/releases/_meta.json
  packages/document/docs/zh/community/releases/v0-6.mdx
  scripts/dictionary.txt
Labels: change: docs

#2059 fix: change rspack min version to 0.6.0
  packages/core/src/provider/shared.ts
Labels: change: fix

#2063 docs: fix output.inlineStyle example
  packages/document/docs/en/config/output/inline-scripts.mdx
  packages/document/docs/en/config/output/inline-styles.mdx
  packages/document/docs/zh/config/output/inline-scripts.mdx
  packages/document/docs/zh/config/output/inline-styles.mdx
Labels: change: docs

#2065 fix(deps): bump rspack to 0.6.1
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#2067 docs: add async chunk all in one example
  packages/document/docs/en/config/performance/chunk-split.mdx
  packages/document/docs/en/guide/optimization/split-chunk.md
  packages/document/docs/zh/config/performance/chunk-split.mdx
  packages/document/docs/zh/guide/optimization/split-chunk.md
Labels: change: docs

#2068 feat: support resourceQuery for transform API
  packages/core/src/provider/initPlugins.ts
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/zh/plugins/dev/core.mdx
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2069 fix(plugin-solid): only enable solid-refresh when target is web
  .changeset/many-cycles-end.md
  packages/plugin-solid/src/index.ts
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/utils.ts
Labels: change: fix

#2071 docs: improve quickstart guide
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2075 docs: add transform API handler param
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/en/plugins/dev/index.md
  packages/document/docs/zh/plugins/dev/core.mdx
  packages/document/docs/zh/plugins/dev/index.md
Labels: change: docs

#2078 feat: add modifyHTMLTags plugin API
  e2e/cases/plugin-api/plugin-modify-tags/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags/myPlugin.ts
  e2e/cases/plugin-api/plugin-modify-tags/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-modify-tags/src/index.css
  e2e/cases/plugin-api/plugin-modify-tags/src/index.js
  packages/compat/webpack/src/provider.ts
  packages/compat/webpack/src/shared.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/initHooks.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/index.ts
  packages/core/src/provider/initPlugins.ts
  packages/core/src/provider/provider.ts
  packages/core/src/provider/shared.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/hooks.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
  packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2081 fix: ensure `crossorigin` can be applied to all tags
  e2e/cases/html/cross-origin/index.test.ts
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/HtmlCrossOriginPlugin.ts
  packages/core/tests/html.test.ts
  packages/plugin-rem/src/index.ts
  packages/shared/src/chain.ts
Labels: change: fix

#2083 docs: update features list
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/zh/guide/start/features.mdx
Labels: change: docs

#2090 perf: remove webpack-sources dependency
  e2e/cases/html/app-icon/index.test.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/shared/compiled/webpack-sources/index.d.ts
  packages/shared/compiled/webpack-sources/index.js
  packages/shared/compiled/webpack-sources/license
  packages/shared/compiled/webpack-sources/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: perf

#2096 docs: update assets domain
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/community/releases/v0-2.mdx
  packages/document/docs/en/community/releases/v0-3.mdx
  packages/document/docs/en/community/releases/v0-4.mdx
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/en/community/releases/v0-6.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/community/releases/v0-1.mdx
  packages/document/docs/zh/community/releases/v0-2.mdx
  packages/document/docs/zh/community/releases/v0-3.mdx
  packages/document/docs/zh/community/releases/v0-4.mdx
  packages/document/docs/zh/community/releases/v0-5.mdx
  packages/document/docs/zh/community/releases/v0-6.mdx
  packages/document/docs/zh/index.md
  packages/document/rspress.config.ts
Labels: change: docs

#2097 docs: add image assets guide to contributing
  CONTRIBUTING.md
Labels: change: docs

#2099 feat(server): add HMR forced reload error log
  packages/core/src/client/hmr/index.ts
Labels: change: feat

#2101 docs: add api.modifyHTMLTags to document
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#2103 fix: failed to resolve mjs or cjs entry
  packages/core/src/config.ts
Labels: change: fix

#2114 fix: remove the SIGINT listener
  packages/shared/src/utils.ts
Labels: change: fix

#2118 docs: update Rspack v0.6 link
  packages/core/src/provider/initPlugins.ts
  packages/document/docs/en/community/releases/v0-6.mdx
  packages/document/docs/zh/community/releases/v0-6.mdx
  packages/shared/src/utils.ts
Labels: change: docs

#2122 perf: use Rspack native IgnorePlugin
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/src/plugins/moment.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/provider/shared.ts
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/shared/src/types/hooks.ts
Labels: change: perf

#2128 docs: update unocss config
  packages/document/docs/en/guide/basic/unocss.mdx
  packages/document/docs/zh/guide/basic/unocss.mdx
Labels: change: docs

#2115 fix(plugin-assets-retry): runtime code is cut off by </script> and support es5
  e2e/cases/assets-retry/index.test.ts
  e2e/cases/assets-retry/src/App.css
  e2e/cases/assets-retry/src/App.tsx
  e2e/cases/assets-retry/src/AsyncCompTest.css
  e2e/cases/assets-retry/src/AsyncCompTest.tsx
  e2e/cases/assets-retry/src/CompTest.css
  e2e/cases/assets-retry/src/CompTest.tsx
  e2e/cases/assets-retry/src/ErrorBoundary.tsx
  e2e/cases/assets-retry/src/index.tsx
  packages/plugin-assets-retry/src/runtime/index.ts
Labels: change: fix

#2129 docs: fix entry function example
  packages/document/docs/en/config/source/entry.mdx
  packages/document/docs/zh/config/source/entry.mdx
Labels: change: docs

#2134 feat: add new `output.emitAssets` config
  .changeset/fair-singers-chew.md
  e2e/cases/emit-assets/index.test.ts
  e2e/cases/emit-assets/rsbuild.config.ts
  e2e/cases/emit-assets/src/index.js
  packages/core/src/config.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/asset.ts
  packages/document/docs/en/config/output/emit-assets.mdx
  packages/document/docs/en/guide/basic/static-assets.md
  packages/document/docs/zh/config/output/emit-assets.mdx
  packages/document/docs/zh/guide/basic/static-assets.md
  packages/shared/src/types/config/output.ts
Labels: change: feat

#2135 docs: bump Rspress v1.18.2 and remove dividers
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/en/community/releases/v0-6.mdx
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/optimization/split-chunk.md
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/community/releases/v0-5.mdx
  packages/document/docs/zh/community/releases/v0-6.mdx
  packages/document/docs/zh/guide/basic/cli.mdx
  packages/document/docs/zh/guide/optimization/split-chunk.md
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: docs

#2139 fix: failed access globalThis in legacy browsers
  packages/core/src/client/overlay.ts
Labels: change: fix

#2142 fix(plugin-vue2): fix loaders duplicating problem caused by vue-loader@15
  e2e/cases/vue2/sfc-style/index.test.ts
  e2e/cases/vue2/sfc-style/src/App.vue
  packages/plugin-vue2/src/VueLoader15PitchFixPlugin.ts
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/chain.ts
Labels: change: fix

#2147 docs: simplify environment setup guide
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2148 docs: add online example to quick start
  scripts/dictionary.txt
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2149 fix: ignore the CSS conflicting order warning by default
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2152 docs: add node version badge to README
  README.md
  README.zh-CN.md
Labels: change: docs

#2154 fix: skip open in codesandbox
  packages/core/src/plugins/startUrl.ts
Labels: change: fix

#2155 docs: link more content to Rspack website
  packages/core/src/client/hmr/index.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/config/source.ts
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/en/config/output/asset-prefix.mdx
  website/docs/en/config/output/externals.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/guide/debug/debug-mode.md
  website/docs/en/guide/faq/features.md
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/en/guide/optimization/split-chunk.md
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/plugins/dev/index.md
  website/docs/en/plugins/list/plugin-styled-components.mdx
  website/docs/zh/config/output/externals.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/guide/debug/debug-mode.md
  website/docs/zh/guide/faq/features.md
  website/docs/zh/guide/optimization/build-performance.mdx
  website/docs/zh/guide/optimization/split-chunk.md
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/plugins/dev/index.md
  website/docs/zh/plugins/list/plugin-styled-components.mdx
Labels: change: docs

#2143 feat(plugin-react): enable support for profiling React in prod env
  e2e/cases/react/enable-profiler/index.test.ts
  e2e/cases/react/enable-profiler/rsbuild.config.ts
  e2e/cases/react/enable-profiler/src/App.jsx
  e2e/cases/react/enable-profiler/src/index.js
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  website/docs/en/plugins/list/plugin-react.mdx
Labels: change: feat

#2157 docs(plugin-react): translate enableProfiler to Chinese
  .changeset/clean-hornets-move.md
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: change: docs

#2168 feat: proxy bypass support return true
  packages/core/src/server/proxy.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/server/proxy.mdx
  website/docs/zh/config/server/proxy.mdx
Labels: change: feat

#2171 fix: should not log compile warning when warning is ignored
  packages/core/src/provider/shared.ts
Labels: change: fix

#2145 feat(server): support dev.watchFiles config
  e2e/cases/server/watch-files/assets/example.txt
  e2e/cases/server/watch-files/assets/example2.txt
  e2e/cases/server/watch-files/index.test.ts
  e2e/cases/server/watch-files/other/other.txt
  e2e/cases/server/watch-files/rsbuild.config.ts
  e2e/cases/server/watch-files/src/App.tsx
  e2e/cases/server/watch-files/src/index.tsx
  packages/core/src/client/hmr/index.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/watchFiles.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/server.ts
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: change: feat

#2176 feat: support plugin-basic-ssl
  packages/plugin-basic-ssl/LICENSE
  packages/plugin-basic-ssl/README.md
  packages/plugin-basic-ssl/modern.config.ts
  packages/plugin-basic-ssl/package.json
  packages/plugin-basic-ssl/src/index.ts
  packages/plugin-basic-ssl/src/util.ts
  packages/plugin-basic-ssl/tsconfig.json
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/config/server/https.mdx
  website/docs/zh/config/server/https.mdx
Labels: change: feat

#2177 docs: bump Rspress 1.18.3 and add title suffix
  pnpm-lock.yaml
  website/docs/en/index.md
  website/docs/zh/index.md
  website/package.json
Labels: change: docs

#2179 fix: remove unused sourceMap default value of swc-loader
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2174 feat(server): support watch publicDir in dev
  e2e/cases/server/public-dir/publicDir.test.ts
  packages/core/src/config.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/watchFiles.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/server/public-dir.mdx
  website/docs/zh/config/server/public-dir.mdx
Labels: change: feat

#2182 feat(deps): bump Rspack v0.6.3
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2169 types: import swc loader options from Rspack
  .changeset/dry-penguins-ring.md
  packages/core/src/provider/plugins/swc.ts
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/shared/src/chain.ts
  packages/shared/src/types/config/tools.ts
  packages/shared/src/types/rspack.ts
  website/docs/en/guide/optimization/split-chunk.md
  website/docs/zh/config/dev/watch-files.mdx
Labels: change: feat

#2184 docs: add plugin-basic-ssl document
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/start/index.mdx
  website/docs/en/config/server/https.mdx
  website/docs/en/guide/start/npm-packages.mdx
  website/docs/en/plugins/list/_meta.json
  website/docs/en/plugins/list/index.md
  website/docs/en/plugins/list/plugin-basic-ssl.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/start/index.mdx
  website/docs/zh/config/server/https.mdx
  website/docs/zh/guide/start/npm-packages.mdx
  website/docs/zh/plugins/list/_meta.json
  website/docs/zh/plugins/list/index.md
  website/docs/zh/plugins/list/plugin-basic-ssl.mdx
Labels: change: docs

#2186 docs: update Rspack links
  packages/plugin-styled-components/src/index.ts
  website/docs/en/community/releases/v0-3.mdx
  website/docs/en/community/releases/v0-6.mdx
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/config/tools/swc.mdx
  website/docs/en/guide/basic/static-assets.md
  website/docs/en/guide/faq/exceptions.md
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/plugins/list/plugin-styled-components.mdx
  website/docs/en/shared/bundlerChain.md
  website/docs/en/shared/onBeforeBuild.md
  website/docs/en/shared/onBeforeCreateCompiler.md
  website/docs/zh/community/releases/v0-3.mdx
  website/docs/zh/community/releases/v0-6.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/swc.mdx
  website/docs/zh/guide/basic/static-assets.md
  website/docs/zh/guide/faq/exceptions.md
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/plugins/list/plugin-styled-components.mdx
  website/docs/zh/shared/bundlerChain.md
  website/docs/zh/shared/onBeforeBuild.md
  website/docs/zh/shared/onBeforeCreateCompiler.md
Labels: change: docs

#2187 fix(plugin-check-syntax): allow to match assets with query
  packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
Labels: change: fix

#2190 feat(plugin-react): support for configuring react refresh plugin
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: change: feat

#2086 feat(plugin-asset-retry): support async chunk retry
  e2e/cases/assets-retry/index.test.ts
  e2e/cases/assets-retry/src/App.tsx
  packages/plugin-assets-retry/scripts/postCompile.js
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/types.ts
  packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
  packages/plugin-assets-retry/tests/assetsRetry.test.ts
  packages/shared/package.json
  packages/shared/src/chain.ts
  packages/shared/src/rspack.ts
Labels: change: feat

#2196 feat(core): export the rspack object
  .changeset/few-lobsters-yell.md
  packages/core/src/index.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/plugins/minimize.ts
  packages/core/src/provider/plugins/output.ts
  packages/core/src/provider/plugins/progress.ts
  packages/core/src/provider/plugins/rspackProfile.ts
  packages/core/src/provider/rspackConfig.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/shared/package.json
  packages/shared/src/rspack.ts
  packages/shared/src/types/config/tools.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2197 fix(core): prebundle should be devDependencies
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#2202 feat: supports use targets as a filter of the transform API
  e2e/cases/plugin-api/plugin-transform-by-targets/index.test.ts
  e2e/cases/plugin-api/plugin-transform-by-targets/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-by-targets/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-by-targets/src/index.js
  packages/core/src/initPlugins.ts
  packages/shared/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: feat

#2206 docs: CSS modules named imports example
  e2e/cases/css/css-modules-named-export/index.test.ts
  e2e/cases/css/css-modules-named-export/src/a.module.css
  e2e/cases/css/css-modules-named-export/src/b.module.scss
  e2e/cases/css/css-modules-named-export/src/c.module.less
  e2e/cases/css/css-modules-named-export/src/index.js
  website/docs/en/guide/basic/css-modules.md
  website/docs/zh/guide/basic/css-modules.md
Labels: change: docs

#2205 feat(server): when liveReload is disabled, the page does not reload in HMR
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/hmr/types.d.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
  packages/shared/src/types/server.ts
Labels: change: feat

#2207 feat(create-rsbuild): upgrade react to v18.3.0
  e2e/cases/source-map/package.json
  e2e/package.json
  examples/mdx/package.json
  examples/module-federation/host/package.json
  examples/module-federation/remote/package.json
  examples/react/package.json
  examples/webpack/package.json
  packages/create-rsbuild/template-react-js/package.json
  packages/create-rsbuild/template-react-ts/package.json
  pnpm-lock.yaml
  website/package.json
Labels: change: feat

#2209 docs: improve CSS modules type declaration
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/zh/guide/basic/css-modules.mdx
Labels: change: docs

#2201 fix(plugin-assets-retry): execute onSuccess onFail once in async-chunk-retry
  e2e/cases/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: change: fix

#2210 fix(assets-entry): string.endsWith compatibility issue
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: change: fix

#2213 fix(asset-retry): should use unminified code in dev builds
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: change: fix

#2220 feat(deps): bump html-rspack-plugin@5.7.0
  packages/compat/webpack/package.json
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2225 fix(overlay): fallback to moduleName if moduleIdentifier parse failed
  packages/core/src/client/formatStats.ts
Labels: change: fix

#2226 fix: failed to display overlay when use MF
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/overlay.ts
Labels: change: fix

#2241 types: fix types broken by prebundle
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/proxy.ts
  packages/create-rsbuild/package.json
  packages/plugin-babel/package.json
  packages/plugin-rem/package.json
  packages/plugin-svgr/package.json
  packages/plugin-yaml/package.json
  packages/shared/package.json
  packages/shared/prebundle.config.mjs
  packages/shared/src/types/config/server.ts
  packages/shared/src/types/thirdParty.ts
  pnpm-lock.yaml
Labels: change: feat

#2242 feat: ship runtime code in es2017 by default
  packages/compat/plugin-swc/src/plugin.ts
  packages/core/modern.config.ts
  packages/core/src/plugins/target.ts
  packages/core/src/provider/plugins/swc.ts
  packages/shared/src/chain.ts
Labels: change: feat

#2244 fix(hmr): should not register node compiler event
  packages/core/tests/server.test.ts
  packages/shared/src/utils.ts
Labels: change: fix
