Repository web-infra-dev/rsbuild, pull requests merged in 2024-12, with the labels that each got.

#4095 docs: improve dedupe guides
  website/docs/en/config/resolve/dedupe.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/zh/config/resolve/dedupe.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/optimization/optimize-bundle.mdx
Labels: release: document

#4097 fix: remove unused if condition
  packages/core/src/plugins/resolve.ts
Labels: release: bug fix

#4100 docs: update environment and template parameters
  website/docs/en/config/environments.mdx
  website/docs/en/config/html/template-parameters.mdx
  website/docs/zh/config/environments.mdx
  website/docs/zh/config/html/template-parameters.mdx
Labels: release: document

#4106 fix: `resolve.dedupe` may set incorrect path
  packages/core/src/plugins/resolve.ts
Labels: release: bug fix

#4108 fix: improve compatibility of `source.alias`
  packages/core/src/config.ts
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/core/tests/mergeConfig.test.ts
  packages/core/tests/resolve.test.ts
Labels: release: bug fix

#4109 docs: move alias config to resolve
  package.json
  pnpm-lock.yaml
  website/docs/en/config/environments.mdx
  website/docs/en/config/resolve/alias-strategy.mdx
  website/docs/en/config/resolve/alias.mdx
  website/docs/en/config/resolve/dedupe.mdx
  website/docs/en/guide/advanced/alias.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/environments.mdx
  website/docs/zh/config/resolve/alias-strategy.mdx
  website/docs/zh/config/resolve/alias.mdx
  website/docs/zh/config/resolve/dedupe.mdx
  website/docs/zh/guide/advanced/alias.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/start/features.mdx
  website/package.json
  website/rspress.config.ts
Labels: release: document

#4113 docs: add environment API type
  website/docs/en/api/javascript-api/environment-context.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/api/javascript-api/environment-context.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: release: document

#4117 docs: update some links
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#4122 fix(plugin-sass): mute import deprecation warning
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: bug fix

#4123 docs: import Node.js addons
  website/docs/en/config/output/target.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/output/target.mdx
  website/docs/zh/guide/start/features.mdx
Labels: release: document

#4125 fix: correct `cliShortcuts.custom` typing
  packages/core/src/types/config.ts
  website/docs/en/config/dev/cli-shortcuts.mdx
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: bug fix

#4127 docs: fix mistakes in cli.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: document

#4126 feat: make environment API result cacheable
  e2e/cases/server/ssr/index.test.ts
  e2e/cases/server/ssr/src/index.server.tsx
  packages/core/src/server/devServer.ts
  packages/core/src/server/environment.ts
Labels: release: feature

#4142 feat(create-rsbuild): create React 19 project by default
  .changeset/angry-berries-grab.md
  .changeset/perfect-suns-attend.md
  e2e/cases/react/enable-profiler/index.test.ts
  e2e/cases/source-map/package.json
  e2e/cases/svg/svgr-external-react/index.test.ts
  e2e/cases/svg/svgr-external-react/rsbuild.config.ts
  e2e/cases/svg/svgr-external-react/src/App.css
  e2e/cases/svg/svgr-external-react/src/App.jsx
  e2e/cases/svg/svgr-external-react/src/index.js
  e2e/cases/svg/svgr-external-react/static/index.html
  e2e/package.json
  examples/module-federation-v2/host/package.json
  examples/module-federation-v2/remote/package.json
  examples/module-federation/host/package.json
  examples/module-federation/remote/package.json
  examples/react/package.json
  examples/webpack/package.json
  packages/create-rsbuild/template-react-js/package.json
  packages/create-rsbuild/template-react-ts/package.json
  pnpm-lock.yaml
  website/docs/en/config/resolve/alias.mdx
  website/docs/en/config/resolve/dedupe.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/config/resolve/alias.mdx
  website/docs/zh/config/resolve/dedupe.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/package.json
Labels: release: feature

#4146 feat: add `resolve.extensions` config
  packages/core/src/config.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/resolve.test.ts
Labels: release: feature

#4147 docs: add `resolve.extensions` config
  pnpm-lock.yaml
  website/docs/en/config/resolve/extensions.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/config/resolve/extensions.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/package.json
Labels: release: document

#4129 fix(plugin-assets-retry): support `output.assetPrefix` with absolute url
  e2e/cases/assets/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: release: bug fix

#4149 docs: update preconnect and dns-prefetch configurations
  e2e/cases/performance/preconnect/rsbuild.config.ts
  packages/core/src/plugins/resourceHints.ts
  packages/core/src/types/config.ts
  scripts/dictionary.txt
  website/docs/en/config/performance/dns-prefetch.mdx
  website/docs/en/config/performance/preconnect.mdx
  website/docs/zh/config/performance/dns-prefetch.mdx
  website/docs/zh/config/performance/preconnect.mdx
Labels: release: document

#4153 fix: print file size should ends with a new line
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#4154 docs: update `createRsbuild` options
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: document

#4155 fix: perform cleanup at the right time
  packages/core/src/cli/init.ts
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
Labels: release: bug fix

#4156 fix: correct the restart build message
  packages/core/src/server/restart.ts
Labels: release: bug fix

#4160 docs: correct Rspack links
  website/docs/en/config/dev/lazy-compilation.mdx
  website/docs/en/config/output/polyfill.mdx
  website/docs/en/config/tools/css-extract.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/plugins/list/plugin-preact.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/config/output/polyfill.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: release: document

#4165 fix: should not trigger dev hooks when building
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/types/context.ts
Labels: release: bug fix

#4168 docs(plugin-svgr): explain base64 URL
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
Labels: release: document

#4169 docs: set title for SPA
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: document

#4170 docs: upgrade to React 19 and fix peer issues
  e2e/package.json
  examples/module-federation-v2/host/package.json
  examples/module-federation-v2/remote/package.json
  pnpm-lock.yaml
  website/package.json
Labels: release: document

#4175 fix(webpack): use html-webpack-plugin by default
  .changeset/chilled-falcons-fetch.md
  e2e/cases/html/html-tags/function-usage/index.test.ts
  e2e/cases/html/inject/index.test.ts
  e2e/cases/html/meta/index.test.ts
  e2e/cases/html/script-loading/index.test.ts
  e2e/cases/javascript-api/build/index.test.ts
  e2e/cases/nonce/basic/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags/index.test.ts
  e2e/cases/sri/algotithm/index.test.ts
  e2e/cases/sri/basic/index.test.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/src/provider.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/index.ts
  packages/core/src/provider/helpers.ts
  pnpm-lock.yaml
Labels: release: bug fix

#4178 docs: improve `server.port`
  website/docs/en/config/server/port.mdx
  website/docs/zh/config/server/port.mdx
Labels: release: document

#4182 fix(create-rsbuild): remove Svelte 4 template
  examples/svelte/package.json
  packages/create-rsbuild/src/index.ts
  packages/create-rsbuild/template-svelte4-js/package.json
  packages/create-rsbuild/template-svelte4-js/rsbuild.config.mjs
  packages/create-rsbuild/template-svelte4-js/src/App.svelte
  packages/create-rsbuild/template-svelte4-js/src/index.css
  packages/create-rsbuild/template-svelte4-js/src/index.js
  packages/create-rsbuild/template-svelte4-ts/package.json
  packages/create-rsbuild/template-svelte4-ts/rsbuild.config.ts
  packages/create-rsbuild/template-svelte4-ts/src/App.svelte
  packages/create-rsbuild/template-svelte4-ts/src/env.d.ts
  packages/create-rsbuild/template-svelte4-ts/src/index.css
  packages/create-rsbuild/template-svelte4-ts/src/index.ts
  packages/create-rsbuild/template-svelte4-ts/tsconfig.json
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: bug fix

#4184 fix(plugin-svelte): require is not defined in computing sveltePath variable
  packages/plugin-svelte/src/index.ts
Labels: release: bug fix

#4183 feat: add `server.cors` config
  e2e/cases/server/cors/index.test.ts
  e2e/cases/server/cors/src/index.js
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  pnpm-lock.yaml
Labels: release: feature

#4187 docs: add `server.cors` config
  website/docs/en/config/server/cors.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/config/server/cors.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#4189 docs: improve PostCSS add plugins example
  website/docs/en/config/tools/postcss.mdx
  website/docs/zh/config/tools/postcss.mdx
Labels: release: document

#4193 docs: examples for Environment Context
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
Labels: release: document

#4196 docs: clean up unnecessary Rspress config
  website/rspress.config.ts
Labels: release: document

#4198 docs: React Compiler for React 17 and 18
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: release: document

#4199 docs(website): revise the description
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#4208 docs: improve code splitting
  website/docs/en/config/performance/chunk-split.mdx
  website/docs/en/guide/optimization/_meta.json
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/performance/chunk-split.mdx
  website/docs/zh/guide/optimization/_meta.json
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/optimize-bundle.mdx
  website/docs/zh/guide/start/features.mdx
Labels: release: document

#4212 fix(HMR): should reload page when HTML template changed
  e2e/cases/server/reload-html/index.test.ts
  e2e/cases/server/reload-html/rsbuild.config.ts
  e2e/cases/server/reload-html/src/index.html
  e2e/cases/server/reload-html/src/index.js
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#4215 docs: multi environments build order
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: release: document

#4217 feat: support for `importModule` in `api.transform`
  e2e/cases/plugin-api/plugin-transform-import-module/index.test.ts
  e2e/cases/plugin-api/plugin-transform-import-module/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-import-module/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-import-module/src/foo.ts
  e2e/cases/plugin-api/plugin-transform-import-module/src/index.css
  e2e/cases/plugin-api/plugin-transform-import-module/src/index.js
  packages/core/src/loader/transformLoader.ts
  packages/core/src/types/plugin.ts
Labels: release: feature

#4220 fix: should copy publicDir to the environment distDir when multiple environments
  e2e/cases/server/public-dir/publicDir.test.ts
  packages/core/src/plugins/server.ts
Labels: release: bug fix

#4222 fix: pin rspack version
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4230 docs: configure alias via jsconfig.json
  website/docs/en/guide/advanced/alias.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/zh/guide/advanced/alias.mdx
  website/docs/zh/guide/migration/cra.mdx
Labels: release: document

#4238 docs: update release workflow in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release: document

#4252 fix: should await inspect config in debug mode
  packages/compat/webpack/src/initConfigs.ts
  packages/core/src/provider/initConfigs.ts
Labels: release: bug fix

#4254 fix: set default command for `createCompiler()`
  packages/core/src/createRsbuild.ts
Labels: release: bug fix

#4255 docs: add `importModule` for `api.transform`
  .github/workflows/issue-close-require.yml
  .github/workflows/release.yml
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#4256 docs: link to SWC plugin unmatch FAQ
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/zh/guide/basic/configure-swc.mdx
Labels: release: document

#4261 perf: format stats errors in the Node side
  packages/core/src/client/hmr.ts
  packages/core/src/helpers/format.ts
  packages/core/src/helpers/stats.ts
  packages/core/src/server/socketServer.ts
Labels: release: performance

#4266 feat: display log colors on error overlay
  e2e/cases/server/overlay/index.test.ts
  packages/core/src/client/overlay.ts
  packages/core/src/server/ansiHTML.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/socketServer.ts
  scripts/dictionary.txt
Labels: release: feature

#4269 fix: should writeToDisk correctly when environment writeToDisk configuration same
  e2e/cases/server/write-to-disk-environments/index.test.ts
  packages/core/src/server/compilerDevMiddleware.ts
Labels: release: bug fix

#4270 fix: preserve ansi colors for browser error logs
  packages/core/src/client/hmr.ts
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#4274 feat: hint more unknown file types
  packages/core/src/helpers/format.ts
Labels: release: feature

#4276 perf: move overlay template to server side
  packages/core/src/client/hmr.ts
  packages/core/src/client/overlay.ts
  packages/core/src/server/socketServer.ts
Labels: release: performance

#4279 fix: ansi HTML edge cases
  packages/core/src/server/ansiHTML.ts
  packages/core/tests/ansi.test.ts
Labels: release: bug fix

#4280 fix: overlay renders invalid file path
  packages/core/src/client/hmr.ts
  packages/core/src/client/overlay.ts
  packages/core/src/server/overlay.ts
  packages/core/src/server/socketServer.ts
  packages/core/tests/overlay.test.ts
Labels: release: bug fix

#4283 fix: allow `environment` option of `createRsbuild` to be an empty array
  packages/core/src/createContext.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: bug fix

#4284 perf: replace `commander` with `cac`
  packages/core/package.json
  packages/core/src/cli/commands.ts
  pnpm-lock.yaml
Labels: release: performance

#4287 docs: update UnoCSS guide to use `@unocss/webpack`
  scripts/dictionary.txt
  website/docs/en/guide/basic/unocss.mdx
  website/docs/zh/guide/basic/unocss.mdx
Labels: release: document

#4289 feat: allow to custom manifest JSON
  e2e/cases/output/manifest-generate/index.test.ts
  e2e/cases/output/manifest-generate/src/index.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/types/config.ts
Labels: release: feature

#4290 docs: add `output.manifest.generate` config
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: release: document

#4281 fix: do not copy public dir for node target by default
  e2e/cases/server/public-dir/publicDir.test.ts
  packages/core/src/config.ts
  packages/core/src/plugins/server.ts
  packages/core/src/types/config.ts
  website/docs/en/config/server/public-dir.mdx
  website/docs/zh/config/server/public-dir.mdx
Labels: release: bug fix

#4299 feat: allow `publicDir.copyOnBuild` to be 'auto'
  packages/core/src/config.ts
  packages/core/src/plugins/server.ts
  packages/core/src/types/config.ts
  website/docs/en/config/server/public-dir.mdx
  website/docs/zh/config/server/public-dir.mdx
Labels: release: feature

#4307 feat: allow to filter files included in the manifest
  e2e/cases/output/manifest-async-chunks/index.test.ts
  e2e/cases/output/manifest-generate/index.test.ts
  e2e/cases/output/manifest/index.test.ts
  e2e/cases/output/manifest/src/index.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/types/config.ts
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: release: feature
