Repository web-infra-dev/rsbuild, pull requests merged in 2024-01, with the labels that each got.

#1133 fix(plugin-vue2): alias Vue to support element-ui
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1135 docs: add migration guide links
  packages/document/docs/en/guide/framework/react.mdx
  packages/document/docs/en/guide/framework/vue2.mdx
  packages/document/docs/en/guide/framework/vue3.mdx
  packages/document/docs/zh/guide/framework/react.mdx
  packages/document/docs/zh/guide/framework/vue2.mdx
  packages/document/docs/zh/guide/framework/vue3.mdx
Labels: change: docs

#1136 docs: add template migration guide
  packages/document/docs/en/config/html/template-parameters.mdx
  packages/document/docs/en/guide/basic/html-template.md
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/zh/config/html/template-parameters.mdx
  packages/document/docs/zh/guide/basic/html-template.md
  packages/document/docs/zh/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/vue-cli.mdx
Labels: change: docs

#1138 feat: support custom print urls
  e2e/cases/server/print-urls/index.test.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/prodServer.ts
  packages/core/tests/server.test.ts
  packages/document/docs/en/config/server/print-urls.mdx
  packages/document/docs/zh/config/server/print-urls.mdx
  packages/shared/src/mergeRsbuildConfig.ts
  packages/shared/src/types/config/server.ts
Labels: change: feat

#1139 fix: failed to prepend entry via chain API
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/provider/core/rspackConfig.ts
  packages/shared/src/chain.ts
Labels: change: fix

#1140 docs: add tip for mergeConfig util
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
Labels: change: docs

#1141 docs: add polyfill guide for CRA projects
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1143 fix: doc sidebar disappeared
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: fix

#1144 docs: add migration guide for CRACO configurations
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1146 feat: bump rslog to support customize logger
  e2e/cases/javascript-api/custom-logger/index.test.ts
  e2e/cases/javascript-api/custom-logger/rsbuild.config.ts
  e2e/cases/javascript-api/custom-logger/src/index.js
  packages/create-rsbuild/package.json
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/shared/compiled/rslog/dist/index.d.ts
  packages/shared/compiled/rslog/index.js
  packages/shared/compiled/rslog/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: feat

#1149 fix(server): print local label for more hosts
  packages/shared/src/url.ts
Labels: change: fix

#1150 feat(server): support listening on ipv6 address
  e2e/cases/server/ipv6-host/index.test.ts
  e2e/cases/server/ipv6-host/rsbuild.config.ts
  e2e/cases/server/ipv6-host/src/index.js
  packages/shared/src/url.ts
Labels: change: feat

#1152 docs: update footer time 2023 to 2024
  packages/document/rspress.config.ts
Labels: change: docs

#1153 perf: ncc target to es2019 to reduce bundle size
  .changeset/proud-wombats-do.md
  packages/compat/plugin-esbuild/compiled/esbuild-loader/minify-plugin.d.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/compiled/connect-history-api-fallback/index.js
  packages/core/compiled/dotenv-expand/index.js
  packages/core/compiled/dotenv/index.js
  packages/core/compiled/http-compression/index.js
  packages/core/compiled/open/index.js
  packages/core/compiled/sirv/index.js
  packages/core/compiled/toml-loader/index.js
  packages/core/compiled/ws/index.js
  packages/core/src/plugins/cache.ts
  packages/core/src/plugins/splitChunks.ts
  packages/plugin-babel/compiled/babel-loader/672.index.js
  packages/plugin-babel/compiled/babel-loader/index.js
  packages/plugin-css-minimizer/src/index.ts
  packages/shared/compiled/autoprefixer/index.js
  packages/shared/compiled/browserslist/index.js
  packages/shared/compiled/chokidar/index.js
  packages/shared/compiled/commander/index.js
  packages/shared/compiled/connect/index.js
  packages/shared/compiled/css-loader/index.js
  packages/shared/compiled/deepmerge/index.js
  packages/shared/compiled/fs-extra/index.js
  packages/shared/compiled/fs-extra/package.json
  packages/shared/compiled/gzip-size/index.js
  packages/shared/compiled/http-proxy-middleware/index.js
  packages/shared/compiled/icss-utils/index.js
  packages/shared/compiled/jiti/index.js
  packages/shared/compiled/json5/index.js
  packages/shared/compiled/less-loader/index.js
  packages/shared/compiled/less/index.js
  packages/shared/compiled/line-diff/index.js
  packages/shared/compiled/loader-utils2/index.js
  packages/shared/compiled/mime-types/index.js
  packages/shared/compiled/picocolors/index.js
  packages/shared/compiled/postcss-load-config/index.js
  packages/shared/compiled/postcss-loader/index.js
  packages/shared/compiled/postcss-modules-extract-imports/index.js
  packages/shared/compiled/postcss-modules-local-by-default/index.js
  packages/shared/compiled/postcss-modules-scope/index.js
  packages/shared/compiled/postcss-modules-values/index.js
  packages/shared/compiled/postcss-value-parser/index.js
  packages/shared/compiled/rslog/index.js
  packages/shared/compiled/sass-loader/index.js
  packages/shared/compiled/sass/index.js
  packages/shared/compiled/semver/index.js
  packages/shared/compiled/style-loader/index.js
  packages/shared/compiled/webpack-bundle-analyzer/index.js
  packages/shared/compiled/webpack-chain/index.js
  packages/shared/compiled/webpack-chain/types/index.d.ts
  packages/shared/compiled/webpack-dev-middleware/index.js
  packages/shared/compiled/webpack-merge/index.js
  packages/shared/compiled/webpack-sources/index.js
  packages/shared/compiled/yaml-loader/index.js
  packages/shared/compiled/yaml/index.js
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/prebundle.ts
Labels: change: perf

#1155 feat: validate plugin object, provide better hint
  packages/shared/src/pluginStore.ts
Labels: change: feat

#1156 feat: allow passing falsy plugins
  .changeset/large-scissors-rule.md
  e2e/cases/cli/falsy-plugins/index.test.ts
  e2e/cases/cli/falsy-plugins/rsbuild.config.ts
  e2e/cases/cli/falsy-plugins/src/index.ts
  e2e/cases/cli/falsy-plugins/tsconfig.json
  packages/core/src/index.ts
  packages/core/src/types.ts
  packages/shared/src/mergeChainedOptions.ts
  packages/shared/src/pluginStore.ts
  packages/shared/src/types/config/index.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/types/utils.ts
Labels: change: feat

#1159 docs: document more public types
  packages/document/docs/en/api/javascript-api/types.mdx
  packages/document/docs/zh/api/javascript-api/types.mdx
Labels: change: docs

#1160 fix: html plugin chain_id conflict
  packages/shared/src/chain.ts
Labels: change: fix

#1161 feat: validate config function return value
  packages/core/src/cli/config.ts
  packages/document/docs/en/guide/basic/config.mdx
  packages/document/docs/zh/guide/basic/config.mdx
Labels: change: feat

#1162 feat: check output dir when running the preview command
  packages/core/src/cli/commands.ts
Labels: change: feat

#1167 docs: fix webpack build typo
  packages/document/docs/en/guide/migration/webpack.mdx
  packages/document/docs/zh/guide/migration/webpack.mdx
Labels: change: docs

#1168 docs: add tip for migrating CRACO and ejected projects
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/en/guide/migration/webpack.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/vue-cli.mdx
  packages/document/docs/zh/guide/migration/webpack.mdx
Labels: change: docs

#1169 feat(core): export Rsbuild version
  packages/core/src/index.ts
  packages/core/tests/index.test.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#1174 docs: add more CHAIN_ID to bundler-chain document
  packages/compat/webpack/src/plugins/sass.ts
  packages/core/src/provider/plugins/sass.ts
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/shared/src/chain.ts
Labels: change: docs

#1176 fix(babel): presetEnv need allow null value
  .changeset/famous-penguins-tan.md
  packages/babel-preset/src/web.ts
Labels: change: fix

#1177 fix(babel-preset): allow disable presetEnv for web target
  packages/babel-preset/src/types.ts
  packages/babel-preset/src/web.ts
  packages/babel-preset/tests/__snapshots__/web.test.ts.snap
  packages/babel-preset/tests/web.test.ts
Labels: change: fix

#1179 fix(plugin-babel): export getDefaultBabelOptions util from index
  packages/plugin-babel/src/index.ts
Labels: change: fix

#1178 docs: fix Module Federation terminology explanation
  packages/document/docs/en/guide/start/glossary.mdx
  packages/document/docs/zh/guide/start/glossary.mdx
Labels: change: docs

#1181 breaking change: change default browserslist of node target to v16
  packages/babel-preset/src/node.ts
  packages/babel-preset/tests/__snapshots__/node.test.ts.snap
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/webpack/tests/plugins/__snapshots__/babel.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/swc.test.ts.snap
  packages/document/docs/en/config/output/override-browserslist.mdx
  packages/document/docs/en/config/output/targets.mdx
  packages/document/docs/en/guide/advanced/browserslist.md
  packages/document/docs/zh/config/output/override-browserslist.mdx
  packages/document/docs/zh/config/output/targets.mdx
  packages/document/docs/zh/guide/advanced/browserslist.md
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/constants.ts
Labels: change: breaking

#1182 fix(babel-preset): should merge targets array correctly
  .changeset/old-bags-visit.md
  packages/babel-preset/src/node.ts
  packages/babel-preset/tests/__snapshots__/node.test.ts.snap
  packages/babel-preset/tests/node.test.ts
Labels: change: fix

#1184 docs: add Vue 2 version requirements
  packages/document/docs/en/guide/framework/vue2.mdx
  packages/document/docs/en/plugins/list/plugin-vue2.mdx
  packages/document/docs/zh/guide/framework/vue2.mdx
  packages/document/docs/zh/plugins/list/plugin-vue2.mdx
Labels: change: docs

#1185 feat(plugin-svelte): support pass preprocess options
  packages/plugin-svelte/package.json
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/index.test.ts
  pnpm-lock.yaml
Labels: change: feat

#1186 docs: add unknown assets guide for CRA
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1187 docs: add guides for the svelte process options
  packages/document/docs/en/plugins/list/plugin-svelte.mdx
  packages/document/docs/zh/plugins/list/plugin-svelte.mdx
Labels: change: docs

#1188 docs: add cleanup to loadEnv document
  packages/core/src/loadEnv.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: docs

#1189 feat(plugin-react): add jsxRuntime option to support React 16
  .npmrc
  e2e/cases/react/legacy-jsx/index.test.ts
  e2e/cases/react/legacy-jsx/rsbuild.config.ts
  e2e/cases/react/legacy-jsx/src/App.jsx
  e2e/cases/react/legacy-jsx/src/index.js
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  pnpm-lock.yaml
Labels: change: feat

#1190 feat(plugin-react): add jsxImportSource option
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/index.test.ts
Labels: change: feat

#1191 feat(plugin-react): allow to configure all SWC react options
  e2e/cases/react/legacy-jsx/rsbuild.config.ts
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/index.test.ts
  packages/shared/src/types/rspack.ts
Labels: change: feat

#1192 docs: add migration guide for Modern.js Builder
  packages/document/docs/en/guide/migration/_meta.json
  packages/document/docs/en/guide/migration/modern-builder.mdx
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/guide/migration/_meta.json
  packages/document/docs/zh/guide/migration/modern-builder.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#1194 feat(CLI): add -o alias for --open option
  packages/core/src/cli/commands.ts
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#1195 docs: add guide for specify config file
  packages/document/docs/en/guide/basic/config.mdx
  packages/document/docs/zh/guide/basic/config.mdx
Labels: change: docs

#1198 docs: update slogan
  packages/babel-preset/README.md
  packages/compat/plugin-esbuild/README.md
  packages/compat/plugin-swc/README.md
  packages/core/README.md
  packages/core/package.json
  packages/create-rsbuild/README.md
  packages/document/README.md
  packages/document/docs/en/index.md
  packages/monorepo-utils/README.md
  packages/plugin-assets-retry/README.md
  packages/plugin-babel/README.md
  packages/plugin-check-syntax/README.md
  packages/plugin-css-minimizer/README.md
  packages/plugin-image-compress/README.md
  packages/plugin-node-polyfill/README.md
  packages/plugin-pug/README.md
  packages/plugin-react/README.md
  packages/plugin-rem/README.md
  packages/plugin-solid/README.md
  packages/plugin-source-build/README.md
  packages/plugin-styled-components/README.md
  packages/plugin-stylus/README.md
  packages/plugin-svelte/README.md
  packages/plugin-svgr/README.md
  packages/plugin-type-check/README.md
  packages/plugin-umd/README.md
  packages/plugin-vue-jsx/README.md
  packages/plugin-vue/README.md
  packages/plugin-vue2-jsx/README.md
  packages/plugin-vue2/README.md
  packages/test-helper/README.md
Labels: change: docs

#1200 breaking change: default value of distPath.server is changed to 'server'
  e2e/cases/node-addons/index.test.ts
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/document/docs/en/config/output/dist-path.mdx
  packages/document/docs/en/guide/basic/config.mdx
  packages/document/docs/en/guide/basic/output-files.md
  packages/document/docs/zh/config/output/dist-path.mdx
  packages/document/docs/zh/guide/basic/config.mdx
  packages/document/docs/zh/guide/basic/output-files.md
  packages/shared/src/constants.ts
  packages/shared/src/types/config/output.ts
Labels: change: breaking

#1201 breaking change: extract TOML plugin into a separate package
  e2e/cases/import-toml/rsbuild.config.ts
  e2e/package.json
  packages/compat/webpack/src/shared.ts
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/toml.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-toml/CHANGELOG.md
  packages/plugin-toml/LICENSE
  packages/plugin-toml/README.md
  packages/plugin-toml/compiled/toml-loader/index.d.ts
  packages/plugin-toml/compiled/toml-loader/index.js
  packages/plugin-toml/compiled/toml-loader/license
  packages/plugin-toml/compiled/toml-loader/package.json
  packages/plugin-toml/modern.config.ts
  packages/plugin-toml/package.json
  packages/plugin-toml/src/index.ts
  packages/plugin-toml/tests/__snapshots__/index.test.ts.snap
  packages/plugin-toml/tests/index.test.ts
  packages/plugin-toml/tests/tsconfig.json
  packages/plugin-toml/tsconfig.json
  packages/shared/src/types/plugin.ts
  pnpm-lock.yaml
  scripts/prebundle/src/constant.ts
Labels: change: breaking

#1077 feat: enable Rspack new tree shaking by default
  packages/core/src/provider/plugins/transition.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1203 breaking change: remove deprecated printURLs option
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/shared/src/types/provider.ts
Labels: change: breaking

#1204 breaking change: remove deprecated logger option
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
  packages/shared/src/types/provider.ts
Labels: change: breaking

#1209 docs: adjust configure Rsbuild document
  packages/document/docs/en/config/index.mdx
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/guide/basic/_meta.json
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/en/guide/debug/debug-mode.md
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/config/index.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/guide/basic/_meta.json
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/guide/debug/debug-mode.md
  packages/document/docs/zh/guide/start/index.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#1210 docs: add TOML plugin document
  packages/document/docs/en/guide/basic/json-files.md
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-toml.mdx
  packages/document/docs/zh/guide/basic/json-files.md
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-toml.mdx
Labels: change: docs

#1211 docs: add YAML plugin document
  packages/document/docs/en/guide/basic/json-files.md
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-yaml.mdx
  packages/document/docs/zh/guide/basic/json-files.md
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-yaml.mdx
Labels: change: docs

#1215 perf(RegExp): use non-capturing groups for asset rules
  .changeset/real-kings-protect.md
  packages/compat/webpack/tests/plugins/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/asset.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/plugins/__snapshots__/asset.test.ts.snap
  packages/core/tests/plugins/asset.test.ts
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: perf

#1218 perf(create-rsbuild): improve perf for new solid projects
  examples/solid/rsbuild.config.ts
  packages/create-rsbuild/template-solid-js/rsbuild.config.mjs
  packages/create-rsbuild/template-solid-ts/rsbuild.config.ts
Labels: change: perf

#1220 types: allow to narrow Compiler type for createCompiler
  packages/compat/webpack/src/provider.ts
  packages/core/src/provider/provider.ts
  packages/shared/src/types/provider.ts
Labels: change: feat

#1223 feat: bump Rspack v0.5.0 stable
  .changeset/rude-bugs-clap.md
  packages/core/package.json
  packages/core/src/provider/shared.ts
  packages/document/docs/en/guide/basic/json-files.md
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  packages/test-helper/package.json
  pnpm-lock.yaml
Labels: change: feat

#1228 feat(plugin-source-build): add resolvePriority option
  packages/document/docs/en/plugins/list/plugin-source-build.mdx
  packages/document/docs/zh/plugins/list/plugin-source-build.mdx
  packages/plugin-source-build/package.json
  packages/plugin-source-build/src/index.ts
  packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
  packages/plugin-source-build/tests/index.test.ts
  pnpm-lock.yaml
Labels: change: feat

#1233 types: improve rewriteTo type for historyApiFallback
  packages/shared/src/types/config/server.ts
Labels: change: feat

#1235 feat(create-rsbuild): add extensions config for Vue projects
  .changeset/big-bugs-think.md
  packages/create-rsbuild/template-vue3-js/.vscode/extensions.json
  packages/create-rsbuild/template-vue3-ts/.vscode/extensions.json
  packages/create-rsbuild/template-vue3-ts/src/env.d.ts
Labels: change: feat

#1239 fix(plugin-svgr): missing file-loader peer dependency
  packages/plugin-svgr/package.json
  pnpm-lock.yaml
Labels: change: fix

#1243 perf(plugin-svgr): prebundle url-loader to reduce dependencies
  packages/plugin-svgr/compiled/file-loader/index.d.ts
  packages/plugin-svgr/compiled/file-loader/index.js
  packages/plugin-svgr/compiled/file-loader/license
  packages/plugin-svgr/compiled/file-loader/package.json
  packages/plugin-svgr/compiled/file-loader/schema-utils.js
  packages/plugin-svgr/compiled/url-loader/index.d.ts
  packages/plugin-svgr/compiled/url-loader/index.js
  packages/plugin-svgr/compiled/url-loader/license
  packages/plugin-svgr/compiled/url-loader/package.json
  packages/plugin-svgr/compiled/url-loader/schema-utils.js
  packages/plugin-svgr/package.json
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: perf

#1246 feat: support return modified urls with printUrls
  e2e/cases/server/print-urls/index.test.ts
  packages/core/src/server/helper.ts
  packages/document/docs/en/config/server/print-urls.mdx
  packages/document/docs/zh/config/server/print-urls.mdx
  packages/shared/src/types/config/server.ts
  packages/shared/src/url.ts
Labels: change: feat

#1249 feat: add @rsbuild/plugin-react package
  cspell.json
  examples/preact/package.json
  examples/preact/rsbuild.config.ts
  examples/preact/src/App.css
  examples/preact/src/App.jsx
  examples/preact/src/index.jsx
  packages/plugin-preact/CHANGELOG.md
  packages/plugin-preact/LICENSE
  packages/plugin-preact/README.md
  packages/plugin-preact/modern.config.ts
  packages/plugin-preact/package.json
  packages/plugin-preact/src/index.ts
  packages/plugin-preact/tsconfig.json
  packages/shared/src/chain.ts
  pnpm-lock.yaml
Labels: change: feat

#1251 docs: setup document for plugin-preact
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-preact.mdx
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-preact.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
Labels: change: docs

#1253 docs(vue3): update outdated typescript support
  packages/document/docs/en/guide/framework/vue3.mdx
  packages/document/docs/zh/guide/framework/vue3.mdx
Labels: change: docs

#1254 feat(plugin-preact): add reactAliasesEnabled option
  packages/document/docs/en/plugins/list/plugin-preact.mdx
  packages/document/docs/zh/plugins/list/plugin-preact.mdx
  packages/plugin-preact/src/index.ts
  packages/plugin-preact/tests/__snapshots__/features.test.ts.snap
  packages/plugin-preact/tests/index.test.ts
Labels: change: feat

#1255 feat(create-rsbuild): enable useDefineForClassFields by default
  packages/create-rsbuild/template-lit-ts/tsconfig.json
  packages/create-rsbuild/template-preact-ts/tsconfig.json
  packages/create-rsbuild/template-react-ts/tsconfig.json
  packages/create-rsbuild/template-solid-ts/tsconfig.json
  packages/create-rsbuild/template-svelte-ts/tsconfig.json
  packages/create-rsbuild/template-vanilla-ts/tsconfig.json
  packages/create-rsbuild/template-vue2-ts/tsconfig.json
  packages/create-rsbuild/template-vue3-ts/tsconfig.json
  scripts/tsconfig/base.json
Labels: change: feat

#1263 fix(plugin-svgr): failed to reuse SWC react options
  packages/plugin-svgr/package.json
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/index.test.ts
  pnpm-lock.yaml
Labels: change: fix

#1265 fix(server): access page error when url with query or hash
  e2e/cases/server/htmlFallback.test.ts
  packages/core/src/server/middlewares.ts
Labels: change: fix

#1269 types(core): export the type of config sub key
  packages/core/src/index.ts
  packages/document/docs/en/api/javascript-api/types.mdx
  packages/document/docs/zh/api/javascript-api/types.mdx
Labels: change: feat

#1274 perf(source-build): improve glob performance
  packages/monorepo-utils/src/common/pnpm.ts
Labels: change: perf

#1275 perf(source-build): remove p-map dependency
  packages/monorepo-utils/package.json
  packages/monorepo-utils/src/common/pnpm.ts
  packages/monorepo-utils/src/utils.ts
  pnpm-lock.yaml
Labels: change: perf

#1276 chore(workflow): fix release workflow action
  .github/workflows/release.yml
Labels: change: fix

#1278 perf(source-build): reuse shared dependencies
  packages/monorepo-utils/package.json
  packages/monorepo-utils/src/common/pnpm.ts
  packages/monorepo-utils/src/utils.ts
  packages/shared/compiled/yaml/index.d.ts
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/prebundle/src/constant.ts
Labels: change: perf

#1282 fix: should ignore node addons when targeting service worker
  e2e/cases/mjs-artifact/test.mjs
  packages/core/src/plugins/nodeAddons.ts
  packages/core/tests/plugins/nodeAddons.test.ts
Labels: change: fix

#1285 docs: add path types example for publicDir config
  packages/document/docs/en/config/server/public-dir.mdx
  packages/document/docs/zh/config/server/public-dir.mdx
  packages/shared/src/types/config/server.ts
Labels: change: docs

#1290 docs: move fast refresh guide to react document
  packages/document/docs/en/guide/faq/hmr.md
  packages/document/docs/en/guide/framework/react.mdx
  packages/document/docs/zh/guide/faq/hmr.md
  packages/document/docs/zh/guide/framework/react.mdx
Labels: change: docs

#1289 fix(server): print server url should between listen and beforeCompile
  e2e/cases/javascript-api/plugin-hooks/index.test.ts
  packages/core/src/provider/core/initConfigs.ts
  packages/core/src/server/devServer.ts
Labels: change: fix

#1293 feat: add source.tsconfigPath config
  .changeset/fluffy-llamas-shop.md
  e2e/cases/source/custom-tsconfig/index.test.ts
  e2e/cases/source/custom-tsconfig/rsbuild.config.ts
  e2e/cases/source/custom-tsconfig/src/common/test.ts
  e2e/cases/source/custom-tsconfig/src/common2/test.ts
  e2e/cases/source/custom-tsconfig/src/index.ts
  e2e/cases/source/custom-tsconfig/tsconfig.custom.json
  e2e/cases/source/custom-tsconfig/tsconfig.json
  e2e/cases/source/source.test.ts
  e2e/cases/source/tsconfig-paths/index.test.ts
  packages/compat/webpack/src/plugins/resolve.ts
  packages/core/src/provider/config.ts
  packages/core/src/provider/core/createContext.ts
  packages/core/src/provider/index.ts
  packages/shared/src/types/config/source.ts
Labels: change: feat

#1294 docs: add document for source.tsconfigPath config
  packages/document/docs/en/config/server/public-dir.mdx
  packages/document/docs/en/config/source/tsconfig-path.mdx
  packages/document/docs/en/guide/basic/typescript.md
  packages/document/docs/zh/config/source/tsconfig-path.mdx
  packages/document/docs/zh/guide/basic/typescript.md
Labels: change: docs

#1295 docs: add react plugin introduce in the builder migration guide
  packages/document/docs/en/guide/migration/modern-builder.mdx
  packages/document/docs/zh/guide/migration/modern-builder.mdx
Labels: change: docs

#1299 docs: prettier exceptions faq
  packages/document/docs/en/guide/faq/exceptions.md
  packages/document/docs/zh/guide/faq/exceptions.md
Labels: change: docs

#1301 feat(deps): bump rspack v0.5.1
  package.json
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: feat

#1303 feat: support load browserslist config with env section
  e2e/cases/polyfill/basic/index.test.ts
  e2e/cases/polyfill/basic/src/index.js
  e2e/cases/polyfill/browserslist/.browserslistrc
  e2e/cases/polyfill/browserslist/index.test.ts
  e2e/cases/polyfill/browserslist/rsbuild.config.ts
  e2e/cases/polyfill/browserslist/src/index.js
  e2e/cases/polyfill/helper.ts
  packages/shared/src/getBrowserslist.ts
Labels: change: feat

#1304 docs: add guide for browserslist env section
  packages/document/docs/en/guide/advanced/browserslist.md
  packages/document/docs/zh/guide/advanced/browserslist.md
Labels: change: docs

#1309 feat: enable Rspack new tree shaking by default
  packages/core/src/provider/plugins/transition.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/rspack-provider/plugins/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1310 docs(plugin-type-check): fix broken en page
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
Labels: change: docs

#1312 docs: fix translator removed tabs
  packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx
  packages/document/docs/en/plugins/list/plugin-toml.mdx
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
  packages/document/docs/en/plugins/list/plugin-yaml.mdx
Labels: change: docs

#1305 docs: amend e2e command description
  CONTRIBUTING.md
Labels: change: docs

#1322 fix: double slash in formatted routes
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
Labels: change: fix

#1333 feat: improve time info in debug logs
  packages/core/src/plugins/startUrl.ts
  packages/core/src/provider/core/createCompiler.ts
  packages/shared/src/logger.ts
Labels: change: feat

#1347 feat: add routes param to server.printUrls
  packages/core/src/plugins/startUrl.ts
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
  packages/document/docs/en/config/server/print-urls.mdx
  packages/document/docs/zh/config/server/print-urls.mdx
  packages/shared/src/types/config/server.ts
  packages/shared/src/types/hooks.ts
Labels: change: feat

#1350 fix: infinitely reload when disabling HMR
  packages/core/src/client/hmr/index.ts
Labels: change: fix

#1353 docs: add routes param to server hooks document
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/shared/onAfterStartDevServer.md
  packages/document/docs/en/shared/onAfterStartProdServer.md
  packages/document/docs/zh/api/javascript-api/instance.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/shared/onAfterStartDevServer.md
  packages/document/docs/zh/shared/onAfterStartProdServer.md
Labels: change: docs

#1359 fix: incorrect peer dependency range
  packages/compat/plugin-esbuild/package.json
  packages/compat/plugin-swc/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-babel/package.json
  packages/plugin-check-syntax/package.json
  packages/plugin-css-minimizer/package.json
  packages/plugin-image-compress/package.json
  packages/plugin-node-polyfill/package.json
  packages/plugin-preact/package.json
  packages/plugin-pug/package.json
  packages/plugin-react/package.json
  packages/plugin-rem/package.json
  packages/plugin-solid/package.json
  packages/plugin-source-build/package.json
  packages/plugin-styled-components/package.json
  packages/plugin-stylus/package.json
  packages/plugin-svelte/package.json
  packages/plugin-svgr/package.json
  packages/plugin-toml/package.json
  packages/plugin-type-check/package.json
  packages/plugin-umd/package.json
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  packages/plugin-vue2-jsx/package.json
  packages/plugin-vue2/package.json
  packages/plugin-yaml/package.json
  scripts/check-changeset/src/index.ts
Labels: change: fix

#1366 feat: improve publicDir copy error log
  packages/core/src/plugins/server.ts
Labels: change: feat

#1367 perf(create-rsbuild): bundle dependencies for speed up
  packages/create-rsbuild/.npmignore
  packages/create-rsbuild/modern.config.ts
  packages/create-rsbuild/package.json
  packages/create-rsbuild/src/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/modern.base.config.ts
Labels: change: perf

#1370 feat: support specify env mode via loadEnv
  e2e/cases/javascript-api/load-env/.env
  e2e/cases/javascript-api/load-env/.env.staging
  e2e/cases/javascript-api/load-env/index.test.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/config.ts
  packages/core/src/loadEnv.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#1371 feat(CLI): support --env-mode option
  e2e/cases/cli/load-env/.env.test
  e2e/cases/cli/load-env/index.test.ts
  packages/core/src/cli/commands.ts
  packages/document/docs/en/guide/advanced/env-vars.md
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/zh/guide/advanced/env-vars.md
  packages/document/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#1372 feat: support debug groups
  .changeset/lemon-cups-accept.md
  packages/shared/src/logger.ts
Labels: change: feat

#1377 types: allow less.additionalData to be async function
  .changeset/tender-planes-add.md
  packages/shared/src/types/thirdParty.ts
Labels: change: feat

#1378 docs(plugin-stylus): fix sourceMap default value
  packages/document/docs/en/plugins/list/plugin-stylus.mdx
  packages/document/docs/zh/plugins/list/plugin-stylus.mdx
  packages/plugin-stylus/src/index.ts
Labels: change: docs

#1379 feat: add JSDoc for all plugins options
  packages/document/docs/en/plugins/list/plugin-pug.mdx
  packages/document/docs/en/plugins/list/plugin-solid.mdx
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
  packages/document/docs/zh/plugins/list/plugin-pug.mdx
  packages/document/docs/zh/plugins/list/plugin-solid.mdx
  packages/plugin-assets-retry/src/types.ts
  packages/plugin-babel/src/types.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-pug/src/index.ts
  packages/plugin-rem/src/types.ts
  packages/plugin-solid/src/index.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-type-check/src/index.ts
  packages/plugin-umd/src/index.ts
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue/src/index.ts
  packages/plugin-vue2-jsx/src/index.ts
  packages/plugin-vue2/src/index.ts
Labels: change: feat

#1380 fix: improve regex for package name matching
  e2e/cases/performance/split-by-module/index.test.ts
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/plugins/splitChunks.test.ts
Labels: change: fix

#1381 feat(server): support launch editor
  e2e/cases/server/custom-server/scripts/pure-server.mjs
  e2e/cases/server/custom-server/scripts/server.mjs
  packages/core/compiled/launch-editor-middleware/index.d.ts
  packages/core/compiled/launch-editor-middleware/index.js
  packages/core/compiled/launch-editor-middleware/license
  packages/core/compiled/launch-editor-middleware/package.json
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/shared/src/types/server.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: feat

#1382 perf: reuse some precompiled dependencies
  packages/core/compiled/launch-editor-middleware/index.js
  packages/shared/compiled/css-loader/index.js
  packages/shared/compiled/css-loader/package.json
  packages/shared/compiled/postcss-modules-local-by-default/index.js
  packages/shared/compiled/postcss-modules-values/index.js
  packages/shared/compiled/webpack-chain/index.js
  packages/shared/package.json
  scripts/prebundle/src/constant.ts
Labels: change: perf

#1387 docs: add env vars replacement scope
  packages/document/docs/en/guide/advanced/env-vars.md
  packages/document/docs/zh/guide/advanced/env-vars.md
Labels: change: docs

#1390 feat: validate config exports to improve error message
  packages/core/src/cli/config.ts
Labels: change: feat

#1393 fix: merge dev.startUrl with overrides strategy
  packages/shared/src/mergeRsbuildConfig.ts
  packages/shared/tests/mergeConfig.test.ts
Labels: change: fix

#1394 types: mergeRsbuildConfig no longer needs generics
  .changeset/curly-cats-itch.md
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/compat/webpack/tests/webpackConfig.test.ts
  packages/core/src/provider/config.ts
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/shared/src/mergeRsbuildConfig.ts
  packages/shared/tests/mergeConfig.test.ts
Labels: change: feat

#1395 fix: prevent using 'local' as the env mode
  packages/core/src/loadEnv.ts
Labels: change: fix

#1404 fix(plugin-source-build): skip references for JS project
  packages/plugin-source-build/src/index.ts
  packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1406 feat(node-polyfill): upgrade polyfill packages to latest version
  packages/plugin-node-polyfill/package.json
  packages/plugin-node-polyfill/src/libs.ts
  packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#1407 perf: improve mergeRsbuildConfig performance
  packages/core/src/plugins/html.ts
  packages/shared/src/mergeRsbuildConfig.ts
Labels: change: perf

#1409 feat: support more image and media formats
  cspell.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/types.d.ts
  packages/document/docs/en/guide/basic/static-assets.md
  packages/document/docs/zh/guide/basic/static-assets.md
  packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/constants.ts
Labels: change: feat

#1412 perf: lazy load html-webpack-plugin
  .changeset/rude-kangaroos-appear.md
  packages/core/src/provider/htmlPluginUtil.ts
Labels: change: perf

#1414 docs: add releases page
  packages/document/docs/en/_meta.json
  packages/document/docs/en/community/_meta.json
  packages/document/docs/en/community/releases/_meta.json
  packages/document/docs/en/community/releases/index.mdx
  packages/document/docs/zh/_meta.json
  packages/document/docs/zh/community/_meta.json
  packages/document/docs/zh/community/releases/_meta.json
  packages/document/docs/zh/community/releases/index.mdx
Labels: change: docs

#1415 docs: add all release notes
  packages/document/docs/en/community/releases/_meta.json
  packages/document/docs/en/community/releases/index.mdx
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/community/releases/v0-2.mdx
  packages/document/docs/en/community/releases/v0-3.mdx
  packages/document/docs/zh/_meta.json
  packages/document/docs/zh/community/_meta.json
  packages/document/docs/zh/community/releases/_meta.json
  packages/document/docs/zh/community/releases/v0-1.mdx
  packages/document/docs/zh/community/releases/v0-2.mdx
  packages/document/docs/zh/community/releases/v0-3.mdx
Labels: change: docs

#1408 feature(server): print more server logs in debug mode
  packages/core/compiled/on-finished/index.d.ts
  packages/core/compiled/on-finished/index.js
  packages/core/compiled/on-finished/license
  packages/core/compiled/on-finished/package.json
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/prodServer.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: feat

#1417 perf: reduce color calls of debug
  packages/core/src/server/middlewares.ts
Labels: change: perf

#1418 feat: add new isDev param
  packages/compat/webpack/src/core/webpackConfig.ts
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/provider/core/rspackConfig.ts
  packages/core/src/provider/index.ts
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/plugins/list/plugin-svelte.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/list/plugin-svelte.mdx
  packages/plugin-check-syntax/src/index.ts
  packages/plugin-image-compress/src/index.ts
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/src/index.ts
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/types/hooks.ts
Labels: change: feat

#1419 feat(plugin-node-polyfill): add new globals option
  packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx
  packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx
  packages/plugin-node-polyfill/src/index.ts
  packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap
  packages/plugin-node-polyfill/tests/index.test.ts
Labels: change: feat

#1423 docs: add tailwindcss performance tip
  packages/document/docs/en/guide/basic/tailwindcss.mdx
  packages/document/docs/zh/guide/basic/tailwindcss.mdx
Labels: change: docs

#1424 docs: missing zh period
  README.zh-CN.md
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#1426 docs: improve configuration structure
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: change: docs

#1427 feat: support mode parameter in defineConfig
  packages/core/src/cli/commands.ts
  packages/core/src/cli/config.ts
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: change: feat

#1428 docs: integrate rsfamily-nav-icon
  cspell.json
  packages/document/package.json
  packages/document/theme/index.tsx
  packages/document/tsconfig.json
  pnpm-lock.yaml
Labels: change: docs

#1429 docs: bump rsfamily-nav-icon v1.0.1
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: docs

#1431 docs: fix missing nav icon CSS
  packages/document/theme/index.tsx
Labels: change: docs

#1432 docs: improve config function params
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: change: docs

#1433 feat: do not clean dist path if it is outside root
  .changeset/unlucky-jars-drop.md
  cspell.json
  e2e/cases/output/clean-dist-path/index.test.ts
  e2e/cases/output/clean-dist-path/src/index.js
  e2e/cases/output/output.test.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/document/docs/en/config/output/clean-dist-path.mdx
  packages/document/docs/zh/config/output/clean-dist-path.mdx
  packages/shared/src/config.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#1437 docs: improve plugin hooks document
  README.md
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/config/dev/asset-prefix.mdx
  packages/document/docs/en/config/output/asset-prefix.mdx
  packages/document/docs/en/config/output/filename.mdx
  packages/document/docs/en/config/output/inject-styles.mdx
  packages/document/docs/en/guide/advanced/env-vars.md
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/basic/output-files.md
  packages/document/docs/en/guide/debug/debug-mode.md
  packages/document/docs/en/guide/faq/hmr.md
  packages/document/docs/en/guide/migration/modern-builder.mdx
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/shared/deployApp.md
  packages/document/docs/en/shared/onAfterStartDevServer.md
  packages/document/docs/en/shared/onBeforeStartDevServer.md
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/shared/src/types/config/dev.ts
Labels: change: docs

#1438 docs: add guide for plugin hooks execution order
  e2e/cases/javascript-api/plugin-hooks/index.test.ts
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#1441 feat: support automatically enable Rsdoctor
  e2e/cases/rsdoctor/index.test.ts
  e2e/cases/rsdoctor/mock/index.cjs
  e2e/cases/rsdoctor/mock/package.json
  e2e/cases/rsdoctor/src/index.js
  packages/compat/webpack/src/shared.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/rsdoctor.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/shared/src/types/plugin.ts
  pnpm-lock.yaml
Labels: change: feat

#1442 perf: set default WATCHPACK_WATCHER_LIMIT to 20
  cspell.json
  packages/core/src/provider/plugins/transition.ts
Labels: change: perf

#1445 fix: treat publicPath auto as empty string
  packages/shared/src/utils.ts
  packages/shared/tests/url.test.ts
Labels: change: fix

#1449 fix: downgrade Rspack v0.5.0 to fix module federation
  packages/core/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: fix

#1451 fix: format assetPrefix for define and template
  e2e/cases/asset-prefix/index.test.ts
  e2e/cases/asset-prefix/src/template.html
  packages/core/src/plugins/define.ts
  packages/core/src/plugins/html.ts
  packages/document/docs/en/config/dev/asset-prefix.mdx
  packages/document/docs/en/config/output/asset-prefix.mdx
  packages/document/docs/zh/config/dev/asset-prefix.mdx
  packages/document/docs/zh/config/output/asset-prefix.mdx
  packages/shared/src/chain.ts
  packages/shared/src/utils.ts
Labels: change: fix

#1452 feat: allow chunkSplit.strategy to be optional
  examples/module-federation/host/module-federation.config.ts
  examples/module-federation/host/rsbuild.config.ts
  examples/module-federation/remote/module-federation.config.ts
  examples/module-federation/remote/rsbuild.config.ts
  packages/core/src/plugins/splitChunks.ts
  packages/document/docs/en/config/performance/chunk-split.mdx
  packages/document/docs/zh/config/performance/chunk-split.mdx
  packages/shared/src/types/config/performance.ts
Labels: change: feat

#1456 docs: add guide for examples and e2e
  e2e/README.md
  examples/README.md
  packages/document/docs/en/guide/start/glossary.mdx
  packages/document/docs/zh/guide/start/glossary.mdx
Labels: change: docs

#1458 docs(typo): some untranslated content
  packages/document/docs/en/guide/basic/cli.mdx
Labels: change: docs

#1459 feat(deps): bump Rspack v0.5.3
  .changeset/fluffy-kangaroos-hunt.md
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: feat

#1462 feat: add new decorators.version config
  e2e/cases/decorator/2022-03/index.test.ts
  e2e/cases/decorator/2022-03/rsbuild.config.ts
  e2e/cases/decorator/2022-03/src/index.js
  e2e/cases/decorator/basic/index.test.ts
  e2e/cases/decorator/basic/src/index.js
  e2e/cases/decorator/latest/index.test.ts
  e2e/cases/decorator/latest/src/index.js
  e2e/cases/decorator/legacy/index.test.ts
  e2e/cases/decorator/legacy/src/index.js
  packages/compat/plugin-swc/src/utils.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/core/src/provider/index.ts
  packages/core/src/provider/plugins/swc.ts
  packages/shared/src/config.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/config/source.ts
  packages/shared/src/types/rspack.ts
Labels: change: feat

#1463 docs: add document for decorators config
  packages/document/docs/en/config/source/decorators.mdx
  packages/document/docs/zh/config/source/decorators.mdx
Labels: change: docs

#1464 fix: bump Rslog v1.2.1 to format Rspack error stack
  packages/core/compiled/dotenv/index.js
  packages/core/compiled/dotenv/lib/main.d.ts
  packages/core/compiled/dotenv/package.json
  packages/create-rsbuild/package.json
  packages/shared/compiled/autoprefixer/index.js
  packages/shared/compiled/autoprefixer/package.json
  packages/shared/compiled/postcss-modules-scope/index.js
  packages/shared/compiled/postcss-modules-scope/package.json
  packages/shared/compiled/rslog/dist/index.d.ts
  packages/shared/compiled/rslog/index.js
  packages/shared/compiled/rslog/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: fix

#1472 feat: support declare plugin hooks order
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/shared/src/createHook.ts
  packages/shared/src/types/plugin.ts
  packages/shared/tests/createAsyncHook.test.ts
Labels: change: feat

#1471 feat: support decorator syntax when use babel plugin
  e2e/cases/decorator/2022-03/index.test.ts
  e2e/cases/decorator/basic/index.test.ts
  packages/plugin-babel/package.json
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#1473 docs: add security.nonce config
  packages/document/docs/en/config/_meta.json
  packages/document/docs/en/config/security/nonce.md
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/config/_meta.json
  packages/document/docs/zh/config/security/nonce.md
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: change: docs

#1474 fix: attach SWC rule to the pre stage
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/src/index.ts
Labels: change: fix

#1477 docs: improve include monorepo pkgs example
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/zh/config/source/include.mdx
Labels: change: docs

#1478 docs: fix config options order
  packages/document/docs/en/config/_meta.json
  packages/document/docs/zh/config/_meta.json
  packages/document/src/rsbuildPluginOverview.ts
Labels: change: docs

#1481 perf(plugin-react): reduce deepmerge overhead
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/react.ts
Labels: change: perf
