Repository web-infra-dev/rsbuild, pull requests merged in 2024-06, with the labels that each got.

#2485 fix(plugin-babel): run babel loader before builtin SWC loader
  packages/plugin-babel/src/plugin.ts
Labels: change: fix

#2493 docs(plugin-sass): add tip for legacy API
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: change: docs

#2496 docs: add guide for upgrading Rsbuild
  scripts/dictionary.txt
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/upgrade-rsbuild.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/upgrade-rsbuild.mdx
Labels: change: docs

#2497 feat: allow to access compilation in modifyHTMLTags hook
  packages/core/src/createRsbuild.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/shared/src/types/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2498 feat: expose assetPrefix for modifyHTMLTags hook
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags/myPlugin.ts
  e2e/cases/plugin-api/plugin-modify-tags/rsbuild.config.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/shared/src/types/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2500 feat: support override library type config when target is node
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/output.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
Labels: change: feat

#2499 feat: support generating SRI for initial chunks
  packages/core/src/config.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/sri.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/shared/src/types/config/security.ts
Labels: change: feat

#2511 docs: add security.sri config
  website/docs/en/config/security/sri.mdx
  website/docs/zh/config/security/sri.mdx
Labels: change: docs

#2512 perf(plugin-lightningcss): only validate in setup stage
  packages/plugin-lightningcss/src/index.ts
  packages/plugin-lightningcss/src/loader.ts
  packages/plugin-lightningcss/src/minimizer.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-lightningcss/src/types.ts
  website/docs/en/config/security/nonce.mdx
  website/docs/en/config/security/sri.mdx
  website/docs/en/plugins/list/plugin-lightningcss.mdx
  website/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: perf

#2513 fix: apply lightningcss minify to the correct stage
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/plugin-lightningcss/src/minimizer.ts
Labels: change: fix

#2515 feat: allow tools.rspack to be async function
  .changeset/empty-flies-own.md
  e2e/cases/configure-rspack/index.test.ts
  packages/core/src/provider/rspackConfig.ts
  packages/shared/src/reduceConfigs.ts
  packages/shared/src/types/config/tools.ts
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: change: feat

#2516 feat: allow tools.bundlerChain to be async function
  e2e/cases/bundler-chain/index.test.ts
  packages/shared/src/chain.ts
  packages/shared/src/types/config/tools.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
Labels: change: feat

#2517 feat(deps): bump Rspack v0.7.1
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  website/package.json
Labels: change: feat

#2520 docs: add filename query hash example
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: change: docs

#2527 docs: add dev server comparison
  biome.json
  website/docs/en/guide/basic/server.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/zh/guide/basic/server.mdx
  website/docs/zh/guide/migration/webpack.mdx
Labels: change: docs

#2529 docs: update module federation guide
  scripts/dictionary.txt
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
Labels: change: docs

#2533 docs: replace bundler-chain with rspack-chain
  e2e/cases/inline-chunk/index.test.ts
  packages/compat/webpack/src/plugin.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/helpers.ts
  packages/core/src/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/plugins/swc.ts
  packages/plugin-babel/src/helper.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-react/src/react.ts
  packages/plugin-source-build/src/plugin.ts
  packages/shared/src/chain.ts
  packages/shared/src/types/bundlerConfig.ts
  packages/shared/src/types/config/tools.ts
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/index.ts
  packages/shared/src/types/rspack.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/en/shared/bundlerChain.mdx
  website/docs/en/shared/rspackChain.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/index.mdx
  website/docs/zh/shared/bundlerChain.mdx
  website/docs/zh/shared/rspackChain.mdx
Labels: change: docs

#2536 docs: add tip for load env mode
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: change: docs

#2539 docs: add some bad cases of define replacement
  website/docs/en/config/source/define.mdx
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/config/source/define.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: change: docs

#2540 feat(e2e): add case for glob import
  e2e/cases/glob-import/index.test.ts
  e2e/cases/glob-import/rsbuild.config.ts
  e2e/cases/glob-import/src/App.jsx
  e2e/cases/glob-import/src/components/Footer.jsx
  e2e/cases/glob-import/src/components/Header.jsx
  e2e/cases/glob-import/src/index.js
Labels: change: feat

#2548 feat: support open with specified path
  packages/core/src/plugins/startUrl.ts
  packages/core/tests/startUrl.test.ts
  packages/shared/src/url.ts
  website/docs/en/config/dev/start-url.mdx
  website/docs/zh/config/dev/start-url.mdx
Labels: change: feat

#2549 feat: allow output.filename.js to be a function
  e2e/cases/filename-function/index.test.ts
  e2e/cases/filename-function/rsbuild.config.ts
  e2e/cases/filename-function/src/async.css
  e2e/cases/filename-function/src/async.js
  e2e/cases/filename-function/src/index.css
  e2e/cases/filename-function/src/index.js
  packages/core/src/plugins/output.ts
  packages/shared/src/fs.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: change: feat

#2550 feat(create-rsbuild): allow to add prettier as formatter
  packages/create-rsbuild/package.json
  packages/create-rsbuild/src/index.ts
  packages/create-rsbuild/template-prettier/.prettierrc
  packages/create-rsbuild/template-prettier/extra-package.json
  pnpm-lock.yaml
Labels: change: feat

#2551 feat(create-rsbuild): allow to add Biome
  packages/create-rsbuild/src/index.ts
  packages/create-rsbuild/template-biome/biome.json
  packages/create-rsbuild/template-biome/extra-package.json
  packages/create-rsbuild/template-preact-ts/src/index.tsx
  packages/create-rsbuild/template-react-ts/src/index.tsx
  packages/create-rsbuild/template-solid-ts/src/index.tsx
Labels: change: feat

#2552 feat(create-rsbuild): add svelte-check for svelte TS project
  packages/create-rsbuild/template-svelte-js/src/index.js
  packages/create-rsbuild/template-svelte-ts/package.json
  packages/create-rsbuild/template-svelte-ts/src/index.ts
Labels: change: feat

#2553 feat: add server.open config, deprecate dev.startUrl
  .changeset/red-numbers-sell.md
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/open.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/core/tests/mergeConfig.test.ts
  packages/core/tests/open.test.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/dev/before-start-url.mdx
  website/docs/en/config/server/open.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/dev/before-start-url.mdx
  website/docs/zh/config/server/open.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/server.mdx
  website/docs/zh/guide/start/features.mdx
  website/rspress.config.ts
Labels: change: feat

#2555 fix(create-rsbuild): let prettier ignore lock files
  packages/create-rsbuild/template-prettier/.prettierignore
  packages/create-rsbuild/template-prettier/.prettierrc
Labels: change: fix

#2557 feat(create-rsbuild): allow to add ESLint as linter
  packages/create-rsbuild/src/index.ts
  packages/create-rsbuild/template-eslint/common-js/eslint.config.mjs
  packages/create-rsbuild/template-eslint/common-js/extra-package.json
  packages/create-rsbuild/template-eslint/common-ts/eslint.config.mjs
  packages/create-rsbuild/template-eslint/common-ts/extra-package.json
  packages/create-rsbuild/template-eslint/react-js/eslint.config.mjs
  packages/create-rsbuild/template-eslint/react-js/extra-package.json
  packages/create-rsbuild/template-eslint/react-ts/eslint.config.mjs
  packages/create-rsbuild/template-eslint/react-ts/extra-package.json
  packages/create-rsbuild/template-eslint/svelte-js/eslint.config.mjs
  packages/create-rsbuild/template-eslint/svelte-js/extra-package.json
  packages/create-rsbuild/template-eslint/svelte-ts/eslint.config.mjs
  packages/create-rsbuild/template-eslint/svelte-ts/extra-package.json
  packages/create-rsbuild/template-eslint/vue-js/eslint.config.mjs
  packages/create-rsbuild/template-eslint/vue-js/extra-package.json
  packages/create-rsbuild/template-eslint/vue-ts/eslint.config.mjs
  packages/create-rsbuild/template-eslint/vue-ts/extra-package.json
Labels: change: feat

#2558 docs: remove duplicated comma in plugin-svgr.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
Labels: change: docs

#2559 docs: add optional tools to quick start
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2560 feat: add `server.open.before` config
  packages/core/src/plugins/open.ts
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/dev/before-start-url.mdx
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/dev/before-start-url.mdx
  website/docs/zh/config/server/open.mdx
Labels: change: feat

#2562 docs: add configuring Rspack tips
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
Labels: change: docs

#2567 docs: vite migration guide
  website/docs/en/guide/migration/_meta.json
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/migration/_meta.json
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2568 fix: allow to import multiple core-js versions
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2569 feat(deps): bump Rspack v0.7.2
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  website/package.json
Labels: change: feat

#2578 feat: support for multiple public dirs
  e2e/cases/server/public-dir/publicDir.test.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/src/plugins/server.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/watchFiles.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/server/public-dir.mdx
  website/docs/zh/config/server/public-dir.mdx
Labels: change: feat

#2579 docs: fix discord badge
  README.md
  README.zh-CN.md
Labels: change: docs

#2581 docs: improve output.copy examples
  e2e/cases/output/copy/index.test.ts
  website/docs/en/config/output/copy.mdx
  website/docs/zh/config/output/copy.mdx
Labels: change: docs

#2584 feat: type declaration for `import.meta.env`
  examples/react/package.json
  examples/react/src/App.tsx
  examples/react/src/env.d.ts
  examples/react/src/index.jsx
  examples/react/src/index.tsx
  examples/react/tsconfig.json
  packages/core/types.d.ts
  pnpm-lock.yaml
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: change: feat

#2585 docs: add 404 page redirect to document
  website/docs/404.mdx
  website/docs/public/netlify.toml
  website/docs/public/og-image.png
Labels: change: docs

#2588 feat: export plugin name const
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-babel/src/index.ts
  packages/plugin-check-syntax/src/index.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-eslint/src/index.ts
  packages/plugin-image-compress/src/index.ts
  packages/plugin-mdx/src/index.ts
  packages/plugin-node-polyfill/src/index.ts
  packages/plugin-preact/src/index.ts
  packages/plugin-pug/src/index.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-styled-components/src/index.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-toml/src/index.ts
  packages/plugin-type-check/src/index.ts
  packages/plugin-typed-css-modules/src/index.ts
  packages/plugin-umd/src/index.ts
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue/src/index.ts
  packages/plugin-vue2-jsx/src/index.ts
  packages/plugin-vue2/src/index.ts
  packages/plugin-yaml/src/index.ts
Labels: change: feat

#2589 feat: increase overlay width to display more informations
  packages/core/src/client/overlay.ts
Labels: change: feat

#2590 feat: only display verbose msgs in prod build or debug mode
  packages/core/src/client/format.ts
  packages/core/src/helpers.ts
Labels: change: feat

#2592 feat(deps): bump rspack to 0.7.3
  .changeset/beige-bags-refuse.md
  packages/core/package.json
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2593 feat: reference Rspack client module types
  packages/core/tsconfig.json
  packages/core/types.d.ts
Labels: change: feat

#2600 fix(create-rsbuild): should allow skipping tools selection
  packages/create-rsbuild/src/index.ts
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: fix

#2603 docs: add Vue SFC JSX guide
  scripts/dictionary.txt
  website/docs/en/plugins/list/plugin-vue-jsx.mdx
  website/docs/en/plugins/list/plugin-vue2-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Labels: change: docs

#2606 feat: export ensureAssetPrefix helper
  packages/core/src/helpers.ts
  packages/core/src/index.ts
  packages/core/src/plugins/open.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/server/helper.ts
  packages/core/tests/helpers.test.ts
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/shared/src/index.ts
  packages/shared/src/url.ts
  packages/shared/tests/url.test.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#2608 docs: glob imports migration
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: change: docs

#2610 feat(check-syntax): print the expected ECMA version
  e2e/cases/check-syntax/basic/index.test.ts
  packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
  packages/plugin-check-syntax/src/helpers/printErrors.ts
  website/docs/en/plugins/list/plugin-check-syntax.mdx
  website/docs/zh/plugins/list/plugin-check-syntax.mdx
Labels: change: feat

#2612 fix: chain type when using webpack plugin
  .changeset/pretty-toes-invent.md
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-source-build/src/plugin.ts
  packages/plugin-svelte/src/index.ts
  packages/shared/package.json
  packages/shared/tests/rspackChain.test.ts
  pnpm-lock.yaml
Labels: change: fix

#2614 feat: make it easier to access distPath config
  packages/core/src/createContext.ts
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/asset.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/wasm.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-svgr/src/index.ts
  packages/shared/src/fs.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#2615 docs: fix broken cssnano link
  website/docs/en/plugins/list/plugin-css-minimizer.mdx
  website/docs/zh/plugins/list/plugin-css-minimizer.mdx
Labels: change: docs

#2621 docs: use the default 404 page
  website/docs/404.mdx
Labels: change: docs

#2624 feat: init environment config
  packages/core/src/createRsbuild.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/shared/src/types/config/index.ts
Labels: change: feat

#2627 feat(deps): bump Rspack 0.7.4
  .changeset/lazy-toys-shop.md
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2631 feat: expose `reduceConfigs` helper
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/index.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/reduceConfigs.ts
  packages/core/tests/reduceConfigs.test.ts
  packages/plugin-babel/src/helper.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-less/src/index.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-pug/src/index.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/src/types.ts
  packages/plugin-styled-components/src/index.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-type-check/src/index.ts
  packages/shared/src/index.ts
  packages/shared/src/types/config/html.ts
  packages/shared/src/types/config/source.ts
  packages/shared/src/types/config/tools.ts
  packages/shared/src/types/utils.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: change: feat

#2633 feat: normalize environment config
  packages/core/src/config.ts
  packages/core/src/createContext.ts
  packages/core/src/helpers.ts
  packages/core/src/initPlugins.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/shared/src/types/config/index.ts
  packages/shared/src/types/context.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2637 perf(core): remove fs-extra dependency
  e2e/cases/cache/index.test.ts
  e2e/cases/cli/build-watch/index.test.ts
  e2e/cases/cli/load-import-meta-env/index.test.ts
  e2e/cases/cli/load-process-env/index.test.ts
  e2e/cases/inspect-config/index.test.ts
  e2e/cases/node-addons/index.test.ts
  e2e/cases/output/clean-dist-path/index.test.ts
  e2e/cases/plugin-api/plugin-after-build-hook/index.test.ts
  e2e/cases/rsdoctor/mock/index.cjs
  e2e/cases/server/public-dir/publicDir.test.ts
  e2e/cases/source/plugin-import/helper.ts
  e2e/cases/type-check/exclude-node-modules/index.test.ts
  e2e/package.json
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  packages/core/src/helpers.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/rspackProfile.ts
  packages/core/src/plugins/server.ts
  packages/create-rsbuild/package.json
  packages/plugin-babel/src/plugin.ts
  packages/plugin-source-build/src/common/isMonorepo.ts
  packages/plugin-source-build/src/project-utils/getDependentProjects.ts
  packages/plugin-source-build/src/utils.ts
  packages/shared/package.json
  packages/shared/prebundle.config.mjs
  packages/shared/src/index.ts
  packages/shared/src/utils.ts
  pnpm-lock.yaml
Labels: change: perf

#2638 fix: preload util type assertion
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/rspack/preload/helpers/extractChunks.ts
Labels: change: fix

#2639 fix: HMR not work on online IDEs
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
  website/docs/en/config/dev/client.mdx
  website/docs/zh/config/dev/client.mdx
Labels: change: fix

#2640 fix: apply default dev config
  packages/core/src/client/hmr.ts
  packages/core/src/config.ts
  packages/core/src/constants.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/server.test.ts
  packages/shared/src/types/config/dev.ts
  website/docs/en/guide/advanced/hmr.mdx
  website/docs/zh/guide/advanced/hmr.mdx
Labels: change: fix

#2636 breaking change: replace output.targets with output.target
  e2e/cases/babel/preset-node/rsbuild.config.ts
  e2e/cases/emit-assets/rsbuild.config.ts
  e2e/cases/ignore-css/removeCss.test.ts
  e2e/cases/inspect-config/index.test.ts
  e2e/cases/multi-compiler/index.test.ts
  e2e/cases/node-addons/rsbuild.config.ts
  e2e/cases/output/externals/tests/index.test.ts
  e2e/cases/output/manifest/index.test.ts
  e2e/cases/performance/print-file-size/index.test.ts
  e2e/cases/plugin-api/plugin-after-build-hook/index.test.ts
  e2e/cases/plugin-api/plugin-transform-by-targets/rsbuild.config.ts
  e2e/cases/source/alias-by-target/rsbuild.config.ts
  e2e/cases/source/multiple-entry/rsbuild.config.ts
  e2e/cases/web-worker/web-worker-target/index.test.ts
  examples/node/rsbuild.config.ts
  examples/service-worker/rsbuild.config.ts
  package.json
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/compat/webpack/src/initConfigs.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/default.test.ts
  packages/core/src/config.ts
  packages/core/src/createContext.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/css.test.ts
  packages/core/tests/default.test.ts
  packages/core/tests/html.test.ts
  packages/core/tests/inlineChunk.test.ts
  packages/core/tests/nodeAddons.test.ts
  packages/core/tests/output.test.ts
  packages/core/tests/splitChunks.test.ts
  packages/core/tests/swc.test.ts
  packages/core/tests/target.test.ts
  packages/plugin-assets-retry/tests/assetsRetry.test.ts
  packages/plugin-check-syntax/tests/index.test.ts
  packages/plugin-eslint/tests/index.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/index.test.ts
  packages/plugin-rem/tests/index.test.ts
  packages/plugin-styled-components/tests/index.test.ts
  packages/plugin-type-check/tests/index.test.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/hooks.ts
  pnpm-lock.yaml
Labels: change: breaking

#2642 feat!: remove deprecated `dev.startUrl`
  packages/core/src/config.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/open.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/shared/src/types/config/dev.ts
Labels: change: feat

#2641 feat: allow to use port placeholder in `client.port`
  e2e/cases/server/hmr/index.test.ts
  packages/core/src/server/devServer.ts
  website/docs/en/config/dev/client.mdx
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/dev/client.mdx
  website/docs/zh/config/server/open.mdx
Labels: change: feat

#2643 feat: support read environments source.entry config
  packages/core/src/createContext.ts
  packages/core/src/plugins/entry.ts
  packages/core/tests/__snapshots__/entry.test.ts.snap
  packages/core/tests/entry.test.ts
Labels: change: feat

#2646 feat!: add browserslist to context.environments
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/core/src/createContext.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/plugins/target.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/swc.test.ts
  packages/core/tests/target.test.ts
  packages/plugin-check-syntax/src/index.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/shared/src/getBrowserslist.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/context.ts
  packages/shared/tests/getBrowserslist.test.ts
Labels: change: feat

#2648 docs: override browserslist by environment
  website/docs/en/config/output/override-browserslist.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/zh/config/output/override-browserslist.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
Labels: change: docs

#2649 feat!: output.emitAssets changed to boolean type
  e2e/cases/emit-assets/rsbuild.config.ts
  e2e/cases/svg/svgr-disable-emit-asset/rsbuild.config.ts
  packages/core/src/config.ts
  packages/core/src/helpers.ts
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/asset.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/emit-assets.mdx
  website/docs/zh/config/output/emit-assets.mdx
Labels: change: feat

#2650 feat!: remove `target` param for `source.alias`
  e2e/cases/source/alias-by-target/rsbuild.config.ts
  packages/core/src/plugins/resolve.ts
  packages/shared/src/types/config/source.ts
  website/docs/en/config/source/alias.mdx
  website/docs/zh/config/source/alias.mdx
Labels: change: feat

#2647 feat: support apply environment html-related config
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/createContext.ts
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
  packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
  packages/core/tests/html.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/types/context.ts
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/utils.ts
  scripts/test-helper/src/rsbuild.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2651 docs: support htmlPlugin param in tools.rspack utils
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: change: docs

#2652 feat: support apply more environment configs
  packages/compat/webpack/src/plugin.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/plugins/splitChunks.ts
  packages/core/src/types.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-less/src/index.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-solid/src/index.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-svelte/src/index.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-vue-jsx/src/index.ts
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
Labels: change: feat

#2654 docs: add basic environment config
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/config/_meta.json
  website/docs/en/config/environments.mdx
  website/docs/en/shared/getNormalizedConfig.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/environments.mdx
  website/docs/zh/shared/getNormalizedConfig.mdx
Labels: change: docs

#2656 feat: support apply more environment configs
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/core/src/index.ts
  packages/core/src/plugins/define.ts
  packages/core/src/plugins/externals.ts
  packages/core/src/plugins/lazyCompilation.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/plugins/moment.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/resourceHints.ts
  packages/core/src/plugins/sri.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/plugins/wasm.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/external.test.ts
  packages/core/tests/swc.test.ts
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-babel/tests/index.test.ts
  packages/shared/src/chain.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: change: feat

#2658 fix: failed to empty dir in some cases
  packages/core/src/helpers.ts
Labels: change: fix

#2659 fix: should not print empty urls if target is node
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
Labels: change: fix

#2666 docs: update releases page for 1.0 release
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  website/docs/en/community/releases/index.mdx
  website/docs/zh/community/releases/index.mdx
Labels: change: docs

#2671 feat: handle more cases in ensureAssetPrefix helper
  packages/core/src/helpers.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/core/src/rspack/InlineChunkHtmlPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/server/devServer.ts
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/shared/src/utils.ts
Labels: change: feat

#2673 feat(deps): bump core-js v3.37 and @swc/helpers
  packages/compat/babel-preset/package.json
  packages/compat/babel-preset/tests/__snapshots__/web.test.ts.snap
  packages/compat/plugin-swc/package.json
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#2678 docs: update relay example to use SWC plugin
  website/docs/en/config/tools/swc.mdx
  website/docs/zh/config/tools/swc.mdx
Labels: change: docs

#2677 feat!: decorators version defaults to `2022-03`
  e2e/cases/babel/decorator/rsbuild.config.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/source/decorators.mdx
  website/docs/zh/config/source/decorators.mdx
Labels: change: feat

#2679 feat(styled-components): use SWC Wasm plugin
  packages/core/tests/mergeConfig.test.ts
  packages/plugin-styled-components/package.json
  packages/plugin-styled-components/src/index.ts
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: fix

#2681 fix: bundle analyze with environment name
  packages/core/src/plugins/bundleAnalyzer.ts
  website/docs/en/config/performance/bundle-analyze.mdx
  website/docs/zh/config/performance/bundle-analyze.mdx
Labels: change: fix

#2684 feat(type-check): allow to check multiple tsconfig files
  .github/workflows/release-nightly.yml
  e2e/cases/type-check/multiple-tsconfig/index.test.ts
  e2e/cases/type-check/multiple-tsconfig/rsbuild.config.ts
  e2e/cases/type-check/multiple-tsconfig/server/index.ts
  e2e/cases/type-check/multiple-tsconfig/src/index.ts
  e2e/cases/type-check/multiple-tsconfig/tsconfig.json
  e2e/cases/type-check/multiple-tsconfig/tsconfig.server.json
  packages/plugin-type-check/src/index.ts
Labels: change: feat

#2683 feat: print file size grouped by environment
  e2e/cases/performance/print-file-size/index.test.ts
  packages/core/src/plugins/fileSize.ts
Labels: change: feat

#2685 feat: support apply environment nonce config
  e2e/cases/nonce/basic/index.test.ts
  packages/core/src/helpers.ts
  packages/core/src/plugins/nonce.ts
Labels: change: feat

#2690 fix!: remove context.tsconfigPath
  packages/core/src/createContext.ts
  packages/core/src/provider/initConfigs.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/env.d.ts
  website/tsconfig.json
Labels: change: fix

#2691 fix: remove unused lazy compilation wrapper
  packages/core/src/plugins/lazyCompilation.ts
Labels: change: fix

#2693 fix: rspack profile outputPath unexpected
  packages/core/src/plugins/rspackProfile.ts
Labels: change: fix

#2694 docs: add guide for Preact
  website/docs/en/guide/framework/_meta.json
  website/docs/en/guide/framework/preact.mdx
  website/docs/zh/guide/framework/_meta.json
  website/docs/zh/guide/framework/preact.mdx
Labels: change: docs

#2695 types: allow to configure dev in environments
  packages/core/src/plugins/lazyCompilation.ts
  packages/shared/src/types/config/index.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: change: feat

#2696 fix!: remove `output.distPath.server`
  e2e/cases/babel/preset-node/index.test.ts
  e2e/cases/node-addons/index.test.ts
  e2e/cases/output/externals/tests/index.test.ts
  e2e/cases/performance/print-file-size/index.test.ts
  e2e/cases/plugin-api/plugin-transform-by-targets/rsbuild.config.ts
  e2e/cases/source/alias-by-target/rsbuild.config.ts
  e2e/cases/source/multiple-entry/rsbuild.config.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/constants.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/performance.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
  packages/core/tests/output.test.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/guide/basic/output-files.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/guide/basic/output-files.mdx
Labels: change: fix

#2697 fix!: remove function usage of `source.entry`
  e2e/cases/source/multiple-entry/rsbuild.config.ts
  packages/core/src/createContext.ts
  packages/core/src/plugins/entry.ts
  packages/shared/src/types/config/source.ts
  website/docs/en/config/output/override-browserslist.mdx
  website/docs/en/config/source/alias.mdx
  website/docs/en/config/source/entry.mdx
  website/docs/zh/config/output/override-browserslist.mdx
  website/docs/zh/config/source/alias.mdx
  website/docs/zh/config/source/entry.mdx
Labels: change: fix

#2698 docs: update document for `output.target`
  packages/core/src/mergeConfig.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/config/output/target.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/en/guide/basic/output-files.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/shared/onBeforeBuild.mdx
  website/docs/en/shared/onBeforeCreateCompiler.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/output/target.mdx
  website/docs/zh/config/source/entry.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
  website/docs/zh/guide/basic/output-files.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
  website/docs/zh/shared/onBeforeCreateCompiler.mdx
Labels: change: docs

#2701 docs: update badge links in README
  README.md
  README.zh-CN.md
Labels: change: docs

#2700 feat: support for merging environments config
  packages/core/src/mergeConfig.ts
  packages/core/tests/mergeConfig.test.ts
Labels: change: feat

#2699 docs: update dev command in webpack.mdx
  website/docs/en/guide/migration/webpack.mdx
Labels: change: docs

#2707 feat: add modifyEnvironmentConfig hook
  packages/core/src/initHooks.ts
  packages/core/src/initPlugins.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/hooks.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/shared/src/types/config/index.ts
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#2708 fix(plugin-sass): additionalData function type
  README.md
  README.zh-CN.md
  packages/plugin-sass/src/types.ts
Labels: change: fix

#2692 feat: support apply environment moduleFederation config
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/moduleFederation.test.ts
  packages/plugin-assets-retry/src/index.ts
Labels: change: feat

#2710 feat(create-rsbuild): enable allowImportingTsExtensions
  packages/create-rsbuild/template-lit-ts/tsconfig.json
  packages/create-rsbuild/template-preact-ts/tsconfig.json
  packages/create-rsbuild/template-react-ts/tsconfig.json
  packages/create-rsbuild/template-solid-ts/tsconfig.json
  packages/create-rsbuild/template-svelte-ts/tsconfig.json
  packages/create-rsbuild/template-vanilla-ts/tsconfig.json
  packages/create-rsbuild/template-vue2-ts/tsconfig.json
  packages/create-rsbuild/template-vue3-ts/tsconfig.json
Labels: change: feat

#2712 fix: bump Rspack 1.0 canary, fix types
  package.json
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-source-build/src/plugin.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: fix

#2713 fix: print and serve multiple environments html route correctly
  e2e/cases/environments/outputs/index.test.ts
  e2e/cases/server/environments/index.test.ts
  e2e/cases/server/environments/src/index.js
  e2e/cases/server/environments/src/web1.js
  e2e/cases/server/print-urls/index.test.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/core/src/cli/commands.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/prodServer.ts
  packages/core/tests/__snapshots__/entry.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
  packages/core/tests/entry.test.ts
  packages/core/tests/mergeConfig.test.ts
  packages/core/tests/output.test.ts
Labels: change: fix

#2714 feat: add basic server environment api
  e2e/cases/server/environments/index.test.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/shared/src/types/config/dev.ts
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
Labels: change: feat

#2715 fix(typed-css-modules): missing auto function params
  packages/plugin-typed-css-modules/src/loader.ts
  packages/plugin-typed-css-modules/tests/helper.test.ts
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: change: fix

#2716 feat!: enable LightningCSS minimizer as default CSS minimizer
  e2e/cases/css/css-minimize/index.test.ts
  e2e/cases/css/css-modules-composes/index.test.ts
  e2e/cases/css/css-modules-exports-global/index.test.ts
  e2e/cases/css/css-modules-named-export/index.test.ts
  e2e/cases/css/css-modules/index.test.ts
  e2e/cases/css/import-common-css/index.test.ts
  e2e/cases/css/import-loaders/index.test.ts
  e2e/cases/css/less-inline-js/index.test.ts
  e2e/cases/css/less-inline-js/src/a.less
  e2e/cases/css/multi-css/index.test.ts
  e2e/cases/css/nested-npm-import/index.test.ts
  e2e/cases/css/relative-import/index.test.ts
  e2e/cases/css/resolve-alias/index.test.ts
  e2e/cases/plugin-api/plugin-transform/index.test.ts
  e2e/cases/stylus-rem/index.test.ts
  e2e/cases/stylus/index.test.ts
  e2e/cases/typed-css-modules/basic/index.test.ts
  packages/core/src/plugins/minimize.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/shared/src/index.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: change: feat

#2717 fix!(plugin-lightningcss): remove minify option
  e2e/cases/css/lightningcss/index.test.ts
  packages/plugin-lightningcss/src/minimizer.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-lightningcss/src/types.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/index.test.ts
  website/docs/en/plugins/list/plugin-lightningcss.mdx
  website/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: fix

#2718 fix: no longer filter rsbuild config
  packages/core/src/createRsbuild.ts
  packages/core/tests/pickConfig.test.ts
Labels: change: fix

#2719 docs: update assets URLs
  README.md
  README.zh-CN.md
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/config/performance/bundle-analyze.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/en/guide/faq/hmr.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/config/performance/bundle-analyze.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
  website/docs/zh/guide/faq/hmr.mdx
  website/docs/zh/guide/optimization/optimize-bundle.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#2720 fix(ci): use canary specific version instead of npm tag
  package.json
  pnpm-lock.yaml
Labels: change: fix

#2722 feat(deps)!: bump Rspack 1.0 alpha
  package.json
  packages/core/package.json
  packages/core/src/plugins/sri.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2728 fix(config): no need to disable experiments.css
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2729 docs(plugin-babel): compile jsx in node_modules
  e2e/cases/solid/hmr/rsbuild.config.ts
  e2e/cases/solid/index.test.ts
  e2e/cases/solid/ref/rsbuild.config.ts
  e2e/cases/vue/jsx-basic/rsbuild.config.ts
  e2e/cases/vue/jsx-hmr/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-jsx/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-tsx/rsbuild.config.ts
  e2e/cases/vue2/jsx-basic/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-jsx/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-tsx/rsbuild.config.ts
  examples/solid/rsbuild.config.ts
  packages/create-rsbuild/template-solid-js/rsbuild.config.mjs
  packages/create-rsbuild/template-solid-ts/rsbuild.config.ts
  website/docs/en/guide/framework/solid.mdx
  website/docs/en/plugins/list/plugin-solid.mdx
  website/docs/en/plugins/list/plugin-vue-jsx.mdx
  website/docs/en/plugins/list/plugin-vue2-jsx.mdx
  website/docs/zh/guide/framework/solid.mdx
  website/docs/zh/plugins/list/plugin-solid.mdx
  website/docs/zh/plugins/list/plugin-vue-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Labels: change: docs

#2730 feat: allow to configure progress bar by environment
  packages/core/src/plugins/progress.ts
  packages/shared/src/types/config/index.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: change: feat
