Repository web-infra-dev/rsbuild, pull requests merged in 2024-07, with the labels that each got.

#2528 feat(server): support load SSR module
  e2e/cases/server/ssr/index.test.ts
  e2e/cases/server/ssr/package.json
  e2e/cases/server/ssr/rsbuild.config.ts
  e2e/cases/server/ssr/src/App.css
  e2e/cases/server/ssr/src/App.tsx
  e2e/cases/server/ssr/src/env.d.ts
  e2e/cases/server/ssr/src/index.server.tsx
  e2e/cases/server/ssr/src/index.tsx
  e2e/cases/server/ssr/src/test.ts
  e2e/cases/server/ssr/template.html
  e2e/package.json
  packages/core/src/index.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/environment.ts
  packages/core/src/server/runner/asModule.ts
  packages/core/src/server/runner/basic.ts
  packages/core/src/server/runner/cjs.ts
  packages/core/src/server/runner/esm.ts
  packages/core/src/server/runner/index.ts
  packages/core/src/server/runner/type.ts
  packages/shared/src/types/config/dev.ts
  pnpm-lock.yaml
Labels: change: feat

#2740 fix(image-compress): prefer using Rspack types
  packages/plugin-image-compress/package.json
  packages/plugin-image-compress/src/minimizer.ts
  pnpm-lock.yaml
Labels: change: fix

#2748 fix: error message in decorator
  packages/core/src/plugins/swc.ts
Labels: change: fix

#2738 feat: support output environment config when inspect config
  e2e/cases/inspect-config/debug.test.ts
  e2e/cases/inspect-config/index.test.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/compat/webpack/src/shared.ts
  packages/core/src/config.ts
  packages/core/src/internal.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/shared/src/types/provider.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: change: feat

#2749 fix(plugin-svelte): failed to HMR with style tag
  e2e/cases/svelte/hmr/src/B.svelte
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/zh/plugins/list/plugin-svelte.mdx
Labels: change: fix

#2750 fix(create-rsbuild): enable verbatimModuleSyntax for svelte
  e2e/cases/svelte/ts/tsconfig.json
  packages/create-rsbuild/template-svelte-ts/tsconfig.json
Labels: change: fix

#2753 fix(plugin-vue2): apply js resolve config to vue2 sfc template
  e2e/cases/vue/sfc-basic/index.test.ts
  e2e/cases/vue/sfc-basic/src/A.vue
  e2e/cases/vue2/sfc-basic/index.test.ts
  e2e/cases/vue2/sfc-basic/src/A.vue
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2/tests/index.test.ts
Labels: change: fix

#2755 docs: fix typo in exportsPresence example
  website/docs/en/guide/faq/exceptions.mdx
  website/docs/zh/guide/faq/exceptions.mdx
Labels: change: docs

#2756 docs: add modifyEnvironmentConfig hook
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#2754 fix(server): should match resource correctly with full url assetPrefix
  e2e/cases/prod-server/index.test.ts
  e2e/cases/server/assetPrefix/index.test.ts
  e2e/cases/server/assetPrefix/src/index.js
  packages/core/src/helpers/path.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/prodServer.ts
Labels: change: fix

#2761 feat: prettier print file size log
  e2e/cases/performance/print-file-size/index.test.ts
  packages/core/src/plugins/fileSize.ts
Labels: change: feat

#2645 fix(plugin/assets-retry): repeated retrying of async css chunk
  e2e/cases/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/types.ts
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: change: fix

#2768 feat: add environments param into rsbuild api
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/devServer.ts
  packages/shared/src/types/hooks.ts
  website/docs/en/shared/onAfterBuild.mdx
  website/docs/en/shared/onAfterCreateCompiler.mdx
  website/docs/en/shared/onAfterStartDevServer.mdx
  website/docs/en/shared/onBeforeBuild.mdx
  website/docs/en/shared/onBeforeCreateCompiler.mdx
  website/docs/en/shared/onBeforeStartDevServer.mdx
  website/docs/en/shared/onDevCompileDone.mdx
  website/docs/zh/shared/onAfterBuild.mdx
  website/docs/zh/shared/onAfterCreateCompiler.mdx
  website/docs/zh/shared/onAfterStartDevServer.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
  website/docs/zh/shared/onBeforeCreateCompiler.mdx
  website/docs/zh/shared/onBeforeStartDevServer.mdx
  website/docs/zh/shared/onDevCompileDone.mdx
Labels: change: feat

#2770 docs: fix typo in quick-start.mdx
  website/docs/en/guide/start/quick-start.mdx
Labels: change: docs

#2773 docs: remove underlines between badges
  README.md
  README.zh-CN.md
  website/docs/en/plugins/list/_meta.json
  website/docs/zh/plugins/list/_meta.json
Labels: change: docs

#2769 docs: add basic environments guide
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/environments.mdx
Labels: change: docs

#2774 fix(plugin-source-build): avoid self reference
  packages/plugin-source-build/src/plugin.ts
Labels: change: fix

#2777 fix(plugin-source-build): dedupe references
  packages/plugin-source-build/src/plugin.ts
  packages/plugin-source-build/src/types/index.ts
Labels: change: fix

#2775 fix: update plugin context and documentation
  packages/core/src/createContext.ts
  packages/shared/src/types/context.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/shared/environmentContext.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/docs/zh/shared/environmentContext.mdx
Labels: change: fix

#2781 fix(core): incorrect Rspack version
  packages/core/package.json
Labels: change: fix

#2786 perf(core): lazy load http-proxy-middleware
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/server/proxy.ts
Labels: change: perf

#2785 feat!(plugin-vue2): update Vue 2 compiler options to condense whitespace
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
  website/docs/en/plugins/list/plugin-vue2.mdx
  website/docs/zh/plugins/list/plugin-vue2.mdx
Labels: change: feat

#2790 fix: tools.rspack / bundlerChain can be used in environment config
  packages/compat/webpack/src/webpackConfig.ts
  packages/compat/webpack/tests/__snapshots__/environment.test.ts.snap
  packages/compat/webpack/tests/environment.test.ts
  packages/core/src/configChain.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
Labels: change: fix

#2791 fix(plugin-swc): type issue with moduleResolution node16+
  packages/compat/plugin-swc/modern.config.ts
  packages/compat/plugin-swc/package.json
Labels: change: fix

#2792 feat: improve the default splitting cache groups
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/index.ts
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/en/guide/optimization/split-chunk.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
  website/docs/zh/guide/optimization/split-chunk.mdx
Labels: change: feat

#2793 fix: remove cache groups helper
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
  packages/shared/src/index.ts
  packages/shared/tests/utils.test.ts
Labels: change: fix

#2788 fix: unexpected url print in windows
  packages/core/src/server/helper.ts
  packages/core/tests/helpers.test.ts
Labels: change: fix

#2795 fix: output config should works when target is node
  packages/core/src/config.ts
  packages/core/src/helpers.ts
  packages/core/src/plugins/output.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
  packages/core/tests/output.test.ts
  packages/shared/src/types/config/index.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/config/output/filename.mdx
Labels: change: fix

#2796 docs: add get environment context info guide
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#2803 feat(deps): bump Rspack 1.0.0-alpha.1
  package.json
  packages/core/package.json
  packages/core/src/plugins/rspackProfile.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#2809 perf: prefer using dynamic import to load config
  packages/core/src/config.ts
Labels: change: perf

#2804 perf!: disable polyfill injection by default
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/output/polyfill.mdx
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/zh/config/output/polyfill.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
  website/docs/zh/guide/optimization/optimize-bundle.mdx
Labels: change: perf

#2813 perf: compute gzip size in parallel
  .github/renovate.json5
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/plugins/fileSize.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: change: perf

#2743 fix: hmr failed when adding initial chunk
  e2e/cases/lazy-compilation/add-initial-chunk/index.test.ts
  e2e/cases/lazy-compilation/add-initial-chunk/rsbuild.config.ts
  e2e/cases/lazy-compilation/add-initial-chunk/src/index.js
  e2e/cases/lazy-compilation/add-initial-chunk/src/initial.js
  packages/core/src/server/socketServer.ts
Labels: change: fix

#2816 perf: simplify node_modules RegExps
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-babel/tests/index.test.ts
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
  website/docs/en/config/performance/chunk-split.mdx
  website/docs/en/config/source/include.mdx
  website/docs/en/config/source/transform-import.mdx
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/zh/config/performance/chunk-split.mdx
  website/docs/zh/config/source/include.mdx
  website/docs/zh/config/source/transform-import.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
Labels: change: perf

#2818 fix: failed to render page if html in public dir
  e2e/cases/server/public-dir-with-multi-template/index.test.ts
  e2e/cases/server/public-dir-with-multi-template/public/aa.txt
  e2e/cases/server/public-dir-with-multi-template/public/bar.html
  e2e/cases/server/public-dir-with-multi-template/public/foo.html
  e2e/cases/server/public-dir-with-multi-template/rsbuild.config.ts
  e2e/cases/server/public-dir-with-multi-template/src/bar.js
  e2e/cases/server/public-dir-with-multi-template/src/foo.js
  e2e/cases/server/public-dir-with-template/index.test.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/middlewares.ts
Labels: change: fix

#2820 perf: read file async when printing file size
  packages/core/src/plugins/fileSize.ts
Labels: change: perf

#2821 perf: bump html plugin to redue entrypoints overhead
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  pnpm-lock.yaml
Labels: change: perf

#2822 perf: bump html plugin to redue appcache overhead
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  pnpm-lock.yaml
Labels: change: perf

#2826 perf: skip PostCSS AST version compasion
  packages/core/package.json
  packages/core/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: perf

#2828 perf: resolve mjs config first
  packages/core/src/config.ts
Labels: change: perf

#2831 fix: missing picocolors dependency
  packages/core/prebundle.config.mjs
  packages/core/tsconfig.json
Labels: change: fix

#2833 perf!: remove builtin terser HTML minimizer
  e2e/cases/html-tags/function-usage/index.test.ts
  e2e/cases/html/inject/index.test.ts
  e2e/cases/html/legal-comments/index.test.ts
  e2e/cases/html/legal-comments/rsbuild.config.ts
  e2e/cases/html/legal-comments/src/index.html
  e2e/cases/html/legal-comments/src/index.js
  e2e/cases/html/meta/index.test.ts
  e2e/cases/html/minify/index.test.ts
  e2e/cases/html/minify/static/index.html
  e2e/cases/html/script-loading/index.test.ts
  e2e/cases/nonce/basic/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags/index.test.ts
  e2e/cases/rem/basic/index.test.ts
  e2e/cases/sri/algotithm/index.test.ts
  e2e/cases/sri/basic/index.test.ts
  e2e/scripts/helper.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/package.json
  packages/core/src/helpers.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/types/config/output.ts
  packages/core/src/types/thirdParty.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
  packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
  packages/core/tests/html.test.ts
  packages/core/tests/minimize.test.ts
  packages/plugin-assets-retry/package.json
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/package.json
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  pnpm-lock.yaml
  website/docs/en/config/output/filename.mdx
  website/docs/en/config/output/minify.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/config/output/minify.mdx
Labels: change: perf

#2836 feat(deps): bump Rspack 1.0.0-alpha.2
  package.json
  packages/core/package.json
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: change: feat

#2834 docs: add environment api basic guide
  packages/core/src/types/config/dev.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: change: docs

#2839 perf: bump html plugin to unify tapable
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  pnpm-lock.yaml
Labels: change: perf

#2840 feat: allow to custom CSS minify options
  e2e/cases/css/css-minify-options/index.test.ts
  e2e/cases/css/css-minify-options/rsbuild.config.ts
  e2e/cases/css/css-minify-options/src/index.css
  e2e/cases/css/css-minify-options/src/index.js
  packages/core/src/plugins/minimize.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/rspack/preload/helpers/determineAsValue.ts
  packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts
  packages/core/src/rspack/preload/helpers/extractChunks.ts
  packages/core/src/types/config/output.ts
  website/docs/en/config/output/minify.mdx
  website/docs/zh/config/output/minify.mdx
Labels: change: feat

#2842 fix(plugin-solid): remove `@babel/preset-typescript` for resolve the babel warning
  packages/plugin-solid/src/index.ts
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2845 docs: baidu SEO verification
  website/rspress.config.ts
Labels: change: docs

#2846 docs: enable sitemap for SEO
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/package.json
  website/rspress.config.ts
Labels: change: docs

#2848 docs: HTML minify guide
  scripts/dictionary.txt
  website/docs/en/guide/basic/html-template.mdx
  website/docs/en/guide/basic/json-files.mdx
  website/docs/zh/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/json-files.mdx
  website/rspress.config.ts
Labels: change: docs

#2850 fix: transform Module Federation runtime
  e2e/cases/module-federation/index.test.ts
  packages/core/src/plugins/moduleFederation.ts
Labels: change: fix

#2852 fix: incorrect WS port when using MF
  packages/core/src/plugins/moduleFederation.ts
Labels: change: fix

#2853 feat: set uniqueName for module federation HMR
  e2e/cases/module-federation/index.test.ts
  e2e/cases/module-federation/remote/moduleFederation.config.ts
  e2e/cases/module-federation/remote/src/App.js
  e2e/cases/module-federation/remote/src/Button.js
  packages/core/src/plugins/moduleFederation.ts
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  website/docs/en/config/module-federation/options.mdx
  website/docs/zh/config/module-federation/options.mdx
Labels: change: feat

#2855 docs: correct polyfill description
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
Labels: change: docs

#2856 docs: add check syntax limitations
  website/docs/en/plugins/list/plugin-check-syntax.mdx
  website/docs/zh/plugins/list/plugin-check-syntax.mdx
Labels: change: docs

#2857 perf: bump html plugin to remove lodash
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  pnpm-lock.yaml
Labels: change: perf

#2858 docs: add template params escape guide
  e2e/cases/html/template-escape/index.test.ts
  e2e/cases/html/template-escape/rsbuild.config.ts
  e2e/cases/html/template-escape/src/bar.js
  e2e/cases/html/template-escape/src/foo.js
  e2e/cases/html/template-escape/static/bar.html
  e2e/cases/html/template-escape/static/foo.html
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: change: docs

#2861 types: export HtmlRspackPlugin type
  packages/compat/webpack/tests/webpackConfig.test.ts
  packages/core/src/configChain.ts
  packages/core/src/index.ts
  packages/core/src/pluginHelper.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/rspack/preload/helpers/type.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/thirdParty.ts
  packages/plugin-assets-retry/package.json
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-rem/package.json
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  pnpm-lock.yaml
Labels: change: feat

#2863 types: allow passing user config to mergeEnvironmentConfig
  packages/core/src/types/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2868 docs: update custom loader examples
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
Labels: change: docs

#2870 perf: prebundle html-rspack-plugin
  package.json
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: change: perf

#2871 docs: improve environment config
  e2e/cases/server/environments/index.test.ts
  website/docs/en/config/environments.mdx
  website/docs/en/config/html/tags.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/en/plugins/list/plugin-check-syntax.mdx
  website/docs/zh/config/environments.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
  website/docs/zh/plugins/list/plugin-check-syntax.mdx
Labels: change: docs

#2874 feat(create-rsbuild): support for project name with npm scope
  packages/create-rsbuild/src/index.ts
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: feat

#2875 types: fix plugins type mismatch
  e2e/scripts/shared.ts
  package.json
  packages/compat/webpack/tests/helper.ts
  packages/core/src/types/plugin.ts
  pnpm-lock.yaml
  scripts/test-helper/src/rsbuild.ts
Labels: change: feat

#2877 fix: rspack plugin apply error after merging config
  packages/core/src/helpers.ts
  packages/core/tests/mergeConfig.test.ts
  scripts/dictionary.txt
Labels: change: fix

#2879 perf: prettier the compiled packages
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/plugin-babel/package.json
  packages/plugin-babel/prebundle.config.mjs
  packages/plugin-less/package.json
  packages/plugin-less/prebundle.config.mjs
  packages/plugin-rem/package.json
  packages/plugin-rem/prebundle.config.mjs
  packages/plugin-sass/package.json
  packages/plugin-sass/prebundle.config.mjs
  packages/plugin-svgr/package.json
  packages/plugin-svgr/prebundle.config.mjs
  packages/plugin-typed-css-modules/package.json
  packages/plugin-typed-css-modules/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: perf

#2883 feat(deps): bump Rspack 1.0.0-alpha.3
  e2e/cases/css/resolve-ts-paths/index.test.ts
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/define.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#2882 perf: skip calculation if browserslist is default value
  packages/core/src/plugins/target.ts
Labels: change: perf

#2835 fix(plugin-assets-retry): url calculation when using asset prefix
  e2e/cases/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: change: fix

#2867 feat: OPTIONS request return success code
  packages/core/src/server/getDevMiddlewares.ts
Labels: change: feat

#2885 fix(server): register OPTIONS fallback middleware at last
  packages/core/src/server/getDevMiddlewares.ts
Labels: change: fix

#2891 feat(CLI): add new --env-dir option
  e2e/cases/cli/custom-env-dir/env/.env
  e2e/cases/cli/custom-env-dir/index.test.ts
  e2e/cases/cli/custom-env-dir/rsbuild.config.ts
  e2e/cases/cli/custom-env-dir/src/index.js
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#2892 feat: allow to disable gzip compression size
  e2e/cases/performance/print-file-size/index.test.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/types/config/performance.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: change: feat

#2893 docs: update benchmark graph
  README.md
  README.zh-CN.md
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#2895 docs: Replace 'tailwindcss' with 'UnoCSS' in unocss.mdx
  website/docs/en/guide/basic/unocss.mdx
Labels: change: docs

#2898 perf: bump html-rspack-plugin 6.0.0-beta.8
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
  packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: perf

#2900 fix(type): webpack type should works with moduleResolution node16+
  packages/compat/webpack/modern.config.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/tsconfig.json
Labels: change: fix

#2901 fix(plugin-sass): additionalData missing string type
  packages/plugin-sass/src/types.ts
Labels: change: fix

#2905 docs: port value should be string instead of int
  website/docs/en/config/dev/client.mdx
Labels: change: docs

#2903 feat(create-rsbuild): allow to create via CLI options
  packages/create-rsbuild/package.json
  packages/create-rsbuild/src/index.ts
  pnpm-lock.yaml
Labels: change: feat

#2907 feat: allow dev.client.port to be a number
  packages/core/src/client/hmr.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/types/config/dev.ts
  website/docs/en/config/dev/client.mdx
  website/docs/zh/config/dev/client.mdx
Labels: change: feat

#2910 fix(create-rsbuild): lit should be dependency
  packages/create-rsbuild/template-lit-js/package.json
  packages/create-rsbuild/template-lit-ts/package.json
Labels: change: fix

#2911 fix(create-rsbuild): skip tools selection when using CLI options
  packages/create-rsbuild/src/index.ts
Labels: change: fix

#2914 fix: es template string breaks template compiling
  e2e/cases/html/template-with-script/index.html
  e2e/cases/html/template-with-script/index.test.ts
  e2e/cases/html/template-with-script/rsbuild.config.ts
  e2e/cases/html/template-with-script/src/index.js
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#2915 fix: allow setting NODE_ENV from env files
  e2e/cases/cli/load-node-env/.env
  e2e/cases/cli/load-node-env/index.test.ts
  e2e/cases/cli/load-node-env/rsbuild.config.ts
  e2e/cases/cli/load-node-env/src/index.js
  packages/core/src/loadEnv.ts
Labels: change: fix

#2918 docs: add create-rsbuild quick creation guide
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#2920 docs: update the builtin CHAIN_ID list
  packages/core/src/configChain.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
Labels: change: docs

#2922 feat(create-rsbuild): add framework alias and validate input
  packages/create-rsbuild/src/index.ts
Labels: change: feat

#2929 fix(webpack): should generate config files correctly when output is specified
  e2e/cases/inspect-config/index.test.ts
  packages/compat/webpack/src/inspectConfig.ts
Labels: change: fix

#2930 docs: add modify config tips
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/getNormalizedConfig.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/getNormalizedConfig.mdx
Labels: change: docs

#2936 feat(deps): bump rspack 1.0.0-alpha.4
  packages/core/package.json
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: change: feat

#2931 fix: minify.jsOptions is not pass to SwcMinimizerPlugin
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/plugin-swc/tests/plugin.test.ts
Labels: change: fix

#2938 feat: add `htmlPlugin` and `rspackConfig` template parameters
  e2e/cases/html/inject/static/index.html
  e2e/cases/html/title/index.test.ts
  e2e/cases/html/title/src/plugin-options-title.html
  examples/react/index.html
  examples/react/rsbuild.config.ts
  packages/core/src/plugins/html.ts
  website/docs/en/config/html/template-parameters.mdx
  website/docs/en/guide/basic/html-template.mdx
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/config/html/template-parameters.mdx
  website/docs/zh/guide/basic/html-template.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: change: feat

#2941 fix: only print verbose error logs in debug mode
  packages/core/src/helpers.ts
Labels: change: fix

#2942 fix: should print stats.file as file name when have build errors
  e2e/cases/type-check/basic/index.test.ts
  packages/core/src/client/format.ts
Labels: change: fix

#2946 docs: add benchmark to homepage
  README.md
  README.zh-CN.md
  pnpm-lock.yaml
  website/components/global.d.ts
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/guide/start/index.mdx
  website/package.json
  website/rspress.config.ts
  website/theme/components/Benchmark.module.scss
  website/theme/components/Benchmark.tsx
  website/theme/components/NextSteps.module.scss
  website/theme/components/NextSteps.tsx
  website/theme/components/Overview.module.scss
  website/theme/components/Overview.tsx
  website/theme/components/Step.module.scss
  website/theme/components/Step.tsx
  website/theme/components/utils.ts
  website/theme/env.d.ts
  website/theme/i18n.ts
  website/theme/index.tsx
  website/theme/pages/index.tsx
  website/theme/rsbuildPluginOverview.ts
  website/tsconfig.json
Labels: change: docs

#2947 feat: add environments as a filter of `api.transform`
  e2e/cases/plugin-api/plugin-transform-by-environments/index.test.ts
  e2e/cases/plugin-api/plugin-transform-by-environments/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-by-environments/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-by-environments/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: feat

#2949 feat(deps): bump Rspack 1.0.0-alpha.5
  packages/core/package.json
  packages/plugin-react/package.json
  pnpm-lock.yaml
Labels: change: feat

#2952 docs: fix `tools.htmlPlugin` default options
  packages/core/src/types/plugin.ts
  website/docs/en/config/html/tags.mdx
  website/docs/en/config/source/exclude.mdx
  website/docs/en/config/tools/html-plugin.mdx
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/config/html/tags.mdx
  website/docs/zh/config/source/exclude.mdx
  website/docs/zh/config/tools/html-plugin.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: change: docs

#2955 docs: fix output.externals type
  website/docs/en/config/output/externals.mdx
  website/docs/zh/config/output/externals.mdx
Labels: change: docs

#2958 docs: add tool stack to homepage
  pnpm-lock.yaml
  website/package.json
  website/theme/components/ToolStack.module.scss
  website/theme/components/ToolStack.tsx
  website/theme/i18n.ts
  website/theme/pages/index.tsx
Labels: change: docs

#2963 docs: use Rspress i18n API
  website/i18n.json
  website/theme/components/Benchmark.tsx
  website/theme/components/ToolStack.tsx
  website/theme/i18n.ts
  website/tsconfig.json
Labels: change: docs

#2965 docs: fix Vue JSX example
  website/docs/en/plugins/list/plugin-vue-jsx.mdx
  website/docs/en/plugins/list/plugin-vue2-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue2-jsx.mdx
Labels: change: docs

#2966 feat: add new plugin API to process assets
  e2e/cases/plugin-api/plugin-process-assets/index.test.ts
  e2e/cases/plugin-api/plugin-process-assets/myPlugin.ts
  e2e/cases/plugin-api/plugin-process-assets/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-process-assets/src/index.css
  e2e/cases/plugin-api/plugin-process-assets/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  scripts/dictionary.txt
Labels: change: feat

#2967 feat: allow to process assets for specific target
  e2e/cases/plugin-api/plugin-process-assets-by-targets/index.test.ts
  e2e/cases/plugin-api/plugin-process-assets-by-targets/myPlugin.ts
  e2e/cases/plugin-api/plugin-process-assets-by-targets/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-process-assets-by-targets/src/index.css
  e2e/cases/plugin-api/plugin-process-assets-by-targets/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
Labels: change: feat

#2968 feat: allow to access environment context in transform API
  e2e/cases/plugin-api/plugin-transform-by-environments/index.test.ts
  e2e/cases/plugin-api/plugin-transform-by-environments/myPlugin.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/initPlugins.ts
  packages/core/src/loader/transformLoader.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/nodeAddons.test.ts.snap
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2969 docs: move environment context to separate page
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/environment-context.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/config/output/clean-dist-path.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/environment-context.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/docs/zh/config/output/clean-dist-path.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: docs

#2970 feat: allow to access environment context in process assets
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
Labels: change: feat

#2975 feat: allow to access compiler in modifyHTMLTags hook
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/types/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2977 fix: exclude method options when checking `[hash].hot-update.json`
  packages/core/src/server/getDevMiddlewares.ts
Labels: change: fix

#2987 feat: add sources param to api.processAssets
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/plugins/sri.ts
  packages/core/src/types/plugin.ts
  packages/plugin-assets-retry/src/AssetsRetryPlugin.ts
  packages/plugin-rem/src/index.ts
Labels: change: feat

#2989 fix: webSocket stats message conflict when multiple web environment
  e2e/cases/server/environments-hmr/index.test.ts
  e2e/cases/server/environments-hmr/src/App.css
  e2e/cases/server/environments-hmr/src/App.tsx
  e2e/cases/server/environments-hmr/src/index.ts
  e2e/cases/server/environments-hmr/src/web1.js
  packages/core/src/client/hmr.ts
  packages/core/src/client/types.d.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/socketServer.ts
  packages/core/tests/server.test.ts
Labels: change: fix

#2986 feat: support add plugins for specified environment
  e2e/cases/environments/plugins/index.test.ts
  e2e/cases/environments/plugins/src/App.tsx
  e2e/cases/environments/plugins/src/index.ts
  e2e/cases/environments/plugins/src/index1.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/config.ts
  packages/core/src/configChain.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/initHooks.ts
  packages/core/src/initPlugins.ts
  packages/core/src/pluginManager.ts
  packages/core/src/plugins/html.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config/index.ts
  packages/core/src/types/context.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/environments.test.ts
  packages/core/tests/hooks.test.ts
  packages/core/tests/pluginDagSort.test.ts
  packages/core/tests/pluginStore.test.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/index.test.ts
  website/docs/en/config/environments.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/config/environments.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: change: feat

#2993 docs: add `api.processAssets` API
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: docs

#2992 fix: modify the criteria for verifying the Rsdoctor plugin
  packages/core/src/plugins/rsdoctor.ts
Labels: change: fix

#2995 docs: update modifyEnvironmentConfig example code
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#2996 docs: correct onAfterCreateCompiler example
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: change: docs

#2994 feat: more plugins support used as environment plugin
  e2e/cases/environments/vue-react-plugins/index.test.ts
  e2e/cases/environments/vue-react-plugins/rsbuild.config.ts
  e2e/cases/environments/vue-react-plugins/src/react/App.tsx
  e2e/cases/environments/vue-react-plugins/src/react/index.ts
  e2e/cases/environments/vue-react-plugins/src/vue/A.jsx
  e2e/cases/environments/vue-react-plugins/src/vue/index.js
  packages/core/src/index.ts
  packages/plugin-preact/src/index.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-source-build/src/plugin.ts
  packages/plugin-styled-components/src/index.ts
  packages/plugin-vue/src/index.ts
  packages/plugin-vue2/src/index.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: change: feat

#2998 fix: only listen to process exit when onExit hook is used
  e2e/cases/cli/vue/rsbuild.config.mjs
  packages/core/src/initPlugins.ts
Labels: change: fix

#3001 fix: css-loader type declaration is outdated
  packages/core/src/types/thirdParty.ts
Labels: change: fix

#3003 docs(instance.mdx): adjust the references
  website/docs/zh/api/javascript-api/instance.mdx
Labels: change: docs

#3004 docs: distinguish between rspack watchOptions and rsbuild watchFiles configuration
  website/docs/en/config/dev/watch-files.mdx
  website/docs/zh/config/dev/watch-files.mdx
Labels: change: docs

#3008 docs: fix build typo in the benchmark
  website/theme/components/Benchmark.tsx
Labels: change: docs

#3009 feat: add environments as a filter of `api.processAssets`
  e2e/cases/plugin-api/plugin-process-assets-by-environments/index.test.ts
  e2e/cases/plugin-api/plugin-process-assets-by-environments/myPlugin.ts
  e2e/cases/plugin-api/plugin-process-assets-by-environments/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-process-assets-by-environments/src/index.css
  e2e/cases/plugin-api/plugin-process-assets-by-environments/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/pluginManager.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: feat

#3000 feat: enable inline chunks based on conditions through output options
  e2e/cases/inline-chunk/index.test.ts
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/types/config/output.ts
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/en/config/output/inline-styles.mdx
  website/docs/zh/config/output/inline-scripts.mdx
  website/docs/zh/config/output/inline-styles.mdx
Labels: change: feat

#3012 docs: add tips for inline scripts in production mode
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/en/config/output/inline-styles.mdx
  website/docs/zh/config/output/inline-scripts.mdx
  website/docs/zh/config/output/inline-styles.mdx
Labels: change: docs

#3018 docs: update Rstack repo links
  README.md
  README.zh-CN.md
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/README.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
  website/package.json
  website/theme/components/Benchmark.tsx
  website/theme/components/ToolStack.tsx
  website/theme/index.tsx
Labels: change: docs

#3022 feat(deps): bump Rspack 1.0.0-beta.0
  e2e/cases/swc-plugin/package.json
  packages/core/package.json
  packages/core/src/helpers.ts
  packages/plugin-react/package.json
  packages/plugin-styled-components/package.json
  pnpm-lock.yaml
Labels: change: feat

#3024 feat: allow absolute output path for inspectConfig
  e2e/cases/inspect-config/index.test.ts
  packages/compat/webpack/src/inspectConfig.ts
  packages/core/src/cli/commands.ts
  packages/core/src/provider/inspectConfig.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: change: feat

#3025 fix(core): incorrect exports fields
  packages/core/package.json
Labels: change: fix

#3026 fix(plugin-sass): type issue with moduleResolution node16+
  packages/compat/webpack/modern.config.ts
  packages/plugin-sass/modern.config.ts
  packages/plugin-sass/package.json
  scripts/config/modern.config.ts
Labels: change: fix

#3034 feat: enable lightningcss-loader by default
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/tools/css-loader.mdx
  website/docs/zh/config/tools/css-loader.mdx
Labels: change: feat

#3035 perf!: remove built-in autoprefixer
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/plugins/css.ts
  packages/core/src/types/config/output.ts
  packages/core/src/types/config/tools.ts
  packages/core/src/types/thirdParty.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/css.test.ts
  packages/core/tsconfig.json
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
  website/docs/en/config/output/override-browserslist.mdx
  website/docs/en/config/tools/autoprefixer.mdx
  website/docs/en/config/tools/postcss.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/plugins/list/plugin-lightningcss.mdx
  website/docs/zh/config/tools/autoprefixer.mdx
  website/docs/zh/config/tools/postcss.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
  website/docs/zh/guide/basic/css-usage.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
  website/docs/zh/guide/start/features.mdx
  website/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: perf

#3036 perf: skip postcss-loader if no plugins are registered
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: change: perf

#3038 fix: targets options of lightningcss-loader
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/css.test.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#3039 fix: targets of lightningcss-loader not work
  e2e/cases/css/lightningcss-prefixes/.browserslistrc
  e2e/cases/css/lightningcss-prefixes/index.test.ts
  e2e/cases/css/lightningcss-prefixes/src/index.css
  e2e/cases/css/lightningcss-prefixes/src/index.js
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  scripts/dictionary.txt
Labels: change: fix

#3043 feat: add new `tools.lightningcssLoader` config
  packages/core/src/plugins/css.ts
  packages/core/src/types/config/tools.ts
  website/docs/en/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
Labels: change: feat

#3047 fix!: remove lightningcss plugin
  e2e/cases/css/lightningcss/index.test.ts
  e2e/cases/css/lightningcss/rsbuild.config.ts
  e2e/cases/css/lightningcss/src/_styl.js
  e2e/cases/css/lightningcss/src/a.module.less
  e2e/cases/css/lightningcss/src/b.module.scss
  e2e/cases/css/lightningcss/src/c.module.styl
  e2e/cases/css/lightningcss/src/index.html
  e2e/cases/css/lightningcss/src/index.js
  e2e/cases/css/lightningcss/src/minify.css
  e2e/cases/css/lightningcss/src/transform.css
  e2e/cases/esm-exports/test.mjs
  e2e/package.json
  packages/plugin-lightningcss/LICENSE
  packages/plugin-lightningcss/README.md
  packages/plugin-lightningcss/modern.config.ts
  packages/plugin-lightningcss/package.json
  packages/plugin-lightningcss/src/index.ts
  packages/plugin-lightningcss/src/loader.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-lightningcss/src/types.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/index.test.ts
  packages/plugin-lightningcss/tsconfig.json
  pnpm-lock.yaml
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/plugins/list/_meta.json
  website/docs/en/plugins/list/index.mdx
  website/docs/en/plugins/list/plugin-lightningcss.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/start/features.mdx
  website/docs/zh/plugins/list/_meta.json
  website/docs/zh/plugins/list/index.mdx
  website/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: fix

#3048 fix: set browserset for lightningcss minimizer
  e2e/cases/css/lightningcss-prefixes/index.test.ts
  packages/core/src/plugins/minimize.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/minimize.test.ts
Labels: change: fix

#3049 docs: add guide for builtin lightningcss loader
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: change: docs

#3051 fix: add uniqueName to WebSocket compilation name
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/socketServer.ts
Labels: change: fix

#3053 docs: add remove plugin tip when use environment plugin
  packages/core/tests/pluginStore.test.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: change: docs

#3054 fix: processAssets callback should only called once
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/index.test.ts
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/myPlugin.ts
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/src/index.css
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/src/index.js
  e2e/cases/plugin-api/plugin-process-assets-with-html-child-compiler/static/index.html
  packages/core/src/initPlugins.ts
Labels: change: fix

#3060 docs: make moduleFederation.options more clear
  website/docs/en/config/module-federation/options.mdx
  website/docs/zh/config/module-federation/options.mdx
Labels: change: docs

#3061 docs: simplify `tools.rspack` examples
  website/docs/en/config/dev/watch-files.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/zh/config/dev/watch-files.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
Labels: change: docs

#3062 perf: prebundle postcss
  packages/core/package.json
  packages/core/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: perf

#3063 perf: remove cosmiconfig from postcss-loader
  packages/core/prebundle.config.mjs
Labels: change: perf

#3064 perf: bump rspack-manifest-plugin v5.0.1
  packages/core/package.json
  packages/core/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: perf

#3065 feat: add `isWatch` param to determine whether it is watch mode when build
  packages/compat/webpack/src/build.ts
  packages/core/src/provider/build.ts
  packages/core/src/types/hooks.ts
  website/docs/en/shared/onAfterBuild.mdx
  website/docs/en/shared/onBeforeBuild.mdx
  website/docs/zh/shared/onAfterBuild.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
Labels: change: feat
