Repository web-infra-dev/rsbuild, pull requests merged in 2024-03, with the labels that each got.

#1705 feat: add output.distPath.jsAsync config
  .changeset/slimy-wasps-tell.md
  packages/core/tests/output.test.ts
  packages/document/docs/en/config/output/dist-path.mdx
  packages/document/docs/zh/config/output/dist-path.mdx
  packages/shared/src/chain.ts
  packages/shared/src/fs.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#1707 feat: add output.distPath.cssAsync config
  e2e/cases/custom-dist-path/index.test.ts
  e2e/cases/custom-dist-path/rsbuild.config.ts
  e2e/cases/custom-dist-path/src/async.css
  e2e/cases/custom-dist-path/src/async.js
  e2e/cases/custom-dist-path/src/index.css
  e2e/cases/custom-dist-path/src/index.js
  e2e/cases/custom-dist-path/src/small.png
  packages/compat/webpack/src/plugins/output.ts
  packages/core/src/provider/plugins/output.ts
  packages/document/docs/en/config/output/dist-path.mdx
  packages/document/docs/zh/config/output/dist-path.mdx
  packages/shared/src/fs.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#1712 docs: add example for modifyRsbuildConfig
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#1714 docs: intro merge rule of mergeRsbuildConfig
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: docs

#1716 types: narrow dev.client.protocol type
  packages/core/src/client/hmr/createSocketUrl.ts
  packages/core/src/server/helper.ts
  packages/core/tests/server.test.ts
  packages/document/docs/en/config/dev/client.mdx
  packages/document/docs/en/guide/advanced/hmr.md
  packages/document/docs/zh/config/dev/client.mdx
  packages/document/docs/zh/guide/advanced/hmr.md
  packages/shared/src/types/config/dev.ts
Labels: change: feat

#1718 docs(README): add graphs contributors
  README.md
  README.zh-CN.md
Labels: change: docs

#1719 docs: improve contributor graph query params
  README.md
  README.zh-CN.md
Labels: change: docs

#1720 docs: update benchmark data
  README.md
  README.zh-CN.md
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#1721 feat(plugin-source-build): support merge user references config
  e2e/cases/source-build/components/package.json
  packages/plugin-source-build/src/index.ts
Labels: change: feat

#1722 feat(plugin-source-build): support analyze exports field
  e2e/cases/source-build/utils/package.json
  packages/monorepo-utils/src/project-utils/filter.ts
  packages/monorepo-utils/src/project/project.ts
  packages/plugin-source-build/src/index.ts
Labels: change: feat

#1723 feat(plugin-css-minimizer): export webpack-plugin to let users customize configurations
  packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx
  packages/document/docs/zh/plugins/list/plugin-css-minimizer.mdx
  packages/plugin-css-minimizer/src/index.ts
Labels: change: feat

#1725 feat(plugin-rem): apply html.scriptLoading to runtime script
  .changeset/sweet-tools-end.md
  e2e/cases/rem/basic/index.test.ts
  e2e/cases/rem/basic/tsconfig.json
  e2e/cases/rem/with-viewport/index.test.ts
  e2e/cases/rem/with-viewport/rsbuild.config.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1729 docs: add using unplugin guide
  packages/document/docs/en/config/plugins.mdx
  packages/document/docs/zh/config/plugins.mdx
Labels: change: docs

#1731 docs: add more guide for html plugin
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/en/config/tools/html-plugin.mdx
  packages/document/docs/en/guide/basic/html-template.md
  packages/document/docs/en/plugins/list/plugin-assets-retry.mdx
  packages/document/docs/zh/config/html/tags.mdx
  packages/document/docs/zh/config/tools/html-plugin.mdx
  packages/document/docs/zh/guide/basic/html-template.md
  packages/document/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: change: docs

#1733 feat: add tools.swc config to configure builtin swc-loader
  .changeset/wicked-rules-drive.md
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/core/tests/swc.test.ts
  packages/shared/src/types/config/tools.ts
Labels: change: feat

#1730 feat: add output.minify config
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/compat/webpack/src/plugins/minimize.ts
  packages/compat/webpack/tests/minimize.test.ts
  packages/core/src/plugins/html.ts
  packages/core/src/provider/config.ts
  packages/core/src/provider/plugins/minimize.ts
  packages/core/tests/mergeConfig.test.ts
  packages/core/tests/minimize.test.ts
  packages/document/docs/en/config/output/disable-minimize.mdx
  packages/document/docs/en/config/output/minify.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/zh/config/output/disable-minimize.mdx
  packages/document/docs/zh/config/output/minify.mdx
  packages/document/docs/zh/guide/start/features.mdx
  packages/plugin-css-minimizer/src/index.ts
  packages/shared/src/config.ts
  packages/shared/src/minimize.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#1736 fix: merge tools.swc deeply with default config
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/swc.test.ts.snap
Labels: change: fix

#1737 docs: add tools.swc document
  packages/document/docs/en/config/output/minify.mdx
  packages/document/docs/en/config/tools/style-loader.mdx
  packages/document/docs/en/config/tools/swc.mdx
  packages/document/docs/zh/config/output/minify.mdx
  packages/document/docs/zh/config/tools/style-loader.mdx
  packages/document/docs/zh/config/tools/swc.mdx
Labels: change: docs

#1744 docs: add emotion and relay guide
  packages/document/docs/en/config/tools/swc.mdx
  packages/document/docs/zh/config/tools/swc.mdx
Labels: change: docs

#1749 fix(create-rsbuild): remove vue3 deprecated plugin (TypeScript Vue Plugin)
  packages/create-rsbuild/template-vue3-js/.vscode/extensions.json
  packages/create-rsbuild/template-vue3-ts/.vscode/extensions.json
Labels: change: fix

#1750 feat: coloring printed asset names
  packages/core/src/plugins/fileSize.ts
Labels: change: feat

#1752 fix(webpack): duplicated JS minimizer
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/webpack/tests/minimize.test.ts
Labels: change: fix

#1755 feat: allow output.dataUriLimit to be a number
  .changeset/soft-dryers-brake.md
  e2e/cases/output/assets.test.ts
  packages/core/src/plugins/asset.ts
  packages/document/docs/en/config/output/data-uri-limit.mdx
  packages/document/docs/zh/config/output/data-uri-limit.mdx
  packages/plugin-svgr/src/index.ts
  packages/shared/src/types/config/output.ts
Labels: change: feat

#1756 fix: print ipv6 url correctly
  packages/shared/src/url.ts
Labels: change: fix

#1757 docs: add assetPrefix path types tip
  packages/document/docs/en/config/dev/asset-prefix.mdx
  packages/document/docs/en/config/output/asset-prefix.mdx
  packages/document/docs/zh/config/dev/asset-prefix.mdx
  packages/document/docs/zh/config/output/asset-prefix.mdx
Labels: change: docs

#1759 docs: add ipv6 setup guide
  packages/document/docs/en/config/server/host.mdx
  packages/document/docs/zh/config/server/host.mdx
  packages/shared/src/url.ts
Labels: change: docs

#1762 fix: html-rspack-plugin peer dependency issue
  packages/compat/webpack/package.json
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1763 fix: emit assets to server dist folder correctly
  e2e/cases/node-addons/index.test.ts
  e2e/cases/node-addons/rsbuild.config.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/output.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
  packages/document/docs/en/config/output/targets.mdx
  packages/document/docs/zh/config/output/targets.mdx
  packages/shared/src/chain.ts
Labels: change: fix

#1764 fix: failed to print size of multiple targets
  e2e/cases/performance/print-file-size/index.test.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/provider/build.ts
  packages/shared/src/types/stats.ts
Labels: change: fix

#1767 fix: incorrect node addons path
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/compiled/node-loader/index.d.ts
  packages/core/compiled/node-loader/index.js
  packages/core/compiled/node-loader/license
  packages/core/compiled/node-loader/package.json
  packages/core/src/plugins/nodeAddons.ts
  packages/core/src/rspack/nodeAddonsLoader.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/nodeAddons.test.ts.snap
  packages/shared/src/fs.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: fix

#1768 fix: use raw loader to handle Node addons
  e2e/cases/node-addons/index.test.ts
  e2e/cases/node-addons/src/a.node
  e2e/cases/node-addons/src/index.js
  packages/core/src/rspack/nodeAddonsLoader.ts
Labels: change: fix

#1771 fix(core): call `onAfterBuild` on every build
  packages/compat/webpack/src/core/build.ts
  packages/core/src/provider/build.ts
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/shared/onAfterBuild.md
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/shared/onAfterBuild.md
  packages/shared/src/types/hooks.ts
Labels: change: fix

#1772 docs: update hooks documents
  packages/document/docs/en/community/releases/v0-3.mdx
  packages/document/docs/en/config/tools/swc.mdx
  packages/document/docs/en/guide/faq/exceptions.md
  packages/document/docs/en/shared/onAfterBuild.md
  packages/document/docs/en/shared/onAfterCreateCompiler.md
  packages/document/docs/en/shared/onBeforeBuild.md
  packages/document/docs/en/shared/onBeforeCreateCompiler.md
  packages/document/docs/zh/community/releases/v0-3.mdx
  packages/document/docs/zh/config/tools/swc.mdx
  packages/document/docs/zh/guide/faq/exceptions.md
  packages/document/docs/zh/shared/onAfterBuild.md
  packages/document/docs/zh/shared/onAfterCreateCompiler.md
  packages/document/docs/zh/shared/onBeforeBuild.md
  packages/document/docs/zh/shared/onBeforeCreateCompiler.md
Labels: change: docs

#1777 fix: should await for onDevCompileDone hook
  packages/compat/webpack/src/core/createCompiler.ts
  packages/core/src/provider/createCompiler.ts
Labels: change: fix

#1780 docs: update contribution guide
  CONTRIBUTING.md
  package.json
Labels: change: docs

#1781 docs: fix missing container type
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/zh/guide/start/npm-packages.mdx
Labels: change: docs

#1783 feat(plugin-svgr): support for react query
  e2e/cases/svg/svgr-query-react/index.test.ts
  e2e/cases/svg/svgr-query-react/rsbuild.config.ts
  e2e/cases/svg/svgr-query-react/src/App.jsx
  e2e/cases/svg/svgr-query-react/src/index.js
  e2e/cases/svg/svgr-query-react/src/small.svg
  packages/core/src/plugins/asset.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/chain.ts
  packages/shared/src/config.ts
Labels: change: feat

#1786 docs(plugin-svgr): add react query guide
  .changeset/little-ways-hunt.md
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
Labels: change: docs

#1789 fix(plugin-svgr): prefer using svgrOptions.exportType option
  e2e/cases/svg/svg.test.ts
  e2e/cases/svg/svgo-minify-id-prefix/rsbuild.config.ts
  e2e/cases/svg/svgo-minify-view-box/rsbuild.config.ts
  e2e/cases/svg/svgr-default-export-url/rsbuild.config.ts
  e2e/cases/svg/svgr-query-url/rsbuild.config.ts
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/index.test.ts
Labels: change: fix

#1796 feat: support for SWC experimental plugins
  .gitignore
  e2e/cases/swc-plugin/index.test.ts
  e2e/cases/swc-plugin/package.json
  e2e/cases/swc-plugin/rsbuild.config.ts
  e2e/cases/swc-plugin/src/index.js
  packages/shared/src/types/rspack.ts
  pnpm-lock.yaml
Labels: change: feat

#1800 docs: add tailwindcss package installation tip
  packages/document/docs/en/guide/basic/tailwindcss.mdx
  packages/document/docs/zh/guide/basic/tailwindcss.mdx
Labels: change: docs

#1802 feat(deps): bump core-js from v3.32 to v3.36
  packages/babel-preset/package.json
  packages/babel-preset/tests/__snapshots__/web.test.ts.snap
  packages/compat/plugin-swc/package.json
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#1741 feat(plugin-lightningcss): integrated rsbuild with lightningcss
  e2e/cases/css/lightningcss/index.test.ts
  e2e/cases/css/lightningcss/src/_styl.js
  e2e/cases/css/lightningcss/src/a.module.less
  e2e/cases/css/lightningcss/src/b.module.scss
  e2e/cases/css/lightningcss/src/c.module.styl
  e2e/cases/css/lightningcss/src/index.html
  e2e/cases/css/lightningcss/src/index.js
  e2e/cases/css/lightningcss/src/minify.css
  e2e/cases/css/lightningcss/src/transform.css
  e2e/package.json
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
  packages/plugin-lightningcss/LICENSE
  packages/plugin-lightningcss/README.md
  packages/plugin-lightningcss/modern.config.ts
  packages/plugin-lightningcss/package.json
  packages/plugin-lightningcss/src/index.ts
  packages/plugin-lightningcss/src/loader.ts
  packages/plugin-lightningcss/src/minimizer.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-lightningcss/src/types.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/index.test.ts
  packages/plugin-lightningcss/tsconfig.json
  packages/shared/src/chain.ts
  pnpm-lock.yaml
Labels: change: feat

#1808 docs: add Lightning CSS to intro
  README.md
  README.zh-CN.md
  packages/document/docs/en/community/releases/v0-1.mdx
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/community/releases/v0-1.mdx
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#1805 feat(plugin-svgr): add mixedImport option
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/index.test.ts
Labels: change: feat

#1811 breaking change(svgr): remove deprecated svgDefaultExport
  packages/plugin-svgr/src/index.ts
Labels: change: breaking

#1815 breaking change(svgr): disable mixed import by default
  e2e/cases/svg/svg-external-react/src/App.jsx
  e2e/cases/svg/svg/src/App.jsx
  e2e/cases/svg/svgo-minify-id-prefix/src/index.jsx
  e2e/cases/svg/svgo-minify-view-box/src/index.jsx
  e2e/cases/svg/svgr-default-export-url/rsbuild.config.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: change: breaking

#1816 fix(svgr): named type without mixed import not work
  e2e/cases/svg/svg-assets/index.test.ts
  e2e/cases/svg/svg.test.ts
  e2e/cases/svg/svg/src/App.css
  e2e/cases/svg/svg/src/App.jsx
  e2e/cases/svg/svgr-default-export-component/index.test.ts
  e2e/cases/svg/svgr-default-export-component/rsbuild.config.ts
  e2e/cases/svg/svgr-default-export-component/src/App.jsx
  e2e/cases/svg/svgr-default-export-component/src/app.svg
  e2e/cases/svg/svgr-default-export-component/src/index.js
  e2e/cases/svg/svgr-external-react/index.test.ts
  e2e/cases/svg/svgr-external-react/rsbuild.config.ts
  e2e/cases/svg/svgr-external-react/src/App.css
  e2e/cases/svg/svgr-external-react/src/App.jsx
  e2e/cases/svg/svgr-external-react/src/app.svg
  e2e/cases/svg/svgr-external-react/src/index.js
  e2e/cases/svg/svgr-external-react/static/index.html
  e2e/cases/svg/svgr-named-export-component copy/index.test.ts
  e2e/cases/svg/svgr-named-export-component copy/rsbuild.config.ts
  e2e/cases/svg/svgr-named-export-component copy/src/App.jsx
  e2e/cases/svg/svgr-named-export-component copy/src/app.svg
  e2e/cases/svg/svgr-named-export-component copy/src/index.js
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1819 docs: make some demos more type friendly
  .vscode/settings.json
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/en/plugins/dev/index.md
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
  packages/document/docs/zh/plugins/dev/index.md
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
Labels: change: docs

#1823 docs: add check syntax link to source.include
  packages/document/docs/en/config/source/include.mdx
  packages/document/docs/zh/config/source/include.mdx
Labels: change: docs

#1822 feat(plugin-svgr): add support for mdx
  e2e/cases/svg/svgr-mdx/index.test.ts
  e2e/cases/svg/svgr-mdx/rsbuild.config.ts
  e2e/cases/svg/svgr-mdx/src/app.mdx
  e2e/cases/svg/svgr-mdx/src/index.js
  e2e/cases/svg/svgr-mdx/src/small.svg
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1827 breaking change: remove deprecated disableMinimize config
  .changeset/new-flowers-tie.md
  e2e/cases/styled-component/index.test.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/compat/webpack/src/plugins/minimize.ts
  packages/compat/webpack/tests/minimize.test.ts
  packages/core/src/provider/config.ts
  packages/core/src/provider/plugins/minimize.ts
  packages/core/tests/minimize.test.ts
  packages/document/docs/en/config/output/disable-minimize.mdx
  packages/document/docs/en/config/tools/html-plugin.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/en/plugins/dev/index.md
  packages/document/docs/en/plugins/list/plugin-check-syntax.mdx
  packages/document/docs/zh/config/output/disable-minimize.mdx
  packages/document/docs/zh/config/tools/html-plugin.mdx
  packages/document/docs/zh/guide/start/features.mdx
  packages/document/docs/zh/plugins/dev/index.md
  packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/shared/src/config.ts
  packages/shared/src/types/config/output.ts
Labels: change: breaking

#1830 fix(plugin-type-check): options type should be non nullable
  packages/plugin-type-check/src/index.ts
  packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
  packages/plugin-type-check/tests/index.test.ts
Labels: change: fix

#1831 docs: fix yarn1.x create@latest wont work
  packages/document/docs/en/guide/framework/react.mdx
  packages/document/docs/en/guide/framework/solid.mdx
  packages/document/docs/en/guide/framework/svelte.mdx
  packages/document/docs/en/guide/framework/vue2.mdx
  packages/document/docs/en/guide/framework/vue3.mdx
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/guide/framework/react.mdx
  packages/document/docs/zh/guide/framework/solid.mdx
  packages/document/docs/zh/guide/framework/svelte.mdx
  packages/document/docs/zh/guide/framework/vue2.mdx
  packages/document/docs/zh/guide/framework/vue3.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#1832 fix: improve greet log when using bun
  packages/core/src/cli/prepare.ts
Labels: change: fix

#1833 docs: correct output.minify examples
  packages/document/docs/en/config/output/minify.mdx
  packages/document/docs/zh/config/output/minify.mdx
Labels: change: docs

#1838 docs: add Rspack Profiling guide
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/zh/guide/optimization/build-performance.mdx
Labels: change: docs

#1839 feat: enable new tree shaking in production
  cspell.json
  packages/core/src/provider/plugins/transition.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: change: feat

#1840 fix: handle more cases in ES version helper
  packages/shared/src/getBrowserslist.ts
  packages/shared/tests/getBrowserslist.test.ts
Labels: change: fix

#1841 fix: set correct rspack target based on browserslist
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/target.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/target.test.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/getBrowserslist.ts
Labels: change: fix

#1844 feat(plugin-check-syntax): support infer es2016 to es2018
  e2e/cases/check-syntax/index.test.ts
  packages/document/docs/en/plugins/list/plugin-check-syntax.mdx
  packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
  packages/plugin-check-syntax/package.json
  packages/plugin-check-syntax/src/CheckSyntaxPlugin.ts
  packages/plugin-check-syntax/src/helpers/getEcmaVersion.ts
  packages/plugin-check-syntax/src/helpers/index.ts
  packages/plugin-check-syntax/tests/CheckSyntaxPlugin.test.ts
  packages/plugin-check-syntax/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#1849 docs: improve SVGR types guide
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
Labels: change: docs

#1851 feat: allow tools.htmlPlugin to be true
  e2e/cases/umd/basic/rsbuild.config.ts
  e2e/cases/umd/export-array/rsbuild.config.ts
  e2e/cases/umd/export/rsbuild.config.ts
  packages/core/src/plugins/html.ts
  packages/document/docs/en/config/tools/html-plugin.mdx
  packages/document/docs/zh/config/tools/html-plugin.mdx
  packages/shared/src/types/config/tools.ts
Labels: change: feat

#1852 docs(plugin-umd): add HTML generation tip
  packages/document/docs/en/plugins/list/plugin-umd.mdx
  packages/document/docs/zh/plugins/list/plugin-umd.mdx
Labels: change: docs

#1853 docs: use Rsdoctor for duplicated packages
  packages/document/docs/en/config/module-federation/options.mdx
  packages/document/docs/en/guide/optimization/optimize-bundle.md
  packages/document/docs/zh/config/module-federation/options.mdx
  packages/document/docs/zh/guide/optimization/optimize-bundle.md
Labels: change: docs

#1860 feat: support setting html.tags by entry name
  e2e/cases/html-tags/basic/index.test.ts
  e2e/cases/html-tags/basic/rsbuild.config.ts
  e2e/cases/html-tags/basic/src/index.js
  e2e/cases/html-tags/index.test.ts
  e2e/cases/html-tags/modify-by-entry/index.test.ts
  e2e/cases/html-tags/modify-by-entry/rsbuild.config.ts
  e2e/cases/html-tags/modify-by-entry/src/bar.js
  e2e/cases/html-tags/modify-by-entry/src/foo.js
  e2e/cases/html-tags/src/foo.ts
  e2e/cases/html-tags/src/index.ts
  e2e/cases/html-tags/tsconfig.json
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/en/config/performance/chunk-split.mdx
  packages/document/docs/en/plugins/dev/core.mdx
  packages/document/docs/zh/config/html/tags.mdx
  packages/document/docs/zh/config/performance/chunk-split.mdx
  packages/shared/src/types/config/html.ts
Labels: change: feat

#1863 docs: modify MacOS to macOS
  packages/document/docs/en/config/dev/start-url.mdx
Labels: change: docs

#1862 docs: modify Toml to TOML
  packages/document/docs/en/config/tools/bundler-chain.mdx
Labels: change: docs

#1868 fix: allow `html.tags` function to modify append
  e2e/cases/html-tags/function-usage/index.test.ts
  e2e/cases/html-tags/function-usage/rsbuild.config.ts
  e2e/cases/html-tags/function-usage/src/index.js
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/zh/config/html/tags.mdx
Labels: change: fix

#1869 docs: add react-jest example to CRA migration doc
  packages/document/docs/en/guide/migration/cra.mdx
  packages/document/docs/zh/guide/migration/cra.mdx
Labels: change: docs

#1873 docs: update custom server introduce
  packages/document/docs/en/guide/basic/server.md
  packages/document/docs/zh/guide/basic/server.md
Labels: change: docs

#1875 fix: revert new tree shaking
  .changeset/lazy-terms-perform.md
  packages/core/src/provider/plugins/transition.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: change: fix

#1879 fix: allow to call loadConfig without options
  packages/core/src/config.ts
  packages/core/src/createRsbuild.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: fix

#1880 docs: update custom server example
  e2e/cases/server/custom-server/index.test.ts
  e2e/cases/server/custom-server/scripts/pure-server.mjs
  e2e/cases/server/custom-server/scripts/server.mjs
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/zh/api/javascript-api/instance.mdx
Labels: change: docs

#1884 docs: announcing Rsbuild v0.5
  packages/document/docs/en/community/releases/_meta.json
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/community/releases/_meta.json
  packages/document/docs/zh/community/releases/v0-5.mdx
  packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: docs

#1885 docs(plugin-lightningcss): notes of lightningcss
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: docs

#1886 docs: fix mistake of cssModules.auto RegExp
  packages/document/docs/en/community/releases/v0-5.mdx
  packages/document/docs/zh/config/output/css-modules.mdx
Labels: change: docs

#1887 feat: bump Rspack v0.5.8
  packages/core/package.json
  packages/plugin-lightningcss/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: feat

#1892 docs: add meta tag for displaying twitter card
  packages/document/docs/public/og-image.png
  packages/document/rspress.config.ts
Labels: change: docs

#1893 docs: update outdated tree shaking link
  package.json
  packages/document/docs/en/guide/faq/exceptions.md
  packages/document/docs/en/guide/optimization/optimize-bundle.md
  packages/document/docs/en/guide/optimization/split-chunk.md
  packages/document/docs/zh/guide/advanced/browserslist.md
  packages/document/docs/zh/guide/faq/exceptions.md
  packages/document/docs/zh/guide/optimization/build-performance.mdx
  packages/document/docs/zh/guide/optimization/optimize-bundle.md
  packages/document/docs/zh/guide/optimization/split-chunk.md
Labels: change: docs

#1894 docs: remove outdated lodash FAQ
  packages/document/docs/en/guide/faq/exceptions.md
  packages/document/docs/zh/guide/faq/exceptions.md
Labels: change: docs

#1897 fix: should apply nonce to style tags and rem script
  .changeset/lemon-tools-sleep.md
  e2e/cases/nonce/basic/index.test.ts
  e2e/cases/nonce/basic/rsbuild.config.ts
  e2e/cases/nonce/basic/src/index.css
  e2e/cases/nonce/basic/src/index.js
  e2e/cases/nonce/with-rem/index.test.ts
  e2e/cases/nonce/with-rem/rsbuild.config.ts
  e2e/cases/nonce/with-rem/src/index.js
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/rspack/HtmlNoncePlugin.ts
  packages/document/docs/en/config/security/nonce.md
  packages/document/docs/zh/config/security/nonce.md
Labels: change: fix

#1899 feat(server): return 404 code when xxx.hot-update.json file not found
  packages/core/src/server/getDevMiddlewares.ts
Labels: change: feat

#1906 fix: apply nonce to dynamic chunks
  e2e/cases/nonce/dynamic-chunk/index.test.ts
  e2e/cases/nonce/dynamic-chunk/rsbuild.config.ts
  e2e/cases/nonce/dynamic-chunk/src/foo.js
  e2e/cases/nonce/dynamic-chunk/src/index.js
  packages/core/src/rspack/HtmlNoncePlugin.ts
Labels: change: fix

#1908 docs: add nonce scope of effect
  e2e/cases/nonce/basic/index.test.ts
  e2e/cases/nonce/basic/rsbuild.config.ts
  e2e/cases/nonce/dynamic-chunk/index.test.ts
  e2e/cases/nonce/dynamic-chunk/rsbuild.config.ts
  e2e/cases/nonce/with-rem/index.test.ts
  e2e/cases/nonce/with-rem/rsbuild.config.ts
  packages/document/docs/en/config/security/nonce.md
  packages/document/docs/zh/config/security/nonce.md
Labels: change: docs

#1909 feat(plugin-svgr): add new query option
  e2e/cases/svg/svgr-query-custom/index.test.ts
  e2e/cases/svg/svgr-query-custom/rsbuild.config.ts
  e2e/cases/svg/svgr-query-custom/src/App.jsx
  e2e/cases/svg/svgr-query-custom/src/index.js
  e2e/cases/svg/svgr-query-custom/src/small.svg
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
  packages/plugin-svgr/src/index.ts
Labels: change: feat

#1913 docs: fix pluginLightningcss unnecessary `transform` object key
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
Labels: change: docs

#1914 docs: add Open Sans to font-family
  packages/document/rspress.config.ts
  packages/document/src/global.css
  packages/document/src/open-sans-italic.woff2
  packages/document/src/open-sans.woff2
Labels: change: docs

#1915 docs: bump rsfamily-nav-icon v1.0.2
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: docs

#1916 docs: use rspress-plugin-font-open-sans
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/document/src/global.css
  packages/document/src/open-sans-italic.woff2
  packages/document/src/open-sans.woff2
  pnpm-lock.yaml
Labels: change: docs

#1918 feat(plugin-lightningcss): transform accepts boolean type
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/plugins/list/plugin-lightningcss.mdx
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-lightningcss/src/types.ts
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-lightningcss/tests/index.test.ts
Labels: change: feat

#1923 docs: bump Rspress 1.16.0
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: docs

#1924 docs: integrate rsbuild-plugin-google-analytics
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#1931 docs: use rsbuild-plugin-open-graph
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#1925 fix(babel-plugin): support legacy decorators out of the box
  e2e/cases/babel/decorator/index.test.ts
  e2e/cases/babel/decorator/package.json
  e2e/cases/babel/decorator/src/decorator.ts
  e2e/cases/babel/decorator/src/index.ts
  e2e/cases/babel/decorator/src/js-decorator.js
  e2e/cases/babel/decorator/src/js-index.js
  e2e/cases/babel/decorator/tsconfig.json
  e2e/cases/decorator/2022-03/index.test.ts
  e2e/cases/decorator/2022-03/src/decoratorBeforeExport.js
  e2e/cases/decorator/basic/index.test.ts
  e2e/cases/decorator/basic/src/index.js
  e2e/scripts/helper.ts
  packages/babel-preset/src/base.ts
  packages/babel-preset/tests/__snapshots__/node.test.ts.snap
  packages/babel-preset/tests/__snapshots__/web.test.ts.snap
  packages/babel-preset/tests/node.test.ts
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/plugin-babel/package.json
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-solid/tests/__snapshots__/index.test.ts.snap
  packages/plugin-source-build/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue-jsx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2-jsx/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: fix

#1933 docs: update roadmap
  .changeset/six-bees-kiss.md
  README.md
  README.zh-CN.md
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#1935 docs(plugin-styled-components): rspack styled-components link fix
  packages/document/docs/en/plugins/list/plugin-styled-components.mdx
  packages/document/docs/zh/plugins/list/plugin-styled-components.mdx
Labels: change: docs

#1937 fix(nx.json): modify defaultBase configuration
  nx.json
Labels: change: fix

#1938 docs: update html.tags `append` introduce
  packages/document/docs/en/config/html/tags.mdx
  packages/document/docs/zh/config/html/tags.mdx
Labels: change: docs

#1942 fix(plugin-react): no chunk group of react if federation enabled
  .changeset/thin-worms-build.md
  packages/plugin-react/src/splitChunks.ts
Labels: change: fix

#1402 feat(node-polyfill): support protocol imports
  e2e/cases/node-polyfill/src/App.jsx
  packages/plugin-node-polyfill/src/ProtocolImportsPlugin.ts
  packages/plugin-node-polyfill/src/index.ts
  packages/plugin-node-polyfill/tests/__snapshots__/index.test.ts.snap
  packages/plugin-node-polyfill/tests/index.test.ts
Labels: change: feat

#1944 docs: add document for node polyfill plugin options
  packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx
  packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx
Labels: change: docs

#1946 fix: disable default split chunks rules for MF
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/plugins/splitChunks.ts
  packages/document/docs/en/config/module-federation/options.mdx
  packages/document/docs/zh/config/module-federation/options.mdx
  packages/plugin-react/src/splitChunks.ts
Labels: change: fix

#1950 docs: add rsfamily-design-resources link
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  README.zh-CN.md
  packages/document/docs/en/guide/start/index.mdx
  packages/document/docs/zh/guide/start/index.mdx
Labels: change: docs

#1939 feat: support show overlay in the browser when compiler error
  packages/core/src/client/hmr/createSocketUrl.ts
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/hmr/overlay.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/document/docs/en/config/dev/client.mdx
  packages/document/docs/zh/config/dev/client.mdx
  packages/shared/src/types/config/dev.ts
Labels: change: feat

#1955 fix: onAfterBuild hook async not work
  e2e/cases/javascript-api/plugin-after-build-hook/index.test.ts
  e2e/cases/javascript-api/plugin-after-build-hook/src/index.js
  examples/webpack/rsbuild.config.ts
  packages/compat/webpack/src/core/build.ts
  packages/core/package.json
  packages/core/src/provider/build.ts
  packages/plugin-lightningcss/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1956 fix: onDevCompileDone hook async not work
  packages/compat/webpack/src/core/build.ts
  packages/compat/webpack/src/core/createCompiler.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/shared/src/utils.ts
Labels: change: fix

#1957 feat: make overlay responsive
  packages/core/src/client/hmr/overlay.ts
Labels: change: feat

#1961 docs: add lightningcss to build perf guide
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/en/plugins/list/plugin-lightningcss.mdx
  packages/document/docs/zh/guide/optimization/build-performance.mdx
Labels: change: docs

#1958 fix(overlay): detect document, respect overlay option
  .changeset/itchy-lions-battle.md
  packages/core/src/client/hmr/index.ts
  packages/core/src/client/hmr/overlay.ts
Labels: change: fix

#1964 feat: improve overlay close icon style
  packages/core/src/client/hmr/overlay.ts
Labels: change: feat

#1965 docs: add SWC Wasm plugin guide
  packages/document/docs/en/config/tools/swc.mdx
  packages/document/docs/en/guide/start/features.mdx
  packages/document/docs/zh/config/tools/swc.mdx
Labels: change: docs

#1966 fix(plugin-solid): downgrade solid-refresh to v0.6.3
  e2e/cases/solid/ref/index.test.ts
  e2e/cases/solid/ref/rsbuild.config.ts
  e2e/cases/solid/ref/src/App.jsx
  e2e/cases/solid/ref/src/index.jsx
  packages/plugin-solid/package.json
  pnpm-lock.yaml
Labels: change: fix

#1968 feat: support for close overlay with esc
  .changeset/six-houses-impress.md
  packages/core/src/client/hmr/overlay.ts
Labels: change: feat

#1969 feat: add fade out transition for error overlay
  packages/core/src/client/hmr/overlay.ts
Labels: change: feat
