Repository web-infra-dev/rsbuild, pull requests merged in 2024-02, with the labels that each got.

#1487 fix: resolve error when fullySpecified rule after js rule
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/chain.ts
Labels: change: fix

#1490 breaking change: loadConfig method return value changed
  e2e/scripts/shared.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/config.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: breaking

#1492 breaking change(react): remove default config for antd/arco
  .changeset/two-impalas-develop.md
  packages/compat/plugin-swc/src/utils.ts
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/plugin-react/src/antd.ts
  packages/plugin-react/src/arco.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/src/utils.ts
  packages/plugin-react/tests/__snapshots__/features.test.ts.snap
  packages/plugin-react/tests/features.test.ts
  packages/shared/src/utils.ts
Labels: change: breaking

#1493 types: fix cacheGroups type mismatch
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
Labels: change: feat

#1496 fix: remove unused CHAIN_ID
  packages/shared/src/chain.ts
Labels: change: fix

#1495 fix(vue3-ts): rollback vue3-ts template env.d.ts config which will curse error on windows
  packages/create-rsbuild/template-vue3-ts/src/env.d.ts
Labels: change: fix

#1503 docs: add Node.js profiling guide
  packages/document/docs/en/config/performance/profile.mdx
  packages/document/docs/en/guide/optimization/build-performance.mdx
  packages/document/docs/zh/config/performance/profile.mdx
  packages/document/docs/zh/guide/optimization/build-performance.mdx
Labels: change: docs

#1506 perf: remove duplicate autoprefixer plugin
  packages/compat/webpack/tests/__snapshots__/css.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/document/docs/en/config/tools/autoprefixer.mdx
  packages/document/docs/en/guide/basic/css-usage.md
  packages/document/docs/zh/config/tools/autoprefixer.mdx
  packages/document/docs/zh/guide/basic/css-usage.md
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
  packages/shared/src/css.ts
  packages/shared/tests/css.test.ts
Labels: change: perf

#1507 breaking change: remove builtin postcss-flexbugs-fixes
  packages/compat/webpack/tests/__snapshots__/css.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/document/docs/en/config/tools/postcss.mdx
  packages/document/docs/en/guide/basic/css-usage.md
  packages/document/docs/zh/config/tools/postcss.mdx
  packages/document/docs/zh/guide/basic/css-usage.md
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
  packages/shared/compiled/postcss-flexbugs-fixes/index.d.ts
  packages/shared/compiled/postcss-flexbugs-fixes/index.js
  packages/shared/compiled/postcss-flexbugs-fixes/license
  packages/shared/compiled/postcss-flexbugs-fixes/package.json
  packages/shared/src/css.ts
  packages/shared/src/types/utils.ts
  pnpm-lock.yaml
  scripts/prebundle/package.json
  scripts/prebundle/src/constant.ts
Labels: change: breaking

#1504 feat(core): add onCloseDevServer hook
  .changeset/fair-cats-fail.md
  e2e/cases/javascript-api/plugin-hooks/index.test.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/index.ts
  packages/core/src/provider/core/initHooks.ts
  packages/core/src/provider/core/initPlugins.ts
  packages/core/src/server/devServer.ts
  packages/core/tests/__snapshots__/hooks.test.ts.snap
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/en/shared/onCloseDevServer.md
  packages/document/docs/zh/api/javascript-api/instance.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/shared/onCloseDevServer.md
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/types/rsbuild.ts
Labels: change: feat

#1509 perf(shared): bump webpack-bundle-analyzer to remove lodash dependency
  .github/renovate.json5
  packages/plugin-check-syntax/package.json
  packages/shared/compiled/webpack-bundle-analyzer/index.js
  packages/shared/compiled/webpack-bundle-analyzer/package.json
  packages/shared/compiled/webpack-bundle-analyzer/public/viewer.js
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: perf

#1511 breaking change: rename disableFilenameHash to filenameHash
  .changeset/two-impalas-develop.md
  e2e/cases/cli/build-watch/rsbuild.config.mjs
  e2e/cases/cli/custom-env-prefix/rsbuild.config.ts
  e2e/cases/cli/public-env-vars/rsbuild.config.ts
  e2e/cases/cli/reload-env/index.test.ts
  e2e/cases/html/meta/index.test.ts
  e2e/cases/performance/single-vendor/index.test.ts
  e2e/cases/performance/split-by-module/index.test.ts
  packages/document/docs/en/config/output/disable-filename-hash.mdx
  packages/document/docs/en/config/output/filename-hash.mdx
  packages/document/docs/en/config/output/filename.mdx
  packages/document/docs/en/guide/migration/vue-cli.mdx
  packages/document/docs/zh/config/output/disable-filename-hash.mdx
  packages/document/docs/zh/config/output/filename-hash.mdx
  packages/document/docs/zh/config/output/filename.mdx
  packages/document/docs/zh/guide/migration/vue-cli.mdx
  packages/plugin-umd/src/index.ts
  packages/shared/src/config.ts
  packages/shared/src/fs.ts
  packages/shared/src/types/config/output.ts
Labels: change: breaking

#1513 feat: add new moduleFederation config
  e2e/cases/module-federation/host/rsbuild.config.ts
  e2e/cases/module-federation/remote/rsbuild.config.ts
  examples/module-federation/host/rsbuild.config.ts
  examples/module-federation/remote/rsbuild.config.ts
  packages/compat/webpack/src/shared.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/provider/shared.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/shared/src/chain.ts
  packages/shared/src/config.ts
  packages/shared/src/types/config/index.ts
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1515 feat: patch split chunks for module federation
  e2e/cases/module-federation/host/rsbuild.config.ts
  e2e/cases/module-federation/remote/rsbuild.config.ts
  examples/module-federation/host/rsbuild.config.ts
  examples/module-federation/remote/rsbuild.config.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/plugins/splitChunks.ts
  packages/shared/src/types/config/performance.ts
  packages/shared/src/utils.ts
Labels: change: feat

#1516 docs: add document for moduleFederation.options
  packages/document/docs/en/config/_meta.json
  packages/document/docs/en/config/module-federation/options.mdx
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/config/_meta.json
  packages/document/docs/zh/config/module-federation/options.mdx
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
  packages/document/src/rsbuildPluginOverview.ts
Labels: change: docs

#1517 fix: less default resolve directory
  packages/compat/webpack/src/plugins/less.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/provider/plugins/less.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/document/docs/en/config/tools/less.mdx
  packages/document/docs/zh/config/tools/less.mdx
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/getLoaderOptions.ts
Labels: change: fix

#1520 docs: add announcing Rsbuild v0.4
  packages/document/docs/en/community/releases/_meta.json
  packages/document/docs/en/community/releases/v0-4.mdx
  packages/document/docs/zh/community/releases/_meta.json
  packages/document/docs/zh/community/releases/v0-4.mdx
Labels: change: docs

#1531 fix(server): not proxy websocket by default
  packages/core/src/server/proxy.ts
  packages/document/docs/en/config/server/proxy.mdx
  packages/document/docs/zh/config/server/proxy.mdx
Labels: change: fix

#1536 docs: improve transformImport config
  packages/document/docs/en/config/source/transform-import.mdx
  packages/document/docs/zh/config/source/transform-import.mdx
Labels: change: docs

#1538 types: improve tools.styleLoader typing
  .changeset/mean-pants-chew.md
  packages/core/src/provider/plugins/css.ts
  packages/shared/src/types/thirdParty.ts
Labels: change: feat

#1539 types: improve tools.cssLoader typing
  packages/shared/src/types/thirdParty.ts
Labels: change: feat

#1545 docs: add import lodash tip
  packages/document/docs/en/community/releases/v0-4.mdx
  packages/document/docs/en/config/source/transform-import.mdx
  packages/document/docs/zh/community/releases/v0-4.mdx
  packages/document/docs/zh/config/source/transform-import.mdx
Labels: change: docs

#1547 feat(deps): bump html-rspack-plugin 5.6.0
  .changeset/shaggy-sheep-lay.md
  packages/compat/webpack/package.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/package.json
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
  packages/core/tests/__snapshots__/inlineChunk.test.ts.snap
  packages/plugin-assets-retry/package.json
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#1548 feat: add @rsbuild/plugin-mdx package
  examples/mdx/package.json
  examples/mdx/rsbuild.config.ts
  examples/mdx/src/App.jsx
  examples/mdx/src/hello.mdx
  examples/mdx/src/index.jsx
  packages/plugin-mdx/LICENSE
  packages/plugin-mdx/README.md
  packages/plugin-mdx/modern.config.ts
  packages/plugin-mdx/package.json
  packages/plugin-mdx/src/index.ts
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/index.test.ts
  packages/plugin-mdx/tests/tsconfig.json
  packages/plugin-mdx/tsconfig.json
  pnpm-lock.yaml
Labels: change: feat

#1550 feat(plugin-mdx): support configuring loader options
  packages/plugin-mdx/src/index.ts
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/index.test.ts
Labels: change: feat

#1556 docs: add document for MDX plugin
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-mdx.mdx
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-mdx.mdx
Labels: change: docs

#1558 feat(plugin-mdx): support React refresh for MDX
  packages/plugin-mdx/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1560 feat(plugin-mdx): add extensions option
  packages/document/docs/en/plugins/list/plugin-mdx.mdx
  packages/document/docs/zh/plugins/list/plugin-mdx.mdx
  packages/plugin-mdx/src/index.ts
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
Labels: change: feat

#1561 feat(create-rsbuild): update all dependencies
  e2e/cases/pug/vue3-template/package.json
  e2e/cases/svelte/package.json
  e2e/cases/vue/package.json
  e2e/package.json
  examples/lit/package.json
  examples/vue3/package.json
  packages/core/compiled/dotenv/index.js
  packages/core/compiled/dotenv/lib/main.d.ts
  packages/core/compiled/dotenv/package.json
  packages/core/compiled/http-compression/index.js
  packages/core/compiled/http-compression/package.json
  packages/core/compiled/sirv/index.js
  packages/core/compiled/sirv/package.json
  packages/create-rsbuild/template-lit-js/package.json
  packages/create-rsbuild/template-lit-ts/package.json
  packages/create-rsbuild/template-preact-js/package.json
  packages/create-rsbuild/template-preact-ts/package.json
  packages/create-rsbuild/template-svelte-js/package.json
  packages/create-rsbuild/template-svelte-ts/package.json
  packages/create-rsbuild/template-vue3-js/package.json
  packages/create-rsbuild/template-vue3-ts/package.json
  packages/shared/compiled/browserslist/index.js
  packages/shared/compiled/browserslist/package.json
  packages/shared/compiled/chokidar/index.js
  packages/shared/compiled/chokidar/package.json
  packages/shared/compiled/chokidar/types/index.d.ts
  packages/shared/compiled/css-loader/index.js
  packages/shared/compiled/css-loader/package.json
  packages/shared/compiled/semver/index.js
  packages/shared/compiled/semver/package.json
  packages/shared/compiled/webpack-bundle-analyzer/index.d.ts
  packages/shared/compiled/webpack-bundle-analyzer/index.js
  pnpm-lock.yaml
  scripts/prebundle/package.json
Labels: change: feat

#1564 docs: add guide for public folder
  packages/document/docs/en/config/server/public-dir.mdx
  packages/document/docs/en/guide/basic/static-assets.md
  packages/document/docs/zh/config/server/public-dir.mdx
  packages/document/docs/zh/guide/basic/static-assets.md
Labels: change: docs

#1567 fix(plugin-solid): lock solid-refresh to fix runtime error
  packages/plugin-solid/package.json
  pnpm-lock.yaml
Labels: change: fix

#1568 docs: add more info for MF options
  packages/document/docs/en/config/module-federation/options.mdx
  packages/document/docs/en/plugins/list/plugin-mdx.mdx
  packages/document/docs/zh/config/module-federation/options.mdx
  packages/document/docs/zh/plugins/list/plugin-mdx.mdx
Labels: change: docs

#1570 feat: support for set different alias by target
  .changeset/sweet-parents-act.md
  e2e/cases/source/alias-by-target/index.test.ts
  e2e/cases/source/alias-by-target/rsbuild.config.ts
  e2e/cases/source/alias-by-target/src/common/test.js
  e2e/cases/source/alias-by-target/src/common2/test.js
  e2e/cases/source/alias-by-target/src/index.js
  e2e/cases/source/alias-by-target/tsconfig.json
  packages/document/docs/en/config/source/alias.mdx
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/en/config/tools/rspack.mdx
  packages/document/docs/zh/config/source/alias.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/rspack.mdx
  packages/shared/src/chain.ts
  packages/shared/src/types/config/source.ts
Labels: change: feat

#1571 docs: update vue-cli.mdx
  packages/document/docs/zh/guide/migration/vue-cli.mdx
Labels: change: docs

#1572 fix(plugin-swc): build error when set transformLodash false
  packages/compat/plugin-swc/src/utils.ts
Labels: change: fix

#1575 docs: add using Rsdoctor guide
  packages/document/docs/en/guide/debug/_meta.json
  packages/document/docs/en/guide/debug/rsdoctor.mdx
  packages/document/docs/zh/guide/debug/_meta.json
  packages/document/docs/zh/guide/debug/rsdoctor.mdx
Labels: change: docs

#1578 fix: display more accurate compile times
  .changeset/ten-balloons-jog.md
  packages/shared/src/utils.ts
  packages/shared/tests/prettyTime.test.ts
Labels: change: fix

#1579 perf(webpack): remove unused webpack-sources dependency
  packages/compat/webpack/compiled/webpack-sources/index.d.ts
  packages/compat/webpack/compiled/webpack-sources/index.js
  packages/compat/webpack/compiled/webpack-sources/license
  packages/compat/webpack/compiled/webpack-sources/package.json
Labels: change: perf

#1584 docs: add extend-middleware guide
  packages/document/docs/en/guide/basic/server.md
  packages/document/docs/zh/guide/basic/server.md
Labels: change: docs

#1595 docs: add MDX type declarations guide
  packages/document/docs/en/plugins/list/plugin-mdx.mdx
  packages/document/docs/zh/plugins/list/plugin-mdx.mdx
Labels: change: docs

#1598 fix(plugin-type-check): missing webpack peer dependency
  packages/plugin-type-check/package.json
  pnpm-lock.yaml
Labels: change: fix

#1611 docs: move typed CSS modules content to separate file
  packages/document/docs/en/guide/basic/css-modules.md
  packages/document/docs/en/plugins/list/plugin-typed-css-modules.mdx
  packages/document/docs/zh/guide/basic/css-modules.md
  packages/document/docs/zh/plugins/list/plugin-typed-css-modules.mdx
Labels: change: docs

#1614 docs: improve assetPrefix document
  packages/document/docs/en/config/dev/asset-prefix.mdx
  packages/document/docs/en/config/output/asset-prefix.mdx
  packages/document/docs/en/config/output/disable-minimize.mdx
  packages/document/docs/en/config/output/inject-styles.mdx
  packages/document/docs/en/guide/advanced/env-vars.md
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/guide/faq/features.md
  packages/document/docs/en/guide/optimization/optimize-bundle.md
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
  packages/document/docs/en/plugins/list/plugin-typed-css-modules.mdx
  packages/document/docs/zh/config/dev/asset-prefix.mdx
  packages/document/docs/zh/config/output/asset-prefix.mdx
  packages/document/docs/zh/plugins/list/plugin-typed-css-modules.mdx
  packages/shared/src/types/config/output.ts
Labels: change: docs

#1620 fix(plugin-babel): missing babel loader types
  packages/plugin-babel/src/types.ts
Labels: change: fix

#1621 perf(plugin-babel): enable compile cache to improve rebuild perf
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/plugin-babel/src/helper.ts
  packages/plugin-babel/src/plugin.ts
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-babel/tests/index.test.ts
  packages/plugin-solid/tests/index.test.ts
  packages/plugin-source-build/tests/index.test.ts
  packages/plugin-vue-jsx/tests/index.test.ts
  packages/plugin-vue2-jsx/tests/index.test.ts
Labels: change: perf

#1622 docs: add plugins comparison
  packages/document/docs/en/plugins/dev/index.md
  packages/document/docs/zh/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/index.md
Labels: change: docs

#1624 docs: recommend using Node.js 20
  CONTRIBUTING.md
  packages/document/docs/en/guide/start/quick-start.mdx
  packages/document/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#1632 docs: add source code link for plugins
  packages/document/docs/en/plugins/list/plugin-assets-retry.mdx
  packages/document/docs/en/plugins/list/plugin-babel.mdx
  packages/document/docs/en/plugins/list/plugin-check-syntax.mdx
  packages/document/docs/en/plugins/list/plugin-css-minimizer.mdx
  packages/document/docs/en/plugins/list/plugin-image-compress.mdx
  packages/document/docs/en/plugins/list/plugin-mdx.mdx
  packages/document/docs/en/plugins/list/plugin-node-polyfill.mdx
  packages/document/docs/en/plugins/list/plugin-preact.mdx
  packages/document/docs/en/plugins/list/plugin-pug.mdx
  packages/document/docs/en/plugins/list/plugin-react.mdx
  packages/document/docs/en/plugins/list/plugin-rem.mdx
  packages/document/docs/en/plugins/list/plugin-solid.mdx
  packages/document/docs/en/plugins/list/plugin-source-build.mdx
  packages/document/docs/en/plugins/list/plugin-styled-components.mdx
  packages/document/docs/en/plugins/list/plugin-stylus.mdx
  packages/document/docs/en/plugins/list/plugin-svelte.mdx
  packages/document/docs/en/plugins/list/plugin-svgr.mdx
  packages/document/docs/en/plugins/list/plugin-toml.mdx
  packages/document/docs/en/plugins/list/plugin-type-check.mdx
  packages/document/docs/en/plugins/list/plugin-typed-css-modules.mdx
  packages/document/docs/en/plugins/list/plugin-umd.mdx
  packages/document/docs/en/plugins/list/plugin-vue-jsx.mdx
  packages/document/docs/en/plugins/list/plugin-vue.mdx
  packages/document/docs/en/plugins/list/plugin-vue2-jsx.mdx
  packages/document/docs/en/plugins/list/plugin-vue2.mdx
  packages/document/docs/en/plugins/list/plugin-yaml.mdx
  packages/document/docs/zh/plugins/list/plugin-assets-retry.mdx
  packages/document/docs/zh/plugins/list/plugin-babel.mdx
  packages/document/docs/zh/plugins/list/plugin-check-syntax.mdx
  packages/document/docs/zh/plugins/list/plugin-css-minimizer.mdx
  packages/document/docs/zh/plugins/list/plugin-image-compress.mdx
  packages/document/docs/zh/plugins/list/plugin-mdx.mdx
  packages/document/docs/zh/plugins/list/plugin-node-polyfill.mdx
  packages/document/docs/zh/plugins/list/plugin-preact.mdx
  packages/document/docs/zh/plugins/list/plugin-pug.mdx
  packages/document/docs/zh/plugins/list/plugin-react.mdx
  packages/document/docs/zh/plugins/list/plugin-rem.mdx
  packages/document/docs/zh/plugins/list/plugin-solid.mdx
  packages/document/docs/zh/plugins/list/plugin-source-build.mdx
  packages/document/docs/zh/plugins/list/plugin-styled-components.mdx
  packages/document/docs/zh/plugins/list/plugin-stylus.mdx
  packages/document/docs/zh/plugins/list/plugin-svelte.mdx
  packages/document/docs/zh/plugins/list/plugin-svgr.mdx
  packages/document/docs/zh/plugins/list/plugin-toml.mdx
  packages/document/docs/zh/plugins/list/plugin-type-check.mdx
  packages/document/docs/zh/plugins/list/plugin-typed-css-modules.mdx
  packages/document/docs/zh/plugins/list/plugin-umd.mdx
  packages/document/docs/zh/plugins/list/plugin-vue-jsx.mdx
  packages/document/docs/zh/plugins/list/plugin-vue.mdx
  packages/document/docs/zh/plugins/list/plugin-vue2-jsx.mdx
  packages/document/docs/zh/plugins/list/plugin-vue2.mdx
  packages/document/docs/zh/plugins/list/plugin-yaml.mdx
Labels: change: docs

#1635 docs: add entry function guide
  e2e/cases/source/multiple-entry/rsbuild.config.ts
  packages/core/src/plugins/entry.ts
  packages/document/docs/en/api/javascript-api/instance.mdx
  packages/document/docs/en/config/source/entry.mdx
  packages/document/docs/zh/api/javascript-api/instance.mdx
  packages/document/docs/zh/config/source/entry.mdx
  packages/shared/src/types/config/source.ts
Labels: change: docs

#1637 docs: add rspack-examples to README
  README.md
  README.zh-CN.md
  packages/shared/compiled/webpack-dev-middleware/index.js
  packages/shared/compiled/webpack-dev-middleware/package.json
  packages/shared/compiled/webpack-dev-middleware/types/index.d.ts
Labels: change: docs

#1639 fix: loadConfig method allow cwd to be optional
  .changeset/early-mangos-attend.md
  packages/core/src/cli/config.ts
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
  packages/shared/compiled/commander/index.js
  packages/shared/compiled/commander/package.json
  packages/shared/compiled/commander/typings/index.d.ts
  packages/shared/compiled/postcss-load-config/index.js
  packages/shared/compiled/postcss-loader/index.js
  packages/shared/compiled/postcss-loader/package.json
  packages/shared/compiled/sass-loader/index.js
  packages/shared/compiled/sass-loader/package.json
Labels: change: fix

#1640 docs: fix unused provider param of createRsbuild
  packages/document/docs/en/api/javascript-api/core.mdx
  packages/document/docs/zh/api/javascript-api/core.mdx
Labels: change: docs

#1650 docs: add script tag guide for inline script
  packages/document/docs/en/config/output/inline-scripts.mdx
  packages/document/docs/zh/config/output/inline-scripts.mdx
Labels: change: docs

#1652 perf(plugin-svgr): merge duplicated rules
  .changeset/happy-gorillas-rush.md
  packages/document/docs/en/config/tools/bundler-chain.mdx
  packages/document/docs/zh/config/tools/bundler-chain.mdx
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/chain.ts
  packages/shared/src/config.ts
Labels: change: perf

#1654 docs: update bundler type of modifyBundlerChain
  packages/document/docs/en/plugins/dev/hooks.mdx
  packages/document/docs/zh/plugins/dev/hooks.mdx
Labels: change: docs

#1653 fix: mobx v5 class property decorators doesn't work
  e2e/cases/external-helpers/index.test.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1656 docs: add community plugins guide
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/document/docs/en/config/plugins.mdx
  packages/document/docs/en/guide/basic/cli.mdx
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/zh/config/plugins.mdx
  packages/document/docs/zh/guide/basic/cli.mdx
  packages/document/docs/zh/plugins/list/index.md
Labels: change: docs

#1657 feat: support registering async plugin in config
  e2e/cases/async-plugin/index.test.ts
  e2e/cases/async-plugin/src/index.js
  e2e/scripts/shared.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/pluginManager.ts
  packages/document/docs/en/config/plugins.mdx
  packages/document/docs/zh/config/plugins.mdx
  packages/shared/src/types/plugin.ts
Labels: change: feat

#1658 fix(server): avoid multiple prints of localhost
  packages/shared/src/url.ts
Labels: change: fix

#1659 fix(server): do not cleanup NODE_ENV on restart
  packages/core/src/loadEnv.ts
Labels: change: fix

#1660 fix(webpack): add rsbuild config to build dependencies
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/default.test.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/server/restart.ts
  packages/shared/src/config.ts
  packages/shared/src/types/config/index.ts
Labels: change: fix

#1663 fix: avoid merge provider object
  packages/shared/src/mergeRsbuildConfig.ts
Labels: change: fix

#1661 fix: progress plugin custom prefix not work
  packages/core/src/provider/plugins/progress.ts
Labels: change: fix

#1664 fix(plugin-rem): runtime code should inject at head end
  e2e/cases/html/rem/index.test.ts
  e2e/cases/html/rem/src/index.js
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
Labels: change: fix

#1667 docs: format in bundler-chain
  packages/document/docs/zh/config/tools/bundler-chain.mdx
Labels: change: docs

#1668 fix: no need to set crossorigin if publicPath is auto
  e2e/cases/html/cross-origin/index.test.ts
  packages/core/src/rspack/HtmlCrossOriginPlugin.ts
  packages/document/docs/en/config/html/crossorigin.mdx
  packages/document/docs/zh/config/html/crossorigin.mdx
Labels: change: fix

#1669 docs: improve configuration structure
  packages/document/docs/en/guide/basic/configure-rsbuild.mdx
  packages/document/docs/zh/guide/basic/configure-rsbuild.mdx
  packages/shared/src/types/config/index.ts
Labels: change: docs

#1673 feat(deps): bump Rspack v0.5.5
  .changeset/kind-wombats-hunt.md
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: feat

#1674 fix: apply crossorigin to the rem runtime script
  e2e/cases/output/copy/index.test.ts
  e2e/cases/output/copy/src/assets/icon.png
  e2e/cases/output/copy/src/index.js
  e2e/cases/output/output.test.ts
  e2e/cases/output/rem/.gitignore
  e2e/cases/rem/basic/src/App.css
  e2e/cases/rem/basic/src/App.module.less
  e2e/cases/rem/basic/src/App.module.scss
  e2e/cases/rem/basic/src/App.tsx
  e2e/cases/rem/basic/src/index.ts
  e2e/cases/rem/basic/src/types.d.ts
  e2e/cases/rem/basic/tests/index.test.ts
  e2e/cases/rem/basic/tsconfig.json
  e2e/cases/rem/with-viewport/index.test.ts
  e2e/cases/rem/with-viewport/src/index.js
  packages/core/src/rspack/HtmlCrossOriginPlugin.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1677 types: Optimize timer using ReturnType
  packages/core/src/server/socketServer.ts
Labels: change: feat

#1679 feat: add @rsbuild/plugin-eslint package
  package.json
  packages/plugin-eslint/LICENSE
  packages/plugin-eslint/README.md
  packages/plugin-eslint/modern.config.ts
  packages/plugin-eslint/package.json
  packages/plugin-eslint/src/index.ts
  packages/plugin-eslint/tsconfig.json
  packages/shared/src/chain.ts
  pnpm-lock.yaml
Labels: change: feat

#1682 perf(plugin-eslint): avoid multiple registration
  packages/plugin-eslint/src/index.ts
  packages/plugin-eslint/tests/__snapshots__/index.test.ts.snap
  packages/plugin-eslint/tests/index.test.ts
  packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
  packages/plugin-type-check/tests/index.test.ts
Labels: change: perf

#1683 fix(plugin-eslint): ignore dist folder by default
  packages/plugin-eslint/src/index.ts
  packages/plugin-eslint/tests/__snapshots__/index.test.ts.snap
  packages/plugin-type-check/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#1685 docs: add @rsbuild/plugin-eslint document
  packages/document/docs/en/guide/faq/features.md
  packages/document/docs/en/guide/start/npm-packages.mdx
  packages/document/docs/en/plugins/list/_meta.json
  packages/document/docs/en/plugins/list/index.md
  packages/document/docs/en/plugins/list/plugin-eslint.mdx
  packages/document/docs/zh/guide/faq/features.md
  packages/document/docs/zh/guide/start/npm-packages.mdx
  packages/document/docs/zh/plugins/list/_meta.json
  packages/document/docs/zh/plugins/list/index.md
  packages/document/docs/zh/plugins/list/plugin-eslint.mdx
Labels: change: docs

#1691 docs: fix proxy typo in hmr.md
  packages/document/docs/en/guide/advanced/hmr.md
Labels: change: docs

#1692 docs: add ESLint examples
  packages/document/docs/en/plugins/list/plugin-eslint.mdx
  packages/document/docs/zh/plugins/list/plugin-eslint.mdx
Labels: change: docs
