Repository web-infra-dev/rsbuild, pull requests merged in 2024-05, with the labels that each got.

#2252 docs: fix broken plugin links and update MF glossary
  scripts/dictionary.txt
  website/docs/en/config/module-federation/options.mdx
  website/docs/en/config/source/define.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/zh/config/module-federation/options.mdx
  website/docs/zh/config/source/define.mdx
  website/docs/zh/guide/start/glossary.mdx
Labels: change: docs

#2253 docs: add module federation guide
  website/docs/en/config/module-federation/options.mdx
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/zh/config/module-federation/options.mdx
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/module-federation.mdx
  website/docs/zh/guide/start/features.mdx
  website/docs/zh/guide/start/glossary.mdx
Labels: change: docs

#2255 fix: lodash is not defined error
  .changeset/swift-experts-taste.md
  packages/core/package.json
  packages/plugin-assets-retry/package.json
  packages/plugin-rem/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#2257 fix: print dist folder correctly if it's not a subdir of root
  e2e/cases/performance/print-file-size/index.test.ts
  packages/core/src/plugins/fileSize.ts
Labels: change: fix

#2258 docs: add comparisons to introduction
  README.md
  README.zh-CN.md
  scripts/dictionary.txt
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#2259 docs: improve introduction and fix links in README
  README.md
  README.zh-CN.md
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#2261 docs: add basic deploy static site guide
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: change: docs

#2262 docs: add asset prefix section to deploy guide
  website/docs/en/guide/basic/output-files.mdx
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/output-files.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: change: docs

#2264 docs: add deploy guide for Netlify
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: change: docs

#2269 fix: failed to resolve fsevents when using chokidar
  .changeset/stale-bags-double.md
  packages/shared/package.json
  packages/shared/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: fix

#2272 docs: add deploy guide for Vercel
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: change: docs

#2273 fix(plugin-svgr): failed to resolve file-loader
  .changeset/nine-tips-draw.md
  packages/plugin-svgr/prebundle.config.mjs
Labels: change: fix

#2274 docs: add community overview page
  website/docs/en/_meta.json
  website/docs/en/community/_meta.json
  website/docs/en/community/index.mdx
  website/docs/en/community/releases/index.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/zh/_meta.json
  website/docs/zh/community/_meta.json
  website/docs/zh/community/index.mdx
  website/docs/zh/community/releases/index.mdx
Labels: change: docs

#2279 feat(deps): bump Rspack v0.6.4
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2281 docs: add deploy guide for Cloudflare Pages
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: change: docs

#2283 docs: unify CSS Modules
  README.md
  e2e/cases/css/css-modules-composes/index.test.ts
  e2e/cases/css/css-modules-global/index.test.ts
  e2e/cases/css/css-modules-named-export/index.test.ts
  e2e/cases/css/css-modules/index.test.ts
  e2e/cases/css/import-loaders/index.test.ts
  packages/shared/src/loaders/ignoreCssLoader.ts
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/thirdParty.ts
  website/docs/en/community/releases/v0-6.mdx
  website/docs/en/config/output/css-modules.mdx
  website/docs/en/guide/start/index.mdx
Labels: change: docs

#2280 feat: support `output.manifest` config
  e2e/cases/output/manifest/index.test.ts
  e2e/cases/output/manifest/src/index.ts
  packages/compat/webpack/src/provider.ts
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/provider/provider.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts
  packages/core/src/rspack/preload/helpers/extractChunks.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/shared/src/types/config/output.ts
  pnpm-lock.yaml
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: change: feat

#2286 fix(deps): bump Rspack v0.6.5
  .changeset/polite-rules-kneel.md
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#2291 docs: improve publicDir document
  website/docs/en/config/server/public-dir.mdx
  website/docs/zh/config/server/public-dir.mdx
Labels: change: docs

#2292 fix(html): should inject chunks for entry.dependOn
  e2e/cases/source/entry-depend-on/index.test.ts
  e2e/cases/source/entry-depend-on/rsbuild.config.ts
  e2e/cases/source/entry-depend-on/src/bar.js
  e2e/cases/source/entry-depend-on/src/baz.js
  e2e/cases/source/entry-depend-on/src/foo.js
  packages/core/src/plugins/html.ts
Labels: change: fix

#2277 feat(plugin/assets-retry): support addQuery option
  e2e/cases/assets-retry/index.test.ts
  e2e/cases/assets-retry/src/testQueryEntry.js
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/types.ts
  packages/plugin-assets-retry/tests/__snapshots__/assetsRetry.test.ts.snap
  packages/plugin-assets-retry/tests/assetsRetry.test.ts
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: change: feat

#2302 docs: add some examples for prefetch / preload
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: change: docs

#2303 fix: server hooks not trigger when target is others
  packages/shared/src/utils.ts
Labels: change: fix

#2305 docs(react): add vanilla-extract guide
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2306 docs: remove outdated deploy guide
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/framework/solid.mdx
  website/docs/en/guide/framework/svelte.mdx
  website/docs/en/guide/framework/vue2.mdx
  website/docs/en/shared/deployApp.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/guide/framework/solid.mdx
  website/docs/zh/guide/framework/svelte.mdx
  website/docs/zh/guide/framework/vue2.mdx
  website/docs/zh/shared/deployApp.mdx
Labels: change: docs

#2307 fix(client): Array.prototype.at not exist on legacy browsers
  packages/core/src/client/format.ts
Labels: change: fix

#2308 docs: add guide for Emotion
  website/docs/en/config/tools/swc.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/config/tools/swc.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2309 feat: add unplugin transform hook doc
  website/docs/en/config/plugins.mdx
  website/docs/zh/config/plugins.mdx
Labels: change: feat

#2312 docs: add guide for StyleX
  scripts/dictionary.txt
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/basic/css-usage.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2313 docs: add guide for styled-jsx
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2320 docs: add more example of configuring Rspack plugins
  website/docs/en/guide/basic/configure-rspack.mdx
  website/docs/en/shared/bundlerChain.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/guide/basic/configure-rspack.mdx
  website/docs/zh/shared/bundlerChain.mdx
Labels: change: docs

#2321 fix: generate manifest for async CSS chunks
  e2e/cases/output/manifest-async-chunks/index.test.ts
  e2e/cases/output/manifest-async-chunks/src/async.ts
  e2e/cases/output/manifest-async-chunks/src/index.ts
  e2e/cases/output/manifest-async-chunks/src/style.css
  packages/core/src/plugins/manifest.ts
Labels: change: fix

#2324 fix: core-js accidentally compiled in some cases
  .changeset/breezy-baboons-jump.md
  packages/shared/src/chain.ts
Labels: change: fix

#2322 docs: make performance.profile more clear
  packages/core/src/plugins/performance.ts
  website/docs/en/config/performance/profile.mdx
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/config/performance/profile.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: change: docs

#2331 docs: localIdentName hashDigest has been supported in rspack mode
  e2e/cases/css/css-modules/index.test.ts
  packages/core/tests/css.test.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: change: docs

#2333 feat(shared): provide mjs exports
  e2e/cases/mjs-artifact/test.mjs
  packages/compat/webpack/src/provider.ts
  packages/core/src/internal.ts
  packages/core/src/pluginHelper.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/output.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/rspack/HtmlAppIconPlugin.ts
  packages/core/src/rspack/HtmlBasicPlugin.ts
  packages/core/src/rspack/InlineChunkHtmlPlugin.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/chain.ts
  packages/shared/src/config.ts
  packages/shared/src/fs.ts
  packages/shared/src/getBrowserslist.ts
  packages/shared/src/logger.ts
  packages/shared/src/minimize.ts
  packages/shared/src/utils.ts
Labels: change: feat

#2335 feat: make more packages support esm exports
  e2e/cases/babel/preset-node/index.test.ts
  e2e/cases/babel/preset-node/rsbuild.config.ts
  e2e/cases/babel/preset-node/src/index.js
  e2e/cases/babel/preset-web/index.test.ts
  e2e/cases/babel/preset-web/rsbuild.config.ts
  e2e/cases/babel/preset-web/src/index.js
  e2e/cases/mjs-artifact/test.mjs
  e2e/package.json
  packages/compat/babel-preset/modern.config.ts
  packages/compat/babel-preset/package.json
  packages/compat/babel-preset/src/web.ts
  packages/compat/babel-preset/tests/__snapshots__/web.test.ts.snap
  packages/compat/plugin-swc/modern.config.ts
  packages/compat/plugin-swc/package.json
  packages/compat/plugin-swc/src/minimizer.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
  packages/compat/webpack/compiled/ansi-escapes/index.d.ts
  packages/compat/webpack/compiled/ansi-escapes/index.js
  packages/compat/webpack/compiled/ansi-escapes/license
  packages/compat/webpack/compiled/ansi-escapes/package.json
  packages/compat/webpack/compiled/ansi-escapes/type-fest/index.d.ts
  packages/compat/webpack/compiled/cli-truncate/index.d.ts
  packages/compat/webpack/compiled/cli-truncate/index.js
  packages/compat/webpack/compiled/cli-truncate/license
  packages/compat/webpack/compiled/cli-truncate/package.json
  packages/compat/webpack/compiled/copy-webpack-plugin/index.d.ts
  packages/compat/webpack/compiled/copy-webpack-plugin/index.js
  packages/compat/webpack/compiled/copy-webpack-plugin/license
  packages/compat/webpack/compiled/copy-webpack-plugin/package.json
  packages/compat/webpack/compiled/patch-console/build/index.d.ts
  packages/compat/webpack/compiled/patch-console/index.js
  packages/compat/webpack/compiled/patch-console/package.json
  packages/compat/webpack/compiled/schema-utils3/index.d.ts
  packages/compat/webpack/compiled/schema-utils3/index.js
  packages/compat/webpack/compiled/schema-utils3/license
  packages/compat/webpack/compiled/schema-utils3/package.json
  packages/compat/webpack/compiled/tapable/index.js
  packages/compat/webpack/compiled/tapable/license
  packages/compat/webpack/compiled/tapable/package.json
  packages/compat/webpack/compiled/tapable/tapable.d.ts
  packages/compat/webpack/modern.config.ts
  packages/compat/webpack/package.json
  packages/compat/webpack/src/build.ts
  packages/compat/webpack/src/createCompiler.ts
  packages/compat/webpack/src/plugins/copy.ts
  packages/compat/webpack/src/progress/helpers/bar.ts
  packages/compat/webpack/src/progress/helpers/bus.ts
  packages/compat/webpack/src/progress/helpers/log.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/monorepo-utils/modern.config.ts
  packages/monorepo-utils/package.json
  pnpm-lock.yaml
Labels: change: feat

#2336 docs: update Rspack JS API link
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: change: docs

#2337 fix: only enable React JSX compilation when using React plugin
  e2e/cases/performance/print-file-size/rsbuild.config.ts
  packages/core/src/provider/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-mdx/tests/__snapshots__/index.test.ts.snap
  packages/plugin-preact/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-styled-components/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/tools/swc.mdx
  website/docs/zh/config/tools/swc.mdx
Labels: change: fix

#2338 feat: output.dataUriLimit defaults to 4096
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-image-compress/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/constants.ts
  website/docs/en/config/output/data-uri-limit.mdx
  website/docs/zh/config/output/data-uri-limit.mdx
Labels: change: feat

#2340 feat: add new `@rsbuild/plugin-typed-css-modules` package
  e2e/cases/css/css-modules-dom/index.test.ts
  e2e/cases/css/css-modules-ts-declaration/index.test.ts
  e2e/cases/stylus/index.test.ts
  e2e/package.json
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/css.test.ts
  packages/plugin-typed-css-modules/LICENSE
  packages/plugin-typed-css-modules/README.md
  packages/plugin-typed-css-modules/modern.config.ts
  packages/plugin-typed-css-modules/package.json
  packages/plugin-typed-css-modules/prebundle.config.mjs
  packages/plugin-typed-css-modules/src/index.ts
  packages/plugin-typed-css-modules/src/loader.ts
  packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap
  packages/plugin-typed-css-modules/tests/index.test.ts
  packages/plugin-typed-css-modules/tests/loader.test.ts
  packages/plugin-typed-css-modules/tsconfig.json
  packages/shared/src/types/config/output.ts
  pnpm-lock.yaml
Labels: change: feat

#2341 fix: some inaccurate target judgments
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/resourceHints.ts
  packages/plugin-lightningcss/src/plugin.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/override-browserslist.mdx
  website/docs/en/config/tools/css-loader.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/config/output/override-browserslist.mdx
  website/docs/zh/config/tools/css-loader.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
Labels: change: fix

#2342 docs: introduce typed-css-modules plugin
  website/docs/en/plugins/list/_meta.json
  website/docs/en/plugins/list/index.mdx
  website/docs/en/plugins/list/plugin-typed-css-modules.mdx
  website/docs/zh/plugins/list/_meta.json
  website/docs/zh/plugins/list/index.mdx
  website/docs/zh/plugins/list/plugin-typed-css-modules.mdx
Labels: change: docs

#2347 fix: bundle dts files for ESM packages
  packages/compat/babel-preset/package.json
  packages/core/src/cli/commands.ts
  packages/core/src/loadEnv.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/plugins/sass.ts
  packages/core/src/plugins/startUrl.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/server/socketServer.ts
  packages/plugin-svelte/modern.config.ts
  packages/plugin-typed-css-modules/src/loader.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/types/config/dev.ts
  packages/shared/src/types/config/performance.ts
  packages/shared/src/types/config/server.ts
  packages/shared/src/types/config/tools.ts
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/types/server.ts
  packages/shared/src/types/thirdParty.ts
  packages/shared/src/types/utils.ts
  pnpm-lock.yaml
  scripts/modern.base.config.ts
Labels: change: fix

#2349 fix: remove rslog from prebundle config
  packages/core/bin/rsbuild.js
  packages/core/src/cli/prepare.ts
  packages/shared/package.json
  packages/shared/prebundle.config.mjs
  packages/shared/src/logger.ts
Labels: change: fix

#2348 fix: increase priority split-by-module so it can differ from defaultVendors
  packages/core/src/plugins/splitChunks.ts
  packages/core/tests/__snapshots__/splitChunks.test.ts.snap
Labels: change: fix

#2353 fix(shared): broken types due to type module
  nx.json
  packages/compat/babel-preset/modern.config.ts
  packages/compat/plugin-swc/modern.config.ts
  packages/compat/webpack/modern.config.ts
  packages/create-rsbuild/modern.config.ts
  packages/monorepo-utils/modern.config.ts
  packages/plugin-assets-retry/modern.config.ts
  packages/plugin-babel/modern.config.ts
  packages/plugin-basic-ssl/modern.config.ts
  packages/plugin-check-syntax/modern.config.ts
  packages/plugin-css-minimizer/modern.config.ts
  packages/plugin-eslint/modern.config.ts
  packages/plugin-image-compress/modern.config.ts
  packages/plugin-lightningcss/modern.config.ts
  packages/plugin-mdx/modern.config.ts
  packages/plugin-node-polyfill/modern.config.ts
  packages/plugin-preact/modern.config.ts
  packages/plugin-pug/modern.config.ts
  packages/plugin-react/modern.config.ts
  packages/plugin-rem/modern.config.ts
  packages/plugin-solid/modern.config.ts
  packages/plugin-source-build/modern.config.ts
  packages/plugin-styled-components/modern.config.ts
  packages/plugin-stylus/modern.config.ts
  packages/plugin-svelte/modern.config.ts
  packages/plugin-svgr/modern.config.ts
  packages/plugin-toml/modern.config.ts
  packages/plugin-type-check/modern.config.ts
  packages/plugin-typed-css-modules/modern.config.ts
  packages/plugin-umd/modern.config.ts
  packages/plugin-vue-jsx/modern.config.ts
  packages/plugin-vue/modern.config.ts
  packages/plugin-vue2-jsx/modern.config.ts
  packages/plugin-vue2/modern.config.ts
  packages/plugin-yaml/modern.config.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  pnpm-workspace.yaml
  scripts/modern.base.config.ts
Labels: change: fix

#2357 docs: add guide for React Compiler
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2366 fix: build target of client bundles
  scripts/modern.base.config.ts
Labels: change: fix

#2367 fix: lazy import webpack-dev-middleware
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/devMiddleware.ts
Labels: change: fix

#2368 docs: add rsbuild-storybook link
  README.md
  README.zh-CN.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#2369 feat: add rsbuild.getPlugins JavaScript API
  packages/compat/webpack/src/inspectConfig.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/pluginManager.ts
  packages/core/src/provider/inspectConfig.ts
  packages/core/tests/createPluginManager.test.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/types/rsbuild.ts
  scripts/test-helper/src/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: change: feat

#2372 perf: reduce fs calls caused by getCompiledPath
  packages/core/src/helpers.ts
  packages/core/src/provider/rspackConfig.ts
  packages/shared/src/types/hooks.ts
Labels: change: perf

#2373 fix: missing resourceQuery param of cssLoader.module.auto
  packages/shared/src/types/config/output.ts
  packages/shared/src/types/thirdParty.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: change: fix

#2374 feat(plugin-vue): support CSS Modules in SFC
  e2e/cases/vue/sfc-css-modules/index.test.ts
  e2e/cases/vue/sfc-css-modules/rsbuild.config.ts
  e2e/cases/vue/sfc-css-modules/src/A.vue
  e2e/cases/vue/sfc-css-modules/src/index.js
  e2e/cases/vue/sfc-css-modules/src/style.module.css
  packages/plugin-vue/src/index.ts
Labels: change: feat

#2380 feat(core): export config subtypes
  e2e/cases/css/css-modules-dom/index.test.ts
  packages/compat/plugin-swc/src/plugin.ts
  packages/compat/plugin-swc/src/utils.ts
  packages/compat/plugin-swc/tests/plugin.test.ts
  packages/core/src/index.ts
  packages/core/src/plugins/css.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/types.ts
  packages/plugin-babel/src/helper.ts
  packages/plugin-babel/src/types.ts
  packages/plugin-check-syntax/src/index.ts
  packages/plugin-css-minimizer/src/index.ts
  packages/plugin-lightningcss/tests/index.test.ts
  packages/plugin-react/src/react.ts
  packages/plugin-react/src/splitChunks.ts
  packages/plugin-react/tests/features.test.ts
  packages/plugin-rem/src/AutoSetRootFontSizePlugin.ts
  packages/plugin-rem/src/index.ts
  packages/plugin-styled-components/src/index.ts
  packages/plugin-type-check/src/index.ts
  packages/plugin-typed-css-modules/src/index.ts
  packages/plugin-typed-css-modules/src/loader.ts
  packages/plugin-typed-css-modules/tests/helper.test.ts
  packages/plugin-typed-css-modules/tests/index.test.ts
  packages/plugin-vue/src/splitChunks.ts
  packages/plugin-vue2/src/splitChunks.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: change: feat

#2385 fix: failed to load postcss.config.ts
  e2e/cases/css/postcss-config-ts/index.test.ts
  e2e/cases/css/postcss-config-ts/postcss.config.ts
  e2e/cases/css/postcss-config-ts/rsbuild.config.ts
  e2e/cases/css/postcss-config-ts/src/index.css
  e2e/cases/css/postcss-config-ts/src/index.html
  e2e/cases/css/postcss-config-ts/src/index.ts
  e2e/cases/css/postcss-config-ts/tailwind.config.cjs
  packages/core/prebundle.config.mjs
Labels: change: fix

#2388 docs(css-modules): add generate exact type definitions guide
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/zh/guide/basic/css-modules.mdx
Labels: change: docs

#2391 docs: add example for exports format
  website/docs/en/api/start/index.mdx
  website/docs/en/config/dev/before-start-url.mdx
  website/docs/en/config/html/script-loading.mdx
  website/docs/zh/api/start/index.mdx
  website/docs/zh/config/dev/before-start-url.mdx
  website/docs/zh/config/html/script-loading.mdx
Labels: change: docs

#2392 feat: add cssModules.exportGlobals option
  e2e/cases/css/css-modules-exports-global/index.test.ts
  e2e/cases/css/css-modules-exports-global/rsbuild.config.ts
  e2e/cases/css/css-modules-exports-global/src/a.module.css
  e2e/cases/css/css-modules-exports-global/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-lightningcss/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/rspack.test.ts.snap
  packages/plugin-typed-css-modules/tests/__snapshots__/index.test.ts.snap
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: change: feat

#2393 feat: support tools.cssExtract config
  e2e/cases/css/configure-css-extract/index.test.ts
  e2e/cases/css/configure-css-extract/rsbuild.config.ts
  e2e/cases/css/configure-css-extract/src/index.css
  e2e/cases/css/configure-css-extract/src/index.js
  packages/core/src/config.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/output.ts
  packages/shared/package.json
  packages/shared/src/chain.ts
  packages/shared/src/types/config/tools.ts
  packages/shared/src/types/thirdParty.ts
  pnpm-lock.yaml
  website/docs/en/config/tools/css-extract.mdx
  website/docs/zh/config/tools/css-extract.mdx
Labels: change: feat

#2396 docs: fix node.org dead link
  website/docs/en/guide/faq/exceptions.mdx
  website/docs/en/plugins/list/plugin-source-build.mdx
  website/docs/zh/guide/faq/exceptions.mdx
  website/docs/zh/plugins/list/plugin-source-build.mdx
Labels: change: docs

#2408 perf(plugin-sass): defaults to sass-embedded and modern API
  packages/plugin-rem/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/package.json
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/src/types.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  pnpm-lock.yaml
Labels: change: perf

#2411 docs: update document for Sass/Less plugins
  website/docs/en/config/plugins.mdx
  website/docs/en/config/tools/autoprefixer.mdx
  website/docs/en/config/tools/less.mdx
  website/docs/en/config/tools/sass.mdx
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/migration/vue-cli.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/guide/start/npm-packages.mdx
  website/docs/en/plugins/list/_meta.json
  website/docs/en/plugins/list/index.mdx
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/en/plugins/list/plugin-vue.mdx
  website/docs/en/plugins/list/plugin-vue2.mdx
  website/docs/zh/config/tools/autoprefixer.mdx
  website/docs/zh/config/tools/less.mdx
  website/docs/zh/config/tools/sass.mdx
  website/docs/zh/guide/basic/css-usage.mdx
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/migration/vue-cli.mdx
  website/docs/zh/guide/start/features.mdx
  website/docs/zh/guide/start/npm-packages.mdx
  website/docs/zh/plugins/list/_meta.json
  website/docs/zh/plugins/list/index.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-mdx.mdx
  website/docs/zh/plugins/list/plugin-preact.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-solid.mdx
  website/docs/zh/plugins/list/plugin-styled-components.mdx
  website/docs/zh/plugins/list/plugin-stylus.mdx
  website/docs/zh/plugins/list/plugin-svelte.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
  website/docs/zh/plugins/list/plugin-vue-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue.mdx
  website/docs/zh/plugins/list/plugin-vue2-jsx.mdx
  website/docs/zh/plugins/list/plugin-vue2.mdx
Labels: change: docs

#2421 feat: print hints for CSS preprocessors plugins
  e2e/cases/css/less-plugin-hints/index.test.ts
  e2e/cases/css/less-plugin-hints/src/a.less
  e2e/cases/css/less-plugin-hints/src/index.js
  e2e/cases/css/sass-plugin-hints/index.test.ts
  e2e/cases/css/sass-plugin-hints/src/a.scss
  e2e/cases/css/sass-plugin-hints/src/index.js
  e2e/cases/css/stylus-plugin-hints/index.test.ts
  e2e/cases/css/stylus-plugin-hints/src/a.styl
  e2e/cases/css/stylus-plugin-hints/src/index.js
  packages/core/src/client/format.ts
  packages/core/src/helpers.ts
Labels: change: feat

#2422 feat(plugin-vue): support for lang="postcss"
  e2e/cases/vue/sfc-lang-pcss/index.test.ts
  e2e/cases/vue/sfc-lang-pcss/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-pcss/src/App.vue
  e2e/cases/vue/sfc-lang-pcss/src/index.js
  e2e/cases/vue/sfc-lang-postcss/index.test.ts
  e2e/cases/vue/sfc-lang-postcss/rsbuild.config.ts
  e2e/cases/vue/sfc-lang-postcss/src/App.vue
  e2e/cases/vue/sfc-lang-postcss/src/index.js
  e2e/cases/vue2/sfc-lang-pcss/index.test.ts
  e2e/cases/vue2/sfc-lang-pcss/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-pcss/src/App.vue
  e2e/cases/vue2/sfc-lang-pcss/src/index.js
  e2e/cases/vue2/sfc-lang-postcss/index.test.ts
  e2e/cases/vue2/sfc-lang-postcss/rsbuild.config.ts
  e2e/cases/vue2/sfc-lang-postcss/src/App.vue
  e2e/cases/vue2/sfc-lang-postcss/src/index.js
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/tests/__snapshots__/index.test.ts.snap
  packages/plugin-vue2/src/index.ts
  packages/plugin-vue2/tests/__snapshots__/index.test.ts.snap
  scripts/dictionary.txt
Labels: change: feat

#2424 feat(plugin-umd): allow to configure chunk split strategy
  e2e/cases/umd/split-chunks/index.test.ts
  e2e/cases/umd/split-chunks/rsbuild.config.ts
  e2e/cases/umd/split-chunks/src/index.html
  e2e/cases/umd/split-chunks/src/index.js
  packages/plugin-umd/src/index.ts
  website/docs/en/plugins/list/plugin-umd.mdx
  website/docs/zh/plugins/list/plugin-umd.mdx
Labels: change: feat

#2425 docs: add rsbuild.initConfigs to document
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/tsconfig.json
Labels: change: docs

#2426 fix(plugin-lightningcss): ensure works with CSS preprocessors
  e2e/cases/css/lightningcss/index.test.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-lightningcss/src/plugin.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
Labels: change: fix

#2428 feat(server): support for HTTP/2
  packages/core/src/server/devServer.ts
  packages/core/src/server/httpServer.ts
  packages/core/src/server/prodServer.ts
  packages/shared/src/types/config/server.ts
  website/docs/en/config/server/https.mdx
  website/docs/zh/config/server/https.mdx
Labels: change: feat

#2430 fix: preview command print invalid URL
  e2e/cases/server/print-urls/index.test.ts
  packages/core/src/server/prodServer.ts
Labels: change: fix

#2432 perf: lazy load server related dependencies
  packages/compat/webpack/package.json
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/httpServer.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/server/proxy.ts
  packages/core/src/server/socketServer.ts
  packages/core/src/types.ts
  packages/plugin-sass/package.json
  packages/plugin-typed-css-modules/package.json
  packages/shared/package.json
  packages/shared/prebundle.config.mjs
  packages/shared/src/types/index.ts
  packages/shared/src/types/server.ts
  pnpm-lock.yaml
Labels: change: perf

#2437 fix(plugin-eslint): make ESLint as a peer dependency
  e2e/cases/eslint/flat-config/rsbuild.config.ts
  packages/plugin-eslint/package.json
  pnpm-lock.yaml
  website/docs/en/plugins/list/plugin-eslint.mdx
  website/docs/zh/plugins/list/plugin-eslint.mdx
Labels: change: fix

#2440 fix(plugin-pug): bump pug and fix security alert
  packages/plugin-pug/package.json
  pnpm-lock.yaml
Labels: change: fix

#2441 fix: allow to load empty env vars
  e2e/cases/javascript-api/load-env/.env
  e2e/cases/javascript-api/load-env/index.test.ts
  packages/core/src/loadEnv.ts
Labels: change: fix

#2442 docs: improve startUrl config guide
  website/docs/en/config/dev/start-url.mdx
  website/docs/zh/config/dev/start-url.mdx
Labels: change: docs

#2446 fix: browserslist resolve is broken by prebundle
  e2e/cases/browserslist/browserslist-config-mock/index.json
  e2e/cases/browserslist/browserslist-config-mock/package.json
  e2e/cases/browserslist/extends-browserslist/index.test.ts
  e2e/cases/browserslist/extends-browserslist/package.json
  e2e/cases/browserslist/extends-browserslist/rsbuild.config.ts
  e2e/cases/browserslist/extends-browserslist/src/index.js
  packages/shared/prebundle.config.mjs
  pnpm-lock.yaml
Labels: change: fix

#2398 docs: announcing Rsbuild v0.7
  website/docs/en/community/releases/_meta.json
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/en/guide/start/npm-packages.mdx
  website/docs/en/plugins/list/plugin-typed-css-modules.mdx
  website/docs/zh/community/releases/_meta.json
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/guide/basic/css-modules.mdx
  website/docs/zh/guide/start/npm-packages.mdx
  website/docs/zh/plugins/list/index.mdx
  website/docs/zh/plugins/list/plugin-typed-css-modules.mdx
Labels: change: docs

#2448 feat(create-rsbuild): allow to create in the current folder
  packages/create-rsbuild/src/index.ts
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: feat

#2447 fix: update css-loader modules typing
  packages/core/src/plugins/css.ts
  packages/shared/src/types/thirdParty.ts
Labels: change: fix

#2450 feat: bump Rspack v0.7.0
  packages/core/package.json
  packages/plugin-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#2452 docs: OG image is broken
  website/rspress.config.ts
Labels: change: docs

#2449 docs: improve v0.7 announcement
  website/docs/en/community/releases/v0-7.mdx
  website/docs/zh/community/releases/v0-7.mdx
Labels: change: docs

#2453 types(plugin-sass): export PluginSassOptions type
  packages/plugin-sass/src/index.ts
Labels: change: feat

#2454 feat: add dev.lazyCompilation config
  e2e/cases/lazy-compilation/basic/index.test.ts
  e2e/cases/lazy-compilation/basic/rsbuild.config.ts
  e2e/cases/lazy-compilation/basic/src/page1/App.jsx
  e2e/cases/lazy-compilation/basic/src/page1/index.js
  e2e/cases/lazy-compilation/basic/src/page2/App.jsx
  e2e/cases/lazy-compilation/basic/src/page2/index.js
  packages/core/src/createRsbuild.ts
  packages/core/src/plugins/lazyCompilation.ts
  packages/core/tests/__snapshots__/inspect.test.ts.snap
  packages/shared/src/types/config/dev.ts
Labels: change: feat

#2457 fix: exclude all CSS lazy compilation
  .changeset/tiny-donkeys-search.md
  packages/core/src/plugins/lazyCompilation.ts
Labels: change: fix

#2455 docs: add lazy compilation to document
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/config/dev/lazy-compilation.mdx
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/config/dev/lazy-compilation.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: change: docs

#2459 feat: add cssModules.mode option
  e2e/cases/css/css-modules-mode/index.test.ts
  e2e/cases/css/css-modules-mode/src/a.module.css
  e2e/cases/css/css-modules-mode/src/index.js
  packages/core/src/plugins/css.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: change: feat

#2460 feat: check if dist folder is empty before previewing
  packages/core/src/cli/commands.ts
  packages/core/src/helpers.ts
Labels: change: feat

#2461 docs: move Less FAQ to plugin-less document
  website/docs/en/guide/faq/exceptions.mdx
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/zh/guide/faq/exceptions.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
Labels: change: docs

#2462 docs(plugin-less): fix lessOptions example
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
Labels: change: docs

#2463 fix: avoid printing undefined file path
  packages/core/src/client/format.ts
Labels: change: fix

#2465 feat: print compiler close errors
  packages/core/src/provider/build.ts
Labels: change: feat

#2466 docs: fix dataUriLimit default value
  packages/core/src/provider/build.ts
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/optimization/inline-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/optimization/inline-assets.mdx
Labels: change: docs

#2468 docs: recommend using @swc/plugin-emotion
  website/docs/en/config/tools/swc.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/config/tools/swc.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: change: docs

#2473 docs: add custom manifest path example
  e2e/cases/output/manifest/index.test.ts
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: change: docs

#2474 fix(typed-css-modules): avoid exporting invalid `cssExports`
  packages/plugin-typed-css-modules/src/loader.ts
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/guide/basic/css-modules.mdx
  website/docs/en/plugins/list/plugin-typed-css-modules.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/guide/basic/css-modules.mdx
  website/docs/zh/plugins/list/plugin-typed-css-modules.mdx
Labels: change: fix

#2475 feat: allow to enable namedExport for CSS Modules
  e2e/cases/css/css-modules-named-export/index.test.ts
  packages/core/src/config.ts
  packages/core/src/plugins/css.ts
  packages/shared/src/types/config/output.ts
  website/docs/en/config/output/css-modules.mdx
  website/docs/en/config/output/externals.mdx
  website/docs/en/config/tools/css-loader.mdx
  website/docs/zh/config/output/css-modules.mdx
  website/docs/zh/config/output/externals.mdx
  website/docs/zh/config/tools/css-loader.mdx
Labels: change: feat

#2476 feat(typed-css-modules): support for named export
  e2e/cases/css/css-modules-dom/index.test.ts
  e2e/cases/css/css-modules-ts-declaration/rsbuild.config.ts
  e2e/cases/typed-css-modules/basic/index.test.ts
  e2e/cases/typed-css-modules/basic/rsbuild.config.ts
  e2e/cases/typed-css-modules/basic/src/a.css
  e2e/cases/typed-css-modules/basic/src/a.module.scss
  e2e/cases/typed-css-modules/basic/src/b.module.scss
  e2e/cases/typed-css-modules/basic/src/c.module.less
  e2e/cases/typed-css-modules/basic/src/d.global.less
  e2e/cases/typed-css-modules/basic/src/index.js
  e2e/cases/typed-css-modules/named-export/index.test.ts
  e2e/cases/typed-css-modules/named-export/rsbuild.config.ts
  e2e/cases/typed-css-modules/named-export/src/a.module.scss
  e2e/cases/typed-css-modules/named-export/src/b.module.scss
  e2e/cases/typed-css-modules/named-export/src/c.module.less
  e2e/cases/typed-css-modules/named-export/src/index.js
  packages/plugin-typed-css-modules/src/loader.ts
  scripts/dictionary.txt
  website/docs/en/plugins/list/plugin-typed-css-modules.mdx
  website/docs/zh/plugins/list/plugin-typed-css-modules.mdx
Labels: change: feat

#2479 fix(typed-css-modules): change webpack to Rsbuild
  packages/plugin-typed-css-modules/src/loader.ts
Labels: change: fix

#2481 docs: reorganize the webpack migration guide
  website/docs/en/guide/migration/webpack.mdx
  website/docs/zh/guide/migration/webpack.mdx
Labels: change: docs
