Repository web-infra-dev/rsbuild, pull requests merged in 2025-06, with the labels that each got.

#5341 docs: update terminology and clarify compilation scope
  website/docs/en/config/source/include.mdx
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/zh/config/source/include.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
Labels: release: document

#5342 perf: disable progress bar by default
  e2e/cases/server/multi-server/index.test.ts
  packages/core/src/plugins/progress.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  website/docs/en/config/dev/progress-bar.mdx
  website/docs/zh/config/dev/progress-bar.mdx
Labels: release: performance

#5344 feat: let SWC compile modules outside the project
  e2e/cases/source/source-include/index.test.ts
  e2e/cases/source/test.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#5347 docs: enhance parameter descriptions of api.transform
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5349 feat(create-rsbuild): update .gitignore to include rspack profile
  packages/create-rsbuild/template-common/gitignore
Labels: release: feature

#5353 feat: allow to get raw JS content with `?raw`
  e2e/cases/assets/raw-query/index.test.ts
  e2e/cases/assets/raw-query/src/bar.ts
  e2e/cases/assets/raw-query/src/baz.tsx
  e2e/cases/assets/raw-query/src/foo.js
  e2e/cases/assets/raw-query/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/configChain.ts
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#5354 fix(plugin-react): skip React Refresh injection for raw JS content
  e2e/cases/assets/raw-query/index.test.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: bug fix

#5355 docs: update static assets guide to include raw JS content support
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: document

#5362 docs: clarify swc-loader default options
  website/docs/en/config/tools/swc.mdx
  website/docs/zh/config/tools/swc.mdx
Labels: release: document

#5364 fix(type): make the PostCSS plugin type loose
  packages/core/src/plugins/css.ts
  packages/core/src/types/config.ts
  packages/core/src/types/thirdParty.ts
Labels: release: bug fix

#5375 docs: add missing default value section to server.cors
  website/docs/en/config/server/cors.mdx
Labels: release: document

#5376 docs: add mobile adaptation for the next step's style
  website/docs/en/guide/start/features.mdx
  website/theme/components/Step.module.scss
Labels: release: document

#5382 fix(create-rsbuild): missing env.d.ts in some templates
  packages/create-rsbuild/template-preact-ts/src/env.d.ts
  packages/create-rsbuild/template-vanilla-ts/src/env.d.ts
Labels: release: bug fix

#5383 perf: lazy import node crypto
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/cache.ts
Labels: release: performance

#5385 feat(types): add type declarations for normal CSS module
  packages/core/types.d.ts
Labels: release: feature

#5391 fix(create-rsbuild): correct ESLint template name in react18-ts preset
  packages/create-rsbuild/src/index.ts
Labels: release: bug fix

#5397 docs: add more hooks to migration guide
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#5398 docs: update TypeScript guide to include verbatimModuleSyntax
  website/docs/en/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: document

#5404 fix(plugin-sass): unpin sass-embedded and update to v1.89.2
  packages/plugin-sass/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#5407 feat(deps): update @rspack/core to v1.4.0-beta.0
  packages/core/package.json
  packages/core/src/plugins/rspackProfile.ts
  packages/core/src/server/devMiddlewares.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: release: feature

#5410 docs: update Rspack tracing file name
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5420 docs: add section on global styles in CSS Modules
  website/docs/en/guide/styling/css-modules.mdx
  website/docs/zh/guide/styling/css-modules.mdx
Labels: release: document

#5427 feat(plugin-less): add type for `lessLogAsWarnOrErr` option
  packages/plugin-less/src/index.ts
Labels: release: feature

#5433 feat(CLI): add --logLevel flag
  e2e/cases/cli/log-level/index.test.ts
  e2e/cases/cli/log-level/src/index.js
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  packages/core/src/types/config.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#5434 fix: ensure log level can work for all logs
  e2e/cases/cli/log-level/index.test.ts
  packages/core/src/cli/index.ts
Labels: release: bug fix

#5435 feat(core): export `LogLevel` type
  packages/core/package.json
  packages/core/src/index.ts
  pnpm-lock.yaml
Labels: release: feature

#5444 docs: add `logLevel` page to sidebar
  website/docs/en/config/_meta.json
  website/docs/zh/config/_meta.json
Labels: release: document

#5446 feat: support lazy compilation in multi environments
  packages/core/src/server/devMiddlewares.ts
Labels: release: feature

#5447 fix: failed to enable lazy compilation in some cases
  packages/core/src/plugins/lazyCompilation.ts
Labels: release: bug fix

#5448 fix(types): make PostCSSPlugin type loose
  packages/core/src/types/config.ts
  packages/core/src/types/thirdParty.ts
Labels: release: bug fix

#5453 docs(website): use useI18nUrl to avoid useHookAtTopLevel error
  biome.json
  website/theme/components/Overview.tsx
  website/theme/components/Step.tsx
Labels: release: document

#5454 docs: update externals.mdx
  website/docs/zh/config/output/externals.mdx
Labels: release: document

#5461 fix(socketServer): use clearTimeout instead of clearInterval
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#5462 feat: expose logger in plugin API
  e2e/cases/plugin-api/logger/index.test.ts
  e2e/cases/plugin-api/logger/src/index.js
  packages/core/src/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#5463 feat: streamline setupMiddlewares usage
  e2e/cases/output/manifest-environment/index.test.ts
  e2e/cases/server/custom-server/scripts/pureServer.mjs
  e2e/cases/server/environments/index.test.ts
  e2e/cases/server/fallback/index.test.ts
  e2e/cases/server/setup-middlewares/index.test.ts
  e2e/cases/server/ssr-type-module/rsbuild.config.ts
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: feature

#5464 refactor: rename the second parameter of setupMiddlewares
  e2e/cases/server/environments/index.test.ts
  e2e/cases/server/setup-middlewares/index.test.ts
  e2e/cases/server/ssr-type-module/rsbuild.config.ts
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/core/src/index.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: refactor

#5470 fix: lazy compilation port replacement
  e2e/cases/lazy-compilation/port-placeholder/index.test.ts
  packages/core/src/plugins/lazyCompilation.ts
  packages/core/src/server/devMiddlewares.ts
Labels: release: bug fix

#5472 feat(deps): update @rspack/core to 1.4.0-rc.0
  e2e/cases/config/rspack-config-validate/index.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5471 docs(svelte): add less alias import solution
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/zh/plugins/list/plugin-svelte.mdx
Labels: release: document

#5474 docs(svelte): prefer replace for less alias import
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/zh/plugins/list/plugin-svelte.mdx
Labels: release: document

#5475 perf: disable Rspack config schema validation
  e2e/cases/config/rspack-config-validate/index.test.ts
  e2e/playwright.config.ts
  packages/core/src/plugins/basic.ts
Labels: release: performance

#5476 perf: disable bundler info injection
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: performance

#5478 docs: improve env and target contexts
  packages/core/src/types/hooks.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: release: document

#4928 fix: allow to enable lazy compilation via Rspack config
  e2e/cases/lazy-compilation/basic/index.test.ts
  e2e/cases/lazy-compilation/basic/rsbuild.config.ts
  packages/core/src/server/devMiddlewares.ts
Labels: release: bug fix

#5487 feat(deps): update @rspack/core to 1.4.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5490 feat(create-rsbuild): update README additional resources
  packages/create-rsbuild/template-common/README.md
Labels: release: feature

#5483 feat: support output extra configs when `inspectConfig`
  e2e/cases/config/inspect-config/index.test.ts
  packages/core/src/inspectConfig.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#5498 fix: disable bundle info when SRI is enabled
  packages/core/src/plugins/basic.ts
Labels: release: bug fix

#5500 feat: update open to v10 and improve error handling
  .github/renovate.json5
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/open.ts
  pnpm-lock.yaml
Labels: release: feature

#5502 perf: minify the prebundled webpack-bundle-analyzer
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/plugin-babel/package.json
  packages/plugin-less/package.json
  packages/plugin-sass/package.json
  packages/plugin-svgr/package.json
  pnpm-lock.yaml
Labels: release: performance

#5508 docs: fix use-bundler-chain anchor
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/configuration/rspack.mdx
Labels: release: document
