Repository web-infra-dev/rsbuild, pull requests merged in 2025-08, with the labels that each got.

#5729 docs: update Node version requirements for loading TS config
  website/docs/en/guide/configuration/rsbuild.mdx
  website/docs/zh/guide/configuration/rsbuild.mdx
Labels: release: document

#5731 feat: add support for disabling live reload in environments
  e2e/cases/environments/disable-hmr/index.test.ts
  e2e/cases/environments/disable-hmr/src/bar.js
  e2e/cases/environments/disable-hmr/src/foo.js
  packages/core/src/provider/initConfigs.ts
  packages/core/src/server/compilationManager.ts
  packages/core/src/server/compilationMiddleware.ts
  packages/core/src/types/config.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: release: feature

#5735 refactor: socket message types
  packages/core/src/client/hmr.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/socketServer.ts
Labels: release: refactor

#5743 fix(runner): remove redundant module.instantiate calls
  packages/core/src/helpers/index.ts
  packages/core/src/server/runner/asModule.ts
  packages/core/src/server/runner/esm.ts
Labels: release: bug fix

#5744 feat(create-rsbuild): update tsconfig modules settings
  packages/create-rsbuild/template-lit-ts/tsconfig.json
  packages/create-rsbuild/template-preact-ts/tsconfig.json
  packages/create-rsbuild/template-react-ts/tsconfig.json
  packages/create-rsbuild/template-react18-ts/tsconfig.json
  packages/create-rsbuild/template-solid-ts/tsconfig.json
  packages/create-rsbuild/template-svelte-ts/tsconfig.json
  packages/create-rsbuild/template-vanilla-ts/tsconfig.json
  packages/create-rsbuild/template-vue2-ts/tsconfig.json
  packages/create-rsbuild/template-vue3-ts/tsconfig.json
  scripts/config/tsconfig.json
Labels: release: feature

#5746 feat: add support for custom favicon output directory
  e2e/cases/html/favicon/index.test.ts
  packages/core/src/constants.ts
  packages/core/src/defaultConfig.ts
  packages/core/src/plugins/html.ts
  packages/core/src/rspack-plugins/RsbuildHtmlPlugin.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#5748 docs: display llms copy buttons
  pnpm-lock.yaml
  website/package.json
  website/theme/index.tsx
Labels: release: document

#5753 feat(core): add `action` option to `rsbuild.initConfigs`
  packages/core/src/index.ts
  packages/core/src/provider/provider.ts
  packages/core/src/types/rsbuild.ts
  packages/core/tests/pluginApply.test.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#5766 refactor: extracting environment error creation
  packages/core/src/provider/initConfigs.ts
Labels: release: refactor

#5773 feat: add support for custom HMR client in environments
  e2e/cases/hmr/client-multiple-environment/index.test.ts
  e2e/cases/hmr/client-multiple-environment/rsbuild.config.ts
  e2e/cases/hmr/client-multiple-environment/src/bar.js
  e2e/cases/hmr/client-multiple-environment/src/foo.js
  packages/core/src/client/hmr.ts
  packages/core/src/env.d.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/compilationManager.ts
  packages/core/src/server/compilationMiddleware.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/hmrFallback.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/server/watchFiles.ts
  packages/core/src/types/config.ts
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: release: feature

#5774 docs: add rslint to the list of Rstack tools
  README.md
  README.pt-BR.md
  README.zh-CN.md
  scripts/dictionary.txt
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#5776 docs: add version badges to Rstack tool table
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#5777 refactor: remove unnecessary async and update type definitions
  README.zh-CN.md
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/cli/index.ts
  packages/core/src/createContext.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/plugins/moment.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/progress.ts
  packages/core/src/plugins/resourceHints.ts
  packages/core/src/plugins/rspackProfile.ts
  packages/core/src/plugins/server.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/plugins/target.ts
  packages/core/src/plugins/wasm.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/provider.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/restart.ts
  packages/core/src/server/compilationManager.ts
  packages/core/src/server/environment.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/runner/index.ts
  packages/core/src/types/rsbuild.ts
  packages/core/tests/rspackVersion.test.ts
  packages/plugin-less/src/index.ts
  packages/plugin-sass/src/helpers.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-solid/src/index.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-vue/src/index.ts
  rslint.json
  website/docs/zh/guide/start/index.mdx
Labels: release: refactor

#5781 fix: appendRules helper not work in some cases
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/hooks.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/configureRspack.test.ts
Labels: release: bug fix

#5786 feat!: update minimum Node.js version to 18.12.0
  package.json
  packages/core/package.json
  packages/create-rsbuild/package.json
Labels: release: feature

#5787 docs: update JavaScript runtime installation instructions
  CONTRIBUTING.md
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#5790 perf: update build configs to target ES2022
  e2e/cases/server/overlay-type-errors/tsconfig.json
  examples/node/tsconfig.json
  examples/react/tsconfig.json
  examples/vue/tsconfig.json
  packages/core/rslib.config.ts
  packages/create-rsbuild/rslib.config.ts
  scripts/config/rslib.config.ts
  scripts/config/tsconfig.json
Labels: release: performance

#5791 fix(cli): ensure consistent spacing for npx of node 20+
  packages/core/src/cli/index.ts
Labels: release: bug fix

#5792 feat: improve command descriptions and documentations
  packages/core/src/cli/commands.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#5794 fix(cli): skip greeting when help is requested
  packages/core/src/cli/index.ts
Labels: release: bug fix

#5803 refactor: eliminate switch exhaustiveness checks
  packages/core/src/helpers/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/minimize.ts
  rslint.json
Labels: release: refactor

#5805 feat(plugin-less): support for parallel loader execution
  e2e/cases/plugin-less/parallel/index.test.ts
  e2e/cases/plugin-less/parallel/rsbuild.config.ts
  e2e/cases/plugin-less/parallel/src/a.less
  e2e/cases/plugin-less/parallel/src/b.less
  e2e/cases/plugin-less/parallel/src/c.less
  e2e/cases/plugin-less/parallel/src/d.less
  e2e/cases/plugin-less/parallel/src/e.less
  e2e/cases/plugin-less/parallel/src/f.less
  e2e/cases/plugin-less/parallel/src/index.js
  packages/plugin-less/src/index.ts
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
Labels: release: feature

#5808 perf: remove pre-bundling of postcss-load-config
  packages/core/prebundle.config.mjs
  packages/core/rslib.config.ts
  packages/core/src/plugins/css.ts
Labels: release: performance

#5809 docs: add less parallel to build performance guide
  packages/plugin-less/src/index.ts
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
Labels: release: document

#5811 docs: add version info to onBeforeDevCompile hook
  website/docs/en/shared/onBeforeDevCompile.mdx
  website/docs/zh/shared/onBeforeDevCompile.mdx
Labels: release: document

#5816 docs: improve code splitting documentation clarity
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/en/plugins/list/plugin-vue.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-vue.mdx
Labels: release: document

#5818 feat(deps): update @rspack/core to v1.5.0-beta.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5823 feat: add experimental ESM output support for node target
  e2e/cases/server/ssr-type-module/rsbuild.config.ts
  e2e/cases/server/ssr/rsbuild.config.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/defaultConfig.ts
  packages/core/src/plugins/esm.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#5826 fix(server): adjust indentation in debug log message
  packages/core/src/server/middlewares.ts
Labels: release: bug fix

#5824 feat: enable lazyCompilation.imports by default
  e2e/cases/nonce/dynamic-chunk/index.test.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/client/hmr.ts
  packages/core/src/defaultConfig.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#5828 fix(hmr): remove redundant condition check
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#5830 fix: should apply lazyCompilationMiddleware when using top-level configuration
  packages/core/src/server/devMiddlewares.ts
Labels: release: bug fix

#5839 fix(cache): handle fs operations errors
  packages/core/src/plugins/cache.ts
  scripts/test-helper/rstest.setup.ts
Labels: release: bug fix

#5840 perf: enable Rspack's barrel file optimization by default
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: performance

#5844 fix: failed to create multiple HMR connections
  e2e/cases/css/inject-styles/index.test.ts
  e2e/cases/hmr/basic/index.test.ts
  e2e/cases/hmr/multiple-connection/index.test.ts
  e2e/cases/hmr/multiple-connection/rsbuild.config.ts
  e2e/cases/hmr/multiple-connection/src/App.tsx
  e2e/cases/hmr/multiple-connection/src/index.ts
  e2e/cases/server/environments-hmr/index.test.ts
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#5848 docs: Add missing backtick to filename.mdx
  website/docs/en/config/output/filename.mdx
Labels: release: document

#5845 docs(config): add links to chunk splitting strategies
  website/docs/en/config/performance/chunk-split.mdx
  website/docs/zh/config/performance/chunk-split.mdx
Labels: release: document

#5852 fix(server): handle Deno compatibility in public dir copy
  packages/core/src/constants.ts
  packages/core/src/env.d.ts
  packages/core/src/plugins/server.ts
Labels: release: bug fix

#5859 fix: ensure inspectConfig properly initializes action before execution
  e2e/cases/config/inspect-config/index.test.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
Labels: release: bug fix

#5882 feat: add new `onAfterDevCompile` plugin hook
  e2e/cases/output/manifest-environment/index.test.ts
  e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  e2e/cases/rspack-profile/dev.mjs
  e2e/helper/jsApi.ts
  e2e/helper/utils.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/hooks.ts
  packages/core/src/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/server/devServer.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/rsbuild.ts
  packages/core/tests/__snapshots__/hooks.test.ts.snap
Labels: release: feature

#5886 docs: add version info for modifyHTML hook
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5899 feat(core): expose modifyEnvironmentConfig method in instance
  e2e/cases/javascript-api/instance-api/index.test.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#5902 refactor: improve debug log messages for better clarity
  e2e/cases/config/debug-mode/index.test.ts
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/configChain.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/loadConfig.ts
  packages/core/src/pluginManager.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/rspackConfig.ts
  website/docs/en/guide/debug/debug-mode.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/debug/debug-mode.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: release: refactor

#5904 docs: add code examples for html tags config options
  website/docs/en/config/html/tags.mdx
  website/docs/zh/config/html/tags.mdx
Labels: release: document

#5908 docs: add exclude option to `printFileSize` type
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: document

#5913 fix: add `OnDevCompileDoneFn` type for backward compatibility
  packages/core/src/index.ts
  packages/core/src/types/hooks.ts
  website/docs/zh/api/javascript-api/types.mdx
Labels: release: bug fix

#5914 docs(config): add security warning about source maps in production
  website/docs/en/config/output/source-map.mdx
  website/docs/zh/config/output/source-map.mdx
Labels: release: document

#5919 docs: update Rspress to beta.28 and remove unused openGraph fields
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
Labels: release: document

#5926 fix: floating promise in rspackProfile plugin
  packages/core/src/plugins/rspackProfile.ts
Labels: release: bug fix

#5939 fix: enhance inline query regex to support more patterns
  e2e/cases/assets/inline-query-auto/index.test.ts
  e2e/cases/assets/inline-query-auto/src/App.jsx
  e2e/cases/assets/inline-query-auto/src/index.js
  e2e/cases/assets/inline-query-false/index.test.ts
  e2e/cases/assets/inline-query-false/src/App.jsx
  e2e/cases/assets/inline-query-false/src/index.js
  e2e/cases/assets/inline-query/index.test.ts
  e2e/cases/assets/inline-query/src/App.jsx
  e2e/cases/assets/inline-query/src/index.js
  e2e/cases/css/inline-query/index.test.ts
  e2e/cases/css/inline-query/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/constants.ts
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#5943 feat: add more params for `performance.printFileSize.total`
  packages/core/src/plugins/fileSize.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#5950 feat(deps): update @rspack/core to v1.5.0
  packages/core/package.json
  packages/core/src/helpers/index.ts
  pnpm-lock.yaml
Labels: release: feature

#5954 docs: improve plugin type documentation
  packages/core/src/types/plugin.ts
  website/docs/en/api/javascript-api/types.mdx
  website/docs/zh/api/javascript-api/types.mdx
Labels: release: document

#5960 fix: temporarily disable inline enum optimization
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#5969 feat(plugin-react): improve transpilation scope of ReactRefreshPlugin
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/index.test.ts
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: feature

#5971 feat(deps): update dependency @rspack/core to v1.5.1
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5975 refactor(types): use `LoaderDefinition` to declare loader types
  packages/core/src/loader/ignoreCssLoader.ts
  packages/core/src/loader/transformLoader.ts
  packages/plugin-svgr/src/loader.ts
Labels: release: refactor

#5980 fix: rerun onBeforeDevCompile hook correctly with multiple environments
  e2e/cases/plugin-api/plugin-hooks-environment/rebuild.test.ts
  packages/core/src/hooks.ts
Labels: release: bug fix

#5989 docs: add example for `cssModules.auto` configuration
  website/docs/en/config/output/css-modules.mdx
  website/docs/zh/config/output/css-modules.mdx
Labels: release: document

#5998 refactor(e2e): simplify test setup by using helper methods
  e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts
  e2e/cases/plugin-api/plugin-hooks-environment/rebuild.test.ts
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
Labels: release: refactor

#6004 docs: adjust the links of rspack-splitChunks
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
Labels: release: document
