Repository web-infra-dev/rsbuild, pull requests merged in 2025-03, with the labels that each got.

#4680 docs: add guide for customizing JSX in React
  website/docs/en/guide/framework/react.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: document

#4681 fix(create-rsbuild): update tsconfig `moduleResolution` to lowercase
  e2e/cases/server/overlay-type-errors/tsconfig.json
  examples/node/tsconfig.json
  examples/react/tsconfig.json
  examples/vue/tsconfig.json
  packages/create-rsbuild/template-lit-ts/tsconfig.json
  packages/create-rsbuild/template-preact-ts/tsconfig.json
  packages/create-rsbuild/template-react-ts/tsconfig.json
  packages/create-rsbuild/template-react18-ts/tsconfig.json
  packages/create-rsbuild/template-solid-ts/tsconfig.json
  packages/create-rsbuild/template-svelte-ts/tsconfig.json
  packages/create-rsbuild/template-vanilla-ts/tsconfig.json
  packages/create-rsbuild/template-vue2-ts/tsconfig.json
  packages/create-rsbuild/template-vue3-ts/tsconfig.json
  scripts/config/tsconfig-node16.json
  scripts/config/tsconfig.json
Labels: release: bug fix

#4683 fix(deps): revert @rspack/core to v1.2.5 to fix HMR
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4688 docs: fix react.mdx translation
  website/docs/en/guide/framework/react.mdx
Labels: release: document

#4693 docs: update rspack-examples references to rstack-examples
  README.md
  README.pt-BR.md
  README.zh-CN.md
  examples/README.md
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/community/index.mdx
  website/docs/en/config/module-federation/options.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/community/index.mdx
  website/docs/zh/config/module-federation/options.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
  website/docs/zh/guide/advanced/ssr.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#4698 fix(mf): add more MF packages to `source.include`
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#4701 feat(server): add graceful shutdown support
  packages/core/src/server/devServer.ts
  packages/core/src/server/gracefulShutdown.ts
  packages/core/src/server/prodServer.ts
Labels: release: feature

#4708 fix: `forceSplitting` not work with `single-vendor`
  e2e/cases/performance/single-vendor-splitting/index.test.ts
  e2e/cases/performance/single-vendor-splitting/rsbuild.config.ts
  e2e/cases/performance/single-vendor-splitting/src/App.jsx
  e2e/cases/performance/single-vendor-splitting/src/index.js
  packages/core/src/plugins/splitChunks.ts
  packages/core/src/types/config.ts
Labels: release: bug fix

#4710 feat: make HMR logs less verbose
  e2e/cases/server/hmr-logs/index.test.ts
  e2e/cases/server/hmr-logs/rsbuild.config.ts
  e2e/cases/server/hmr-logs/src/App.css
  e2e/cases/server/hmr-logs/src/App.tsx
  e2e/cases/server/hmr-logs/src/index.ts
  packages/core/src/provider/createCompiler.ts
Labels: release: feature

#4711 docs: update contributing guide
  CONTRIBUTING.md
  website/docs/en/guide/basic/static-deploy.mdx
  website/docs/zh/guide/basic/static-deploy.mdx
Labels: release: document

#4713 fix(plugin-vue): order problem with pluginReact
  e2e/cases/vue/with-react/index.test.ts
  e2e/cases/vue/with-react/rsbuild.config.ts
  e2e/cases/vue/with-react/src/A.vue
  e2e/cases/vue/with-react/src/B.vue
  e2e/cases/vue/with-react/src/index.js
  packages/plugin-vue/src/index.ts
Labels: release: bug fix

#4717 feat(css): support `cssLoader.exportType` as `string`
  e2e/cases/css/export-type-string/index.test.ts
  e2e/cases/css/export-type-string/rsbuild.config.ts
  e2e/cases/css/export-type-string/src/a.scss
  e2e/cases/css/export-type-string/src/b.module.scss
  e2e/cases/css/export-type-string/src/index.js
  e2e/cases/output/manifest-single-vendor/index.test.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/compat/webpack/tests/__snapshots__/webpackConfig.test.ts.snap
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/output.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/output.test.ts.snap
Labels: release: feature

#4718 docs(website): add footer to home page
  website/i18n.json
  website/theme/components/Copyright.module.scss
  website/theme/components/HomeFooter.module.scss
  website/theme/components/HomeFooter.tsx
  website/theme/pages/index.tsx
Labels: release: document

#4719 docs: improve filename configuration
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: document

#4722 fix: should apply nonce to preload script tags
  e2e/cases/nonce/dynamic-chunk/index.test.ts
  packages/core/src/plugins/nonce.ts
  website/docs/en/config/security/nonce.mdx
  website/docs/zh/config/security/nonce.mdx
Labels: release: bug fix

#4723 docs: update Angular Rspack link
  website/docs/en/plugins/list/index.mdx
  website/docs/zh/plugins/list/index.mdx
Labels: release: document

#4725 docs: add JSDoc for EnvironmentContext
  packages/core/src/types/hooks.ts
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
Labels: release: document

#4724 fix: improve file size gzip header rendering
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#4734 fix: await watcher close before restart
  packages/core/src/config.ts
Labels: release: bug fix

#4737 docs: update quick start guide
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#4739 feat: allow opening relative paths on error overlay
  e2e/cases/server/overlay-type-errors/index.test.ts
  packages/core/src/server/overlay.ts
  packages/core/src/server/socketServer.ts
Labels: release: feature

#4744 feat: display relative paths on error overlay
  packages/core/src/helpers/path.ts
  packages/core/src/server/overlay.ts
  packages/core/tests/overlay.test.ts
Labels: release: feature

#4745 feat(plugin-webpack-swc): use require.resolve to check react version to support pnpm catalog
  .changeset/bumpy-llamas-guess.md
  packages/compat/plugin-webpack-swc/src/utils.ts
Labels: release: feature

#4748 fix(create-rsbuild): remove public/.gitkeep file
  packages/create-rsbuild/template-common/public/.gitkeep
Labels: release: bug fix

#4749 docs: standardize "web" capitalization across documentation
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/zh/community/releases/v1-0.mdx
  website/docs/zh/guide/optimization/inline-assets.mdx
  website/i18n.json
Labels: release: document

#4750 docs: improve browser compatibility clarity
  website/docs/en/guide/advanced/browser-compatibility.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/zh/guide/advanced/browser-compatibility.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
Labels: release: document

#4752 perf: bundle webpack-merge for faster startup
  packages/core/prebundle.config.mjs
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config.ts
  packages/core/src/types/plugin.ts
Labels: release: performance

#4754 fix: print environment name only when using multi compiler
  packages/core/src/provider/createCompiler.ts
Labels: release: bug fix

#4758 feat(deps): update Rspack to v1.2.8
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4760 docs: add dynamic asset prefix guide
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/en/config/output/asset-prefix.mdx
  website/docs/zh/config/dev/asset-prefix.mdx
  website/docs/zh/config/output/asset-prefix.mdx
Labels: release: document

#4761 docs: improve InspectConfigOptions type
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#4755 fix(rsbuild): add dynamic import callback to cjs vm
  packages/core/src/server/runner/cjs.ts
Labels: release: bug fix

#4767 fix: appendPlugins not work in some cases
  packages/core/src/provider/rspackConfig.ts
  packages/core/tests/configureRspack.test.ts
Labels: release: bug fix

#4770 docs: add Tailwind CSS v4 compatibility tip for preprocessors
  website/docs/en/guide/basic/tailwindcss.mdx
  website/docs/zh/guide/basic/tailwindcss.mdx
Labels: release: document

#4772 fix: simplify build error logs
  packages/compat/webpack/src/build.ts
  packages/core/src/cli/commands.ts
  packages/core/src/provider/build.ts
Labels: release: bug fix

#4773 feat(CLI): allow to run without sub-command to trigger dev
  packages/core/src/cli/commands.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#4778 feat: support async function for rsbuildConfig in createRsbuild options
  packages/core/src/createContext.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
  scripts/test-helper/src/index.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: feature

#4783 feat: integrate env variable loading into createRsbuild options
  e2e/cases/javascript-api/build-and-load-env/.env
  e2e/cases/javascript-api/build-and-load-env/.env.prod
  e2e/cases/javascript-api/build-and-load-env/index.test.ts
  e2e/cases/javascript-api/build-and-load-env/src/index.js
  packages/core/src/cli/init.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/rsbuild.ts
Labels: release: feature

#4784 fix: handle null stats JSON in Socket server
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#4786 docs: update description for build close method
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onCloseBuild.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onCloseBuild.mdx
Labels: release: document

#4788 docs: update examples for server close method
  packages/core/src/server/helper.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onCloseDevServer.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onCloseDevServer.mdx
Labels: release: document

#4790 fix(cache): `buildCache.cacheDirectory` config not work
  packages/core/src/plugins/cache.ts
  packages/core/tests/__snapshots__/cache.test.ts.snap
Labels: release: bug fix

#4793 fix: should merge copy config correctly when copy config type is different
  e2e/cases/output/copy/index.test.ts
  packages/core/src/mergeConfig.ts
Labels: release: bug fix

#4800 docs: add `loadEnv` option in `createRsbuild` method
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: document

#4801 docs: apply new theme colors to the documentation site
  website/theme/index.scss
Labels: release: document

#4802 fix: update null checks to improve type safety
  e2e/cases/preact/prefresh-context/index.test.ts
  e2e/cases/preact/prefresh-disabled/index.test.ts
  e2e/cases/preact/prefresh/index.test.ts
  e2e/cases/solid/hmr/index.test.ts
  e2e/scripts/shared.ts
  packages/compat/plugin-webpack-swc/tests/plugin.test.ts
  packages/compat/webpack/tests/initConfigs.test.ts
  packages/core/src/client/overlay.ts
  packages/core/src/pluginManager.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/plugins/manifest.ts
  packages/core/tests/mergeConfig.test.ts
  packages/create-rsbuild/template-vanilla-ts/src/index.ts
  website/docs/en/config/html/tags.mdx
  website/docs/en/config/index.mdx
  website/docs/zh/config/html/tags.mdx
Labels: release: bug fix

#4803 fix(overlay): avoid multiple error overlay instances
  packages/core/src/client/overlay.ts
Labels: release: bug fix

#4804 docs: `getPlugins` can accept `environment` option
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#4808 docs: improve inline static assets
  website/docs/en/config/output/data-uri-limit.mdx
  website/docs/en/guide/optimization/inline-assets.mdx
  website/docs/zh/config/output/data-uri-limit.mdx
  website/docs/zh/guide/optimization/inline-assets.mdx
Labels: release: document

#4811 docs: update ecosystem diagrams
  README.md
  README.pt-BR.md
  README.zh-CN.md
  pnpm-lock.yaml
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
  website/package.json
Labels: release: document

#4813 docs: add information on obtaining additional templates
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#4815 docs: update release dates for blogs
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/community/releases/v0-2.mdx
  website/docs/en/community/releases/v0-3.mdx
  website/docs/en/community/releases/v0-4.mdx
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/community/releases/v0-6.mdx
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/community/releases/v1-0.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/community/releases/v0-2.mdx
  website/docs/zh/community/releases/v0-3.mdx
  website/docs/zh/community/releases/v0-4.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/community/releases/v0-6.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/community/releases/v1-0.mdx
Labels: release: document

#4816 feat(deps): update Rspack to 1.3.0-beta.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4817 feat: add integrity support for dynamic imports
  e2e/cases/sri/enable-dev/index.test.ts
  e2e/cases/sri/preload/index.test.ts
  packages/core/src/configChain.ts
  packages/core/src/helpers/stats.ts
  packages/core/src/plugins/sri.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
Labels: release: feature

#4819 docs: update SRI to match the latest implementation
  packages/core/src/types/config.ts
  website/docs/en/config/security/sri.mdx
  website/docs/zh/config/security/sri.mdx
Labels: release: document

#4823 docs: update features list
  website/docs/en/guide/start/features.mdx
  website/docs/zh/guide/start/features.mdx
Labels: release: document

#4826 fix: MaxListenersExceeded warning after restarting server
  packages/core/src/server/gracefulShutdown.ts
Labels: release: bug fix

#4829 feat: improve restarting experience
  packages/core/src/helpers/index.ts
  packages/core/src/restart.ts
  packages/core/src/server/cliShortcuts.ts
Labels: release: feature

#4831 feat: expose `context.action` property
  packages/compat/webpack/src/createCompiler.ts
  packages/core/src/cli/init.ts
  packages/core/src/createContext.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/types/context.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#4835 feat(security): add warnings for defining `process.env`
  e2e/cases/source/define/index.test.ts
  packages/core/src/plugins/define.ts
Labels: release: feature

#4836 docs: add MultiCompiler references
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: release: document

#4837 fix: handle errors in transform loader with try-catch block
  e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts
  e2e/cases/plugin-api/plugin-transform-error-handle/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-error-handle/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-error-handle/src/index.js
  packages/core/src/loader/transformLoader.ts
Labels: release: bug fix

#4838 feat: improve build error messages
  e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts
  e2e/cases/server/overlay-type-errors/index.test.ts
  packages/core/src/helpers/format.ts
  packages/core/src/helpers/stats.ts
  website/docs/en/guide/faq/exceptions.mdx
Labels: release: feature

#4841 feat(css): add support for raw CSS imports
  e2e/cases/css/css-raw/index.test.ts
  e2e/cases/css/css-raw/src/a.css
  e2e/cases/css/css-raw/src/b.module.css
  e2e/cases/css/css-raw/src/index.js
  examples/react/src/App.tsx
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/configChain.ts
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/types.d.ts
Labels: release: feature

#4842 docs: add section on importing raw CSS files
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: document

#4843 feat(plugin-sass): add support for raw query
  e2e/cases/css/sass-raw/index.test.ts
  e2e/cases/css/sass-raw/rsbuild.config.ts
  e2e/cases/css/sass-raw/src/a.scss
  e2e/cases/css/sass-raw/src/b.module.scss
  e2e/cases/css/sass-raw/src/index.js
  packages/core/src/configChain.ts
  packages/core/src/plugins/css.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/index.test.ts
Labels: release: feature

#4844 feat(plugin-less): add support for raw query
  e2e/cases/css/less-raw/index.test.ts
  e2e/cases/css/less-raw/rsbuild.config.ts
  e2e/cases/css/less-raw/src/a.less
  e2e/cases/css/less-raw/src/b.module.less
  e2e/cases/css/less-raw/src/index.js
  packages/core/src/configChain.ts
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-less/tests/index.test.ts
Labels: release: feature

#4845 feat(plugin-stylus): add support for raw query
  e2e/cases/css/stylus-raw/index.test.ts
  e2e/cases/css/stylus-raw/rsbuild.config.ts
  e2e/cases/css/stylus-raw/src/a.styl
  e2e/cases/css/stylus-raw/src/b.module.styl
  e2e/cases/css/stylus-raw/src/index.js
  packages/core/src/configChain.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#4846 feat: add types for raw imports of CSS preprocessors
  packages/core/types.d.ts
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: feature

#4847 docs: update Rspress and fix Overview link style
  pnpm-lock.yaml
  website/package.json
  website/theme/components/Overview.module.scss
Labels: release: document

#4849 feat(css): add support for inline CSS imports
  e2e/cases/css/css-inline/index.test.ts
  e2e/cases/css/css-inline/src/a.css
  e2e/cases/css/css-inline/src/b.module.css
  e2e/cases/css/css-inline/src/index.js
  examples/react/src/App.tsx
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/configChain.ts
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/types.d.ts
Labels: release: feature

#4857 docs: `pluginReact` is also needed when using `pluginSvgr`
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
Labels: release: document

#4856 feat(plugin-sass): add support for inline query
  e2e/cases/css/inline-query/index.test.ts
  e2e/cases/sass/inline-query/index.test.ts
  e2e/cases/sass/inline-query/rsbuild.config.ts
  e2e/cases/sass/inline-query/src/a.scss
  e2e/cases/sass/inline-query/src/b.module.scss
  e2e/cases/sass/inline-query/src/index.js
  e2e/cases/sass/raw-query/index.test.ts
  e2e/cases/sass/raw-query/rsbuild.config.ts
  e2e/cases/sass/raw-query/src/a.scss
  e2e/cases/sass/raw-query/src/b.module.scss
  e2e/cases/sass/raw-query/src/index.js
  packages/core/src/configChain.ts
  packages/core/types.d.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/index.test.ts
  pnpm-lock.yaml
  website/package.json
Labels: release: feature

#4860 feat(plugin-stylus): add support for inline query
  e2e/cases/stylus/inline-query/index.test.ts
  e2e/cases/stylus/inline-query/rsbuild.config.ts
  e2e/cases/stylus/inline-query/src/a.styl
  e2e/cases/stylus/inline-query/src/b.module.styl
  e2e/cases/stylus/inline-query/src/index.js
  e2e/cases/stylus/raw-query/index.test.ts
  e2e/cases/stylus/raw-query/rsbuild.config.ts
  e2e/cases/stylus/raw-query/src/a.styl
  e2e/cases/stylus/raw-query/src/b.module.styl
  e2e/cases/stylus/raw-query/src/index.js
  packages/core/src/configChain.ts
  packages/core/types.d.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#4861 fix(plugin-stylus): `define` option type
  packages/plugin-stylus/src/index.ts
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/zh/plugins/list/plugin-stylus.mdx
Labels: release: bug fix

#4862 feat(plugin-stylus): add `includeCSS` option type and JSDoc
  packages/plugin-stylus/src/index.ts
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/zh/plugins/list/plugin-stylus.mdx
Labels: release: feature

#4865 docs: add inline query parameter to CSS guide
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: document

#4866 feat(deps): update Rspack to v1.3.0-beta.1
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4869 feat(asset): add support for raw query
  e2e/cases/assets/raw/index.test.ts
  e2e/cases/assets/raw/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/asset.ts
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#4872 docs: import static assets as string
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: document

#4875 docs: polish credits in README files
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#4877 fix(types): missing `server.cors` object type
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4876 fix(server)!: should respect the value of the `server.cors` option
  e2e/cases/server/cors/index.test.ts
  e2e/cases/server/fallback/index.test.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/server/getDevMiddlewares.ts
Labels: release: bug fix

#4880 docs: enhance CORS configuration examples
  website/docs/en/config/server/cors.mdx
  website/docs/zh/config/server/cors.mdx
Labels: release: document

#4881 feat: integrate Rspack lazy compilation middleware
  packages/core/src/createRsbuild.ts
  packages/core/src/plugins/lazyCompilation.ts
  packages/core/src/server/compilationManager.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
Labels: release: feature

#4892 feat(plugin): add "addContextDependency" and "addMissingDependency" to api.transform
  packages/core/src/loader/transformLoader.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#4894 docs: clarify CORS security recommendations
  packages/core/src/types/config.ts
  website/docs/en/config/server/cors.mdx
  website/docs/zh/config/server/cors.mdx
Labels: release: document

#4895 docs: correct `server.headers` type
  website/docs/en/config/server/headers.mdx
  website/docs/zh/config/server/headers.mdx
Labels: release: document

#4897 feat(cors): update CORS defaults to allow loopback addresses
  e2e/cases/server/fallback/index.test.ts
  packages/core/src/config.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/server.test.ts
  website/docs/en/config/server/cors.mdx
  website/docs/zh/config/server/base.mdx
  website/docs/zh/config/server/cors.mdx
  website/docs/zh/guide/basic/web-workers.mdx
  website/docs/zh/guide/faq/hmr.mdx
Labels: release: feature

#4898 fix(server): allow `server.headers` to override `server.cors`
  e2e/cases/server/cors/index.test.ts
  e2e/cases/server/proxy/index.test.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/prodServer.ts
  website/docs/en/config/server/headers.mdx
  website/docs/zh/config/server/headers.mdx
Labels: release: bug fix

#4902 docs: clarify env files merge behavior
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#4906 feat(deps): update Rspack to v1.3.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4909 fix: make CSS preprocessor plugins compat with Rsbuild 1.2
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-less/tests/index.test.ts
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/index.test.ts
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/index.test.ts
Labels: release: bug fix

#4914 fix: improve inline rules in CSS preprocessor plugins
  packages/plugin-less/src/index.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/src/index.ts
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#4917 docs: improve `server.compress`
  website/docs/en/config/server/compress.mdx
  website/docs/zh/config/server/compress.mdx
Labels: release: document

#4922 docs: add cacheDir option to migration guide
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#4923 docs: fix env file anchor
  website/docs/zh/config/server/open.mdx
Labels: release: document

#4926 fix: let jiti load `@rspack/core` with native require
  packages/core/src/config.ts
Labels: release: bug fix
