Repository web-infra-dev/rsbuild, pull requests merged in 2025-07, with the labels that each got.

#5515 fix(open): skip opening browser in CodeSandbox
  packages/core/src/server/open.ts
Labels: release: bug fix

#5516 feat(deps): update @rspack/core to v1.4.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5521 docs: add `compress.filter` option
  packages/core/src/types/config.ts
  website/docs/en/config/server/compress.mdx
  website/docs/zh/config/server/compress.mdx
Labels: release: document

#5522 feat(server): add `compress.level` option
  packages/core/src/server/gzipMiddleware.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  website/docs/en/config/server/compress.mdx
  website/docs/zh/config/server/compress.mdx
Labels: release: feature

#5523 docs: clarify execution order with `modifyHTML` and `html.tags`
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5529 refactor: normalize config types in compilation manager
  packages/core/src/client/hmr.ts
  packages/core/src/server/compilationManager.ts
Labels: release: refactor

#5538 fix: ensure that raw query of scripts can be accurately matched
  e2e/cases/assets/raw-query/index.test.ts
  e2e/cases/assets/raw-query/src/foo.js
  e2e/cases/assets/raw-query/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#5539 docs: Update typescript.mdx with fixed typo in `isolatedModules ` example
  website/docs/en/guide/basic/typescript.mdx
Labels: release: document

#5542 docs: fix typo in isolatedModules example
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: document

#5544 docs: update raw import JSDoc to include scripts
  packages/core/types.d.ts
  website/docs/en/guide/styling/css-usage.mdx
  website/docs/zh/guide/styling/css-usage.mdx
Labels: release: document

#5547 fix: ensure that raw query of assets can be accurately matched
  e2e/cases/assets/raw-query/index.test.ts
  e2e/cases/assets/raw-query/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/asset.ts
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/react.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: bug fix

#5531 feat(server): token-based WebSocket authentication
  packages/core/src/client/hmr.ts
  packages/core/src/createContext.ts
  packages/core/src/env.d.ts
  packages/core/src/server/compilationManager.ts
  packages/core/src/server/compilationMiddleware.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/socketServer.ts
  packages/core/src/types/hooks.ts
  packages/core/tests/server.test.ts
Labels: release: feature

#5548 docs: add webSocketToken to documentation
  packages/core/src/types/hooks.ts
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
Labels: release: document

#5555 fix: improve formatting of minutes in build time
  packages/core/src/helpers/index.ts
  packages/core/tests/helpers.test.ts
Labels: release: bug fix

#5561 fix: Use `hostname` to determine local or network
  packages/core/src/server/helper.ts
Labels: release: bug fix

#5565 docs: update plugin development introduction
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/plugins/_meta.json
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#5567 fix: update Node.js engine requirement to >=16.17.0
  packages/core/package.json
Labels: release: bug fix

#5570 fix: patch open to maintaining Node 16.10 compatibility
  packages/core/package.json
  patches/open@10.1.2.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: release: bug fix

#5578 feat(deps): update @rspack/core to v1.4.6
  e2e/cases/server/ssr-type-module/index.test.ts
  e2e/cases/server/ssr/index.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5581 docs: update plugin API title
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5583 fix(create-rsbuild): update ESLint config in React templates
  e2e/cases/create-rsbuild/tools.test.ts
  packages/create-rsbuild/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#5585 feat: export `HtmlTag` type
  packages/core/src/index.ts
Labels: release: feature

#5587 fix(types): type error when importing SVG file with React query
  packages/create-rsbuild/template-react-ts/src/env.d.ts
  packages/create-rsbuild/template-react18-ts/src/env.d.ts
Labels: release: bug fix

#5586 feat: add `metadata` field to tag object
  e2e/cases/plugin-api/plugin-modify-tags-meta/index.test.ts
  e2e/cases/plugin-api/plugin-modify-tags-meta/myPlugin.ts
  e2e/cases/plugin-api/plugin-modify-tags-meta/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-modify-tags-meta/src/index.js
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/types/config.ts
  website/docs/en/config/html/tags.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/config/html/tags.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: feature

#5593 docs: add section on vite-tsconfig-paths support
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#5598 docs: update migration guides for plugins
  website/docs/en/guide/migration/_meta.json
  website/docs/en/guide/migration/vite-plugin.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/guide/migration/_meta.json
  website/docs/zh/guide/migration/vite-plugin.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#5603 feat(deps): update @rspack/core to 1.4.8
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5610 docs: add example for migrating HTML hook
  website/docs/en/guide/migration/vite-plugin.mdx
  website/docs/zh/guide/migration/vite-plugin.mdx
Labels: release: document

#5612 docs: minor english adjustment
  website/docs/en/guide/faq/features.mdx
Labels: release: document

#5613 docs: add example for migrating configureServer hook
  website/docs/en/guide/migration/vite-plugin.mdx
  website/docs/zh/guide/migration/vite-plugin.mdx
Labels: release: document

#5615 fix: wait until the last build is finished before calling `stats.toJson`
  packages/core/src/server/devServer.ts
Labels: release: bug fix

#5616 refactor: simplify plugin environment handling
  packages/core/src/hooks.ts
  packages/core/src/initPlugins.ts
  packages/core/src/pluginManager.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/rsbuild.ts
Labels: release: refactor

#5619 docs: middleware can be an async function
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
Labels: release: document

#5620 feat: allow plugin to specify `apply` property
  e2e/cases/plugin-api/plugin-apply/index.test.ts
  e2e/cases/plugin-api/plugin-apply/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-apply/src/index.css
  e2e/cases/plugin-api/plugin-apply/src/index.js
  packages/core/src/pluginManager.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/pluginStore.test.ts
Labels: release: feature

#5623 docs: update plugin existence checks guide
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/shared/isPluginExists.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/shared/isPluginExists.mdx
Labels: release: document

#5622 fix: failed to call `getStats` before the first build is finished
  e2e/cases/javascript-api/get-stats/index.test.ts
  e2e/cases/javascript-api/get-stats/src/index.js
  packages/core/src/server/devServer.ts
Labels: release: bug fix

#5625 docs: enhance type declaration guidance for env variables
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#5627 feat: allow control of type safety for import.meta.env
  packages/core/types.d.ts
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: feature

#5629 docs: add introduction to conditional apply plugin
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5628 fix: adjust when lazy compilation can be applied
  packages/core/src/plugins/lazyCompilation.ts
Labels: release: bug fix

#5638 docs: enhance migration guide for resolved config
  website/docs/en/guide/migration/vite-plugin.mdx
  website/docs/zh/guide/migration/vite-plugin.mdx
Labels: release: document

#5641 docs: add example for migrating configEnvironment hook
  website/docs/en/guide/migration/vite-plugin.mdx
  website/docs/zh/guide/migration/vite-plugin.mdx
Labels: release: document

#5642 docs(deps): update @rstack-dev/doc-ui to 1.10.8
  pnpm-lock.yaml
  website/package.json
Labels: release: document

#5645 feat(plugin): support for the `enforce` property
  packages/core/src/pluginManager.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/pluginDependencies.test.ts
  packages/core/tests/pluginEnforce.test.ts
Labels: release: feature

#5654 docs(plugin): update `apply` property for its function signature
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5656 fix: patch is-wsl to maintaining Node 16.10 compatibility
  patches/wsl-utils@0.1.0.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: release: bug fix

#5664 docs: mention Rstest in CRA guide
  website/docs/en/guide/migration/cra.mdx
  website/docs/zh/guide/migration/cra.mdx
Labels: release: document

#5670 feat: enable error tolerance for type re-exports
  e2e/cases/typescript/type-re-exports/index.test.ts
  e2e/cases/typescript/type-re-exports/src/bar.ts
  e2e/cases/typescript/type-re-exports/src/foo.ts
  e2e/cases/typescript/type-re-exports/src/index.ts
  e2e/cases/typescript/type-re-exports/tsconfig.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/swc.test.ts.snap
  packages/plugin-babel/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#5673 perf: require rspack to improve startup performance
  packages/core/src/index.ts
  packages/core/src/pluginHelper.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/plugins/moduleFederation.ts
  packages/core/src/plugins/output.ts
  packages/core/src/plugins/progress.ts
  packages/core/src/plugins/rspackProfile.ts
  packages/core/src/plugins/sri.ts
  packages/core/src/provider/build.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/rspack.ts
  packages/core/src/server/devMiddlewares.ts
Labels: release: performance

#5674 fix: watch options not work in build watch mode
  e2e/cases/cli/build-watch-options/index.test.ts
  e2e/cases/cli/build-watch-options/rsbuild.config.mjs
  e2e/cases/cli/build-watch-options/src/bar.js
  e2e/cases/cli/build-watch-options/src/foo.js
  e2e/cases/cli/build-watch-options/src/index.js
  e2e/cases/cli/build-watch/tsconfig.json
  packages/core/src/provider/build.ts
Labels: release: bug fix

#5677 feat: add `filename.wasm` config
  e2e/cases/wasm/wasm-filename/index.test.ts
  e2e/cases/wasm/wasm-filename/rsbuild.config.ts
  e2e/cases/wasm/wasm-filename/src/factorial.wasm
  e2e/cases/wasm/wasm-filename/src/index.js
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/wasm.ts
  packages/core/src/types/config.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: feature

#5681 perf: reduce getStatus cost when previewing static assets
  packages/core/src/helpers/stats.ts
  packages/core/src/plugins/fileSize.ts
  packages/core/src/server/middlewares.ts
Labels: release: performance

#5685 perf(deps): update rspack-chain to 1.3.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: performance

#5690 fix(plugin-less): pin less version to 4.3.0
  .github/renovate.json5
  e2e/cases/plugin-svelte/package.json
  packages/plugin-less/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#5694 refactor: fork connect-history-api-fallback dependency
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/historyApiFallback.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: release: refactor

#5696 fix: remove the deprecated `url.parse` from historyApiFallback
  packages/core/src/helpers/index.ts
  packages/core/src/server/historyApiFallback.ts
  packages/core/src/types/config.ts
Labels: release: bug fix

#5712 docs: update historyApiFallback documentation
  packages/core/src/types/config.ts
  website/docs/en/config/server/history-api-fallback.mdx
  website/docs/zh/config/server/history-api-fallback.mdx
Labels: release: document

#5713 refactor: fix unbound-method lint issues
  packages/core/package.json
  packages/core/src/inspectConfig.ts
  packages/core/src/server/gzipMiddleware.ts
  pnpm-lock.yaml
  rslint.json
Labels: release: refactor

#5719 fix(cli): support `--environment` shorten option
  e2e/cases/cli/specified-environment/index.test.ts
  packages/core/src/cli/init.ts
Labels: release: bug fix

#5721 feat(deps): update @rspack/core to v1.4.11
  packages/core/package.json
  packages/core/src/provider/build.ts
  pnpm-lock.yaml
Labels: release: feature
