Repository web-infra-dev/rsbuild, pull requests merged in 2025-05, with the labels that each got.

#5143 docs: enhance api.transform description
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5144 feat: rename hooks function types and export them
  packages/core/src/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/api/javascript-api/types.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#5145 feat: add new `modifyHTML` hook
  e2e/cases/plugin-api/plugin-hooks-environment/index.test.ts
  e2e/cases/plugin-api/plugin-hooks-watch/index.test.ts
  e2e/cases/plugin-api/plugin-hooks/index.test.ts
  e2e/cases/plugin-api/plugin-modify-html/index.test.ts
  e2e/cases/plugin-api/plugin-modify-html/src/index.css
  e2e/cases/plugin-api/plugin-modify-html/src/index.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/createRsbuild.ts
  packages/core/src/hooks.ts
  packages/core/src/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/hooks.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
Labels: release: feature

#5154 docs: update creation instructions to link to create-rsbuild
  website/docs/en/guide/framework/preact.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/framework/solid.mdx
  website/docs/en/guide/framework/svelte.mdx
  website/docs/en/guide/framework/vue.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/framework/preact.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/guide/framework/solid.mdx
  website/docs/zh/guide/framework/svelte.mdx
  website/docs/zh/guide/framework/vue.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#5155 docs: update plugin example to use named export
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5157 docs: add cheerio example for HTML manipulation
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5159 docs: add link to middleware guide
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/prodServer.ts
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/config/server/middleware-mode.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5158 docs: update TransformDescriptor to include more conditions
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#5160 feat: add `mimetype` option to `api.transform`
  e2e/cases/plugin-api/plugin-transform-mime-type/index.test.ts
  e2e/cases/plugin-api/plugin-transform-mime-type/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-mime-type/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-mime-type/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#5162 docs: clarify tag injection position
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/types/config.ts
  website/docs/en/config/html/tags.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/config/html/tags.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#5164 docs: improve manifest data access instructions
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
Labels: release: document

#5165 feat: validate duplicated manifest filenames and throw a warning
  packages/core/src/plugins/manifest.ts
Labels: release: feature

#5166 docs: configuring multiple environments manifest files
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: release: document

#5167 perf: enable Rspack incremental build by default
  e2e/package.json
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: performance

#5170 fix: should not apply incremental config to webpack
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
Labels: release: bug fix

#5174 feat: add `enforce` option to `api.transform`
  e2e/cases/plugin-api/plugin-transform-enforce/index.test.ts
  e2e/cases/plugin-api/plugin-transform-enforce/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-enforce/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-enforce/src/index.js
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#5177 perf: update html-rspack-plugin to 6.1.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: performance

#5181 feat(plugin-less): update webpackImporter type to support 'only'
  packages/plugin-less/src/index.ts
Labels: release: feature

#5182 feat(plugin-less): improve loader options type with JSDoc
  packages/plugin-less/src/index.ts
Labels: release: feature

#5187 docs: update quick-start to include multiple values example
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#5188 feat(deps): update Rspack to v1.3.9
  e2e/cases/server/base-url-env-var/index.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5191 fix: update html-rspack-plugin to 6.1.2 to fix template parsing
  e2e/cases/server/base-url-env-var/index.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#5199 fix(profile): remove unused jscpuprofile.json
  e2e/cases/rspack-profile/index.test.ts
  packages/core/src/plugins/rspackProfile.ts
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: bug fix

#5200 fix(mf): allow to set `server.cors` with MF Rsbuild plugin
  e2e/cases/module-federation-v2/host/rsbuild.config.ts
  e2e/cases/module-federation-v2/remote/rsbuild.config.ts
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#5201 fix(mf): allow to set `server.cors` with built-in MF plugin
  e2e/cases/module-federation/host/rsbuild.config.ts
  e2e/cases/module-federation/index.test.ts
  e2e/cases/module-federation/remote/rsbuild.config.ts
  packages/core/src/plugins/moduleFederation.ts
Labels: release: bug fix

#5202 feat: expose `defaultAllowedOrigins` from core
  e2e/cases/server/cors/index.test.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/tests/server.test.ts
  website/docs/en/config/server/cors.mdx
  website/docs/zh/config/server/cors.mdx
Labels: release: feature

#5204 feat: add `callerName` option to `createRsbuild`
  e2e/cases/javascript-api/caller-name/index.test.ts
  e2e/cases/javascript-api/caller-name/src/index.js
  packages/core/src/createContext.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/types/context.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: feature

#5209 feat: enhance sockWrite type to include 'static-changed'
  packages/core/src/server/socketServer.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
Labels: release: feature

#5211 feat(server): support for `server.sockWrite`
  e2e/cases/javascript-api/sock-write/index.test.ts
  e2e/cases/javascript-api/sock-write/src/index.js
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/socketServer.ts
  packages/core/src/types/config.ts
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
Labels: release: feature

#5213 docs: update dev server API documentation
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
Labels: release: document

#5216 feat: align tracing implementation with Rspack CLI
  .gitignore
  e2e/cases/rspack-profile/index.test.ts
  packages/core/src/plugins/rspackProfile.ts
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: feature

#5220 docs: remove incremental from build perf guide
  website/docs/en/guide/basic/upgrade-rsbuild.mdx
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/guide/basic/upgrade-rsbuild.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#5222 docs: correct default `buildDependencies`
  website/docs/en/config/performance/build-cache.mdx
  website/docs/zh/config/performance/build-cache.mdx
Labels: release: document

#5223 docs: discourage the use of rspack-chain for custom plugin options
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/guide/configuration/rspack.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/configuration/rspack.mdx
Labels: release: document

#5224 fix: failed to custom HTML plugin options via rspack-chain
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/html.test.ts.snap
Labels: release: bug fix

#5221 docs: update Rspack profile recommended value
  e2e/cases/rspack-profile/index.test.ts
  packages/core/src/plugins/rspackProfile.ts
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5228 docs: enhance buildDependencies section
  website/docs/en/config/performance/build-cache.mdx
  website/docs/zh/config/performance/build-cache.mdx
Labels: release: document

#5229 feat(deps): update @rspack/core to 1.3.10
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5230 feat: narrow Rspack configuration type for `tools.rspack`
  e2e/cases/config/configure-rspack/index.test.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config.ts
  packages/core/src/types/plugin.ts
  website/docs/en/config/source/exclude.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/config/source/exclude.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: release: feature

#5231 docs: add documentation for `afterListen` server method
  packages/core/src/server/devServer.ts
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
Labels: release: document

#5233 docs: fix Tailwind CSS optimization guidance link
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#5237 docs: fix typo in lightningcss-loader page
  website/docs/en/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
Labels: release: document

#5241 docs: improve description
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: document

#5242 docs: add close method for dev server API
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#5243 perf(cache): switch hash algorithm to SHA-256 and adjust output length
  packages/core/src/plugins/cache.ts
  packages/core/tests/__snapshots__/cache.test.ts.snap
Labels: release: performance

#5244 perf(hash): use `crypto.hash` in higher versions of Node
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/cache.ts
Labels: release: performance

#5247 docs: add available callerName values
  scripts/dictionary.txt
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#5251 docs: add Rstest to homepage
  pnpm-lock.yaml
  website/package.json
  website/theme/components/HomeFooter.tsx
  website/theme/components/ToolStack.tsx
Labels: release: document

#5253 docs: remove unused i18n config
  website/i18n.json
Labels: release: document

#5254 docs: fix overview page layout
  website/theme/components/Overview.module.scss
Labels: release: document

#5263 feat: normalize tsconfigPath in environment configuration
  packages/core/src/createContext.ts
  packages/core/src/provider/initConfigs.ts
Labels: release: feature

#5266 docs: enhance rsbuild.context with access methods
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#5267 docs: update `context.devServer` with examples
  packages/core/src/types/context.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#5268 fix: update rspackMinVersion to 1.2.4 for SRI support
  packages/core/src/helpers/index.ts
  packages/core/tests/rspackVersion.test.ts
Labels: release: bug fix

#5270 fix(plugin-svelte): should transpile JS code in .svelte files
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#5272 fix(plugin-svelte): transpile the Svelte package to downgrade the syntax
  packages/plugin-svelte/src/index.ts
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#5277 fix: narrow watchFiles type in normalized config
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: bug fix

#5278 feat: reload server when tsconfig.json is changed
  e2e/cases/alias/tsconfig-paths-reload/index.test.ts
  e2e/cases/alias/tsconfig-paths-reload/rsbuild.config.ts
  e2e/cases/alias/tsconfig-paths-reload/src/bar/test.ts
  e2e/cases/alias/tsconfig-paths-reload/src/foo/test.ts
  e2e/cases/alias/tsconfig-paths-reload/src/index.ts
  e2e/cases/alias/tsconfig-paths-reload/tsconfig.json
  e2e/cases/cli/build-watch-restart/index.test.ts
  e2e/cases/cli/build-watch/index.test.ts
  e2e/cases/cli/reload-config/index.test.ts
  e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts
  packages/core/src/provider/initConfigs.ts
Labels: release: feature

#5279 docs: update SWC React options type
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: document

#5280 docs: fix typo in `en/browserslist.mdx`
  website/docs/en/guide/advanced/browserslist.mdx
Labels: release: document

#5282 feat(deps): update Rspack to 1.3.11
  packages/core/package.json
  packages/core/tests/server.test.ts
  pnpm-lock.yaml
Labels: release: feature

#5281 docs: update Rstack introduction
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/community/index.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/zh/community/index.mdx
  website/docs/zh/guide/basic/web-workers.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#5289 docs: correct build profiling output
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5291 docs: template conditional statements usage
  pnpm-lock.yaml
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/guide/basic/html-template.mdx
  website/rspress.config.ts
Labels: release: document

#5293 fix: add warning for modifying plugins in `modifyRsbuildConfig`
  packages/core/src/provider/initConfigs.ts
Labels: release: bug fix

#5294 feat: enhance error messages with color for better visibility
  packages/core/src/createRsbuild.ts
  packages/core/src/helpers/index.ts
  packages/core/src/initPlugins.ts
  packages/core/src/loadConfig.ts
  packages/core/src/loadEnv.ts
  packages/core/src/pluginManager.ts
  packages/core/src/plugins/appIcon.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/define.ts
  packages/core/src/plugins/entry.ts
  packages/core/src/plugins/html.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/plugins/nodeAddons.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/plugins/swc.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/environment.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/open.ts
  packages/core/src/server/runner/basic.ts
  packages/core/src/server/runner/esm.ts
  packages/core/src/server/runner/index.ts
  packages/core/src/types/plugin.ts
Labels: release: feature

#5295 docs: update inlineScripts and inlineStyles
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/en/config/output/inline-styles.mdx
  website/docs/zh/config/output/inline-scripts.mdx
  website/docs/zh/config/output/inline-styles.mdx
Labels: release: document

#5298 docs: update `output.copy` examples
  website/docs/en/config/output/copy.mdx
  website/docs/zh/config/output/copy.mdx
Labels: release: document

#5299 docs: improve build profiling with additional tips
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5300 docs(rspress): use @rspress/plugin-algolia for search
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
  website/theme/index.tsx
Labels: release: document

#5301 docs: clarify default minification options
  packages/core/src/types/config.ts
  website/docs/en/config/output/minify.mdx
  website/docs/zh/config/output/minify.mdx
Labels: release: document

#5304 feat: allow CLI shortcuts help option to accept custom string
  packages/core/src/server/cliShortcuts.ts
  packages/core/src/types/config.ts
  website/docs/en/config/dev/cli-shortcuts.mdx
  website/docs/zh/config/dev/cli-shortcuts.mdx
Labels: release: feature

#5307 perf: use dynamic imports for exec and promisify
  packages/core/src/server/open.ts
Labels: release: performance

#5312 perf: use dynamic import for node:dns
  packages/core/src/server/helper.ts
  packages/core/src/server/hmrFallback.ts
Labels: release: performance

#5314 perf: use dynamic imports for node:net
  packages/core/src/server/devServer.ts
  packages/core/src/server/helper.ts
  packages/core/src/server/open.ts
  packages/core/src/server/prodServer.ts
Labels: release: performance

#5315 feat: allow to enable minify in development mode
  e2e/cases/minify/css-minify-always/index.test.ts
  e2e/cases/minify/css-minify-always/src/index.css
  e2e/cases/minify/css-minify-always/src/index.js
  e2e/cases/minify/css-minify-inherit/index.test.ts
  e2e/cases/minify/css-minify-inherit/rsbuild.config.ts
  e2e/cases/minify/css-minify-inherit/src/index.css
  e2e/cases/minify/css-minify-inherit/src/index.js
  e2e/cases/minify/css-minify-options/index.test.ts
  e2e/cases/minify/css-minify-options/rsbuild.config.ts
  e2e/cases/minify/css-minify-options/src/index.css
  e2e/cases/minify/css-minify-options/src/index.js
  e2e/cases/minify/css-minify/index.test.ts
  e2e/cases/minify/css-minify/src/index.css
  e2e/cases/minify/css-minify/src/index.js
  e2e/cases/minify/js-minify-always/index.test.ts
  e2e/cases/minify/js-minify-always/src/index.js
  packages/compat/plugin-webpack-swc/src/plugin.ts
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/minimize.ts
  packages/core/src/types/config.ts
  packages/core/tests/minimize.test.ts
  website/docs/en/config/output/minify.mdx
  website/docs/zh/config/output/minify.mdx
Labels: release: feature

#5316 feat(deps): update @rspack/core to v1.3.12
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5318 docs: update Rslib website URL
  pnpm-lock.yaml
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/package.json
  website/theme/components/HomeFooter.tsx
Labels: release: document

#5321 fix: display gzip size for markdown files
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#5326 docs: fix inaccurate expression in import wasm module
  website/docs/en/guide/basic/wasm-assets.mdx
  website/docs/zh/guide/basic/wasm-assets.mdx
Labels: release: document

#5325 fix: avoid colon in output config file name
  packages/core/src/inspectConfig.ts
Labels: release: bug fix

#5330 docs: SSR-specific plugins
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/zh/guide/advanced/ssr.mdx
Labels: release: document

#5331 docs: enable domain redirection
  website/docs/public/netlify.toml
Labels: release: document

#5333 docs: fix invalid browserslist query example
  website/docs/en/guide/advanced/browserslist.mdx
Labels: release: document

#5335 docs: clarify methods to access environment context
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
Labels: release: document

#5337 docs: enhance HTML generation for source.entry
  packages/core/src/types/config.ts
  website/docs/en/config/source/entry.mdx
  website/docs/en/guide/basic/html-template.mdx
  website/docs/zh/config/source/entry.mdx
  website/docs/zh/config/tools/html-plugin.mdx
  website/docs/zh/guide/basic/html-template.mdx
Labels: release: document
