Repository web-infra-dev/rsbuild, pull requests merged in 2025-09, with the labels that each got.

#6027 docs(config): update externals documentation with axios example
  website/docs/en/config/output/externals.mdx
  website/docs/zh/config/output/externals.mdx
Labels: release: document

#6034 fix: improve error message for public directory copy failure
  packages/core/src/plugins/server.ts
Labels: release: bug fix

#6043 feat: enable inline const optimization by default
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#6047 fix(hmr): reset reconnect count when connection is established
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#6048 fix(client): prevent duplicate console logs during reconnection
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#6053 docs: add HMR workaround for vanilla-extract-css plugin
  website/docs/en/guide/styling/css-in-js.mdx
  website/docs/zh/guide/styling/css-in-js.mdx
Labels: release: document

#6054 docs: setup the AGENTS.md file
  .github/copilot-instructions.md
  AGENTS.md
Labels: release: document

#6070 docs: add native watcher example to build perf guide
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#6073 fix(server): prints correct urls when configuring web and node environments
  e2e/cases/server/print-urls/index.test.ts
  e2e/cases/server/print-urls/src/index.js
  e2e/helper/logs.ts
  packages/core/src/server/helper.ts
  packages/core/tests/helpers.test.ts
Labels: release: bug fix

#6080 docs: update JSDoc comments for Rsbuild configuration options
  packages/core/src/types/config.ts
Labels: release: document

#6083 docs(config): clarify HTTP/2 behavior
  website/docs/en/config/server/https.mdx
  website/docs/zh/config/server/https.mdx
Labels: release: document

#6085 docs: improve wording in docs
  website/docs/en/config/output/inject-styles.mdx
  website/docs/en/config/server/cors.mdx
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/en/shared/getNormalizedConfig.mdx
Labels: release: document, codex

#6094 perf: lazy loading memfs dependency
  packages/core/prebundle.config.mjs
  packages/core/src/dev-middleware/index.ts
  packages/core/src/dev-middleware/middleware.ts
  packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts
  packages/core/src/server/compilationMiddleware.ts
Labels: release: performance

#6099 refactor(dev-middleware): clean up code by removing redundant type casts
  packages/core/src/dev-middleware/index.ts
  packages/core/src/dev-middleware/middleware.ts
  packages/core/src/dev-middleware/utils/escapeHtml.ts
  packages/core/src/dev-middleware/utils/getFilenameFromUrl.ts
  packages/core/src/dev-middleware/utils/memorize.ts
  packages/core/src/dev-middleware/utils/setupHooks.ts
  packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts
  packages/core/src/dev-middleware/utils/setupWriteToDisk.ts
  rslint.json
Labels: release: refactor

#6071 docs: add zephyr to docs page
  website/docs/en/guide/basic/static-deploy.mdx
Labels: release: document

#6116 docs: add documentation for environment context parameter
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/rspack.mdx
Labels: release: document

#6147 feat: add support for `resolve.conditionNames` configuration
  e2e/cases/resolve/condition-names/index.test.ts
  e2e/cases/resolve/condition-names/package-foo/custom.js
  e2e/cases/resolve/condition-names/package-foo/import.js
  e2e/cases/resolve/condition-names/package-foo/package.json
  e2e/cases/resolve/condition-names/package-foo/require.js
  e2e/cases/resolve/condition-names/src/index.js
  e2e/cases/resolve/extensions/tsconfig.json
  packages/core/src/mergeConfig.ts
  packages/core/src/plugins/resolve.ts
  packages/core/src/types/config.ts
Labels: release: feature

#6154 feat: re-enable enum inlining optimization in production
  e2e/cases/syntax-ts/const-enum/index.test.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/swc.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
Labels: release: feature

#6161 refactor(dev-middleware): simplify compiler handling
  packages/core/src/dev-middleware/index.ts
  packages/core/src/dev-middleware/middleware.ts
  packages/core/src/dev-middleware/utils/getFilenameFromUrl.ts
  packages/core/src/dev-middleware/utils/getPaths.ts
  packages/core/src/dev-middleware/utils/setupHooks.ts
  packages/core/src/dev-middleware/utils/setupOutputFileSystem.ts
  packages/core/src/dev-middleware/utils/setupWriteToDisk.ts
Labels: release: refactor

#6166 fix(types): correct ProxyConfig type definition
  packages/core/src/types/config.ts
  website/docs/en/config/server/proxy.mdx
  website/docs/zh/config/server/proxy.mdx
Labels: release: bug fix

#6169 feat(deps): update dependency @rspack/core to v1.5.5
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#6179 fix: temporarily disable const inlining optimization
  e2e/cases/optimization/inline-const/index.test.ts
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/basic.ts
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
Labels: release: bug fix

#6182 fix(types): update `ImportMetaEnv` interface to use Record
  packages/core/types.d.ts
Labels: release: bug fix

#6192 fix: correct initial chunks order in generated manifest
  packages/core/package.json
  packages/core/src/plugins/manifest.ts
  pnpm-lock.yaml
Labels: release: bug fix

#6200 docs: configuring output directories for multi-env builds
  website/docs/en/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: release: document

#6208 fix(CLI): CLI does not work without sub-command
  e2e/cases/cli/build/index.test.ts
  e2e/cases/cli/build/src/index.js
  e2e/cases/cli/dev/index.test.ts
  e2e/cases/cli/dev/src/index.js
  packages/core/src/cli/commands.ts
Labels: release: bug fix

#6210 fix(cli): improve version log when displaying help
  packages/core/src/cli/commands.ts
  packages/core/src/cli/index.ts
Labels: release: bug fix

#6211 feat(cli): improve help output formatting
  packages/core/src/cli/commands.ts
  packages/core/src/cli/index.ts
Labels: release: feature

#6219 fix: always output all logs in debug mode
  e2e/cases/cli/log-level/index.test.ts
  packages/core/src/cli/index.ts
  packages/core/src/createRsbuild.ts
  website/docs/en/config/log-level.mdx
  website/docs/zh/config/log-level.mdx
Labels: release: bug fix

#6235 fix(dev-middleware): remove unnecessary debug logs
  packages/core/src/dev-middleware/middleware.ts
  packages/core/src/dev-middleware/utils/ready.ts
  packages/core/src/dev-middleware/utils/setupWriteToDisk.ts
Labels: release: bug fix

#6238 feat(deps): update dependency @rspack/core to v1.5.7
  packages/core/package.json
  packages/core/src/provider/createCompiler.ts
  pnpm-lock.yaml
Labels: release: feature

#6240 feat(plugin-react): complete `preserve` React runtime
  packages/plugin-react/src/react.ts
  packages/plugin-react/tests/__snapshots__/index.test.ts.snap
  packages/plugin-react/tests/index.test.ts
Labels: release: feature

#6251 feat: display browser runtime errors in the terminal
  packages/core/src/client/hmr.ts
  packages/core/src/server/socketServer.ts
Labels: release: feature

#6253 feat: add `dev.browserLogs` configuration
  e2e/cases/server/browser-logs/index.test.ts
  packages/core/src/client/hmr.ts
  packages/core/src/defaultConfig.ts
  packages/core/src/env.d.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/server/compilationMiddleware.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
Labels: release: feature

#6257 refactor: extract server assets middleware
  packages/core/src/dev-middleware/index.ts
  packages/core/src/dev-middleware/utils/ready.ts
  packages/core/src/server/assets-middleware/escapeHtml.ts
  packages/core/src/server/assets-middleware/getFilenameFromUrl.ts
  packages/core/src/server/assets-middleware/getPaths.ts
  packages/core/src/server/assets-middleware/index.ts
  packages/core/src/server/assets-middleware/memorize.ts
  packages/core/src/server/assets-middleware/middleware.ts
  packages/core/src/server/assets-middleware/parseTokenList.ts
  packages/core/src/server/assets-middleware/setupHooks.ts
  packages/core/src/server/assets-middleware/setupOutputFileSystem.ts
  packages/core/src/server/assets-middleware/setupWriteToDisk.ts
  packages/core/src/server/buildManager.ts
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/watchFiles.ts
  packages/core/tests/server.test.ts
Labels: release: refactor

#6259 refactor(server): make filename helper independent of assets middleware context
  packages/core/src/server/assets-middleware/getFilenameFromUrl.ts
  packages/core/src/server/assets-middleware/index.ts
  packages/core/src/server/assets-middleware/middleware.ts
  packages/core/src/server/assets-middleware/setupHooks.ts
  packages/core/src/server/assets-middleware/setupOutputFileSystem.ts
  packages/core/src/server/assets-middleware/setupWriteToDisk.ts
  packages/core/src/server/buildManager.ts
Labels: release: refactor

#6261 fix(browser-logs): should skip anonymous frame
  e2e/cases/browser-logs/basic-error/index.test.ts
  e2e/cases/browser-logs/basic-error/src/index.js
  e2e/cases/browser-logs/react-error/index.test.ts
  e2e/cases/browser-logs/react-error/rsbuild.config.ts
  e2e/cases/browser-logs/react-error/src/effectError.jsx
  e2e/cases/browser-logs/react-error/src/eventError.jsx
  e2e/cases/browser-logs/react-error/src/undefinedError.jsx
  packages/core/src/server/browserLogs.ts
Labels: release: bug fix

#6263 fix(browser-logs): deduplicate consecutive runtime error logs
  e2e/cases/browser-logs/dedupe-log/index.test.ts
  e2e/cases/browser-logs/dedupe-log/src/index.js
  e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts
  e2e/helper/utils.ts
  packages/core/src/server/browserLogs.ts
Labels: release: bug fix

#6264 fix: skip browser error reporting for webpack
  e2e/cases/browser-logs/basic-error/index.test.ts
  e2e/cases/browser-logs/dedupe-log/index.test.ts
  e2e/cases/browser-logs/unhandled-rejection/index.test.ts
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#6266 refactor: simplify variable naming in HMR client
  packages/core/src/client/hmr.ts
Labels: release: refactor

#6269 refactor(assets-middleware): simplify context management
  packages/core/src/server/assets-middleware/index.ts
  packages/core/src/server/assets-middleware/middleware.ts
  packages/core/src/server/assets-middleware/setupHooks.ts
  packages/core/src/server/buildManager.ts
Labels: release: refactor

#6270 fix: skip browser error logs when build fails
  .prettierignore
  biome.json
  e2e/cases/browser-logs/skip-build-error/index.test.ts
  e2e/cases/browser-logs/skip-build-error/src/index.js
  packages/core/src/server/socketServer.ts
Labels: release: bug fix

#6272 fix: mark custom compiler option as deprecated
  packages/core/src/types/rsbuild.ts
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: bug fix

#6274 perf: optimize module resolution of compiled packages
  packages/core/prebundle.config.mjs
  packages/plugin-babel/prebundle.config.mjs
Labels: release: performance

#6279 docs: update type checking guide with tsc/vue-tsc
  website/docs/en/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: document

#6281 fix: prioritize custom file path in error logs
  packages/core/src/helpers/format.ts
Labels: release: bug fix

#6287 docs: add dev.browserLogs config
  packages/core/src/types/config.ts
  website/docs/en/config/dev/browser-logs.mdx
  website/docs/zh/config/dev/browser-logs.mdx
Labels: release: document

#6288 refactor: simplify stats error formatting logic
  packages/core/src/helpers/format.ts
  packages/core/src/helpers/stats.ts
  packages/core/src/server/socketServer.ts
Labels: release: refactor

#6290 feat(core): improve module trace formatting in error messages
  e2e/cases/config/stats-module-trace/index.test.ts
  e2e/cases/config/stats-module-trace/src/index.tsx
  e2e/cases/config/stats-module-trace/src/test.tsx
  e2e/cases/diagnostic/import-traces/index.test.ts
  e2e/cases/diagnostic/import-traces/src/child1.js
  e2e/cases/diagnostic/import-traces/src/child2.js
  e2e/cases/diagnostic/import-traces/src/child3.js
  e2e/cases/diagnostic/import-traces/src/index.js
  e2e/cases/diagnostic/node-polyfill-tip-with-protocol/index.test.ts
  e2e/cases/diagnostic/node-polyfill-tip-with-protocol/src/index.js
  e2e/cases/diagnostic/node-polyfill-tip-without-protocol/index.test.ts
  e2e/cases/diagnostic/node-polyfill-tip-without-protocol/src/index.js
  packages/core/src/helpers/format.ts
Labels: release: feature
