Repository web-infra-dev/rsbuild, pull requests merged in 2025-01, with the labels that each got.

#4308 fix: correct extension alias order to align with Node.js
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/plugins/resolve.ts
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/plugin-svelte/tests/__snapshots__/index.test.ts.snap
  website/docs/en/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/typescript.mdx
Labels: release: bug fix

#4313 fix(asset-retry): avoid using function rest parameters
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
Labels: release: bug fix

#4316 docs: correct tips in filename.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: document

#4312 perf(asets-retry): use SWC to transform and minify code
  packages/plugin-assets-retry/package.json
  packages/plugin-assets-retry/scripts/postCompile.mjs
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/runtime.d.ts
  pnpm-lock.yaml
Labels: release: performance

#4320 perf(assets-retry): normalize options on the server side
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: release: performance

#4321 fix: no need to use extensionAlias when using jsconfig.json
  packages/core/src/plugins/resolve.ts
Labels: release: bug fix

#4322 docs: add `@ng-rsbuild/plugin-angular` to plugins list
  website/docs/en/plugins/list/index.mdx
  website/docs/zh/plugins/list/index.mdx
Labels: release: document

#4323 docs: update banner image
  README.md
  README.pt-BR.md
  README.zh-CN.md
  packages/compat/plugin-webpack-swc/README.md
  packages/compat/webpack/README.md
  packages/core/README.md
  packages/create-rsbuild/README.md
  packages/plugin-assets-retry/README.md
  packages/plugin-babel/README.md
  packages/plugin-less/README.md
  packages/plugin-preact/README.md
  packages/plugin-react/README.md
  packages/plugin-sass/README.md
  packages/plugin-solid/README.md
  packages/plugin-stylus/README.md
  packages/plugin-svelte/README.md
  packages/plugin-svgr/README.md
  packages/plugin-vue/README.md
  scripts/test-helper/README.md
Labels: release: document

#4324 docs: update community page
  website/docs/en/community/index.mdx
  website/docs/zh/community/index.mdx
Labels: release: document

#4315 fix(plugin/assets-retry): addQuery and switchDomain should work in async css chunk
  e2e/cases/assets/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  scripts/dictionary.txt
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: release: bug fix

#4325 perf(assets-retry): reduce nullish coalescing operator
  e2e/cases/assets/assets-retry/index.test.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: release: performance

#4326 perf(assets-retry): use shorter namespace prefix
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
Labels: release: performance

#4327 feat: treat `.cur` as image assets
  packages/compat/webpack/tests/__snapshots__/default.test.ts.snap
  packages/core/src/constants.ts
  packages/core/tests/__snapshots__/asset.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/types.d.ts
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
Labels: release: feature

#4329 feat: export some useful types
  packages/core/src/hooks.ts
  packages/core/src/index.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
Labels: release: feature

#4337 feat(deps): bump Rspack 1.2.0-beta.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4340 docs: only generate stats.json
  website/docs/en/config/performance/bundle-analyze.mdx
  website/docs/zh/config/performance/bundle-analyze.mdx
Labels: release: document

#4343 docs: optimize Tailwind CSS build performance
  website/docs/en/guide/basic/tailwindcss.mdx
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/guide/basic/tailwindcss.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#4347 fix: deprecation warning when using proxy with Node 22
  package.json
  patches/http-proxy@1.18.1.patch
  pnpm-lock.yaml
Labels: release: bug fix

#4351 docs: tip decorators version differences
  website/docs/en/config/source/decorators.mdx
  website/docs/zh/config/source/decorators.mdx
Labels: release: document

#4354 feat: add `issuer` and `with` options to `api.transform`
  e2e/cases/plugin-api/plugin-transform-import-attributes/index.test.ts
  e2e/cases/plugin-api/plugin-transform-import-attributes/myPlugin.ts
  e2e/cases/plugin-api/plugin-transform-import-attributes/rsbuild.config.ts
  e2e/cases/plugin-api/plugin-transform-import-attributes/src/index.js
  e2e/cases/plugin-api/plugin-transform-import-attributes/src/pkg-1.json
  packages/core/src/initPlugins.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#4355 docs: correct some cases
  CODE_OF_CONDUCT.md
  README.md
  website/docs/en/community/releases/v1-0.mdx
  website/docs/en/guide/start/index.mdx
  website/i18n.json
Labels: release: document

#4358 docs: babel migration guide
  website/docs/en/guide/migration/webpack.mdx
  website/docs/zh/guide/migration/webpack.mdx
Labels: release: document

#4360 docs: clarity`include` and `exclude` usages
  website/docs/en/config/source/exclude.mdx
  website/docs/en/config/source/include.mdx
  website/docs/en/guide/basic/configure-swc.mdx
  website/docs/zh/config/source/exclude.mdx
  website/docs/zh/config/source/include.mdx
  website/docs/zh/guide/basic/configure-swc.mdx
Labels: release: document

#4364 docs: update PostCSS guide
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/css-usage.mdx
Labels: release: document

#4369 docs: call api.getNormalizedConfig in correct hook
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: document

#4370 docs: add asynchronous entry configuration example
  website/docs/en/config/source/entry.mdx
  website/docs/zh/config/source/entry.mdx
Labels: release: document

#4372 docs: clarify `swcReactOptions.refresh` option
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
Labels: release: document

#4375 feat: add `cleanDistPath.keep` config
  e2e/cases/output/clean-dist-path/index.test.ts
  packages/core/src/helpers/fs.ts
  packages/core/src/index.ts
  packages/core/src/plugins/cleanOutput.ts
  packages/core/src/types/config.ts
Labels: release: feature

#4381 docs: add options for cleanDistPath
  packages/core/src/types/config.ts
  website/docs/en/config/output/clean-dist-path.mdx
  website/docs/en/config/source/include.mdx
  website/docs/zh/config/output/clean-dist-path.mdx
  website/docs/zh/config/source/include.mdx
Labels: release: document

#4384 docs: Svelte v5 HMR tip
  website/docs/en/guide/framework/svelte.mdx
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/zh/guide/framework/svelte.mdx
  website/docs/zh/plugins/list/plugin-svelte.mdx
Labels: release: document

#4386 docs: correct typo in multi-env title
  website/docs/en/guide/advanced/environments.mdx
Labels: release: document

#4390 feat: optimize `cleanDistPath.keep` RegExp
  e2e/cases/output/clean-dist-path/index.test.ts
  packages/core/src/helpers/fs.ts
  packages/core/src/helpers/path.ts
  packages/core/src/plugins/basic.ts
  website/docs/en/config/output/clean-dist-path.mdx
  website/docs/zh/config/output/clean-dist-path.mdx
Labels: release: feature

#4392 fix: let lightningcss minimizer inherit loader options
  e2e/cases/css/css-minify-inherit/index.test.ts
  e2e/cases/css/css-minify-inherit/rsbuild.config.ts
  e2e/cases/css/css-minify-inherit/src/index.css
  e2e/cases/css/css-minify-inherit/src/index.js
  packages/core/src/plugins/css.ts
  packages/core/src/plugins/minimize.ts
  website/docs/en/config/output/minify.mdx
  website/docs/zh/config/output/minify.mdx
Labels: release: bug fix

#4389 feat(plugin-sass): add `useOriginalUrlResolver` option to disable `resolve-url-loader`
  packages/plugin-sass/src/index.ts
  packages/plugin-sass/src/types.ts
  website/docs/en/plugins/list/plugin-sass.mdx
Labels: release: feature

#4385 fix(core): `output.assetsInclude` adds a rule but not exposes public api
  packages/core/src/configChain.ts
  packages/core/src/plugins/asset.ts
Labels: release: bug fix

#4399 fix!: disable `server.cors` by default for security reasons
  e2e/cases/server/cors/index.test.ts
  packages/core/src/config.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/config/server/cors.mdx
  website/docs/zh/config/server/cors.mdx
Labels: release: bug fix

#4401 docs(plugin-sass): improve `rewriteUrls` option
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
Labels: release: document

#4406 feat(deps): bump Rspack v1.2.0
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4412 docs(javascript-api): fix defineConfig parameters
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: document

#4413 docs(javascript-api): fix defineConfig parameters in English documentation
  website/docs/en/api/javascript-api/core.mdx
Labels: release: document

#4416 feat(deps): bump Rspack v1.2.1
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4415 feat: add support for additional entry file extensions (mts, cts)
  packages/core/src/config.ts
  packages/core/src/plugins/entry.ts
  website/docs/en/config/source/entry.mdx
  website/docs/zh/config/source/entry.mdx
Labels: release: feature

#4419 fix(deps): bump Rspack v1.2.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4426 feat: support for `resolve` and `context` in `api.transform`
  packages/core/src/loader/transformLoader.ts
  packages/core/src/types/plugin.ts
  website/docs/en/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/core.mdx
Labels: release: feature

#4431 feat: warn when using Rspack devServer config
  packages/core/src/provider/rspackConfig.ts
Labels: release: feature

#4437 fix(core): failed to register environment plugin
  e2e/cases/stylus/basic/index.test.ts
  e2e/cases/stylus/basic/rsbuild.config.ts
  e2e/cases/stylus/environment/index.test.ts
  e2e/cases/stylus/environment/rsbuild.config.ts
  e2e/cases/stylus/environment/src/a.styl
  e2e/cases/stylus/environment/src/b.module.styl
  e2e/cases/stylus/environment/src/index.js
  e2e/cases/stylus/rem/index.test.ts
  e2e/cases/stylus/rem/rsbuild.config.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/initPlugins.ts
Labels: release: bug fix

#4425 docs: Revise TailwindCSS installation and configuration guide for v4
  website/docs/en/guide/basic/tailwindcss.mdx
Labels: release: document

#4441 docs: remove v1 announcement
  website/theme/index.tsx
Labels: release: document

#4442 docs: provides guides for both Tailwind CSS v3 and v4
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/tailwindcss-v3.mdx
  website/docs/en/guide/basic/tailwindcss.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/tailwindcss-v3.mdx
  website/docs/zh/guide/basic/tailwindcss.mdx
Labels: release: document

#4445 fix(plugin-sass): allow to disable source map
  packages/plugin-sass/src/index.ts
Labels: release: bug fix

#4450 docs: polish README files
  README.md
  README.pt-BR.md
  README.zh-CN.md
  e2e/README.md
  e2e/cases/config/configure-webpack/index.test.ts
  packages/compat/webpack/README.md
  packages/compat/webpack/src/plugin.ts
  packages/core/src/pluginManager.ts
  packages/core/src/types/plugin.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  website/docs/en/community/releases/v0-1.mdx
  website/docs/en/config/plugins.mdx
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/en/guide/migration/modern-builder.mdx
  website/docs/en/guide/migration/vue-cli.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/community/releases/v0-1.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/guide/basic/server.mdx
  website/docs/zh/guide/migration/modern-builder.mdx
  website/docs/zh/guide/migration/vue-cli.mdx
  website/docs/zh/guide/start/index.mdx
  website/docs/zh/plugins/dev/index.mdx
  website/theme/components/Benchmark.tsx
Labels: release: document

#4452 docs: add dev server writeToDisk config mapping
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#4454 docs: improve historyApiFallback and htmlFallback documentation
  website/docs/en/config/server/history-api-fallback.mdx
  website/docs/en/config/server/html-fallback.mdx
  website/docs/zh/config/server/history-api-fallback.mdx
  website/docs/zh/config/server/html-fallback.mdx
Labels: release: document

#4456 fix: allow to only generate source map for CSS files
  e2e/cases/output/source-map/index.test.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/hooks.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: bug fix

#4464 docs: correct onCloseDevServer example
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document
