Repository web-infra-dev/rsbuild, pull requests merged in 2025-02, with the labels that each got.

#4469 docs: fix return value of `rsbuild.rspackConfigs()`
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#4472 docs: improve documentation language and clarity
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/community/releases/v0-6.mdx
  website/docs/en/config/dev/client.mdx
  website/docs/en/config/dev/live-reload.mdx
  website/docs/en/config/dev/progress-bar.mdx
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/en/config/output/inline-styles.mdx
  website/docs/en/config/performance/chunk-split.mdx
  website/docs/en/config/resolve/alias.mdx
  website/docs/en/config/server/compress.mdx
  website/docs/en/config/server/proxy.mdx
  website/docs/en/config/source/entry.mdx
  website/docs/en/config/tools/css-loader.mdx
  website/docs/en/config/tools/html-plugin.mdx
  website/docs/en/config/tools/postcss.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/advanced/hmr.mdx
  website/docs/en/guide/basic/css-usage.mdx
  website/docs/en/guide/basic/html-template.mdx
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/basic/tailwindcss-v3.mdx
  website/docs/en/guide/debug/rsdoctor.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/framework/vue.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/en/guide/optimization/optimize-bundle.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/plugins/list/plugin-less.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/en/plugins/list/plugin-sass.mdx
  website/docs/en/plugins/list/plugin-solid.mdx
  website/docs/en/plugins/list/plugin-stylus.mdx
  website/docs/en/plugins/list/plugin-svelte.mdx
  website/docs/en/plugins/list/plugin-svgr.mdx
  website/docs/en/plugins/list/plugin-vue.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/config/dev/live-reload.mdx
  website/docs/zh/guide/advanced/environments.mdx
Labels: release: document

#4473 docs: enhance legal comments configuration documentation
  website/docs/en/config/output/legal-comments.mdx
  website/docs/zh/config/output/legal-comments.mdx
Labels: release: document

#4477 docs: set Open Graph images based on page routes
  website/rspress.config.ts
Labels: release: document

#4478 feat: allow `proxy.bypass` to be an async function
  packages/core/src/index.ts
  packages/core/src/server/proxy.ts
  packages/core/src/types/config.ts
  website/docs/en/config/server/proxy.mdx
  website/docs/zh/config/server/proxy.mdx
Labels: release: feature

#4474 feat: direct ws connection fallback
  packages/core/src/client/hmr.ts
  packages/core/src/env.d.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/devMiddleware.ts
  packages/core/src/server/hmrFallback.ts
Labels: release: feature

#4482 fix(hmr): avoid duplicated connection
  packages/core/src/client/hmr.ts
Labels: release: bug fix

#4483 docs: update rspress 1.41.0 and enable codeBlocks search
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
Labels: release: document

#4485 docs: improve CLI doc structure and add common flags section
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: document

#4488 docs: add Bluesky social link
  website/rspress.config.ts
Labels: release: document

#4486 feat: native runtime support for loading config
  e2e/cases/cli/config-loader/index.test.ts
  e2e/cases/cli/config-loader/rsbuild.config.mts
  e2e/cases/cli/config-loader/src/index.js
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  packages/core/src/config.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/zh/api/javascript-api/core.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/configure-rsbuild.mdx
Labels: release: feature

#4492 feat(CLI): add `--base` flag
  e2e/cases/cli/base/index.test.ts
  e2e/cases/cli/base/src/index.ts
  e2e/cases/cli/base/tsconfig.json
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#4493 fix: validate `server.base` config
  packages/core/src/config.ts
  packages/core/src/provider/initConfigs.ts
Labels: release: bug fix

#4495 fix: skip clean in dev mode when writeToDisk is false
  e2e/cases/output/clean-dist-path/index.test.ts
  packages/core/src/plugins/cleanOutput.ts
  website/docs/en/config/output/clean-dist-path.mdx
  website/docs/zh/config/output/clean-dist-path.mdx
Labels: release: bug fix

#4502 docs: fix grammar in Rsbuild description
  README.md
  website/docs/en/guide/start/index.mdx
Labels: release: document

#4501 feat: support for Rspack persistent cache
  e2e/cases/cache/index.test.ts
  e2e/cases/cache/src/a.test.js
  packages/core/src/config.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/cache.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/cache.test.ts
  packages/plugin-babel/src/plugin.ts
Labels: release: feature

#4504 fix(core): modifying the dev.watchFiles config in plugins is not effective
  packages/core/src/cli/init.ts
Labels: release: bug fix

#4505 fix(cache): error handling for buildDependencies JSON parsing
  packages/core/src/plugins/cache.ts
Labels: release: bug fix

#4507 fix(cache): only validate buildDependencies for webpack
  e2e/cases/cache/index.test.ts
  packages/core/src/plugins/cache.ts
Labels: release: bug fix

#4509 docs: fix missing admonition end indicator on inline-assets doc
  website/docs/en/guide/optimization/inline-assets.mdx
Labels: release: document

#4510 docs: add guide for incremental build
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#4512 fix: failed to use native config loader on Windows
  e2e/cases/cli/config-loader/index.test.ts
  packages/core/src/config.ts
Labels: release: bug fix

#4511 feat(cache): add experimental cache logging
  packages/core/src/plugins/cache.ts
Labels: release: feature

#4514 fix: failed to load Rsdoctor package on Windows
  e2e/cases/rsdoctor/index.test.ts
  e2e/cases/rsdoctor/mock/index.cjs
  e2e/cases/rsdoctor/mock/package.json
  e2e/package.json
  packages/core/src/plugins/rsdoctor.ts
  pnpm-lock.yaml
Labels: release: bug fix

#4518 docs: access HTML plugin in `modifyRspackConfig`
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/en/config/tools/rspack.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/theme/index.scss
Labels: release: document

#4520 docs: add `performance.buildCache` configuration
  packages/core/src/types/config.ts
  website/docs/en/config/performance/build-cache.mdx
  website/docs/en/guide/optimization/build-performance.mdx
  website/docs/zh/config/performance/build-cache.mdx
  website/docs/zh/guide/optimization/build-performance.mdx
Labels: release: document

#4525 docs: enhance performance section across README files
  README.md
  README.pt-BR.md
  README.zh-CN.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: release: document

#4526 docs: update rspack profile tips
  e2e/cases/rspack-profile/dev.mjs
  e2e/cases/rspack-profile/index.test.ts
  e2e/cases/rspack-profile/src/index.js
  e2e/scripts/helper.ts
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#4529 perf: skip gzip size calculation for non-compressible assets
  e2e/cases/assets/assets-url/index.test.ts
  e2e/cases/assets/assets-url/rsbuild.config.ts
  e2e/cases/assets/assets-url/src/App.jsx
  e2e/cases/print-file-size/basic/index.test.ts
  e2e/cases/print-file-size/basic/src/App.jsx
  packages/core/src/plugins/fileSize.ts
Labels: release: performance

#4530 feat(deps): update Rspack to v1.2.3
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4535 docs: display GitHub button on homepage
  pnpm-lock.yaml
  website/package.json
  website/theme/components/Hero.tsx
Labels: release: document

#4538 docs: update homepage i18n text
  pnpm-lock.yaml
  website/i18n.json
  website/package.json
  website/theme/components/Features.module.scss
  website/theme/components/Features.tsx
  website/theme/components/Hero.tsx
  website/theme/pages/index.tsx
Labels: release: document

#4539 fix: gzipped total file size calculation
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: bug fix

#4542 feat: exclude `.d.ts` files from file size reporting
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#4544 docs: improve static assets docs with inline and URL query examples
  website/docs/en/guide/basic/static-assets.mdx
  website/docs/en/guide/optimization/inline-assets.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/optimization/inline-assets.mdx
Labels: release: document

#4540 feat: support `buildCache.buildDependencies` configuration
  e2e/cases/cache/index.test.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/build-cache.mdx
  website/docs/zh/config/performance/build-cache.mdx
Labels: release: feature

#4550 docs: JSDoc for Rsbuild plugin API
  packages/core/src/createRsbuild.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/rsbuild.ts
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onAfterEnvironmentCompile.mdx
  website/docs/en/shared/onBeforeEnvironmentCompile.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#4555 feat: support generate preload link with duplicate
  e2e/cases/performance/resource-hints/index.test.ts
  packages/core/src/rspack/preload/HtmlPreloadOrPrefetchPlugin.ts
  packages/core/src/rspack/preload/helpers/doesChunkBelongToHtml.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: release: feature

#4559 feat: expose dev server instance for `onBeforeStartDevServer` hook
  e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts
  e2e/cases/plugin-api/plugin-before-start-dev-server-hook/src/index.js
  e2e/cases/server/setup-middlewares/index.test.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/watchFiles.ts
  packages/core/src/types/hooks.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onBeforeStartDevServer.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onBeforeStartDevServer.mdx
Labels: release: feature

#4560 docs: simplify plugin setup method
  e2e/cases/server/preview/index.test.ts
  packages/compat/webpack/tests/default.test.ts
  packages/core/tests/default.test.ts
  packages/core/tests/environments.test.ts
  website/docs/en/community/releases/v0-4.mdx
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/plugins/dev/core.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/plugins/dev/index.mdx
  website/docs/zh/community/releases/v0-4.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#4536 fix(server): remove `.mjs` suffix check when loading ESM module in runner
  e2e/cases/server/ssr-type-module/index.test.ts
  e2e/cases/server/ssr-type-module/package.json
  e2e/cases/server/ssr-type-module/rsbuild.config.ts
  e2e/cases/server/ssr-type-module/src/App.css
  e2e/cases/server/ssr-type-module/src/App.tsx
  e2e/cases/server/ssr-type-module/src/env.d.ts
  e2e/cases/server/ssr-type-module/src/index.server.tsx
  e2e/cases/server/ssr-type-module/src/index.tsx
  e2e/cases/server/ssr-type-module/src/test.ts
  e2e/cases/server/ssr-type-module/template.html
  e2e/cases/server/ssr/index.test.ts
  e2e/package.json
  packages/core/src/server/environment.ts
  packages/core/src/server/runner/basic.ts
  packages/core/src/server/runner/cjs.ts
  packages/core/src/server/runner/esm.ts
  packages/core/src/server/runner/index.ts
  packages/core/src/server/runner/type.ts
  pnpm-lock.yaml
Labels: release: bug fix

#4566 docs: extract dev server API to separate page
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/shared/onBeforeStartDevServer.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/shared/onBeforeStartDevServer.mdx
Labels: release: document

#4567 docs: improve server middlewares documentation
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/config/dev/setup-middlewares.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/config/dev/setup-middlewares.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#4568 docs: add example for accessing dev server in plugin hooks
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#4569 fix: prevent some hook return values from affecting other hooks
  packages/compat/webpack/src/createCompiler.ts
  packages/compat/webpack/src/webpackConfig.ts
  packages/core/src/configChain.ts
  packages/core/src/createRsbuild.ts
  packages/core/src/hooks.ts
  packages/core/src/initPlugins.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/provider/initConfigs.ts
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/prodServer.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/createAsyncHook.test.ts
  packages/core/tests/hooks.test.ts
Labels: release: bug fix

#4570 feat: expose httpServer in RsbuildDevServer
  packages/core/src/server/devServer.ts
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
Labels: release: feature

#4571 fix: type infer for plugin hooks
  packages/core/src/types/plugin.ts
Labels: release: bug fix

#4572 docs: update CRA migration guide
  website/docs/en/guide/migration/cra.mdx
  website/docs/zh/guide/migration/cra.mdx
Labels: release: document

#4573 feat: allow onBeforeStartDevServer hook to return post callback
  e2e/cases/plugin-api/plugin-before-start-dev-server-hook/index.test.ts
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/types/hooks.ts
Labels: release: feature

#4576 docs: register middlewares in onBeforeStartDevServer
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
Labels: release: document

#4577 fix: should handle proxy error correctly
  e2e/cases/server/proxy/index.test.ts
  packages/core/src/server/proxy.ts
Labels: release: bug fix

#4578 fix(core): respect `server.port` when replacing `<port>`
  packages/core/src/plugins/output.ts
  packages/core/tests/output.test.ts
Labels: release: bug fix

#4583 feat: add npm link to plugin hints
  packages/core/src/helpers/format.ts
Labels: release: feature

#4590 docs: update README files for plugin packages
  packages/compat/plugin-webpack-swc/README.md
  packages/compat/webpack/README.md
  packages/core/README.md
  packages/create-rsbuild/README.md
  packages/plugin-assets-retry/README.md
  packages/plugin-babel/README.md
  packages/plugin-less/README.md
  packages/plugin-preact/README.md
  packages/plugin-react/README.md
  packages/plugin-sass/README.md
  packages/plugin-solid/README.md
  packages/plugin-stylus/README.md
  packages/plugin-svelte/README.md
  packages/plugin-svgr/README.md
  packages/plugin-vue/README.md
Labels: release: document

#4594 fix(server): options fallback should only works in rsbuild server mode
  e2e/cases/server/fallback/index.test.ts
  e2e/cases/server/fallback/src/index.js
  packages/core/src/server/devServer.ts
  packages/core/src/server/getDevMiddlewares.ts
  packages/core/src/server/middlewares.ts
  packages/core/src/server/prodServer.ts
Labels: release: bug fix

#4600 docs: improve stats usage example in JavaScript API documentation
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/zh/api/javascript-api/instance.mdx
Labels: release: document

#4591 feat(deps): update Rspack to v1.2.5
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4601 feat(cache): add env files to buildDependencies
  e2e/cases/cache/build-dependencies/index.test.ts
  e2e/cases/cache/build-dependencies/src/a.js
  e2e/cases/cache/build-dependencies/src/a.test.js
  e2e/cases/cache/build-dependencies/src/index.js
  e2e/cases/cache/build-dependencies/tsconfig.json
  e2e/cases/cache/cache-digest/index.test.ts
  e2e/cases/cache/cache-digest/src/a.js
  e2e/cases/cache/cache-digest/src/a.test.js
  e2e/cases/cache/cache-digest/src/index.js
  e2e/cases/cache/cache-digest/tsconfig.json
  e2e/tsconfig.json
  packages/core/src/cli/init.ts
  website/docs/en/config/performance/build-cache.mdx
  website/docs/zh/config/performance/build-cache.mdx
Labels: release: feature

#4604 fix: postcssrc cache may cause memory leak
  packages/core/src/plugins/css.ts
Labels: release: bug fix

#4609 docs: plugin migration guide
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#4608 feat(create-rsbuild): add React 18 templates
  e2e/cases/create-rsbuild/jsTemplates.test.ts
  e2e/cases/create-rsbuild/tsTemplates.test.ts
  packages/create-rsbuild/src/index.ts
  packages/create-rsbuild/template-react18-js/package.json
  packages/create-rsbuild/template-react18-js/rsbuild.config.mjs
  packages/create-rsbuild/template-react18-js/src/App.css
  packages/create-rsbuild/template-react18-js/src/App.jsx
  packages/create-rsbuild/template-react18-js/src/index.jsx
  packages/create-rsbuild/template-react18-ts/package.json
  packages/create-rsbuild/template-react18-ts/rsbuild.config.ts
  packages/create-rsbuild/template-react18-ts/src/App.css
  packages/create-rsbuild/template-react18-ts/src/App.tsx
  packages/create-rsbuild/template-react18-ts/src/env.d.ts
  packages/create-rsbuild/template-react18-ts/src/index.tsx
  packages/create-rsbuild/template-react18-ts/tsconfig.json
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: feature

#4611 docs: update outdated JSDoc for Rsbuild configurations
  packages/core/src/plugins/nonce.ts
  packages/core/src/plugins/server.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/profile.mdx
  website/docs/en/config/server/host.mdx
  website/docs/en/config/server/https.mdx
  website/docs/en/config/server/port.mdx
  website/docs/en/config/server/print-urls.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/configure-rsbuild.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/config/performance/profile.mdx
  website/docs/zh/config/server/host.mdx
  website/docs/zh/config/server/https.mdx
  website/docs/zh/config/server/port.mdx
  website/docs/zh/config/server/print-urls.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#4614 feat: add `server.middlewareMode` config
  e2e/cases/server/custom-server/index.test.ts
  e2e/cases/server/custom-server/scripts/pureServer.mjs
  e2e/cases/server/custom-server/scripts/server.mjs
  e2e/cases/server/multi-server/index.test.ts
  packages/core/src/config.ts
  packages/core/src/server/devServer.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/environments.test.ts.snap
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
Labels: release: feature

#4618 feat: improve socket server connection handling and cleanup
  packages/core/src/server/compilerDevMiddleware.ts
  packages/core/src/server/socketServer.ts
Labels: release: feature

#4621 docs: add `server.middlewareMode` config
  website/docs/en/api/javascript-api/dev-server-api.mdx
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/config/server/middleware-mode.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/zh/api/javascript-api/dev-server-api.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/config/server/middleware-mode.mdx
  website/docs/zh/guide/migration/vite.mdx
Labels: release: document

#4623 feat: add debug logs of config file and env files loading
  packages/core/src/config.ts
  packages/core/src/helpers/fs.ts
  packages/core/src/loadEnv.ts
  packages/core/src/plugins/cache.ts
  packages/core/src/provider/createCompiler.ts
  packages/core/src/server/open.ts
  website/docs/en/guide/debug/debug-mode.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/debug/debug-mode.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: release: feature

#4191 feat(deps): bump jiti to v2
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  pnpm-lock.yaml
Labels: release: feature

#4633 docs: add React Router to React guide
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: release: document

#4636 docs: update quick start guide content
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/guide/start/index.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/theme/components/Step.tsx
Labels: release: document

#4637 docs: correct wrong example in postcss v3 configuration
  website/docs/en/guide/basic/tailwindcss-v3.mdx
  website/docs/zh/guide/basic/tailwindcss-v3.mdx
Labels: release: document

#4641 feat: print changed files when rebuild restarts
  e2e/cases/javascript-api/custom-logger/index.test.ts
  e2e/cases/progress/index.test.ts
  e2e/cases/rspack-profile/index.test.ts
  packages/compat/webpack/src/progress/ProgressPlugin.ts
  packages/compat/webpack/src/progress/helpers/nonTty.ts
  packages/core/src/provider/createCompiler.ts
Labels: release: feature

#4645 feat: add `processEnv` option to loadEnv
  e2e/cases/javascript-api/load-env/index.test.ts
  packages/core/src/loadEnv.ts
  website/docs/en/api/javascript-api/core.mdx
  website/docs/zh/api/javascript-api/core.mdx
Labels: release: feature

#4643 feat(plugin-assets-retry): add delay parameter
  e2e/cases/assets/assets-retry/delay.test.ts
  e2e/cases/assets/assets-retry/helper.ts
  packages/plugin-assets-retry/src/AsyncChunkRetryPlugin.ts
  packages/plugin-assets-retry/src/index.ts
  packages/plugin-assets-retry/src/runtime/asyncChunkRetry.ts
  packages/plugin-assets-retry/src/runtime/initialChunkRetry.ts
  packages/plugin-assets-retry/src/types.ts
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: release: feature

#4646 docs: improve formatting for plugin-assets-retry and app-icon
  website/docs/en/config/html/app-icon.mdx
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: release: document

#4648 docs(plugin-assets-retry): update type and default options
  website/docs/en/plugins/list/plugin-assets-retry.mdx
  website/docs/zh/plugins/list/plugin-assets-retry.mdx
Labels: release: document

#4651 docs: update CRA migration guide for ESLint
  website/docs/en/guide/migration/cra.mdx
  website/docs/zh/guide/migration/cra.mdx
Labels: release: document

#4655 docs: improve filename configuration
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: document

#4656 feat: support for dynamic asset filenames
  e2e/cases/assets/filename-function/index.test.ts
  e2e/cases/assets/filename-function/rsbuild.config.ts
  e2e/cases/assets/filename-function/src/index.js
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/asset.ts
  packages/core/src/types/config.ts
  website/docs/en/config/output/filename.mdx
  website/docs/zh/config/output/filename.mdx
Labels: release: feature

#4657 docs: improve output configuration
  packages/core/src/types/config.ts
  website/docs/en/config/output/dist-path.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/guide/basic/output-files.mdx
  website/docs/zh/config/output/dist-path.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/guide/basic/output-files.mdx
Labels: release: document

#4663 docs: alias differences with Rspack
  packages/core/src/types/config.ts
  website/docs/en/config/resolve/alias.mdx
  website/docs/zh/config/resolve/alias.mdx
Labels: release: document

#4664 feat(deps): update Rspack to v1.2.6
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4667 perf(server): sendStats should not be called when no socket connection
  packages/core/src/server/socketServer.ts
Labels: release: performance

#4669 perf: remove unless `path.resolve` call
  packages/core/src/cli/init.ts
  packages/core/src/helpers/fs.ts
  packages/core/src/plugins/basic.ts
  packages/core/src/plugins/html.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
Labels: release: performance

#4671 fix: processAssets hook filter error
  e2e/cases/plugin-api/plugin-process-assets-by-environments/index.test.ts
  packages/core/src/initPlugins.ts
Labels: release: bug fix

#4672 fix: absolute path for favicon configuration
  e2e/cases/html/favicon/index.test.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
Labels: release: bug fix

#4673 fix: reconnect port error when automatically increment
  packages/core/src/server/devServer.ts
Labels: release: bug fix

#4674 fix: improve favicon handling with better error logging
  packages/core/src/helpers/index.ts
  packages/core/src/rspack/RsbuildHtmlPlugin.ts
Labels: release: bug fix

#4675 fix(deps): bump rsbuild-dev-middleware to unify logger style
  packages/core/package.json
  packages/core/prebundle.config.mjs
  pnpm-lock.yaml
Labels: release: bug fix
