Repository web-infra-dev/rsbuild, pull requests merged in 2025-04, with the labels that each got.

#4944 fix(plugin-svgr): support for raw query
  e2e/cases/assets/raw-query/index.test.ts
  e2e/cases/assets/raw-query/src/index.js
  packages/core/src/configChain.ts
  packages/plugin-svgr/src/index.ts
  packages/plugin-svgr/tests/__snapshots__/index.test.ts.snap
Labels: release: bug fix

#4947 feat(CLI): allow to disable loading .env files
  e2e/cases/cli/no-env/.env
  e2e/cases/cli/no-env/index.test.ts
  e2e/cases/cli/no-env/rsbuild.config.ts
  e2e/cases/cli/no-env/src/index.js
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  scripts/dictionary.txt
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: release: feature

#4953 fix(server): support access globalThis in esm vm
  e2e/cases/server/ssr/package.json
  e2e/cases/server/ssr/src/assert.server.ts
  packages/core/src/server/runner/asModule.ts
  packages/core/src/server/runner/esm.ts
Labels: release: bug fix

#4955 feat: support for specifying more browser names
  packages/core/src/server/open.ts
Labels: release: feature

#4956 docs: improve guide for specifying browser name
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/server/open.mdx
Labels: release: document

#4957 feat(deps): update Rspack to v1.3.2
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4886 feat: support for BROWSER_ARGS
  packages/core/src/server/open.ts
Labels: release: feature

#4959 fix: ensure BROWSER_ARGS works
  packages/core/src/server/open.ts
Labels: release: bug fix

#4960 docs: add BROWSER_ARGS guide
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/server/open.mdx
Labels: release: document

#4961 docs: fix error conditions
  website/docs/zh/plugins/dev/index.mdx
Labels: release: document

#4963 fix(create-rsbuild): Vue TS ESLint template
  packages/create-rsbuild/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4965 feat: make it easier to set browser name
  packages/core/src/server/open.ts
  website/docs/en/config/server/open.mdx
  website/docs/zh/config/server/open.mdx
Labels: release: feature

#4969 fix(security): update http-proxy-middleware to 2.0.7
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4971 fix: invalid type in http-proxy-middleware
  packages/core/prebundle.config.mjs
Labels: release: bug fix

#4972 fix(types): failed to resolve postcss types
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/src/config.ts
  packages/core/src/configChain.ts
  packages/core/src/helpers/index.ts
  packages/core/src/plugins/css.ts
  packages/core/src/types/config.ts
  packages/core/src/types/hooks.ts
  packages/core/src/types/plugin.ts
  packages/core/src/types/rspack.ts
  packages/core/src/types/thirdParty.ts
  packages/core/tests/external.test.ts
  packages/plugin-babel/package.json
  packages/plugin-less/package.json
  packages/plugin-sass/package.json
  packages/plugin-svgr/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4973 docs: correct `getTransformedHtml` link
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/advanced/environments.mdx
  website/docs/en/guide/advanced/ssr.mdx
  website/docs/en/guide/basic/server.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/advanced/environments.mdx
  website/docs/zh/guide/advanced/ssr.mdx
  website/docs/zh/guide/basic/server.mdx
Labels: release: document

#4978 docs(website): switch to shiki
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/config/html/mount-id.mdx
  website/docs/en/config/html/tags.mdx
  website/docs/en/config/output/inline-scripts.mdx
  website/docs/en/config/source/entry.mdx
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/faq/exceptions.mdx
  website/docs/en/guide/faq/hmr.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/migration/modern-builder.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/en/guide/migration/vite.mdx
  website/docs/en/guide/migration/vue-cli.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/config/html/mount-id.mdx
  website/docs/zh/config/html/tags.mdx
  website/docs/zh/config/output/inline-scripts.mdx
  website/docs/zh/config/source/entry.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/faq/exceptions.mdx
  website/docs/zh/guide/faq/hmr.mdx
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/migration/modern-builder.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/vite.mdx
  website/docs/zh/guide/migration/vue-cli.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/package.json
  website/rspress.config.ts
Labels: release: document

#4981 feat(deps): update Rspack to v1.3.3
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4988 fix(plugin-svgr): unpin @rsbuild/plugin-react dependency version
  packages/plugin-svgr/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#4993 feat(overlay): support for clicking links in error logs
  packages/core/src/server/overlay.ts
  packages/core/tests/overlay.test.ts
  scripts/dictionary.txt
Labels: release: feature

#4994 feat(deps): update Rspack to v1.3.4
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#4995 docs(plugin-babel): add execution order section
  website/docs/en/plugins/list/plugin-babel.mdx
  website/docs/zh/plugins/list/plugin-babel.mdx
Labels: release: document

#4997 fix: output.filename config merging
  packages/core/src/mergeConfig.ts
  packages/core/tests/mergeConfig.test.ts
Labels: release: bug fix

#4999 docs: clarify Rsbuild profiling folder generation
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5000 feat: improve rspack profile plugin
  e2e/cases/rspack-profile/index.test.ts
  packages/core/src/plugins/rspackProfile.ts
Labels: release: feature

#5002 feat: support use `rspack` in `tools.bundlerChain`
  e2e/cases/config/bundler-chain/index.test.ts
  e2e/cases/config/bundler-chain/src/index.js
  packages/core/src/provider/rspackConfig.ts
  packages/core/src/types/config.ts
  packages/core/src/types/hooks.ts
  website/docs/en/config/tools/bundler-chain.mdx
  website/docs/zh/config/tools/bundler-chain.mdx
Labels: release: feature

#5003 fix: `onExit` hook should be called with CTRL+C
  packages/core/src/helpers/exitHook.ts
  packages/core/src/initPlugins.ts
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: bug fix

#5004 feat: support for accessing exit code in `onExit` hook
  e2e/cases/plugin-api/plugin-on-exit-hook/index.test.ts
  e2e/cases/plugin-api/plugin-on-exit-hook/run.mjs
  packages/core/src/helpers/exitHook.ts
  packages/core/src/initPlugins.ts
  packages/core/src/types/hooks.ts
  website/docs/en/api/javascript-api/instance.mdx
  website/docs/en/plugins/dev/hooks.mdx
  website/docs/en/shared/onExit.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/plugins/dev/hooks.mdx
  website/docs/zh/shared/onExit.mdx
Labels: release: feature

#5005 fix: correct exit code in graceful shutdown
  packages/core/src/helpers/exitHook.ts
  packages/core/src/server/gracefulShutdown.ts
Labels: release: bug fix

#5008 docs: add example for disabling NODE_ENV injection
  e2e/cases/mode/define/index.test.ts
  website/docs/en/guide/advanced/env-vars.mdx
  website/docs/zh/guide/advanced/env-vars.mdx
Labels: release: document

#5016 fix(plugin-svgr): SVGs generated with different hash
  e2e/cases/svg/svgr-hash-digest/index.test.ts
  e2e/cases/svg/svgr-hash-digest/rsbuild.config.ts
  e2e/cases/svg/svgr-hash-digest/src/index.js
  package.json
  packages/plugin-svgr/package.json
  packages/plugin-svgr/prebundle.config.mjs
  patches/file-loader@6.2.0.patch
  patches/url-loader@4.1.1.patch
  pnpm-lock.yaml
Labels: release: bug fix

#5020 docs: update project terminology to application in framework guides
  website/docs/en/guide/framework/preact.mdx
  website/docs/en/guide/framework/react.mdx
  website/docs/en/guide/framework/solid.mdx
  website/docs/en/guide/framework/svelte.mdx
  website/docs/en/guide/framework/vue.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/framework/preact.mdx
  website/docs/zh/guide/framework/react.mdx
  website/docs/zh/guide/framework/solid.mdx
  website/docs/zh/guide/framework/svelte.mdx
  website/docs/zh/guide/framework/vue.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#5025 fix(types): failed to resolve prebundled types
  packages/core/prebundle.config.mjs
Labels: release: bug fix

#5024 fix(types): failed to resolve webpack types
  packages/core/src/types/plugin.ts
  packages/core/src/types/thirdParty.ts
Labels: release: bug fix

#5029 docs: update Rsdoctor introduction
  website/docs/en/guide/debug/rsdoctor.mdx
  website/docs/zh/guide/debug/rsdoctor.mdx
Labels: release: document

#5030 feat(deps): update Rspack to v1.3.5
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5032 fix: update Node.js engine requirement to >=16.10
  packages/core/package.json
  packages/create-rsbuild/package.json
Labels: release: bug fix

#5033 docs: correct build profiling link
  website/docs/en/config/performance/profile.mdx
  website/docs/zh/config/performance/profile.mdx
Labels: release: document

#5035 feat: support dev.lazyCompilation.serverUrl use <port>
  packages/core/src/server/devMiddlewares.ts
Labels: release: feature

#5036 docs: add React Scan guide
  package.json
  pnpm-lock.yaml
  website/docs/en/guide/framework/react.mdx
  website/docs/zh/guide/framework/react.mdx
Labels: release: document

#5038 docs: add client and serverUrl options to lazy compilation
  website/docs/en/config/dev/lazy-compilation.mdx
  website/docs/zh/config/dev/lazy-compilation.mdx
Labels: release: document

#5047 docs: remove shortcut restrictions in cpuprofile
  website/docs/en/guide/debug/build-profiling.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
Labels: release: document

#5052 fix: enable Lightning CSS `errorRecovery` option
  packages/core/src/plugins/css.ts
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/css.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/minimize.test.ts
  packages/plugin-less/tests/__snapshots__/index.test.ts.snap
  packages/plugin-sass/tests/__snapshots__/index.test.ts.snap
  packages/plugin-stylus/tests/__snapshots__/index.test.ts.snap
  website/docs/en/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
Labels: release: bug fix

#5056 docs: update documentation for preload and prefetch options
  packages/core/src/types/config.ts
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: release: document

#5060 docs: improve resource hints
  website/docs/en/community/releases/v0-5.mdx
  website/docs/en/community/releases/v0-7.mdx
  website/docs/en/config/dev/asset-prefix.mdx
  website/docs/en/config/dev/client.mdx
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/en/config/source/exclude.mdx
  website/docs/en/guide/advanced/hmr.mdx
  website/docs/en/guide/basic/unocss.mdx
  website/docs/en/guide/migration/modern-builder.mdx
  website/docs/en/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/community/releases/v0-5.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/config/dev/client.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
  website/docs/zh/config/source/exclude.mdx
  website/docs/zh/guide/advanced/hmr.mdx
  website/docs/zh/guide/basic/unocss.mdx
  website/docs/zh/guide/migration/modern-builder.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
Labels: release: document

#5062 feat: enhance prefetch and preload filters
  e2e/cases/performance/resource-hints-prefetch/index.test.ts
  e2e/cases/performance/resource-hints-prefetch/src/env.d.ts
  e2e/cases/performance/resource-hints-prefetch/src/page1/App.tsx
  e2e/cases/performance/resource-hints-prefetch/src/page1/index.ts
  e2e/cases/performance/resource-hints-prefetch/src/page2/App.tsx
  e2e/cases/performance/resource-hints-prefetch/src/page2/index.ts
  e2e/cases/performance/resource-hints-prefetch/src/test.css
  e2e/cases/performance/resource-hints-prefetch/src/test.ts
  e2e/cases/performance/resource-hints-prefetch/tsconfig.json
  e2e/cases/performance/resource-hints-preload/index.test.ts
  e2e/cases/performance/resource-hints-preload/src/env.d.ts
  e2e/cases/performance/resource-hints-preload/src/page1/App.tsx
  e2e/cases/performance/resource-hints-preload/src/page1/index.ts
  e2e/cases/performance/resource-hints-preload/src/page2/App.tsx
  e2e/cases/performance/resource-hints-preload/src/page2/index.ts
  e2e/cases/performance/resource-hints-preload/src/test.css
  e2e/cases/performance/resource-hints-preload/src/test.ts
  e2e/cases/performance/resource-hints-preload/tsconfig.json
  e2e/cases/performance/resource-hints/src/test.ts
  packages/core/src/rspack/resource-hints/HtmlResourceHintsPlugin.ts
  packages/core/src/types/config.ts
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: release: feature

#5063 docs: add examples for prefetch and preload filters
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: release: document

#5064 perf: make inline chunk matching faster
  packages/core/src/plugins/inlineChunk.ts
Labels: release: performance

#5067 fix: do not generate resource hints for inlined assets
  e2e/cases/performance/resource-hints-prefetch/index.test.ts
  e2e/cases/performance/resource-hints-preload/index.test.ts
  packages/core/src/plugins/inlineChunk.ts
  packages/core/src/plugins/resourceHints.ts
  packages/core/src/rspack/resource-hints/HtmlResourceHintsPlugin.ts
Labels: release: bug fix

#5069 docs: improve Browserslist content order
  website/docs/en/config/output/override-browserslist.mdx
  website/docs/en/config/output/target.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/zh/config/output/override-browserslist.mdx
  website/docs/zh/config/output/target.mdx
  website/docs/zh/guide/advanced/browserslist.mdx
Labels: release: document

#5070 fix: update error message for Node.js built-in module
  e2e/cases/node-polyfill-tip/with-protocol/index.test.ts
  e2e/cases/node-polyfill-tip/without-protocol/index.test.ts
  packages/core/src/helpers/format.ts
Labels: release: bug fix

#5071 fix: correct highlighting of filename log
  packages/core/src/helpers/format.ts
Labels: release: bug fix

#5089 feat(deps): update Rspack to v1.3.6
  packages/core/package.json
  packages/core/tests/__snapshots__/basic.test.ts.snap
  packages/core/tests/__snapshots__/builder.test.ts.snap
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/__snapshots__/default.test.ts.snap
  packages/core/tests/__snapshots__/environments.test.ts.snap
  packages/core/tests/__snapshots__/moduleFederation.test.ts.snap
  pnpm-lock.yaml
Labels: release: feature

#5090 fix: source map files should always be excluded from resource hints
  packages/core/src/rspack/resource-hints/HtmlResourceHintsPlugin.ts
  website/docs/en/config/performance/prefetch.mdx
  website/docs/en/config/performance/preload.mdx
  website/docs/zh/config/performance/prefetch.mdx
  website/docs/zh/config/performance/preload.mdx
Labels: release: bug fix

#5049 docs(llms): bump to rspress@2.0.0-beta.1 and add llms.txt
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/package.json
  website/rspress.config.ts
Labels: release: document

#5096 fix: call `compiler.close` when having errors
  packages/core/src/provider/build.ts
Labels: release: bug fix

#5097 docs: update alias strategy documentation
  packages/core/src/types/config.ts
  website/docs/en/config/resolve/alias-strategy.mdx
  website/docs/zh/config/resolve/alias-strategy.mdx
  website/docs/zh/guide/advanced/alias.mdx
Labels: release: document

#5098 docs: update guide for switching minifiers
  scripts/dictionary.txt
  website/docs/en/config/mode.mdx
  website/docs/en/config/output/minify.mdx
  website/docs/en/guide/configuration/swc.mdx
  website/docs/zh/config/output/minify.mdx
  website/docs/zh/guide/configuration/swc.mdx
Labels: release: document

#5101 docs(llms.txt): add more description
  website/rspress.config.ts
Labels: release: document

#5104 feat(deps): update Rspack to 1.3.7
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5107 fix: prevent circular references in recursiveChunkGroup
  packages/core/src/rspack/resource-hints/doesChunkBelongToHtml.ts
Labels: release: bug fix

#5108 feat: improve alignment of total output size
  e2e/cases/print-file-size/basic/index.test.ts
  e2e/cases/print-file-size/with-error/index.test.ts
  packages/core/src/plugins/fileSize.ts
  website/docs/en/config/performance/print-file-size.mdx
  website/docs/zh/config/performance/print-file-size.mdx
Labels: release: feature

#5112 docs(environments): add note on server and dev options limitations
  website/docs/en/config/environments.mdx
  website/docs/zh/config/environments.mdx
Labels: release: document

#5113 docs: update plugin examples with conditional and async
  website/docs/en/config/plugins.mdx
  website/docs/en/config/server/https.mdx
  website/docs/en/config/server/middleware-mode.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/config/server/https.mdx
  website/docs/zh/config/server/middleware-mode.mdx
Labels: release: document

#5114 fix: gzip middleware breaks SSE connection
  packages/core/src/server/devMiddlewares.ts
  packages/core/src/server/prodServer.ts
Labels: release: bug fix

#5117 fix: improve error message formatting in build stats
  e2e/cases/plugin-api/plugin-transform-error-handle/index.test.ts
  packages/core/src/helpers/stats.ts
Labels: release: bug fix

#5118 feat: add config link to overlay footer for better accessibility
  packages/core/src/server/overlay.ts
Labels: release: feature

#5125 fix: file size logging when detail is disabled
  e2e/cases/print-file-size/basic/index.test.ts
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#5127 feat(deps): update Rspack to v1.3.8
  packages/core/package.json
  pnpm-lock.yaml
Labels: release: feature

#5132 fix: make file size logs more compact
  e2e/cases/print-file-size/basic/index.test.ts
  packages/core/src/plugins/fileSize.ts
Labels: release: bug fix

#5139 docs: improve links to Rspack documentation
  website/docs/en/config/html/output-structure.mdx
  website/docs/en/config/output/filename.mdx
  website/docs/en/config/performance/bundle-analyze.mdx
  website/docs/en/guide/advanced/browserslist.mdx
  website/docs/en/guide/styling/tailwindcss.mdx
  website/docs/en/plugins/list/plugin-babel.mdx
  website/docs/en/plugins/list/plugin-react.mdx
  website/docs/zh/api/javascript-api/instance.mdx
  website/docs/zh/community/releases/v0-6.mdx
  website/docs/zh/community/releases/v0-7.mdx
  website/docs/zh/config/dev/watch-files.mdx
  website/docs/zh/config/html/output-structure.mdx
  website/docs/zh/config/mode.mdx
  website/docs/zh/config/module-federation/options.mdx
  website/docs/zh/config/output/filename.mdx
  website/docs/zh/config/output/inline-scripts.mdx
  website/docs/zh/config/output/target.mdx
  website/docs/zh/config/performance/bundle-analyze.mdx
  website/docs/zh/config/performance/chunk-split.mdx
  website/docs/zh/config/performance/profile.mdx
  website/docs/zh/config/resolve/extensions.mdx
  website/docs/zh/config/root.mdx
  website/docs/zh/config/security/nonce.mdx
  website/docs/zh/config/security/sri.mdx
  website/docs/zh/config/source/assets-include.mdx
  website/docs/zh/config/source/entry.mdx
  website/docs/zh/config/source/include.mdx
  website/docs/zh/config/tools/lightningcss-loader.mdx
  website/docs/zh/config/tools/rspack.mdx
  website/docs/zh/config/tools/swc.mdx
  website/docs/zh/guide/advanced/hmr.mdx
  website/docs/zh/guide/basic/server.mdx
  website/docs/zh/guide/basic/static-assets.mdx
  website/docs/zh/guide/basic/typescript.mdx
  website/docs/zh/guide/configuration/rspack.mdx
  website/docs/zh/guide/configuration/swc.mdx
  website/docs/zh/guide/debug/build-profiling.mdx
  website/docs/zh/guide/faq/exceptions.mdx
  website/docs/zh/guide/migration/cra.mdx
  website/docs/zh/guide/migration/rsbuild-0-x.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/guide/start/index.mdx
  website/docs/zh/guide/styling/css-usage.mdx
  website/docs/zh/plugins/dev/core.mdx
  website/docs/zh/plugins/dev/index.mdx
  website/docs/zh/plugins/list/plugin-babel.mdx
  website/docs/zh/plugins/list/plugin-less.mdx
  website/docs/zh/plugins/list/plugin-react.mdx
  website/docs/zh/plugins/list/plugin-sass.mdx
  website/docs/zh/plugins/list/plugin-svgr.mdx
  website/docs/zh/shared/onAfterBuild.mdx
  website/docs/zh/shared/onAfterCreateCompiler.mdx
  website/docs/zh/shared/onAfterEnvironmentCompile.mdx
  website/docs/zh/shared/onBeforeBuild.mdx
  website/docs/zh/shared/onBeforeCreateCompiler.mdx
  website/docs/zh/shared/onBeforeEnvironmentCompile.mdx
Labels: release: document

#5140 feat: allow to access manifest data in plugin hooks
  e2e/cases/output/manifest-environment/index.test.ts
  e2e/cases/output/manifest-environment/src/index.ts
  e2e/cases/output/manifest/index.test.ts
  e2e/cases/performance/resource-hints-prefetch/index.test.ts
  e2e/cases/performance/resource-hints-preload/index.test.ts
  packages/core/src/createContext.ts
  packages/core/src/plugins/manifest.ts
  packages/core/src/types/hooks.ts
Labels: release: feature

#5141 docs: accessing manifest data via hooks
  packages/core/src/types/hooks.ts
  website/docs/en/api/javascript-api/environment-api.mdx
  website/docs/en/config/output/manifest.mdx
  website/docs/zh/api/javascript-api/environment-api.mdx
  website/docs/zh/config/output/manifest.mdx
Labels: release: document
